syntax = "proto3";

package er;

option java_package = "er.proto";
option java_multiple_files = true;

enum AbilityEnum {
  ABILITY_NONE = 0;
  ABILITY_STENCH = 1;
  ABILITY_DRIZZLE = 2;
  ABILITY_SPEED_BOOST = 3;
  ABILITY_BATTLE_ARMOR = 4;
  ABILITY_STURDY = 5;
  ABILITY_DAMP = 6;
  ABILITY_LIMBER = 7;
  ABILITY_SAND_VEIL = 8;
  ABILITY_STATIC = 9;
  ABILITY_VOLT_ABSORB = 10;
  ABILITY_WATER_ABSORB = 11;
  ABILITY_OBLIVIOUS = 12;
  ABILITY_CLOUD_NINE = 13;
  ABILITY_COMPOUND_EYES = 14;
  ABILITY_INSOMNIA = 15;
  ABILITY_COLOR_CHANGE = 16;
  ABILITY_IMMUNITY = 17;
  ABILITY_FLASH_FIRE = 18;
  ABILITY_SHIELD_DUST = 19;
  ABILITY_OWN_TEMPO = 20;
  ABILITY_SUCTION_CUPS = 21;
  ABILITY_INTIMIDATE = 22;
  ABILITY_SHADOW_TAG = 23;
  ABILITY_ROUGH_SKIN = 24;
  ABILITY_WONDER_GUARD = 25;
  ABILITY_LEVITATE = 26;
  ABILITY_EFFECT_SPORE = 27;
  ABILITY_SYNCHRONIZE = 28;
  ABILITY_CLEAR_BODY = 29;
  ABILITY_NATURAL_CURE = 30;
  ABILITY_LIGHTNING_ROD = 31;
  ABILITY_SERENE_GRACE = 32;
  ABILITY_SWIFT_SWIM = 33;
  ABILITY_CHLOROPHYLL = 34;
  ABILITY_ILLUMINATE = 35;
  ABILITY_TRACE = 36;
  ABILITY_HUGE_POWER = 37;
  ABILITY_POISON_POINT = 38;
  ABILITY_INNER_FOCUS = 39;
  ABILITY_MAGMA_ARMOR = 40;
  ABILITY_WATER_VEIL = 41;
  ABILITY_MAGNET_PULL = 42;
  ABILITY_SOUNDPROOF = 43;
  ABILITY_RAIN_DISH = 44;
  ABILITY_SAND_STREAM = 45;
  ABILITY_PRESSURE = 46;
  ABILITY_THICK_FAT = 47;
  ABILITY_EARLY_BIRD = 48;
  ABILITY_FLAME_BODY = 49;
  ABILITY_RUN_AWAY = 50;
  ABILITY_KEEN_EYE = 51;
  ABILITY_HYPER_CUTTER = 52;
  ABILITY_PICKUP = 53;
  ABILITY_TRUANT = 54;
  ABILITY_HUSTLE = 55;
  ABILITY_CUTE_CHARM = 56;
  ABILITY_PLUS = 57;
  ABILITY_MINUS = 58;
  ABILITY_FORECAST = 59;
  ABILITY_STICKY_HOLD = 60;
  ABILITY_SHED_SKIN = 61;
  ABILITY_GUTS = 62;
  ABILITY_MARVEL_SCALE = 63;
  ABILITY_LIQUID_OOZE = 64;
  ABILITY_OVERGROW = 65;
  ABILITY_BLAZE = 66;
  ABILITY_TORRENT = 67;
  ABILITY_SWARM = 68;
  ABILITY_ROCK_HEAD = 69;
  ABILITY_DROUGHT = 70;
  ABILITY_ARENA_TRAP = 71;
  ABILITY_VITAL_SPIRIT = 72;
  ABILITY_WHITE_SMOKE = 73;
  ABILITY_PURE_POWER = 74;
  ABILITY_SHELL_ARMOR = 75;
  ABILITY_AIR_LOCK = 76;
  ABILITY_TANGLED_FEET = 77;
  ABILITY_MOTOR_DRIVE = 78;
  ABILITY_RIVALRY = 79;
  ABILITY_STEADFAST = 80;
  ABILITY_SNOW_CLOAK = 81;
  ABILITY_GLUTTONY = 82;
  ABILITY_ANGER_POINT = 83;
  ABILITY_UNBURDEN = 84;
  ABILITY_HEATPROOF = 85;
  ABILITY_SIMPLE = 86;
  ABILITY_DRY_SKIN = 87;
  ABILITY_DOWNLOAD = 88;
  ABILITY_IRON_FIST = 89;
  ABILITY_POISON_HEAL = 90;
  ABILITY_ADAPTABILITY = 91;
  ABILITY_SKILL_LINK = 92;
  ABILITY_HYDRATION = 93;
  ABILITY_SOLAR_POWER = 94;
  ABILITY_QUICK_FEET = 95;
  ABILITY_NORMALIZE = 96;
  ABILITY_SNIPER = 97;
  ABILITY_MAGIC_GUARD = 98;
  ABILITY_NO_GUARD = 99;
  ABILITY_STALL = 100;
  ABILITY_TECHNICIAN = 101;
  ABILITY_LEAF_GUARD = 102;
  ABILITY_KLUTZ = 103;
  ABILITY_MOLD_BREAKER = 104;
  ABILITY_SUPER_LUCK = 105;
  ABILITY_AFTERMATH = 106;
  ABILITY_ANTICIPATION = 107;
  ABILITY_FOREWARN = 108;
  ABILITY_UNAWARE = 109;
  ABILITY_TINTED_LENS = 110;
  ABILITY_FILTER = 111;
  ABILITY_SLOW_START = 112;
  ABILITY_SCRAPPY = 113;
  ABILITY_STORM_DRAIN = 114;
  ABILITY_ICE_BODY = 115;
  ABILITY_SOLID_ROCK = 116;
  ABILITY_SNOW_WARNING = 117;
  ABILITY_HONEY_GATHER = 118;
  ABILITY_FRISK = 119;
  ABILITY_RECKLESS = 120;
  ABILITY_MULTITYPE = 121;
  ABILITY_FLOWER_GIFT = 122;
  ABILITY_BAD_DREAMS = 123;
  ABILITY_PICKPOCKET = 124;
  ABILITY_SHEER_FORCE = 125;
  ABILITY_CONTRARY = 126;
  ABILITY_UNNERVE = 127;
  ABILITY_DEFIANT = 128;
  ABILITY_DEFEATIST = 129;
  ABILITY_CURSED_BODY = 130;
  ABILITY_HEALER = 131;
  ABILITY_FRIEND_GUARD = 132;
  ABILITY_WEAK_ARMOR = 133;
  ABILITY_HEAVY_METAL = 134;
  ABILITY_LIGHT_METAL = 135;
  ABILITY_MULTISCALE = 136;
  ABILITY_TOXIC_BOOST = 137;
  ABILITY_FLARE_BOOST = 138;
  ABILITY_HARVEST = 139;
  ABILITY_TELEPATHY = 140;
  ABILITY_MOODY = 141;
  ABILITY_OVERCOAT = 142;
  ABILITY_POISON_TOUCH = 143;
  ABILITY_REGENERATOR = 144;
  ABILITY_BIG_PECKS = 145;
  ABILITY_SAND_RUSH = 146;
  ABILITY_WONDER_SKIN = 147;
  ABILITY_ANALYTIC = 148;
  ABILITY_ILLUSION = 149;
  ABILITY_IMPOSTER = 150;
  ABILITY_INFILTRATOR = 151;
  ABILITY_MUMMY = 152;
  ABILITY_MOXIE = 153;
  ABILITY_JUSTIFIED = 154;
  ABILITY_RATTLED = 155;
  ABILITY_MAGIC_BOUNCE = 156;
  ABILITY_SAP_SIPPER = 157;
  ABILITY_PRANKSTER = 158;
  ABILITY_SAND_FORCE = 159;
  ABILITY_IRON_BARBS = 160;
  ABILITY_ZEN_MODE = 161;
  ABILITY_VICTORY_STAR = 162;
  ABILITY_TURBOBLAZE = 163;
  ABILITY_TERAVOLT = 164;
  ABILITY_AROMA_VEIL = 165;
  ABILITY_FLOWER_VEIL = 166;
  ABILITY_CHEEK_POUCH = 167;
  ABILITY_PROTEAN = 168;
  ABILITY_FUR_COAT = 169;
  ABILITY_MAGICIAN = 170;
  ABILITY_BULLETPROOF = 171;
  ABILITY_COMPETITIVE = 172;
  ABILITY_STRONG_JAW = 173;
  ABILITY_REFRIGERATE = 174;
  ABILITY_SWEET_VEIL = 175;
  ABILITY_STANCE_CHANGE = 176;
  ABILITY_GALE_WINGS = 177;
  ABILITY_MEGA_LAUNCHER = 178;
  ABILITY_GRASS_PELT = 179;
  ABILITY_SYMBIOSIS = 180;
  ABILITY_TOUGH_CLAWS = 181;
  ABILITY_PIXILATE = 182;
  ABILITY_GOOEY = 183;
  ABILITY_AERILATE = 184;
  ABILITY_PARENTAL_BOND = 185;
  ABILITY_DARK_AURA = 186;
  ABILITY_FAIRY_AURA = 187;
  ABILITY_AURA_BREAK = 188;
  ABILITY_PRIMORDIAL_SEA = 189;
  ABILITY_DESOLATE_LAND = 190;
  ABILITY_DELTA_STREAM = 191;
  ABILITY_STAMINA = 192;
  ABILITY_WIMP_OUT = 193;
  ABILITY_EMERGENCY_EXIT = 194;
  ABILITY_WATER_COMPACTION = 195;
  ABILITY_MERCILESS = 196;
  ABILITY_SHIELDS_DOWN = 197;
  ABILITY_STAKEOUT = 198;
  ABILITY_WATER_BUBBLE = 199;
  ABILITY_STEELWORKER = 200;
  ABILITY_BERSERK = 201;
  ABILITY_SLUSH_RUSH = 202;
  ABILITY_LONG_REACH = 203;
  ABILITY_LIQUID_VOICE = 204;
  ABILITY_TRIAGE = 205;
  ABILITY_GALVANIZE = 206;
  ABILITY_SURGE_SURFER = 207;
  ABILITY_SCHOOLING = 208;
  ABILITY_DISGUISE = 209;
  ABILITY_BATTLE_BOND = 210;
  ABILITY_POWER_CONSTRUCT = 211;
  ABILITY_CORROSION = 212;
  ABILITY_COMATOSE = 213;
  ABILITY_QUEENLY_MAJESTY = 214;
  ABILITY_INNARDS_OUT = 215;
  ABILITY_DANCER = 216;
  ABILITY_BATTERY = 217;
  ABILITY_FLUFFY = 218;
  ABILITY_DAZZLING = 219;
  ABILITY_SOUL_HEART = 220;
  ABILITY_TANGLING_HAIR = 221;
  ABILITY_RECEIVER = 222;
  ABILITY_POWER_OF_ALCHEMY = 223;
  ABILITY_BEAST_BOOST = 224;
  ABILITY_RKS_SYSTEM = 225;
  ABILITY_ELECTRIC_SURGE = 226;
  ABILITY_PSYCHIC_SURGE = 227;
  ABILITY_MISTY_SURGE = 228;
  ABILITY_GRASSY_SURGE = 229;
  ABILITY_FULL_METAL_BODY = 230;
  ABILITY_SHADOW_SHIELD = 231;
  ABILITY_PRISM_ARMOR = 232;
  ABILITY_NEUROFORCE = 233;
  ABILITY_INTREPID_SWORD = 234;
  ABILITY_DAUNTLESS_SHIELD = 235;
  ABILITY_LIBERO = 236;
  ABILITY_BALL_FETCH = 237;
  ABILITY_COTTON_DOWN = 238;
  ABILITY_PROPELLER_TAIL = 239;
  ABILITY_MIRROR_ARMOR = 240;
  ABILITY_GULP_MISSILE = 241;
  ABILITY_STALWART = 242;
  ABILITY_STEAM_ENGINE = 243;
  ABILITY_PUNK_ROCK = 244;
  ABILITY_SAND_SPIT = 245;
  ABILITY_ICE_SCALES = 246;
  ABILITY_RIPEN = 247;
  ABILITY_ICE_FACE = 248;
  ABILITY_POWER_SPOT = 249;
  ABILITY_MIMICRY = 250;
  ABILITY_SCREEN_CLEANER = 251;
  ABILITY_STEELY_SPIRIT = 252;
  ABILITY_PERISH_BODY = 253;
  ABILITY_WANDERING_SPIRIT = 254;
  ABILITY_GORILLA_TACTICS = 255;
  ABILITY_NEUTRALIZING_GAS = 256;
  ABILITY_PASTEL_VEIL = 257;
  ABILITY_HUNGER_SWITCH = 258;
  ABILITY_QUICK_DRAW = 259;
  ABILITY_UNSEEN_FIST = 260;
  ABILITY_CURIOUS_MEDICINE = 261;
  ABILITY_TRANSISTOR = 262;
  ABILITY_DRAGONS_MAW = 263;
  ABILITY_CHILLING_NEIGH = 264;
  ABILITY_GRIM_NEIGH = 265;
  ABILITY_AS_ONE_ICE_RIDER = 266;
  ABILITY_AS_ONE_SHADOW_RIDER = 267;
  ABILITY_CHLOROPLAST = 268;
  ABILITY_WHITEOUT = 269;
  ABILITY_PYROMANCY = 270;
  ABILITY_KEEN_EDGE = 271;
  ABILITY_PRISM_SCALES = 272;
  ABILITY_POWER_FISTS = 273;
  ABILITY_SAND_SONG = 274;
  ABILITY_RAMPAGE = 275;
  ABILITY_VENGEANCE = 276;
  ABILITY_BLITZ_BOXER = 277;
  ABILITY_ANTARCTIC_BIRD = 278;
  ABILITY_IMMOLATE = 279;
  ABILITY_CRYSTALLIZE = 280;
  ABILITY_ELECTROCYTES = 281;
  ABILITY_AERODYNAMICS = 282;
  ABILITY_CHRISTMAS_SPIRIT = 283;
  ABILITY_EXPLOIT_WEAKNESS = 284;
  ABILITY_GROUND_SHOCK = 285;
  ABILITY_ANCIENT_IDOL = 286;
  ABILITY_MYSTIC_POWER = 287;
  ABILITY_PERFECTIONIST = 288;
  ABILITY_GROWING_TOOTH = 289;
  ABILITY_INFLATABLE = 290;
  ABILITY_AURORA_BOREALIS = 291;
  ABILITY_AVENGER = 292;
  ABILITY_LETS_ROLL = 293;
  ABILITY_AQUATIC = 294;
  ABILITY_LOUD_BANG = 295;
  ABILITY_LEAD_COAT = 296;
  ABILITY_AMPHIBIOUS = 297;
  ABILITY_GROUNDED = 298;
  ABILITY_EARTHBOUND = 299;
  ABILITY_FIGHT_SPIRIT = 300;
  ABILITY_FELINE_PROWESS = 301;
  ABILITY_COIL_UP = 302;
  ABILITY_FOSSILIZED = 303;
  ABILITY_MAGICAL_DUST = 304;
  ABILITY_DREAMCATCHER = 305;
  ABILITY_NOCTURNAL = 306;
  ABILITY_SELF_SUFFICIENT = 307;
  ABILITY_TECTONIZE = 308;
  ABILITY_ICE_AGE = 309;
  ABILITY_HALF_DRAKE = 310;
  ABILITY_LIQUIFIED = 311;
  ABILITY_DRAGONFLY = 312;
  ABILITY_DRAGONSLAYER = 313;
  ABILITY_MOUNTAINEER = 314;
  ABILITY_HYDRATE = 315;
  ABILITY_METALLIC = 316;
  ABILITY_PERMAFROST = 317;
  ABILITY_PRIMAL_ARMOR = 318;
  ABILITY_RAGING_BOXER = 319;
  ABILITY_AIR_BLOWER = 320;
  ABILITY_JUGGERNAUT = 321;
  ABILITY_SHORT_CIRCUIT = 322;
  ABILITY_MAJESTIC_BIRD = 323;
  ABILITY_PHANTOM = 324;
  ABILITY_INTOXICATE = 325;
  ABILITY_IMPENETRABLE = 326;
  ABILITY_HYPNOTIST = 327;
  ABILITY_OVERWHELM = 328;
  ABILITY_SCARE = 329;
  ABILITY_MAJESTIC_MOTH = 330;
  ABILITY_SOUL_EATER = 331;
  ABILITY_SOUL_LINKER = 332;
  ABILITY_SWEET_DREAMS = 333;
  ABILITY_BAD_LUCK = 334;
  ABILITY_HAUNTED_SPIRIT = 335;
  ABILITY_ELECTRIC_BURST = 336;
  ABILITY_RAW_WOOD = 337;
  ABILITY_SOLENOGLYPHS = 338;
  ABILITY_SPIDER_LAIR = 339;
  ABILITY_FATAL_PRECISION = 340;
  ABILITY_FORT_KNOX = 341;
  ABILITY_SEAWEED = 342;
  ABILITY_PSYCHIC_MIND = 343;
  ABILITY_POISON_ABSORB = 344;
  ABILITY_SCAVENGER = 345;
  ABILITY_TWISTED_DIMENSION = 346;
  ABILITY_MULTI_HEADED = 347;
  ABILITY_NORTH_WIND = 348;
  ABILITY_OVERCHARGE = 349;
  ABILITY_VIOLENT_RUSH = 350;
  ABILITY_FLAMING_SOUL = 351;
  ABILITY_SAGE_POWER = 352;
  ABILITY_BONE_ZONE = 353;
  ABILITY_WEATHER_CONTROL = 354;
  ABILITY_SPEED_FORCE = 355;
  ABILITY_SEA_GUARDIAN = 356;
  ABILITY_MOLTEN_DOWN = 357;
  ABILITY_HYPER_AGGRESSIVE = 358;
  ABILITY_FLOCK = 359;
  ABILITY_FIELD_EXPLORER = 360;
  ABILITY_STRIKER = 361;
  ABILITY_FROZEN_SOUL = 362;
  ABILITY_PREDATOR = 363;
  ABILITY_LOOTER = 364;
  ABILITY_LUNAR_ECLIPSE = 365;
  ABILITY_SOLAR_FLARE = 366;
  ABILITY_POWER_CORE = 367;
  ABILITY_SIGHTING_SYSTEM = 368;
  ABILITY_BAD_COMPANY = 369;
  ABILITY_OPPORTUNIST = 370;
  ABILITY_GIANT_WINGS = 371;
  ABILITY_MOMENTUM = 372;
  ABILITY_GRIP_PINCER = 373;
  ABILITY_BIG_LEAVES = 374;
  ABILITY_PRECISE_FIST = 375;
  ABILITY_DEADEYE = 376;
  ABILITY_ARTILLERY = 377;
  ABILITY_AMPLIFIER = 378;
  ABILITY_ICE_DEW = 379;
  ABILITY_SUN_WORSHIP = 380;
  ABILITY_POLLINATE = 381;
  ABILITY_VOLCANO_RAGE = 382;
  ABILITY_COLD_REBOUND = 383;
  ABILITY_LOW_BLOW = 384;
  ABILITY_NOSFERATU = 385;
  ABILITY_SPECTRAL_SHROUD = 386;
  ABILITY_DISCIPLINE = 387;
  ABILITY_THUNDERCALL = 388;
  ABILITY_MARINE_APEX = 389;
  ABILITY_MIGHTY_HORN = 390;
  ABILITY_HARDENED_SHEATH = 391;
  ABILITY_ARCTIC_FUR = 392;
  ABILITY_SPECTRALIZE = 393;
  ABILITY_LETHARGY = 394;
  ABILITY_IRON_BARRAGE = 395;
  ABILITY_STEEL_BARREL = 396;
  ABILITY_PYRO_SHELLS = 397;
  ABILITY_FUNGAL_INFECTION = 398;
  ABILITY_PARRY = 399;
  ABILITY_SCRAPYARD = 400;
  ABILITY_LOOSE_QUILLS = 401;
  ABILITY_TOXIC_DEBRIS = 402;
  ABILITY_ROUNDHOUSE = 403;
  ABILITY_MINERALIZE = 404;
  ABILITY_LOOSE_ROCKS = 405;
  ABILITY_SPINNING_TOP = 406;
  ABILITY_RETRIBUTION_BLOW = 407;
  ABILITY_FEARMONGER = 408;
  ABILITY_KINGS_WRATH = 409;
  ABILITY_QUEENS_MOURNING = 410;
  ABILITY_TOXIC_SPILL = 411;
  ABILITY_DESERT_CLOAK = 412;
  ABILITY_DRACONIZE = 413;
  ABILITY_PRETTY_PRINCESS = 414;
  ABILITY_SELF_REPAIR = 415;
  ABILITY_ATOMIC_BURST = 416;
  ABILITY_HELLBLAZE = 417;
  ABILITY_RIPTIDE = 418;
  ABILITY_FOREST_RAGE = 419;
  ABILITY_PRIMAL_MAW = 420;
  ABILITY_SWEEPING_EDGE = 421;
  ABILITY_GIFTED_MIND = 422;
  ABILITY_HYDRO_CIRCUIT = 423;
  ABILITY_EQUINOX = 424;
  ABILITY_ABSORBANT = 425;
  ABILITY_CLUELESS = 426;
  ABILITY_CHEATING_DEATH = 427;
  ABILITY_CHEAP_TACTICS = 428;
  ABILITY_COWARD = 429;
  ABILITY_VOLT_RUSH = 430;
  ABILITY_DUNE_TERROR = 431;
  ABILITY_INFERNAL_RAGE = 432;
  ABILITY_DUAL_WIELD = 433;
  ABILITY_ELEMENTAL_CHARGE = 434;
  ABILITY_AMBUSH = 435;
  ABILITY_ATLAS = 436;
  ABILITY_RADIANCE = 437;
  ABILITY_JAWS_OF_CARNAGE = 438;
  ABILITY_ANGELS_WRATH = 439;
  ABILITY_PRISMATIC_FUR = 440;
  ABILITY_SHOCKING_JAWS = 441;
  ABILITY_FAE_HUNTER = 442;
  ABILITY_GRAVITY_WELL = 443;
  ABILITY_EVAPORATE = 444;
  ABILITY_LUMBERJACK = 445;
  ABILITY_WELL_BAKED_BODY = 446;
  ABILITY_FURNACE = 447;
  ABILITY_ELECTROMORPHOSIS = 448;
  ABILITY_ROCKY_PAYLOAD = 449;
  ABILITY_EARTH_EATER = 450;
  ABILITY_LINGERING_AROMA = 451;
  ABILITY_FAIRY_TALE = 452;
  ABILITY_RAGING_MOTH = 453;
  ABILITY_ADRENALINE_RUSH = 454;
  ABILITY_ARCHMAGE = 455;
  ABILITY_CRYOMANCY = 456;
  ABILITY_PHANTOM_PAIN = 457;
  ABILITY_PURGATORY = 458;
  ABILITY_EMANATE = 459;
  ABILITY_KUNOICHI_BLADE = 460;
  ABILITY_MONKEY_BUSINESS = 461;
  ABILITY_COMBAT_SPECIALIST = 462;
  ABILITY_JUNGLES_GUARD = 463;
  ABILITY_HUNTERS_HORN = 464;
  ABILITY_PIXIE_POWER = 465;
  ABILITY_PLASMA_LAMP = 466;
  ABILITY_MAGMA_EATER = 467;
  ABILITY_SUPER_HOT_GOO = 468;
  ABILITY_NIKA = 469;
  ABILITY_ARCHER = 470;
  ABILITY_COLD_PLASMA = 471;
  ABILITY_SUPER_SLAMMER = 472;
  ABILITY_INVERSE_ROOM = 473;
  ABILITY_ACCELERATE = 474;
  ABILITY_FROST_BURN = 475;
  ABILITY_ITCHY_DEFENSE = 476;
  ABILITY_GENERATOR = 477;
  ABILITY_MOON_SPIRIT = 478;
  ABILITY_DUST_CLOUD = 479;
  ABILITY_BERSERKER_RAGE = 480;
  ABILITY_TRICKSTER = 481;
  ABILITY_SAND_GUARD = 482;
  ABILITY_NATURAL_RECOVERY = 483;
  ABILITY_WIND_RIDER = 484;
  ABILITY_SOOTHING_AROMA = 485;
  ABILITY_PRIM_AND_PROPER = 486;
  ABILITY_SUPER_STRAIN = 487;
  ABILITY_TIPPING_POINT = 488;
  ABILITY_ENLIGHTENED = 489;
  ABILITY_PEACEFUL_SLUMBER = 490;
  ABILITY_AFTERSHOCK = 491;
  ABILITY_FREEZING_POINT = 492;
  ABILITY_CRYO_PROFICIENCY = 493;
  ABILITY_ARCANE_FORCE = 494;
  ABILITY_DOOMBRINGER = 495;
  ABILITY_WISHMAKER = 496;
  ABILITY_YUKI_ONNA = 497;
  ABILITY_SUPPRESS = 498;
  ABILITY_REFRIGERATOR = 499;
  ABILITY_HEAVEN_ASUNDER = 500;
  ABILITY_PURIFYING_WATERS = 501;
  ABILITY_SEABORNE = 502;
  ABILITY_HIGH_TIDE = 503;
  ABILITY_CHANGE_OF_HEART = 504;
  ABILITY_MYSTIC_BLADES = 505;
  ABILITY_DETERMINATION = 506;
  ABILITY_FERTILIZE = 507;
  ABILITY_PURE_LOVE = 508;
  ABILITY_FIGHTER = 509;
  ABILITY_MYCELIUM_MIGHT = 510;
  ABILITY_TELEKINETIC = 511;
  ABILITY_COMBUSTION = 512;
  ABILITY_PONY_POWER = 513;
  ABILITY_POWDER_BURST = 514;
  ABILITY_RETRIEVER = 515;
  ABILITY_MONSTER_MASH = 516;
  ABILITY_TWO_STEP = 517;
  ABILITY_SPITEFUL = 518;
  ABILITY_FORTITUDE = 519;
  ABILITY_DEVOURER = 520;
  ABILITY_PHANTOM_THIEF = 521;
  ABILITY_EARLY_GRAVE = 522;
  ABILITY_GRAPPLER = 523;
  ABILITY_BASS_BOOSTED = 524;
  ABILITY_FLAMING_JAWS = 525;
  ABILITY_MONSTER_HUNTER = 526;
  ABILITY_CROWNED_SWORD = 527;
  ABILITY_CROWNED_SHIELD = 528;
  ABILITY_BERSERK_DNA = 529;
  ABILITY_CROWNED_KING = 530;
  ABILITY_SNAP_TRAP_WHEN_HIT = 531;
  ABILITY_PERMANENCE = 532;
  ABILITY_HUBRIS = 533;
  ABILITY_COSMIC_DAZE = 534;
  ABILITY_MINDS_EYE = 535;
  ABILITY_BLOOD_PRICE = 536;
  ABILITY_SPIKE_ARMOR = 537;
  ABILITY_VOODOO_POWER = 538;
  ABILITY_CHROME_COAT = 539;
  ABILITY_BANSHEE = 540;
  ABILITY_WEB_SPINNER = 541;
  ABILITY_SHOWDOWN_MODE = 542;
  ABILITY_SEED_SOWER = 543;
  ABILITY_AIRBORNE = 544;
  ABILITY_PARROTING = 545;
  ABILITY_SALT_CIRCLE = 546;
  ABILITY_PURIFYING_SALT = 547;
  ABILITY_PROTOSYNTHESIS = 548;
  ABILITY_QUARK_DRIVE = 549;
  ABILITY_WIND_POWER = 550;
  ABILITY_IMPULSE = 551;
  ABILITY_TERMINAL_VELOCITY = 552;
  ABILITY_GUARD_DOG = 553;
  ABILITY_ANGER_SHELL = 554;
  ABILITY_EGOIST = 555;
  ABILITY_SUBDUE = 556;
  ABILITY_READIED_ACTION = 557;
  ABILITY_DARK_GALE_WINGS = 558;
  ABILITY_GUILT_TRIP = 559;
  ABILITY_WATER_GALE_WINGS = 560;
  ABILITY_ZERO_TO_HERO = 561;
  ABILITY_COSTAR = 562;
  ABILITY_COMMANDER = 563;
  ABILITY_EJECT_PACK_ABILITY = 564;
  ABILITY_VENGEFUL_SPIRIT = 565;
  ABILITY_CUD_CHEW = 566;
  ABILITY_ARMOR_TAIL = 567;
  ABILITY_MIND_CRUSH = 568;
  ABILITY_SUPREME_OVERLORD = 569;
  ABILITY_ILL_WILL = 570;
  ABILITY_FIRE_SCALES = 571;
  ABILITY_WATCH_YOUR_STEP = 572;
  ABILITY_RAPID_RESPONSE = 573;
  ABILITY_DOUBLE_IRON_BARBS = 574;
  ABILITY_THERMAL_EXCHANGE = 575;
  ABILITY_GOOD_AS_GOLD = 576;
  ABILITY_SHARING_IS_CARING = 577;
  ABILITY_TABLETS_OF_RUIN = 578;
  ABILITY_SWORD_OF_RUIN = 579;
  ABILITY_VESSEL_OF_RUIN = 580;
  ABILITY_BEADS_OF_RUIN = 581;
  ABILITY_PERMAFROST_CLONE = 582;
  ABILITY_GALLANTRY = 583;
  ABILITY_ORICHALCUM_PULSE = 584;
  ABILITY_SUN_BASKING = 585;
  ABILITY_WINGED_KING = 586;
  ABILITY_HADRON_ENGINE = 587;
  ABILITY_IRON_SERPENT = 588;
  ABILITY_WEATHER_DOUBLE_BOOST = 589;
  ABILITY_SWEEPING_EDGE_PLUS = 590;
  ABILITY_CELESTIAL_BLESSING = 591;
  ABILITY_MINION_CONTROL = 592;
  ABILITY_MOLTEN_BLADES = 593;
  ABILITY_HAUNTING_FRENZY = 594;
  ABILITY_NOISE_CANCEL = 595;
  ABILITY_RADIO_JAM = 596;
  ABILITY_OLE = 597;
  ABILITY_MALICIOUS = 598;
  ABILITY_DEAD_POWER = 599;
  ABILITY_BRAWLING_WYVERN = 600;
  ABILITY_MYTHICAL_ARROWS = 601;
  ABILITY_LAWNMOWER = 602;
  ABILITY_FLOURISH = 603;
  ABILITY_DESERT_SPIRIT = 604;
  ABILITY_CONTEMPT = 605;
  ABILITY_AERIALIST = 606;
  ABILITY_TERA_SHELL = 607;
  ABILITY_TOXIC_CHAIN = 608;
  ABILITY_PARASITIC_SPORES = 609;
  ABILITY_POISON_PUPPETEER = 610;
  ABILITY_ENTRANCE = 611;
  ABILITY_REJECTION = 612;
  ABILITY_APPLE_ENLIGHTENMENT = 613;
  ABILITY_BALLOON_BOMBER = 614;
  ABILITY_FLAMING_MAW = 615;
  ABILITY_DEMOLITIONIST = 616;
  ABILITY_ROCKHARD_WILL = 617;
  ABILITY_FRAGRANT_DAZE = 618;
  ABILITY_LOW_VISIBILITY = 619;
  ABILITY_OLD_MARINER = 620;
  ABILITY_ECTOPLASM = 621;
  ABILITY_BEAUTIFUL_MUSIC = 622;
  ABILITY_SURPRISE = 623;
  ABILITY_SNOW_SONG = 624;
  ABILITY_GREATER_SPIRIT = 625;
  ABILITY_RESONANCE = 626;
  ABILITY_ETHEREAL_RUSH = 627;
  ABILITY_CUTE_ANTECEDENCE = 628;
  ABILITY_RECURRING_NIGHTMARE = 629;
  ABILITY_MENACING_SITUATION = 630;
  ABILITY_SHINY_LIGHTNING = 631;
  ABILITY_TERRIFY = 632;
  ABILITY_ICE_DOWNFALL = 633;
  ABILITY_LAST_STAND = 634;
  ABILITY_PYROCLASTIC_FLOW = 635;
  ABILITY_BLOOD_BATH = 636;
  ABILITY_BATTLE_AURA = 637;
  ABILITY_BLOODLUST = 638;
  ABILITY_PIERCING_SOLO = 639;
  ABILITY_RHYTHMIC = 640;
  ABILITY_CHUNKY_BASS_LINE = 641;
  ABILITY_DUAL_HAMMER = 642;
  ABILITY_DENTING_BLOWS = 643;
  ABILITY_ICE_COLD_HUNTER = 644;
  ABILITY_SOUL_CRUSHER = 645;
  ABILITY_ARC_FLASH = 646;
  ABILITY_UNICORN = 647;
  ABILITY_ON_THE_PROWL = 648;
  ABILITY_PRETENTIOUS = 649;
  ABILITY_VENOBLAZE_PINCERS = 650;
  ABILITY_ETERNAL_BLESSING = 651;
  ABILITY_SUGAR_RUSH = 652;
  ABILITY_PEACEFUL_REST = 653;
  ABILITY_WHITE_NOISE = 654;
  ABILITY_SMOKEY_MANEUVERS = 655;
  ABILITY_TAG = 656;
  ABILITY_POWER_METAL = 657;
  ABILITY_POWER_EDGE = 658;
  ABILITY_SUPERCONDUCTOR = 659;
  ABILITY_ULTRA_INSTINCT = 660;
  ABILITY_UNLOCKED_POTENTIAL = 661;
  ABILITY_HIGHER_RANK = 662;
  ABILITY_FUNERAL_PYRE = 663;
  ABILITY_FLAME_BUBBLE = 664;
  ABILITY_ELEMENTAL_VORTEX = 665;
  ABILITY_SNOWY_WRATH = 666;
  ABILITY_PATTERN_CHANGE = 667;
  ABILITY_NO_TURNING_BACK = 668;
  ABILITY_FLAMMABLE_COAT = 669;
  ABILITY_DRACO_MORALE = 670;
  ABILITY_BAD_OMEN = 671;
  ABILITY_MOSH_PIT = 672;
  ABILITY_BLOOD_STAIN = 673;
  ABILITY_BLOOD_STIGMA = 674;
  ABILITY_MAXIMUM_ACCELERATION = 675;
  ABILITY_SIDEWINDER = 676;
  ABILITY_PETRIFY = 677;
  ABILITY_FLUFFIEST = 678;
  ABILITY_WAY_OF_PRECISION = 679;
  ABILITY_WAY_OF_SWIFTNESS = 680;
  ABILITY_ATOMIC_PUNCH = 681;
  ABILITY_IRON_GIANT = 682;
  ABILITY_MASTER_HAND = 683;
  ABILITY_FINAL_BLOW = 684;
  ABILITY_HOSPITALITY = 685;
  ABILITY_BUTTER_UP = 686;
  ABILITY_VITALITY_STRIKE = 687;
  ABILITY_HUGE_WINGS = 688;
  ABILITY_SWORD_OF_DAMNATION = 689;
  ABILITY_RESTRAINING_ORDER = 690;
  ABILITY_ASSASSINS_TOOLS = 691;
  ABILITY_FROSTMAW = 692;
  ABILITY_PATCHWORK = 693;
  ABILITY_BLIND_RAGE = 694;
  ABILITY_SLIPSTREAM = 695;
  ABILITY_APEX_PREDATOR = 696;
  ABILITY_DRAGONS_RITUAL = 697;
  ABILITY_PINNACLE_BLADE = 698;
  ABILITY_ENERGIZED = 699;
  ABILITY_COLOR_SPECTRUM = 700;
  ABILITY_STEEL_BEETLE = 701;
  ABILITY_FROM_THE_SHADOWS = 702;
  ABILITY_RAGE_POINT = 703;
  ABILITY_HOT_COALS = 704;
  ABILITY_TERASTAL_TREASURE = 705;
  ABILITY_SHOCKING_MAW = 706;
  ABILITY_GLEAM_EYES = 707;
  ABILITY_ROUSED_FANGS = 708;
  ABILITY_DREAM_STATE = 709;
  ABILITY_DREAM_WHIMSY = 710;
  ABILITY_LUNAR_AFFINITY = 711;
  ABILITY_FLAME_SHIELD = 712;
  ABILITY_AQUATIC_DWELLER = 713;
  ABILITY_APPLE_PIE = 714;
  ABILITY_HOVER = 715;
  ABILITY_DEPRAVITY = 716;
  ABILITY_WILDFIRE = 717;
  ABILITY_JUMP_SCARE = 718;
  ABILITY_TAR_TOSS = 719;
  ABILITY_STUN_SHOCK = 720;
  ABILITY_RAGING_GODDESS = 721;
  ABILITY_WHIPLASH = 722;
  ABILITY_SUPERSWEET_SYRUP = 723;
  ABILITY_LUCKY_HALO = 724;
  ABILITY_TRASH_HEAP = 725;
  ABILITY_SLUDGY_MIX = 726;
  ABILITY_OVERWATCH = 727;
  ABILITY_WIND_RAGE = 728;
  ABILITY_VICTORY_BOMB = 729;
  ABILITY_RAZOR_SHARP = 730;
  ABILITY_TO_THE_BONE = 731;
  ABILITY_BLADE_DANCE = 732;
  ABILITY_TAEKKYEON = 733;
  ABILITY_APE_SHIFT = 734;
  ABILITY_KNOW_YOUR_PLACE = 735;
  ABILITY_DEEP_CUTS = 736;
  ABILITY_LIFE_STEAL = 737;
  ABILITY_RUDE_AWAKENING = 738;
  ABILITY_TERAFORM_ZERO = 739;
  ABILITY_SET_ABLAZE = 740;
  ABILITY_BREAKWATER = 741;
  ABILITY_MAGICAL_FISTS = 742;
  ABILITY_CUTTHROAT = 743;
  ABILITY_SAND_BENDER = 744;
  ABILITY_SAND_PIT = 745;
  ABILITY_DESOLATE_SUN = 746;
  ABILITY_DAYBREAK = 747;
  ABILITY_ENERGY_SIPHON = 748;
  ABILITY_RESERVOIR = 749;
  ABILITY_NEUROTOXIN = 750;
  ABILITY_ENERGIZED_HORNS = 751;
  ABILITY_SPIDER_LAIR_UPGRADE = 752;
  ABILITY_CRUST_COAT = 753;
  ABILITY_PUFFY = 754;
  ABILITY_BALLOON_BLITZ = 755;
  ABILITY_STRIKER_PIXILATE = 756;
  ABILITY_DOOM_BLAST = 757;
  ABILITY_BRUTEFORCE = 758;
  ABILITY_FARADAY_CAGE = 759;
  ABILITY_ACIDIC_SLIME = 760;
  ABILITY_ROSE_GARDEN = 761;
  ABILITY_QIGONG = 762;
  ABILITY_CONJOURER_OF_DECEIT = 763;
  ABILITY_DEEP_FREEZE = 764;
  ABILITY_SOUL_DEVOURER = 765;
  ABILITY_CHAMPIONS_ENTRANCE = 766;
  ABILITY_PRESTO = 767;
  ABILITY_SAMBA = 768;
  ABILITY_JUNSHI_SANDA = 769;
  ABILITY_GLADIATOR = 770;
  ABILITY_FORSAKEN_HEART = 771;
  ABILITY_RELENTLESS = 772;
  ABILITY_SOOTHSAYER = 773;
  ABILITY_CORRUPTED_MIND = 774;
  ABILITY_FLAME_COAT = 775;
  ABILITY_UNOWN_POWER = 776;
  ABILITY_SUPER_SCOPE = 777;
  ABILITY_VENOM_CROWN = 778;
  ABILITY_BLIGHT_SCALE = 779;
  ABILITY_GUNMAN = 780;
  ABILITY_HUNTERS_MARK = 781;
  ABILITY_HEMOLYSIS = 782;
  ABILITY_CARETAKER = 783;
  ABILITY_POSEIDONS_DOMINION = 784;
  ABILITY_DUAL_SHADOW = 785;
  ABILITY_LULLABY = 786;
  ABILITY_CRYO_ARCHITECT = 787;
  ABILITY_GLACIAL_RAGE = 788;
  ABILITY_IMMOVABLE_OBJECT = 789;
  ABILITY_FRENZIED_PHANTOM = 790;
  ABILITY_DNA_SCRAMBLE = 791;
  ABILITY_METALLIC_JAWS = 792;
  ABILITY_CALCULATIVE = 793;
  ABILITY_DEADLY_PRECISION = 794;
  ABILITY_EMBODY_ASPECT = 795;
  ABILITY_EMBODY_ASPECT_HEARTHFLAME = 796;
  ABILITY_EMBODY_ASPECT_CORNERSTONE = 797;
  ABILITY_EMBODY_ASPECT_WELLSPRING = 798;
  ABILITY_ROCKHARD_SHAFT = 799;
  ABILITY_DEVIATE = 800;
  ABILITY_SUNS_BOUNTY = 801;
  ABILITY_RITE_OF_SPRING = 802;
  ABILITY_HEADSTRONG = 803;
  ABILITY_FIREFIGHTER = 804;
  ABILITY_SEPIA_LENS = 805;
  ABILITY_SUPER_SNIPER = 806;
  ABILITY_WOODLAND_CURSE = 807;
  ABILITY_MALODOR = 808;
  ABILITY_BLUR = 809;
  ABILITY_ELUDE = 810;
  ABILITY_DRAKE_OF_RAGE = 811;
  ABILITY_REVERBATE = 812;
  ABILITY_MIXED_MARTIAL_ARTS = 813;
  ABILITY_STRATEGIC_PAUSE = 814;
  ABILITY_OVERRULE = 815;
  ABILITY_MENTAL_POLLUTION = 816;
  ABILITY_MADNESS_ENHANCEMENT = 817;
  ABILITY_TENTALOCK = 818;
  ABILITY_SERPENT_BIND = 819;
  ABILITY_SOUL_TAP = 820;
  ABILITY_SCARECROW = 821;
  ABILITY_OMINOUS_SHROUD = 822;
  ABILITY_CHILLING_PRESENCE = 823;
  ABILITY_FROSTBIND = 824;
  ABILITY_GLACIAL_GHOST = 825;
  ABILITY_TENDER_AFFECTION = 826;
  ABILITY_WONDER_SCALE = 827;
  ABILITY_OVERZEALOUS = 828;
  ABILITY_STAINLESS_STEEL = 829;
  ABILITY_TEMPORAL_RUPTURE = 830;
  ABILITY_GRASS_FLUTE = 831;
  ABILITY_HEMOTOXIN = 832;
  ABILITY_HARUKAZE = 833;
  ABILITY_TOXIC_SURGE = 834;
  ABILITY_ATLANTIC_RULER = 835;
  ABILITY_BIOFILM = 836;
  ABILITY_CHOKEHOLD = 837;
  ABILITY_GUARDIAN_COAT = 838;
  ABILITY_NEUTRALIZING_FOG = 839;
  ABILITY_POISON_QUILLS = 840;
  ABILITY_DRACONIC_MIGHT = 841;
  ABILITY_FESTIVITIES = 842;
  ABILITY_FEY_FLIGHT = 843;
  ABILITY_BEST_OFFENSE = 844;
  ABILITY_IMPALER = 845;
  ABILITY_MAGUS_BLADES = 846;
  ABILITY_LIGHTNING_BORN = 847;
  ABILITY_SUPERHEAVY = 848;
  ABILITY_WORLD_SERPENT = 849;
  ABILITY_LUCKY_WINGS = 850;
  ABILITY_KOMODO = 851;
  ABILITY_ENVENOM = 852;
  ABILITY_PURPLE_HAZE = 853;
  ABILITY_GNASHING_CANNON = 854;
  ABILITY_HYPER_CLEANSE = 855;
  ABILITY_MOLTEN_COAT = 856;
  ABILITY_ROYAL_DECREE = 857;
  ABILITY_BREEZY_NEIGH = 858;
  ABILITY_DREAMSCAPE = 859;
  ABILITY_HASTE_MAKES_WASTE = 860;
  ABILITY_HUNGRY_MAWS = 861;
  ABILITY_THERMAL_SLIDE = 862;
  ABILITY_THERMOMANCY = 863;
  ABILITY_CHUCKSTER = 864;
  ABILITY_HEAT_SINK = 865;
  ABILITY_RELIC_STONE = 866;
  ABILITY_SUPERCELL = 867;
  ABILITY_LIGHTNING_ASPECT = 868;
  ABILITY_BLISTERING_SUN = 869;
  ABILITY_MOLTEN_CORE = 870;
  ABILITY_FIRE_ASPECT = 871;
  ABILITY_AURORAS_GALE = 872;
  ABILITY_ICE_PLUMES = 873;
  ABILITY_WINTER_THRONE = 874;
  ABILITY_ENERGY_TAP = 875;
  ABILITY_SLUDGE_SPIT = 876;
  ABILITY_SWAMP_THING = 877;
  ABILITY_FROSTY_PRESCENCE = 878;
  ABILITY_CHILLING_PELLETS = 879;
  ABILITY_PAINT_SHOT = 880;
  ABILITY_STONECUTTER = 881;
  ABILITY_EDGELORD = 882;
  ABILITY_WARMONGER = 883;
  ABILITY_LOCUST_SWARM = 884;
  ABILITY_REVELATION = 885;
  ABILITY_CURSE_OF_FAMINE = 886;
  ABILITY_CRYSTALLINE_ARMOR = 887;
  ABILITY_SOUL_HARVEST = 888;
  ABILITY_THICK_BLUBBER = 889;
  ABILITY_CRAVING = 890;
  ABILITY_RAT_KING = 891;
  ABILITY_CRISPY_CREAM = 892;
  ABILITY_DEEP_FRIED = 893;
  ABILITY_FOOD_LOVERS = 894;
  ABILITY_LUNAR_WRATH = 895;
  ABILITY_SPYWARE = 896;
  ABILITY_VIRUS = 897;
  ABILITY_POWER_LEAK = 898;
  ABILITY_BACKUP_POWER = 899;
  ABILITY_SAND_FIEND = 900;
  ABILITY_MOUSTACHE = 901;
  ABILITY_DEPTH_EXPLORER = 902;
  ABILITY_DUNE_VEIL = 903;
  ABILITY_STRONG_FOUNDATION = 904;
  ABILITY_FOG_MACHINE = 905;
  ABILITY_DROP_BLOCKS = 906;
  ABILITY_LASER_DRILL = 907;
  ABILITY_LIGHT_SABER = 908;
  ABILITY_LOOSE_THORNS = 909;
  ABILITY_TURF_WAR = 910;
  ABILITY_GREEDY = 911;
  ABILITY_MUSICAL_NOTES = 912;
  ABILITY_STRIKEOUT = 913;
  ABILITY_HOME_RUN = 914;
  ABILITY_BRUISER = 915;
  ABILITY_NARCISSIST = 916;
  ABILITY_LETS_DANCE = 917;
  ABILITY_DRAGONFRUIT = 918;
  ABILITY_LEAD_CLAWS = 919;
  ABILITY_ROCKY_EXTERIOR = 920;
  ABILITY_FLAWLESS_PRECISION = 921;
  ABILITY_EMPRESS = 922;
  ABILITY_MASHED_POTATO = 923;
  ABILITY_TASTE_THE_RAINBOW = 924;
  ABILITY_RAINBOW_SCALES = 925;
  ABILITY_HYPNOTIC_TOUCH = 926;
  ABILITY_WINGS_OF_PESTILENCE = 927;
  ABILITY_HYDRA = 928;
  ABILITY_SUNDAE = 929;
  ABILITY_ICE_PICK = 930;
  ABILITY_HAMMER_FIST = 931;
  ABILITY_MACH_3 = 934;
  ABILITY_RAGING_STORM = 935;
  ABILITY_SUMO_GUARD = 936;
  ABILITY_SUMO_WRESTLER = 937;
  ABILITY_COSMIC_WINGS = 938;
  ABILITY_COSMIC_DUST = 939;
  ABILITY_COOL_EXIT = 940;
  ABILITY_DEVIOUS_PRESENT = 941;
  ABILITY_CHRISTMAS_NIGHTMARE = 942;
  ABILITY_SAP_TRAP = 943;
  ABILITY_BARK_SKIN = 944;
  ABILITY_CHAINSAW = 945;
  ABILITY_GALEFORCE_WINGS = 946;
  ABILITY_ECHOLOCATION = 947;
  ABILITY_MASSIVE_PELT = 948;
  ABILITY_I_AM_STEVE = 949;
  ABILITY_TANGLED_TAILS = 950;
  ABILITY_FOAMY_WEB = 951;
  ABILITY_SHARP_TALONS = 952;
  ABILITY_ZEN_GARDEN = 953;
  ABILITY_TUMMYACHE = 954;
  ABILITY_HYPNOTIC_TRANCE = 955;
  ABILITY_BRAIN_OVERLOAD = 956;
  ABILITY_BRAIN_MASS = 957;
  ABILITY_CHESTNUT_SHIELD = 958;
  ABILITY_CHESTNUT_AXE = 959;
  ABILITY_GIANT_SHURIKEN = 960;
  ABILITY_WITCH_BROOM = 961;
  ABILITY_ANGELIC_WINGS = 962;
  ABILITY_WRESTLE_SHOWMAN = 963;
  ABILITY_LUCHA_LIBRE = 964;
  ABILITY_FIRE_RULER = 965;
  ABILITY_CHANDELIER = 966;
  ABILITY_FOGGY_EYE = 967;
  ABILITY_TOXIC_SHELL = 968;
  ABILITY_HAND_BARNACLES = 969;
  ABILITY_VOLTRON = 970;
  ABILITY_FIRES_WRATH = 971;
  ABILITY_EMPERORS_WRATH = 972;
  ABILITY_LEPIDOPTERAN = 973;
  ABILITY_BREAK_IT_DOWN = 974;
  ABILITY_TALON_TRAP = 975;
  ABILITY_BACKSTREET_BOY = 976;
  ABILITY_BACKFLIP = 977;
  ABILITY_CRUSHING_JAW = 978;
  ABILITY_ETERNAL_FLOWER = 979;
  ABILITY_NIHIL_BLASTER = 980;
  ABILITY_HOLLOW_ICE_ZONE = 981;
  ABILITY_CRYOSTASIS = 982;
  ABILITY_OVERCAST = 983;
  ABILITY_FLOWER_NECKLACE = 984;
  ABILITY_MEGA_DRILL = 985;
  ABILITY_MUCUS_MEMBRANE = 986;
  ABILITY_RAIN_SHROUD = 987;
  ABILITY_CURLIPEDE = 988;
}
