syntax = "proto3";

package er;

option java_package = "er.proto";
option java_multiple_files = true;

enum BattleSkillEnum {
  SKILL_NONE = 0;
  SKILL_EVIOLITE = 1;
  SKILL_STICKY_WEB = 2;
  SKILL_SPIKES_1_LAYER = 3;
  SKILL_ON_ENTRY_LEECH_SEED = 4;
  SKILL_EXTRA_ABILITY_UNNERVE = 5;
  SKILL_EXTRA_ABILITY_INNARDS_OUT = 6;
  SKILL_EXTRA_ABILITY_CUTE_CHARM = 7;
  SKILL_TOXIC_SPIKES_2_LAYERS = 8;
  SKILL_EXTRA_ABILITY_FILTER = 9;
  SKILL_EXTRA_ABILITY_SWORD_OF_RUIN = 10;
  SKILL_HAZARDS_ALL = 11;
  SKILL_ON_END_TURN_MOVE_JUDGEMENT_60_BP = 12;
  SKILL_EXTRA_ABILITY_SWARM = 13;
  SKILL_EXTRA_ABILITY_SUPER_LUCK = 14;
  SKILL_ON_SWITCH_MOVE_PAYDAY = 15;
  SKILL_EXTRA_ABILITY_FLASH_FIRE = 16;
  SKILL_NO_CRIT = 17;
  SKILL_ON_ENTRY_DEF_UP_4 = 18;
  SKILL_ON_END_TURN_DEF_UP_1 = 19;
  SKILL_STEALTH_ROCKS = 20;
  SKILL_PLAYER_BLEED = 21;
  SKILL_ON_ENTRY_OMNIBOOST_2 = 22;
  SKILL_LEFTOVERS = 23;
  SKILL_EXTRA_ABILITY_PRESSURE = 24;
  SKILL_ON_END_TURN_HEAL_STATUS_30_PERCENT = 25;
  SKILL_EXTRA_ABILITY_SHIELD_DUST = 26;
  SKILL_BURN_BOTH_SIDES = 27;
  SKILL_ON_ENTRY_SPDEF_UP_1 = 28;
  SKILL_SUN = 29;
  SKILL_INVERSE_ROOM = 30;
  SKILL_FOCUS_SASH = 31;
  SKILL_STICKY_WEB_BOTH_SIDES = 32;
  SKILL_RAINBOW = 33;
  SKILL_SAND = 34;
  SKILL_ON_END_TURN_MOVE_TICKLE = 35;
  SKILL_EXTRA_ABILITY_EMPERORS_WRATH = 36;
  SKILL_FAINT_TAILWIND = 37;
  SKILL_EXTRA_ABILITY_SMOKEY_MANEUVERS = 38;
  SKILL_ON_ENTRY_POWER_TRICK_BOTH_SIDES = 39;
  SKILL_EXTRA_ABILITY_COMATOSE = 40;
  SKILL_EXTRA_ABILITY_SWEET_DREAMS = 41;
  SKILL_ON_HIT_DEFENDER_SLEEP_ATTACKER = 42;
  SKILL_EXTRA_ABILITY_CATASTROPHE = 43;
  SKILL_EXTRA_ABILITY_SUN_WORSHIP = 44;
  SKILL_EXTRA_ABILITY_ACCELERATE = 45;
  SKILL_EXTRA_ABILITY_ANALYTIC = 46;
  SKILL_ON_ENTRY_OMNIBOOST_1 = 47;
  SKILL_DOUBLE_POWER_WATER = 48;
  SKILL_DISABLE_ABILITIES_AFTER_2_TURNS = 49;
  SKILL_HALF_HP_SPEED_UP_1 = 50;
  SKILL_ALLIES_SHARE_STAT_CHANGES = 51;
  SKILL_ALLIES_50_PERCENT_DAMAGE_REDUCTION = 52;
  SKILL_DOUBLE_POWER_FIGHTING = 53;
  SKILL_SPDEF_DEF_UP_4 = 54;
  SKILL_EXTRA_ABILITY_KNOW_YOUR_PLACE = 55;
  SKILL_FOLLOWUP_MOVE_PEBBLE_SHOWER = 56;
  SKILL_ON_END_TURN_MOVE_ANCIENT_POWER = 57;
  SKILL_ON_CONTACT_DEFENDER_SPEED_UP_2 = 58;
  SKILL_SWAMP = 59;
  SKILL_SUPER_EFFECTIVE_50_PERCENT_DAMAGE_REDUCTION = 60;
  SKILL_ON_KO_HEAL_50_PERCENT_HP = 61;
  SKILL_ON_ENTRY_MOVE_MEAN_LOOK = 62;
  SKILL_RAIN = 63;
  SKILL_ON_END_TURN_MOVE_RECYCLE = 64;
  SKILL_EXTRA_ABILITY_STICKY_HOLD = 65;
  SKILL_PERMANENT_HAZARDS = 66;
  SKILL_EXTRA_ABILITY_MYSTIC_POWER = 67;
  SKILL_EXTRA_ABILITY_PRIMORDIAL_SEA = 68;
  SKILL_ROOM_ROULETTE = 69;
  SKILL_FOLLOWUP_MOVE_NIGHT_SHADE = 70;
  SKILL_ON_END_EVERY_2_TURNS_MOVE_WATER_PLEDGE = 71;
  SKILL_MIST = 72;
  SKILL_ON_ENTRY_MOVE_MAGNET_RISE = 73;
  SKILL_EXPERT_BELT = 74;
  SKILL_QUICK_CLAW_100_PERCENT = 75;
  SKILL_STAB_MOVES_ARE_STATUS_MOVES = 76;
  SKILL_ON_END_TURN_PLAYER_DAMAGE_ONE_EIGHTEENTH = 77;
  SKILL_ON_END_TURN_MOVE_REFRESH = 78;
  SKILL_ON_START_TURN_TOXIC_BOTH_SIDES = 79;
  SKILL_ON_ENTRY_PLAYER_HEAL_BLOCK = 80;
  SKILL_ON_PLAYER_STAT_BOOSTING_MOVE_MOVE_SCRATCH = 81;
  SKILL_COPY_DANCE_MOVES_BOTH_SIDES = 82;
  SKILL_PLAYER_RING_TARGET = 83;
}
