syntax = "proto3";

package er;

option java_package = "er.proto";
option java_multiple_files = true;

enum BattleSkillEnum {
  BATTLE_SKILL_NONE = 0;
  BATTLE_SKILL_MOVE_ON_ENTRY = 1;
  BATTLE_SKILL_MOVE_EVERY_N_TURNS = 2;
  BATTLE_SKILL_MOVE_ON_SWITCH = 3;
  BATTLE_SKILL_MOVE_ON_HIT_BY_PLAYER = 4;
  BATTLE_SKILL_MOVE_ON_SWITCH_PLAYER = 5;
  BATTLE_SKILL_MOVE_FOLLOW_UP = 6;
  BATTLE_SKILL_MOVE_ON_STAT_UP_PLAYER = 7;
  BATTLE_SKILL_MOVE_ON_FAINT = 8;
  BATTLE_SKILL_MOVE_EVERY_N_TURNS_ALL = 9;
  BATTLE_SKILL_MOVE_ON_ENTRY_ALL = 10;
  BATTLE_SKILL_STAT_ON_ENTRY = 11;
  BATTLE_SKILL_STAT_EVERY_TURN = 12;
  BATTLE_SKILL_STAT_ON_UNDER_HP = 13;
  BATTLE_SKILL_STAT_ON_HIT_BY_CONTACT = 14;
  BATTLE_SKILL_STAT_RAISE_DOUBLED = 15;
  BATTLE_SKILL_STAT_DROP_CURED = 16;
  BATTLE_SKILL_STAT_DROP_SHARED = 17;
  BATTLE_SKILL_STICKY_WEB = 18;
  BATTLE_SKILL_SPIKES = 19;
  BATTLE_SKILL_TOXIC_SPIKES = 20;
  BATTLE_SKILL_STEALTH_ROCKS = 21;
  BATTLE_SKILL_ALL_HAZARD = 22;
  BATTLE_SKILL_SUN = 23;
  BATTLE_SKILL_RAIN = 24;
  BATTLE_SKILL_SANDSTORM = 25;
  BATTLE_SKILL_HAIL = 26;
  BATTLE_SKILL_RAINBOW = 27;
  BATTLE_SKILL_SWAMP = 28;
  BATTLE_SKILL_FIRE_SEA = 29;
  BATTLE_SKILL_ELECTRIC_TERRAIN = 30;
  BATTLE_SKILL_MISTY_TERRAIN = 31;
  BATTLE_SKILL_GRASSY_TERRAIN = 32;
  BATTLE_SKILL_PSYCHIC_TERRAIN = 33;
  BATTLE_SKILL_TAILWIND = 34;
  BATTLE_SKILL_TAILWIND_ON_FAINT = 35;
  BATTLE_SKILL_MIST = 36;
  BATTLE_SKILL_INVERSE_ROOM = 37;
  BATTLE_SKILL_EXTRA_ABILITY = 38;
}
