syntax = "proto3";

package er;

import "SpeciesEnum.proto";
import "MoveEnum.proto";
import "TrainerList.proto";
import "AbilityEnum.proto";

option java_package = "er.proto";
option java_multiple_files = true;

message BattleFrontierSet {
  enum DoublesSets {
    SINGLES_OR_DOUBLES = 0;
    SINGLES_ONLY = 1;
    DOUBLES_ONLY = 2;
  }

  DoublesSets allowed_formats = 1;
  bool restricted = 2;
  optional Nature nature = 3;
  AbilityEnum ability = 4;
  repeated MoveEnum move = 5;

  bool hp_up = 6;
  bool atk_up = 7;
  bool def_up = 8;
  bool spatk_up = 9;
  bool spdef_up = 10;
  bool speed_up = 11;
  string illegal = 12;
}

message BattleFrontierList {
  message BattleFrontierMon {
    SpeciesEnum id = 1;
    repeated BattleFrontierSet set = 2;
  }
  repeated BattleFrontierMon species = 1;
}