syntax = "proto3";

package er;

option java_package = "er.proto";
option java_multiple_files = true;

enum ItemEnum {
  ITEM_NONE = 0;
  ITEM_MASTER_BALL = 1;
  ITEM_ULTRA_BALL = 2;
  ITEM_GREAT_BALL = 3;
  ITEM_POKE_BALL = 4;
  ITEM_SAFARI_BALL = 5;
  ITEM_NET_BALL = 6;
  ITEM_DIVE_BALL = 7;
  ITEM_NEST_BALL = 8;
  ITEM_REPEAT_BALL = 9;
  ITEM_TIMER_BALL = 10;
  ITEM_LUXURY_BALL = 11;
  ITEM_DUSK_BALL = 12;
  ITEM_HEAL_BALL = 13;
  ITEM_QUICK_BALL = 14;
  ITEM_CHERISH_BALL = 15;
  ITEM_FAST_BALL = 16;
  ITEM_LEVEL_BALL = 17;
  ITEM_LURE_BALL = 18;
  ITEM_HEAVY_BALL = 19;
  ITEM_LOVE_BALL = 20;
  ITEM_FRIEND_BALL = 21;
  ITEM_MOON_BALL = 22;
  ITEM_SPORT_BALL = 23;
  ITEM_PARK_BALL = 24;
  ITEM_DREAM_BALL = 25;
  ITEM_BEAST_BALL = 26;
  ITEM_PREMIER_BALL = 27;
  ITEM_POTION = 28;
  ITEM_ANTIDOTE = 29;
  ITEM_BURN_HEAL = 30;
  ITEM_ICE_HEAL = 31;
  ITEM_AWAKENING = 32;
  ITEM_PARALYZE_HEAL = 33;
  ITEM_FULL_RESTORE = 34;
  ITEM_MAX_POTION = 35;
  ITEM_HYPER_POTION = 36;
  ITEM_SUPER_POTION = 37;
  ITEM_FULL_HEAL = 38;
  ITEM_REVIVE = 39;
  ITEM_MAX_REVIVE = 40;
  ITEM_FRESH_WATER = 41;
  ITEM_SODA_POP = 42;
  ITEM_LEMONADE = 43;
  ITEM_MOOMOO_MILK = 44;
  ITEM_ENERGY_POWDER = 45;
  ITEM_ENERGY_ROOT = 46;
  ITEM_HEAL_POWDER = 47;
  ITEM_REVIVAL_HERB = 48;
  ITEM_ETHER = 49;
  ITEM_MAX_ETHER = 50;
  ITEM_ELIXIR = 51;
  ITEM_MAX_ELIXIR = 52;
  ITEM_LAVA_COOKIE = 53;
  ITEM_BERRY_JUICE = 54;
  ITEM_SWEET_HEART = 55;
  ITEM_BIG_MALASADA = 56;
  ITEM_OLD_GATEAU = 57;
  ITEM_SACRED_ASH = 58;
  ITEM_HP_UP = 59;
  ITEM_PROTEIN = 60;
  ITEM_IRON = 61;
  ITEM_CARBOS = 62;
  ITEM_CALCIUM = 63;
  ITEM_RARE_CANDY = 64;
  ITEM_PP_UP = 65;
  ITEM_ZINC = 66;
  ITEM_PP_MAX = 67;
  ITEM_ABILITY_CAPSULE = 68;
  ITEM_ABILITY_PATCH = 69;
  ITEM_CHERI_BERRY = 70;
  ITEM_CHESTO_BERRY = 71;
  ITEM_PECHA_BERRY = 72;
  ITEM_RAWST_BERRY = 73;
  ITEM_ASPEAR_BERRY = 74;
  ITEM_LEPPA_BERRY = 75;
  ITEM_ORAN_BERRY = 76;
  ITEM_PERSIM_BERRY = 77;
  ITEM_LUM_BERRY = 78;
  ITEM_SITRUS_BERRY = 79;
  ITEM_FIGY_BERRY = 80;
  ITEM_WIKI_BERRY = 81;
  ITEM_MAGO_BERRY = 82;
  ITEM_AGUAV_BERRY = 83;
  ITEM_IAPAPA_BERRY = 84;
  ITEM_RAZZ_BERRY = 85;
  ITEM_BLUK_BERRY = 86;
  ITEM_NANAB_BERRY = 87;
  ITEM_WEPEAR_BERRY = 88;
  ITEM_PINAP_BERRY = 89;
  ITEM_POMEG_BERRY = 90;
  ITEM_KELPSY_BERRY = 91;
  ITEM_QUALOT_BERRY = 92;
  ITEM_HONDEW_BERRY = 93;
  ITEM_GREPA_BERRY = 94;
  ITEM_TAMATO_BERRY = 95;
  ITEM_CORNN_BERRY = 96;
  ITEM_MAGOST_BERRY = 97;
  ITEM_RABUTA_BERRY = 98;
  ITEM_NOMEL_BERRY = 99;
  ITEM_SPELON_BERRY = 100;
  ITEM_PAMTRE_BERRY = 101;
  ITEM_WATMEL_BERRY = 102;
  ITEM_DURIN_BERRY = 103;
  ITEM_BELUE_BERRY = 104;
  ITEM_OCCA_BERRY = 105;
  ITEM_PASSHO_BERRY = 106;
  ITEM_WACAN_BERRY = 107;
  ITEM_RINDO_BERRY = 108;
  ITEM_YACHE_BERRY = 109;
  ITEM_CHOPLE_BERRY = 110;
  ITEM_KEBIA_BERRY = 111;
  ITEM_SHUCA_BERRY = 112;
  ITEM_COBA_BERRY = 113;
  ITEM_PAYAPA_BERRY = 114;
  ITEM_TANGA_BERRY = 115;
  ITEM_CHARTI_BERRY = 116;
  ITEM_KASIB_BERRY = 117;
  ITEM_HABAN_BERRY = 118;
  ITEM_COLBUR_BERRY = 119;
  ITEM_BABIRI_BERRY = 120;
  ITEM_CHILAN_BERRY = 121;
  ITEM_ROSELI_BERRY = 122;
  ITEM_LIECHI_BERRY = 123;
  ITEM_GANLON_BERRY = 124;
  ITEM_SALAC_BERRY = 125;
  ITEM_PETAYA_BERRY = 126;
  ITEM_APICOT_BERRY = 127;
  ITEM_LANSAT_BERRY = 128;
  ITEM_STARF_BERRY = 129;
  ITEM_MICLE_BERRY = 130;
  ITEM_CUSTAP_BERRY = 131;
  ITEM_JABOCA_BERRY = 132;
  ITEM_ROWAP_BERRY = 133;
  ITEM_KEE_BERRY = 134;
  ITEM_MARANGA_BERRY = 135;
  ITEM_ENIGMA_BERRY = 136;
  ITEM_SUN_STONE = 137;
  ITEM_MOON_STONE = 138;
  ITEM_FIRE_STONE = 139;
  ITEM_THUNDER_STONE = 140;
  ITEM_WATER_STONE = 141;
  ITEM_LEAF_STONE = 142;
  ITEM_DAWN_STONE = 143;
  ITEM_DUSK_STONE = 144;
  ITEM_SHINY_STONE = 145;
  ITEM_ICE_STONE = 146;
  ITEM_RED_NECTAR = 147;
  ITEM_YELLOW_NECTAR = 148;
  ITEM_PINK_NECTAR = 149;
  ITEM_PURPLE_NECTAR = 150;
  ITEM_SWEET_APPLE = 151;
  ITEM_TART_APPLE = 152;
  ITEM_CRACKED_POT = 153;
  ITEM_GALARICA_CUFF = 154;
  ITEM_GALARICA_WREATH = 155;
  ITEM_STRAWBERRY_SWEET = 156;
  ITEM_LOVE_SWEET = 157;
  ITEM_BERRY_SWEET = 158;
  ITEM_CLOVER_SWEET = 159;
  ITEM_FLOWER_SWEET = 160;
  ITEM_STAR_SWEET = 161;
  ITEM_RIBBON_SWEET = 162;
  ITEM_BLUE_FLUTE = 163;
  ITEM_YELLOW_FLUTE = 164;
  ITEM_RED_FLUTE = 165;
  ITEM_BLACK_FLUTE = 166;
  ITEM_WHITE_FLUTE = 167;
  ITEM_SHOAL_SALT = 168;
  ITEM_SHOAL_SHELL = 169;
  ITEM_RED_SHARD = 170;
  ITEM_BLUE_SHARD = 171;
  ITEM_YELLOW_SHARD = 172;
  ITEM_GREEN_SHARD = 173;
  ITEM_ESCAPE_ROPE = 174;
  ITEM_REPEL = 175;
  ITEM_SUPER_REPEL = 176;
  ITEM_MAX_REPEL = 177;
  ITEM_TINY_MUSHROOM = 178;
  ITEM_BIG_MUSHROOM = 179;
  ITEM_BALM_MUSHROOM = 180;
  ITEM_PEARL = 181;
  ITEM_BIG_PEARL = 182;
  ITEM_PEARL_STRING = 183;
  ITEM_STARDUST = 184;
  ITEM_STAR_PIECE = 185;
  ITEM_COMET_SHARD = 186;
  ITEM_NUGGET = 187;
  ITEM_BIG_NUGGET = 188;
  ITEM_RELIC_COPPER = 189;
  ITEM_RELIC_SILVER = 190;
  ITEM_RELIC_GOLD = 191;
  ITEM_RELIC_VASE = 192;
  ITEM_RELIC_STATUE = 193;
  ITEM_RELIC_BAND = 194;
  ITEM_HEART_SCALE = 195;
  ITEM_BOTTLE_CAP = 196;
  ITEM_GOLD_BOTTLE_CAP = 197;
  ITEM_HONEY = 198;
  ITEM_RARE_BONE = 199;
  ITEM_OVAL_STONE = 200;
  ITEM_PROTECTOR = 201;
  ITEM_ELECTIRIZER = 202;
  ITEM_MAGMARIZER = 203;
  ITEM_DUBIOUS_DISC = 204;
  ITEM_REAPER_CLOTH = 205;
  ITEM_PRISM_SCALE = 206;
  ITEM_WHIPPED_DREAM = 207;
  ITEM_SACHET = 208;
  ITEM_UPGRADE = 209;
  ITEM_RED_SCARF = 210;
  ITEM_BLUE_SCARF = 211;
  ITEM_PINK_SCARF = 212;
  ITEM_GREEN_SCARF = 213;
  ITEM_YELLOW_SCARF = 214;
  ITEM_ARMOR_FOSSIL = 215;
  ITEM_SKULL_FOSSIL = 216;
  ITEM_HELIX_FOSSIL = 217;
  ITEM_DOME_FOSSIL = 218;
  ITEM_COVER_FOSSIL = 219;
  ITEM_PLUME_FOSSIL = 220;
  ITEM_JAW_FOSSIL = 221;
  ITEM_SAIL_FOSSIL = 222;
  ITEM_ROOT_FOSSIL = 223;
  ITEM_CLAW_FOSSIL = 224;
  ITEM_FOSSILIZED_BIRD = 225;
  ITEM_FOSSILIZED_FISH = 226;
  ITEM_FOSSILIZED_DRAKE = 227;
  ITEM_FOSSILIZED_DINO = 228;
  ITEM_OLD_AMBER = 229;
  ITEM_GUARD_SPEC = 230;
  ITEM_DIRE_HIT = 231;
  ITEM_X_ATTACK = 232;
  ITEM_X_DEFENSE = 233;
  ITEM_X_SPEED = 234;
  ITEM_X_ACCURACY = 235;
  ITEM_X_SP_ATK = 236;
  ITEM_X_SP_DEF = 237;
  ITEM_POKE_DOLL = 238;
  ITEM_FLUFFY_TAIL = 239;
  ITEM_BRIGHT_POWDER = 240;
  ITEM_WHITE_HERB = 241;
  ITEM_MACHO_BRACE = 242;
  ITEM_EXP_SHARE = 243;
  ITEM_QUICK_CLAW = 244;
  ITEM_SOOTHE_BELL = 245;
  ITEM_MENTAL_HERB = 246;
  ITEM_CHOICE_BAND = 247;
  ITEM_KINGS_ROCK = 248;
  ITEM_SILVER_POWDER = 249;
  ITEM_AMULET_COIN = 250;
  ITEM_CLEANSE_TAG = 251;
  ITEM_SMOKE_BALL = 252;
  ITEM_EVERSTONE = 253;
  ITEM_FOCUS_BAND = 254;
  ITEM_LUCKY_EGG = 255;
  ITEM_SCOPE_LENS = 256;
  ITEM_METAL_COAT = 257;
  ITEM_SOFT_SAND = 258;
  ITEM_HARD_STONE = 259;
  ITEM_MIRACLE_SEED = 260;
  ITEM_BLACK_GLASSES = 261;
  ITEM_BLACK_BELT = 262;
  ITEM_MAGNET = 263;
  ITEM_MYSTIC_WATER = 264;
  ITEM_SHARP_BEAK = 265;
  ITEM_POISON_BARB = 266;
  ITEM_NEVER_MELT_ICE = 267;
  ITEM_SPELL_TAG = 268;
  ITEM_TWISTED_SPOON = 269;
  ITEM_CHARCOAL = 270;
  ITEM_DRAGON_FANG = 271;
  ITEM_SILK_SCARF = 272;
  ITEM_LEFTOVERS = 273;
  ITEM_DRAGON_SCALE = 274;
  ITEM_RAZOR_CLAW = 275;
  ITEM_RAZOR_FANG = 276;
  ITEM_SHELL_BELL = 277;
  ITEM_POWER_BRACER = 278;
  ITEM_POWER_BELT = 279;
  ITEM_POWER_LENS = 280;
  ITEM_POWER_BAND = 281;
  ITEM_POWER_ANKLET = 282;
  ITEM_POWER_WEIGHT = 283;
  ITEM_POWER_HERB = 284;
  ITEM_CHOICE_SCARF = 285;
  ITEM_CHOICE_SPECS = 286;
  ITEM_FOCUS_SASH = 287;
  ITEM_WIDE_LENS = 288;
  ITEM_ZOOM_LENS = 289;
  ITEM_METRONOME = 290;
  ITEM_MUSCLE_BAND = 291;
  ITEM_WISE_GLASSES = 292;
  ITEM_EXPERT_BELT = 293;
  ITEM_LIGHT_CLAY = 294;
  ITEM_ICY_ROCK = 295;
  ITEM_SMOOTH_ROCK = 296;
  ITEM_HEAT_ROCK = 297;
  ITEM_DAMP_ROCK = 298;
  ITEM_DESTINY_KNOT = 299;
  ITEM_GRIP_CLAW = 300;
  ITEM_LIFE_ORB = 301;
  ITEM_TOXIC_ORB = 302;
  ITEM_FLAME_ORB = 303;
  ITEM_STICKY_BARB = 304;
  ITEM_BLACK_SLUDGE = 305;
  ITEM_IRON_BALL = 306;
  ITEM_LAGGING_TAIL = 307;
  ITEM_SHED_SHELL = 308;
  ITEM_BIG_ROOT = 309;
  ITEM_EVIOLITE = 310;
  ITEM_FLOAT_STONE = 311;
  ITEM_ROCKY_HELMET = 312;
  ITEM_AIR_BALLOON = 313;
  ITEM_RED_CARD = 314;
  ITEM_RING_TARGET = 315;
  ITEM_BINDING_BAND = 316;
  ITEM_EJECT_BUTTON = 317;
  ITEM_ABSORB_BULB = 318;
  ITEM_CELL_BATTERY = 319;
  ITEM_LUMINOUS_MOSS = 320;
  ITEM_SNOWBALL = 321;
  ITEM_WEAKNESS_POLICY = 322;
  ITEM_ASSAULT_VEST = 323;
  ITEM_SAFETY_GOGGLES = 324;
  ITEM_ADRENALINE_ORB = 325;
  ITEM_TERRAIN_EXTENDER = 326;
  ITEM_PROTECTIVE_PADS = 327;
  ITEM_ELECTRIC_SEED = 328;
  ITEM_PSYCHIC_SEED = 329;
  ITEM_MISTY_SEED = 330;
  ITEM_GRASSY_SEED = 331;
  ITEM_BUG_GEM = 332;
  ITEM_DARK_GEM = 333;
  ITEM_DRAGON_GEM = 334;
  ITEM_ELECTRIC_GEM = 335;
  ITEM_FAIRY_GEM = 336;
  ITEM_FIGHTING_GEM = 337;
  ITEM_FIRE_GEM = 338;
  ITEM_FLYING_GEM = 339;
  ITEM_GHOST_GEM = 340;
  ITEM_GRASS_GEM = 341;
  ITEM_GROUND_GEM = 342;
  ITEM_ICE_GEM = 343;
  ITEM_NORMAL_GEM = 344;
  ITEM_POISON_GEM = 345;
  ITEM_PSYCHIC_GEM = 346;
  ITEM_ROCK_GEM = 347;
  ITEM_STEEL_GEM = 348;
  ITEM_WATER_GEM = 349;
  ITEM_THROAT_SPRAY = 350;
  ITEM_EJECT_PACK = 351;
  ITEM_HEAVY_DUTY_BOOTS = 352;
  ITEM_BLUNDER_POLICY = 353;
  ITEM_ROOM_SERVICE = 354;
  ITEM_UTILITY_UMBRELLA = 355;
  ITEM_RUSTED_SWORD = 356;
  ITEM_RUSTED_SHIELD = 357;
  ITEM_INSECT_PLATE = 358;
  ITEM_DREAD_PLATE = 359;
  ITEM_DRACO_PLATE = 360;
  ITEM_ZAP_PLATE = 361;
  ITEM_PIXIE_PLATE = 362;
  ITEM_FIST_PLATE = 363;
  ITEM_FLAME_PLATE = 364;
  ITEM_SKY_PLATE = 365;
  ITEM_SPOOKY_PLATE = 366;
  ITEM_MEADOW_PLATE = 367;
  ITEM_EARTH_PLATE = 368;
  ITEM_ICICLE_PLATE = 369;
  ITEM_TOXIC_PLATE = 370;
  ITEM_MIND_PLATE = 371;
  ITEM_STONE_PLATE = 372;
  ITEM_IRON_PLATE = 373;
  ITEM_SPLASH_PLATE = 374;
  ITEM_SOUL_DEW = 375;
  ITEM_DEEP_SEA_TOOTH = 376;
  ITEM_DEEP_SEA_SCALE = 377;
  ITEM_LUCKY_PUNCH = 378;
  ITEM_METAL_POWDER = 379;
  ITEM_THICK_CLUB = 380;
  ITEM_LEEK = 381;
  ITEM_LIGHT_BALL = 382;
  ITEM_QUICK_POWDER = 383;
  ITEM_ADAMANT_ORB = 384;
  ITEM_LUSTROUS_ORB = 385;
  ITEM_GRISEOUS_ORB = 386;
  ITEM_DOUSE_DRIVE = 387;
  ITEM_SHOCK_DRIVE = 388;
  ITEM_BURN_DRIVE = 389;
  ITEM_CHILL_DRIVE = 390;
  ITEM_SEA_INCENSE = 391;
  ITEM_LAX_INCENSE = 392;
  ITEM_ODD_INCENSE = 393;
  ITEM_ROCK_INCENSE = 394;
  ITEM_FULL_INCENSE = 395;
  ITEM_WAVE_INCENSE = 396;
  ITEM_ROSE_INCENSE = 397;
  ITEM_LUCK_INCENSE = 398;
  ITEM_PURE_INCENSE = 399;
  ITEM_TRAINING_BAND = 400;
  ITEM_CANDY_BOX = 401;
  ITEM_INFINITE_REPEL = 402;
  ITEM_IRON_PILL = 403;
  ITEM_ABILITY_SHIELD = 411;
  ITEM_CLEAR_AMULET = 412;
  ITEM_MIRROR_HERB = 413;
  ITEM_PUNCHING_GLOVE = 414;
  ITEM_COVERT_CLOAK = 415;
  ITEM_LOADED_DICE = 416;
  ITEM_FAIRY_FEATHER = 419;
  ITEM_FROST_ORB = 427;
  ITEM_TACTICAL_VEST = 428;
  ITEM_BOOSTER_ENERGY = 429;
  ITEM_SWIRLY_GLASSES = 430;
  ITEM_TM01_FOCUS_PUNCH = 530;
  ITEM_TM02_DRAGON_CLAW = 531;
  ITEM_TM03_WATER_PULSE = 532;
  ITEM_TM04_CALM_MIND = 533;
  ITEM_TM05_ROAR = 534;
  ITEM_TM06_TOXIC = 535;
  ITEM_TM07_HAIL = 536;
  ITEM_TM08_BULK_UP = 537;
  ITEM_TM09_BULLET_SEED = 538;
  ITEM_TM10_HIDDEN_POWER = 539;
  ITEM_TM11_SUNNY_DAY = 540;
  ITEM_TM12_TAUNT = 541;
  ITEM_TM13_ICE_BEAM = 542;
  ITEM_TM14_BLIZZARD = 543;
  ITEM_TM15_HYPER_BEAM = 544;
  ITEM_TM16_LIGHT_SCREEN = 545;
  ITEM_TM17_PROTECT = 546;
  ITEM_TM18_RAIN_DANCE = 547;
  ITEM_TM19_GIGA_DRAIN = 548;
  ITEM_TM20_SAFEGUARD = 549;
  ITEM_TM21_FRUSTRATION = 550;
  ITEM_TM22_SOLARBEAM = 551;
  ITEM_TM23_IRON_TAIL = 552;
  ITEM_TM24_THUNDERBOLT = 553;
  ITEM_TM25_THUNDER = 554;
  ITEM_TM26_EARTHQUAKE = 555;
  ITEM_TM27_RETURN = 556;
  ITEM_TM28_DIG = 557;
  ITEM_TM29_PSYCHIC = 558;
  ITEM_TM30_SHADOW_BALL = 559;
  ITEM_TM31_BRICK_BREAK = 560;
  ITEM_TM32_DOUBLE_TEAM = 561;
  ITEM_TM33_REFLECT = 562;
  ITEM_TM34_SLUDGE_WAVE = 563;
  ITEM_TM35_FLAMETHROWER = 564;
  ITEM_TM36_SLUDGE_BOMB = 565;
  ITEM_TM37_SANDSTORM = 566;
  ITEM_TM38_FIRE_BLAST = 567;
  ITEM_TM39_ROCK_TOMB = 568;
  ITEM_TM40_AERIAL_ACE = 569;
  ITEM_TM41_TORMENT = 570;
  ITEM_TM42_FACADE = 571;
  ITEM_TM43_SECRET_POWER = 572;
  ITEM_TM44_REST = 573;
  ITEM_TM45_ATTRACT = 574;
  ITEM_TM46_THIEF = 575;
  ITEM_TM47_STEEL_WING = 576;
  ITEM_TM48_SKILL_SWAP = 577;
  ITEM_TM49_SLEEP_TALK = 578;
  ITEM_TM50_OVERHEAT = 579;
  ITEM_TM51_ROOST = 580;
  ITEM_TM52_FOCUS_BLAST = 581;
  ITEM_TM53_ENERGY_BALL = 582;
  ITEM_TM54_PSYSHOCK = 583;
  ITEM_TM55_SCALD = 584;
  ITEM_TM56_LEECH_LIFE = 585;
  ITEM_TM57_CHARGE_BEAM = 586;
  ITEM_TM58_ENDURE = 587;
  ITEM_TM59_DRAGON_PULSE = 588;
  ITEM_TM60_DRAIN_PUNCH = 589;
  ITEM_TM61_WILL_O_WISP = 590;
  ITEM_TM62_ACROBATICS = 591;
  ITEM_TM63_ROCK_SLIDE = 592;
  ITEM_TM64_EXPLOSION = 593;
  ITEM_TM65_SHADOW_CLAW = 594;
  ITEM_TM66_PAYBACK = 595;
  ITEM_TM67_RECYCLE = 596;
  ITEM_TM68_GIGA_IMPACT = 597;
  ITEM_TM69_ROCK_POLISH = 598;
  ITEM_TM70_AURORA_VEIL = 599;
  ITEM_TM71_STONE_EDGE = 600;
  ITEM_TM72_VOLT_SWITCH = 601;
  ITEM_TM73_THUNDER_WAVE = 602;
  ITEM_TM74_GYRO_BALL = 603;
  ITEM_TM75_SWORDS_DANCE = 604;
  ITEM_TM76_STEALTH_ROCK = 605;
  ITEM_TM77_STRUGGLE_BUG = 606;
  ITEM_TM78_BULLDOZE = 607;
  ITEM_TM79_FREEZE_DRY = 608;
  ITEM_TM80_VENOSHOCK = 609;
  ITEM_TM81_X_SCISSOR = 610;
  ITEM_TM82_DRAGON_TAIL = 611;
  ITEM_TM83_FLAME_CHARGE = 612;
  ITEM_TM84_POISON_JAB = 613;
  ITEM_TM85_DREAM_EATER = 614;
  ITEM_TM86_GRASS_KNOT = 615;
  ITEM_TM87_SMACK_DOWN = 616;
  ITEM_TM88_LOW_SWEEP = 617;
  ITEM_TM89_U_TURN = 618;
  ITEM_TM90_SUBSTITUTE = 619;
  ITEM_TM91_FLASH_CANNON = 620;
  ITEM_TM92_TRICK_ROOM = 621;
  ITEM_TM93_WILD_CHARGE = 622;
  ITEM_TM94_SUCKER_PUNCH = 623;
  ITEM_TM95_SNARL = 624;
  ITEM_TM96_AVALANCHE = 625;
  ITEM_TM97_DARK_PULSE = 626;
  ITEM_TM98_FALSE_SWIPE = 627;
  ITEM_TM99_DAZZLING_GLEAM = 628;
  ITEM_TM100_CURSE = 629;
  ITEM_HM01_CUT = 630;
  ITEM_HM02_FLY = 631;
  ITEM_HM03_SURF = 632;
  ITEM_HM04_STRENGTH = 633;
  ITEM_HM05_FLASH = 634;
  ITEM_HM06_ROCK_SMASH = 635;
  ITEM_HM07_WATERFALL = 636;
  ITEM_HM08_DIVE = 637;
  ITEM_ODD_KEYSTONE = 638;
  ITEM_GRACIDEA = 639;
  ITEM_MEGA_BRACELET = 640;
  ITEM_MACH_BIKE = 641;
  ITEM_COIN_CASE = 642;
  ITEM_ITEMFINDER = 643;
  ITEM_OLD_ROD = 644;
  ITEM_GOOD_ROD = 645;
  ITEM_SUPER_ROD = 646;
  ITEM_SS_TICKET = 647;
  ITEM_CONTEST_PASS = 648;
  ITEM_WAILMER_PAIL = 649;
  ITEM_DEVON_GOODS = 650;
  ITEM_SOOT_SACK = 651;
  ITEM_BASEMENT_KEY = 652;
  ITEM_ACRO_BIKE = 653;
  ITEM_EGG_INCUBATOR = 654;
  ITEM_LETTER = 655;
  ITEM_EON_TICKET = 656;
  ITEM_EXP_CHARM = 657;
  ITEM_PRISON_BOTTLE = 658;
  ITEM_SCANNER = 659;
  ITEM_GO_GOGGLES = 660;
  ITEM_METEORITE = 661;
  ITEM_ROOM_1_KEY = 662;
  ITEM_ROOM_2_KEY = 663;
  ITEM_ROOM_4_KEY = 664;
  ITEM_ROOM_6_KEY = 665;
  ITEM_STORAGE_KEY = 666;
  ITEM_DEVON_SCOPE = 667;
  ITEM_MAGMA_STONE = 668;
  ITEM_LUNAR_WING = 669;
  ITEM_SHINY_CHARM = 670;
  ITEM_OVAL_CHARM = 671;
  ITEM_MAGMA_EMBLEM = 672;
  ITEM_OLD_SEA_MAP = 673;
  ITEM_MYSTIC_TICKET = 674;
  ITEM_AURORA_TICKET = 675;
  ITEM_POWDER_JAR = 676;
  ITEM_REVEAL_GLASS = 677;
  ITEM_DNA_SPLICERS = 678;
  ITEM_POKE_VIAL = 680;
  ITEM_CATCHING_CHARM = 681;
  ITEM_ROTOM_CATALOG = 682;
  ITEM_REINS_OF_UNITY = 683;
  ITEM_ICEROOT_CARROT = 684;
  ITEM_SHADEROOT_CARROT = 685;
  ITEM_WOODEN_CROWN = 686;
  ITEM_N_LUNARIZER = 687;
  ITEM_N_SOLARIZER = 688;
  ITEM_ABOMASITE = 748;
  ITEM_ABSOLITE = 749;
  ITEM_AERODACTYLITE = 750;
  ITEM_AGGRONITE = 751;
  ITEM_ALAKAZITE = 752;
  ITEM_ALTARIANITE = 753;
  ITEM_AMPHAROSITE = 754;
  ITEM_AUDINITE = 755;
  ITEM_BANETTITE = 756;
  ITEM_BEEDRILLITE = 757;
  ITEM_BLASTOISINITE = 758;
  ITEM_BLAZIKENITE = 759;
  ITEM_CAMERUPTITE = 760;
  ITEM_CHARIZARDITE_X = 761;
  ITEM_CHARIZARDITE_Y = 762;
  ITEM_DIANCITE = 763;
  ITEM_GALLADITE = 764;
  ITEM_GARCHOMPITE = 765;
  ITEM_GARDEVOIRITE = 766;
  ITEM_GENGARITE = 767;
  ITEM_GLALITITE = 768;
  ITEM_GYARADOSITE = 769;
  ITEM_HERACRONITE = 770;
  ITEM_HOUNDOOMINITE = 771;
  ITEM_KANGASKHANITE = 772;
  ITEM_LATIASITE = 773;
  ITEM_LATIOSITE = 774;
  ITEM_LOPUNNITE = 775;
  ITEM_LUCARIONITE = 776;
  ITEM_MANECTITE = 777;
  ITEM_MAWILITE = 778;
  ITEM_MEDICHAMITE = 779;
  ITEM_METAGROSSITE = 780;
  ITEM_MEWTWONITE_X = 781;
  ITEM_MEWTWONITE_Y = 782;
  ITEM_PIDGEOTITE = 783;
  ITEM_PINSIRITE = 784;
  ITEM_SABLENITE = 785;
  ITEM_SALAMENCITE = 786;
  ITEM_SCEPTILITE = 787;
  ITEM_SCIZORITE = 788;
  ITEM_SHARPEDONITE = 789;
  ITEM_SLOWBRONITE = 790;
  ITEM_STEELIXITE = 791;
  ITEM_SWAMPERTITE = 792;
  ITEM_TYRANITARITE = 793;
  ITEM_VENUSAURITE = 794;
  ITEM_MILOTICITE = 795;
  ITEM_RED_ORB = 796;
  ITEM_BLUE_ORB = 797;
  ITEM_FLYGONITE = 798;
  ITEM_BUTTERFRENITE = 799;
  ITEM_LAPRASITE_Y = 800;
  ITEM_MACHAMPITE = 801;
  ITEM_KINGLERITE = 802;
  ITEM_KINGDRANITE = 803;
  ITEM_DEWGONGITE = 804;
  ITEM_HITMONCHANITE = 805;
  ITEM_HITMONLEENITE = 806;
  ITEM_HITMONTOPITE = 807;
  ITEM_CROBATITE = 808;
  ITEM_SKARMORITE = 809;
  ITEM_BRUXISHITE = 810;
  ITEM_TORTERRANITE = 811;
  ITEM_INFERNAPENITE = 812;
  ITEM_EMPOLEONITE = 813;
  ITEM_SHUCKLENITE = 814;
  ITEM_RELICANTHITE = 815;
  ITEM_QUAGSIRENITE = 816;
  ITEM_JELLICENTITE = 817;
  ITEM_TOUCANNONITE = 818;
  ITEM_DRAGONITENITE = 819;
  ITEM_BRELOOMITE = 820;
  ITEM_SLAKINGITE = 821;
  ITEM_PURPLE_ORB = 822;
  ITEM_SLOWKINGITE = 823;
  ITEM_GYARADOSITE_Y = 824;
  ITEM_FERALIGATRITE_X = 825;
  ITEM_FERALIGATRITE_Y = 826;
  ITEM_HAXORUSITE = 827;
  ITEM_LUXRAYNITE = 828;
  ITEM_GRANBULLITE = 829;
  ITEM_TYPHLOSIONITE = 830;
  ITEM_NIDOQUEENITE = 831;
  ITEM_NIDOKINGITE = 832;
  ITEM_SANDSLASHITE = 833;
  ITEM_MEGANIUMITE = 834;
  ITEM_KROOKODILENITE = 835;
  ITEM_MAGNEZONITE = 836;
  ITEM_SHEDINJITE = 837;
  ITEM_SWALOTITE = 838;
  ITEM_LANTURNITE = 839;
  ITEM_LAPRASITE_X = 840;
  ITEM_KINGAMBITITE_R = 841;
  ITEM_RIBOMBITE = 842;
  ITEM_GARCHOMPITE_R = 843;
  ITEM_SKARMORITE_R = 844;
  ITEM_MACHAMPITE_R = 845;
  ITEM_ALAKAZITE_R = 846;
  ITEM_BEEDRILLITE_R = 847;
  ITEM_HOUNDOOMINITE_R = 848;
  ITEM_FROSLASSITE = 849;
  ITEM_SCRAFTITE = 850;
  ITEM_MAWILITE_R = 851;
  ITEM_SABLENITE_R = 852;
  ITEM_URSALUNITE = 853;
  ITEM_ARCANITE_R = 854;
  ITEM_TYRANITARITE_R = 855;
  ITEM_WIGGLYTUFFITE = 856;
  ITEM_TINKATITE = 857;
  ITEM_GYARADEATHITE_X = 858;
  ITEM_GYARADEATHITE_Y = 859;
  ITEM_SENZU = 860;
  ITEM_AEGISLASHITE_R = 861;
  ITEM_ARBOKITE = 862;
  ITEM_CLEFABITE_R = 863;
  ITEM_FLYGONITE_R = 864;
  ITEM_EMPOLEONITE_R = 865;
  ITEM_INFERNAPENITE_R = 866;
  ITEM_FROSLASSITE_R = 867;
  ITEM_GLALITITE_R = 868;
  ITEM_RAPIDASHITE_G = 869;
  ITEM_GOLISOPODITE = 870;
  ITEM_HYDREIGONITE_R = 871;
  ITEM_TORTERRANITE_R = 872;
  ITEM_RAPIDASHITE = 873;
  ITEM_CORMOTHITE = 874;
  ITEM_POPCORMITE = 875;
  ITEM_REUNICLUSITE_R = 876;
  ITEM_TOXTRICITITE_R = 877;
  ITEM_ORICORIONITE = 878;
  ITEM_TSAREENITE_R = 879;
  ITEM_URSHIFITE = 880;
  ITEM_AMPHYBUZZITE = 881;
  ITEM_MELMETALITE = 882;
  ITEM_DYNAMAX_ORB = 883;
  ITEM_TERA_ORB = 884;
  ITEM_VENUSAURITE_X = 885;
  ITEM_CHARIZARDITE_Z = 886;
  ITEM_BLASTOISINITE_X = 887;
  ITEM_GENGARITE_X = 888;
  ITEM_SNORLAXITE = 889;
  ITEM_RILLABOOMITE = 890;
  ITEM_CINDERACEITE = 891;
  ITEM_INTELEONITE = 892;
  ITEM_CORVINITE = 893;
  ITEM_DREDNAWITE = 894;
  ITEM_COALOSSITE = 895;
  ITEM_SANDACONDITE = 896;
  ITEM_COPPERAJITE = 897;
  ITEM_HATTERENITE = 898;
  ITEM_GARBODORITE = 899;
  ITEM_ORBEETITE = 900;
  ITEM_GRIMMSNARLITE = 901;
  ITEM_CENTISKITE = 902;
  ITEM_ALCREMITE = 903;
  ITEM_TOXTRICITITE = 904;
  ITEM_PIKANITE = 905;
  ITEM_MEOWTHITE = 906;
  ITEM_EEVITE = 907;
  ITEM_DURALUDITE = 908;
  ITEM_ULTRANECROZIUM_P = 909;
  ITEM_FIDOUGHITE = 910;
  ITEM_WIGGLYTUFFITE_X = 911;
  ITEM_SERPERIORITE = 912;
  ITEM_EMBOARITE = 913;
  ITEM_SAMUROTTITE = 914;
  ITEM_DECIDUITE = 915;
  ITEM_WEAVILEITE = 916;
  ITEM_DECIDUITE_H = 917;
  ITEM_INCINERITE = 918;
  ITEM_MEOWSCARADITE = 919;
  ITEM_PRIMARINITE = 920;
  ITEM_QUAQUAVITE = 921;
  ITEM_SAMUROTTITE_H = 922;
  ITEM_SKELEDIRGEITE = 923;
  ITEM_TYPHLOSIONITE_H = 924;
  ITEM_MIENSHAOITE = 925;
  ITEM_GOODRITE = 926;
  ITEM_SLOWBRONITE_G = 927;
  ITEM_SLOWKINGITE_G = 928;
  ITEM_ROSERADEITE = 929;
  ITEM_ARCANITE = 930;
  ITEM_KINGDRANITE_Y = 931;
  ITEM_PHANTOM_METEOR = 935;
  ITEM_YVELTALITE = 936;
  ITEM_GALACTIC_ORB = 937;
  ITEM_CHIEN_PAOITE = 938;
  ITEM_DRACOVISHITE = 939;
  ITEM_MAWILITE_R_B = 940;
  ITEM_RIBOMBITE_R = 941;
  ITEM_WEAVILEITE_R = 942;
  ITEM_FLYGONITE_R_B = 943;
  ITEM_SNORLAX_ORB = 944;
  ITEM_VICTINI_ORB = 945;
  ITEM_WIGGLITUFF_ORB = 946;
  ITEM_ABOMASITE_S = 947;
  ITEM_FAB_MAIL = 972;
  ITEM_RETRO_MAIL = 973;
  ITEM_BUG_MEMORY = 974;
  ITEM_DARK_MEMORY = 975;
  ITEM_DRAGON_MEMORY = 976;
  ITEM_ELECTRIC_MEMORY = 977;
  ITEM_FAIRY_MEMORY = 978;
  ITEM_FIGHTING_MEMORY = 979;
  ITEM_FIRE_MEMORY = 980;
  ITEM_FLYING_MEMORY = 981;
  ITEM_GHOST_MEMORY = 982;
  ITEM_GRASS_MEMORY = 983;
  ITEM_GROUND_MEMORY = 984;
  ITEM_ICE_MEMORY = 985;
  ITEM_POISON_MEMORY = 986;
  ITEM_PSYCHIC_MEMORY = 987;
  ITEM_ROCK_MEMORY = 988;
  ITEM_STEEL_MEMORY = 989;
  ITEM_WATER_MEMORY = 990;
  ITEM_OAKS_PARCEL = 991;
  ITEM_POKE_FLUTE = 992;
  ITEM_SECRET_KEY = 993;
  ITEM_BIKE_VOUCHER = 994;
  ITEM_GOLD_TEETH = 995;
  ITEM_CARD_KEY = 996;
  ITEM_LIFT_KEY = 997;
  ITEM_SILPH_SCOPE = 998;
  ITEM_BICYCLE = 999;
  ITEM_TOWN_MAP = 1000;
  ITEM_VS_SEEKER = 1001;
  ITEM_FAME_CHECKER = 1002;
  ITEM_TM_CASE = 1003;
  ITEM_BERRY_POUCH = 1004;
  ITEM_TEACHY_TV = 1005;
  ITEM_TRI_PASS = 1006;
  ITEM_RAINBOW_PASS = 1007;
  ITEM_TEA = 1008;
  ITEM_RUBY = 1009;
  ITEM_SAPPHIRE = 1010;
  ITEM_Z_RING = 1011;
  ITEM_NORMALIUM_Z = 1012;
  ITEM_FIGHTINIUM_Z = 1013;
  ITEM_FLYINIUM_Z = 1014;
  ITEM_POISONIUM_Z = 1015;
  ITEM_GROUNDIUM_Z = 1016;
  ITEM_ROCKIUM_Z = 1017;
  ITEM_BUGINIUM_Z = 1018;
  ITEM_GHOSTIUM_Z = 1019;
  ITEM_STEELIUM_Z = 1020;
  ITEM_FIRIUM_Z = 1021;
  ITEM_WATERIUM_Z = 1022;
  ITEM_GRASSIUM_Z = 1023;
  ITEM_ELECTRIUM_Z = 1024;
  ITEM_PSYCHIUM_Z = 1025;
  ITEM_ICIUM_Z = 1026;
  ITEM_DRAGONIUM_Z = 1027;
  ITEM_DARKINIUM_Z = 1028;
  ITEM_FAIRIUM_Z = 1029;
  ITEM_ALORAICHIUM_Z = 1030;
  ITEM_DECIDIUM_Z = 1031;
  ITEM_EEVIUM_Z = 1032;
  ITEM_INCINIUM_Z = 1033;
  ITEM_KOMMONIUM_Z = 1034;
  ITEM_LUNALIUM_Z = 1035;
  ITEM_LYCANIUM_Z = 1036;
  ITEM_MARSHADIUM_Z = 1037;
  ITEM_MEWNIUM_Z = 1038;
  ITEM_MIMIKIUM_Z = 1039;
  ITEM_PIKANIUM_Z = 1040;
  ITEM_PIKASHUNIUM_Z = 1041;
  ITEM_PRIMARIUM_Z = 1042;
  ITEM_SNORLIUM_Z = 1043;
  ITEM_SOLGANIUM_Z = 1044;
  ITEM_TAPUNIUM_Z = 1045;
  ITEM_ULTRANECROZIUM_Z = 1046;
  ITEM_DUDUDUNITE = 404;
}