syntax = "proto3";

package er;

option java_package = "er.proto";
option java_multiple_files = true;

enum ItemEnum {
  ITEM_NONE = 0;
  ITEM_MASTER_BALL = 1;
  ITEM_ULTRA_BALL = 2;
  ITEM_GREAT_BALL = 3;
  ITEM_POKE_BALL = 4;
  ITEM_SAFARI_BALL = 5;
  ITEM_NET_BALL = 6;
  ITEM_DIVE_BALL = 7;
  ITEM_NEST_BALL = 8;
  ITEM_REPEAT_BALL = 9;
  ITEM_TIMER_BALL = 10;
  ITEM_LUXURY_BALL = 11;
  ITEM_DUSK_BALL = 12;
  ITEM_HEAL_BALL = 13;
  ITEM_QUICK_BALL = 14;
  ITEM_CHERISH_BALL = 15;
  ITEM_FAST_BALL = 16;
  ITEM_LEVEL_BALL = 17;
  ITEM_LURE_BALL = 18;
  ITEM_HEAVY_BALL = 19;
  ITEM_LOVE_BALL = 20;
  ITEM_FRIEND_BALL = 21;
  ITEM_MOON_BALL = 22;
  ITEM_SPORT_BALL = 23;
  ITEM_PARK_BALL = 24;
  ITEM_DREAM_BALL = 25;
  ITEM_BEAST_BALL = 26;
  ITEM_PREMIER_BALL = 27;
  ITEM_POTION = 28;
  ITEM_ANTIDOTE = 29;
  ITEM_BURN_HEAL = 30;
  ITEM_ICE_HEAL = 31;
  ITEM_AWAKENING = 32;
  ITEM_PARALYZE_HEAL = 33;
  ITEM_FULL_RESTORE = 34;
  ITEM_MAX_POTION = 35;
  ITEM_HYPER_POTION = 36;
  ITEM_SUPER_POTION = 37;
  ITEM_FULL_HEAL = 38;
  ITEM_REVIVE = 39;
  ITEM_MAX_REVIVE = 40;
  ITEM_FRESH_WATER = 41;
  ITEM_SODA_POP = 42;
  ITEM_LEMONADE = 43;
  ITEM_MOOMOO_MILK = 44;
  ITEM_ENERGY_POWDER = 45;
  ITEM_ENERGY_ROOT = 46;
  ITEM_HEAL_POWDER = 47;
  ITEM_REVIVAL_HERB = 48;
  ITEM_ETHER = 49;
  ITEM_MAX_ETHER = 50;
  ITEM_ELIXIR = 51;
  ITEM_MAX_ELIXIR = 52;
  ITEM_LAVA_COOKIE = 53;
  ITEM_BERRY_JUICE = 54;
  ITEM_SWEET_HEART = 55;
  ITEM_BIG_MALASADA = 56;
  ITEM_OLD_GATEAU = 57;
  ITEM_SACRED_ASH = 58;
  ITEM_HP_UP = 59;
  ITEM_PROTEIN = 60;
  ITEM_IRON = 61;
  ITEM_CARBOS = 62;
  ITEM_CALCIUM = 63;
  ITEM_RARE_CANDY = 64;
  ITEM_PP_UP = 65;
  ITEM_ZINC = 66;
  ITEM_PP_MAX = 67;
  ITEM_ABILITY_CAPSULE = 68;
  ITEM_ABILITY_PATCH = 69;
  ITEM_CHERI_BERRY = 70;
  ITEM_CHESTO_BERRY = 71;
  ITEM_PECHA_BERRY = 72;
  ITEM_RAWST_BERRY = 73;
  ITEM_ASPEAR_BERRY = 74;
  ITEM_LEPPA_BERRY = 75;
  ITEM_ORAN_BERRY = 76;
  ITEM_PERSIM_BERRY = 77;
  ITEM_LUM_BERRY = 78;
  ITEM_SITRUS_BERRY = 79;
  ITEM_FIGY_BERRY = 80;
  ITEM_WIKI_BERRY = 81;
  ITEM_MAGO_BERRY = 82;
  ITEM_AGUAV_BERRY = 83;
  ITEM_IAPAPA_BERRY = 84;
  ITEM_RAZZ_BERRY = 85;
  ITEM_BLUK_BERRY = 86;
  ITEM_NANAB_BERRY = 87;
  ITEM_WEPEAR_BERRY = 88;
  ITEM_PINAP_BERRY = 89;
  ITEM_POMEG_BERRY = 90;
  ITEM_KELPSY_BERRY = 91;
  ITEM_QUALOT_BERRY = 92;
  ITEM_HONDEW_BERRY = 93;
  ITEM_GREPA_BERRY = 94;
  ITEM_TAMATO_BERRY = 95;
  ITEM_CORNN_BERRY = 96;
  ITEM_MAGOST_BERRY = 97;
  ITEM_RABUTA_BERRY = 98;
  ITEM_NOMEL_BERRY = 99;
  ITEM_SPELON_BERRY = 100;
  ITEM_PAMTRE_BERRY = 101;
  ITEM_WATMEL_BERRY = 102;
  ITEM_DURIN_BERRY = 103;
  ITEM_BELUE_BERRY = 104;
  ITEM_OCCA_BERRY = 105;
  ITEM_PASSHO_BERRY = 106;
  ITEM_WACAN_BERRY = 107;
  ITEM_RINDO_BERRY = 108;
  ITEM_YACHE_BERRY = 109;
  ITEM_CHOPLE_BERRY = 110;
  ITEM_KEBIA_BERRY = 111;
  ITEM_SHUCA_BERRY = 112;
  ITEM_COBA_BERRY = 113;
  ITEM_PAYAPA_BERRY = 114;
  ITEM_TANGA_BERRY = 115;
  ITEM_CHARTI_BERRY = 116;
  ITEM_KASIB_BERRY = 117;
  ITEM_HABAN_BERRY = 118;
  ITEM_COLBUR_BERRY = 119;
  ITEM_BABIRI_BERRY = 120;
  ITEM_CHILAN_BERRY = 121;
  ITEM_ROSELI_BERRY = 122;
  ITEM_LIECHI_BERRY = 123;
  ITEM_GANLON_BERRY = 124;
  ITEM_SALAC_BERRY = 125;
  ITEM_PETAYA_BERRY = 126;
  ITEM_APICOT_BERRY = 127;
  ITEM_LANSAT_BERRY = 128;
  ITEM_STARF_BERRY = 129;
  ITEM_MICLE_BERRY = 130;
  ITEM_CUSTAP_BERRY = 131;
  ITEM_JABOCA_BERRY = 132;
  ITEM_ROWAP_BERRY = 133;
  ITEM_KEE_BERRY = 134;
  ITEM_MARANGA_BERRY = 135;
  ITEM_ENIGMA_BERRY = 136;
  ITEM_SUN_STONE = 137;
  ITEM_MOON_STONE = 138;
  ITEM_FIRE_STONE = 139;
  ITEM_THUNDER_STONE = 140;
  ITEM_WATER_STONE = 141;
  ITEM_LEAF_STONE = 142;
  ITEM_DAWN_STONE = 143;
  ITEM_DUSK_STONE = 144;
  ITEM_SHINY_STONE = 145;
  ITEM_ICE_STONE = 146;
  ITEM_RED_NECTAR = 147;
  ITEM_YELLOW_NECTAR = 148;
  ITEM_PINK_NECTAR = 149;
  ITEM_PURPLE_NECTAR = 150;
  ITEM_SWEET_APPLE = 151;
  ITEM_TART_APPLE = 152;
  ITEM_CRACKED_POT = 153;
  ITEM_GALARICA_CUFF = 154;
  ITEM_GALARICA_WREATH = 155;
  ITEM_STRAWBERRY_SWEET = 156;
  ITEM_LOVE_SWEET = 157;
  ITEM_BERRY_SWEET = 158;
  ITEM_CLOVER_SWEET = 159;
  ITEM_FLOWER_SWEET = 160;
  ITEM_STAR_SWEET = 161;
  ITEM_RIBBON_SWEET = 162;
  ITEM_BLUE_FLUTE = 163;
  ITEM_YELLOW_FLUTE = 164;
  ITEM_RED_FLUTE = 165;
  ITEM_BLACK_FLUTE = 166;
  ITEM_WHITE_FLUTE = 167;
  ITEM_SHOAL_SALT = 168;
  ITEM_SHOAL_SHELL = 169;
  ITEM_RED_SHARD = 170;
  ITEM_BLUE_SHARD = 171;
  ITEM_YELLOW_SHARD = 172;
  ITEM_GREEN_SHARD = 173;
  ITEM_ESCAPE_ROPE = 174;
  ITEM_REPEL = 175;
  ITEM_SUPER_REPEL = 176;
  ITEM_MAX_REPEL = 177;
  ITEM_TINY_MUSHROOM = 178;
  ITEM_BIG_MUSHROOM = 179;
  ITEM_BALM_MUSHROOM = 180;
  ITEM_PEARL = 181;
  ITEM_BIG_PEARL = 182;
  ITEM_PEARL_STRING = 183;
  ITEM_STARDUST = 184;
  ITEM_STAR_PIECE = 185;
  ITEM_COMET_SHARD = 186;
  ITEM_NUGGET = 187;
  ITEM_BIG_NUGGET = 188;
  ITEM_RELIC_COPPER = 189;
  ITEM_RELIC_SILVER = 190;
  ITEM_RELIC_GOLD = 191;
  ITEM_RELIC_VASE = 192;
  ITEM_RELIC_STATUE = 193;
  ITEM_RELIC_BAND = 194;
  ITEM_HEART_SCALE = 195;
  ITEM_BOTTLE_CAP = 196;
  ITEM_GOLD_BOTTLE_CAP = 197;
  ITEM_HONEY = 198;
  ITEM_RARE_BONE = 199;
  ITEM_OVAL_STONE = 200;
  ITEM_PROTECTOR = 201;
  ITEM_ELECTIRIZER = 202;
  ITEM_MAGMARIZER = 203;
  ITEM_DUBIOUS_DISC = 204;
  ITEM_REAPER_CLOTH = 205;
  ITEM_PRISM_SCALE = 206;
  ITEM_WHIPPED_DREAM = 207;
  ITEM_SACHET = 208;
  ITEM_UPGRADE = 209;
  ITEM_RED_SCARF = 210;
  ITEM_BLUE_SCARF = 211;
  ITEM_PINK_SCARF = 212;
  ITEM_GREEN_SCARF = 213;
  ITEM_YELLOW_SCARF = 214;
  ITEM_ARMOR_FOSSIL = 215;
  ITEM_SKULL_FOSSIL = 216;
  ITEM_HELIX_FOSSIL = 217;
  ITEM_DOME_FOSSIL = 218;
  ITEM_COVER_FOSSIL = 219;
  ITEM_PLUME_FOSSIL = 220;
  ITEM_JAW_FOSSIL = 221;
  ITEM_SAIL_FOSSIL = 222;
  ITEM_ROOT_FOSSIL = 223;
  ITEM_CLAW_FOSSIL = 224;
  ITEM_FOSSILIZED_BIRD = 225;
  ITEM_FOSSILIZED_FISH = 226;
  ITEM_FOSSILIZED_DRAKE = 227;
  ITEM_FOSSILIZED_DINO = 228;
  ITEM_OLD_AMBER = 229;
  ITEM_GUARD_SPEC = 230;
  ITEM_DIRE_HIT = 231;
  ITEM_X_ATTACK = 232;
  ITEM_X_DEFENSE = 233;
  ITEM_X_SPEED = 234;
  ITEM_X_ACCURACY = 235;
  ITEM_X_SP_ATK = 236;
  ITEM_X_SP_DEF = 237;
  ITEM_POKE_DOLL = 238;
  ITEM_FLUFFY_TAIL = 239;
  ITEM_BRIGHT_POWDER = 240;
  ITEM_WHITE_HERB = 241;
  ITEM_MACHO_BRACE = 242;
  ITEM_EXP_SHARE = 243;
  ITEM_QUICK_CLAW = 244;
  ITEM_SOOTHE_BELL = 245;
  ITEM_MENTAL_HERB = 246;
  ITEM_CHOICE_BAND = 247;
  ITEM_KINGS_ROCK = 248;
  ITEM_SILVER_POWDER = 249;
  ITEM_AMULET_COIN = 250;
  ITEM_CLEANSE_TAG = 251;
  ITEM_SMOKE_BALL = 252;
  ITEM_EVERSTONE = 253;
  ITEM_FOCUS_BAND = 254;
  ITEM_LUCKY_EGG = 255;
  ITEM_SCOPE_LENS = 256;
  ITEM_METAL_COAT = 257;
  ITEM_SOFT_SAND = 258;
  ITEM_HARD_STONE = 259;
  ITEM_MIRACLE_SEED = 260;
  ITEM_BLACK_GLASSES = 261;
  ITEM_BLACK_BELT = 262;
  ITEM_MAGNET = 263;
  ITEM_MYSTIC_WATER = 264;
  ITEM_SHARP_BEAK = 265;
  ITEM_POISON_BARB = 266;
  ITEM_NEVER_MELT_ICE = 267;
  ITEM_SPELL_TAG = 268;
  ITEM_TWISTED_SPOON = 269;
  ITEM_CHARCOAL = 270;
  ITEM_DRAGON_FANG = 271;
  ITEM_SILK_SCARF = 272;
  ITEM_LEFTOVERS = 273;
  ITEM_DRAGON_SCALE = 274;
  ITEM_RAZOR_CLAW = 275;
  ITEM_RAZOR_FANG = 276;
  ITEM_SHELL_BELL = 277;
  ITEM_POWER_BRACER = 278;
  ITEM_POWER_BELT = 279;
  ITEM_POWER_LENS = 280;
  ITEM_POWER_BAND = 281;
  ITEM_POWER_ANKLET = 282;
  ITEM_POWER_WEIGHT = 283;
  ITEM_POWER_HERB = 284;
  ITEM_CHOICE_SCARF = 285;
  ITEM_CHOICE_SPECS = 286;
  ITEM_FOCUS_SASH = 287;
  ITEM_WIDE_LENS = 288;
  ITEM_ZOOM_LENS = 289;
  ITEM_METRONOME = 290;
  ITEM_MUSCLE_BAND = 291;
  ITEM_WISE_GLASSES = 292;
  ITEM_EXPERT_BELT = 293;
  ITEM_LIGHT_CLAY = 294;
  ITEM_ICY_ROCK = 295;
  ITEM_SMOOTH_ROCK = 296;
  ITEM_HEAT_ROCK = 297;
  ITEM_DAMP_ROCK = 298;
  ITEM_DESTINY_KNOT = 299;
  ITEM_GRIP_CLAW = 300;
  ITEM_LIFE_ORB = 301;
  ITEM_TOXIC_ORB = 302;
  ITEM_FLAME_ORB = 303;
  ITEM_STICKY_BARB = 304;
  ITEM_BLACK_SLUDGE = 305;
  ITEM_IRON_BALL = 306;
  ITEM_LAGGING_TAIL = 307;
  ITEM_SHED_SHELL = 308;
  ITEM_BIG_ROOT = 309;
  ITEM_EVIOLITE = 310;
  ITEM_FLOAT_STONE = 311;
  ITEM_ROCKY_HELMET = 312;
  ITEM_AIR_BALLOON = 313;
  ITEM_RED_CARD = 314;
  ITEM_RING_TARGET = 315;
  ITEM_BINDING_BAND = 316;
  ITEM_EJECT_BUTTON = 317;
  ITEM_ABSORB_BULB = 318;
  ITEM_CELL_BATTERY = 319;
  ITEM_LUMINOUS_MOSS = 320;
  ITEM_SNOWBALL = 321;
  ITEM_WEAKNESS_POLICY = 322;
  ITEM_ASSAULT_VEST = 323;
  ITEM_SAFETY_GOGGLES = 324;
  ITEM_ADRENALINE_ORB = 325;
  ITEM_TERRAIN_EXTENDER = 326;
  ITEM_PROTECTIVE_PADS = 327;
  ITEM_ELECTRIC_SEED = 328;
  ITEM_PSYCHIC_SEED = 329;
  ITEM_MISTY_SEED = 330;
  ITEM_GRASSY_SEED = 331;
  ITEM_BUG_GEM = 332;
  ITEM_DARK_GEM = 333;
  ITEM_DRAGON_GEM = 334;
  ITEM_ELECTRIC_GEM = 335;
  ITEM_FAIRY_GEM = 336;
  ITEM_FIGHTING_GEM = 337;
  ITEM_FIRE_GEM = 338;
  ITEM_FLYING_GEM = 339;
  ITEM_GHOST_GEM = 340;
  ITEM_GRASS_GEM = 341;
  ITEM_GROUND_GEM = 342;
  ITEM_ICE_GEM = 343;
  ITEM_NORMAL_GEM = 344;
  ITEM_POISON_GEM = 345;
  ITEM_PSYCHIC_GEM = 346;
  ITEM_ROCK_GEM = 347;
  ITEM_STEEL_GEM = 348;
  ITEM_WATER_GEM = 349;
  ITEM_THROAT_SPRAY = 350;
  ITEM_EJECT_PACK = 351;
  ITEM_HEAVY_DUTY_BOOTS = 352;
  ITEM_BLUNDER_POLICY = 353;
  ITEM_ROOM_SERVICE = 354;
  ITEM_UTILITY_UMBRELLA = 355;
  ITEM_RUSTED_SWORD = 356;
  ITEM_RUSTED_SHIELD = 357;
  ITEM_INSECT_PLATE = 358;
  ITEM_DREAD_PLATE = 359;
  ITEM_DRACO_PLATE = 360;
  ITEM_ZAP_PLATE = 361;
  ITEM_PIXIE_PLATE = 362;
  ITEM_FIST_PLATE = 363;
  ITEM_FLAME_PLATE = 364;
  ITEM_SKY_PLATE = 365;
  ITEM_SPOOKY_PLATE = 366;
  ITEM_MEADOW_PLATE = 367;
  ITEM_EARTH_PLATE = 368;
  ITEM_ICICLE_PLATE = 369;
  ITEM_TOXIC_PLATE = 370;
  ITEM_MIND_PLATE = 371;
  ITEM_STONE_PLATE = 372;
  ITEM_IRON_PLATE = 373;
  ITEM_SPLASH_PLATE = 374;
  ITEM_SOUL_DEW = 375;
  ITEM_DEEP_SEA_TOOTH = 376;
  ITEM_DEEP_SEA_SCALE = 377;
  ITEM_LUCKY_PUNCH = 378;
  ITEM_METAL_POWDER = 379;
  ITEM_THICK_CLUB = 380;
  ITEM_LEEK = 381;
  ITEM_LIGHT_BALL = 382;
  ITEM_QUICK_POWDER = 383;
  ITEM_ADAMANT_ORB = 384;
  ITEM_LUSTROUS_ORB = 385;
  ITEM_GRISEOUS_ORB = 386;
  ITEM_DOUSE_DRIVE = 387;
  ITEM_SHOCK_DRIVE = 388;
  ITEM_BURN_DRIVE = 389;
  ITEM_CHILL_DRIVE = 390;
  ITEM_SEA_INCENSE = 391;
  ITEM_LAX_INCENSE = 392;
  ITEM_ODD_INCENSE = 393;
  ITEM_ROCK_INCENSE = 394;
  ITEM_FULL_INCENSE = 395;
  ITEM_WAVE_INCENSE = 396;
  ITEM_ROSE_INCENSE = 397;
  ITEM_LUCK_INCENSE = 398;
  ITEM_PURE_INCENSE = 399;
  ITEM_TRAINING_BAND = 400;
  ITEM_CANDY_BOX = 401;
  ITEM_INFINITE_REPEL = 402;
  ITEM_IRON_PILL = 403;
  ITEM_ABILITY_SHIELD = 409;
  ITEM_CLEAR_AMULET = 410;
  ITEM_MIRROR_HERB = 411;
  ITEM_PUNCHING_GLOVE = 412;
  ITEM_COVERT_CLOAK = 413;
  ITEM_LOADED_DICE = 414;
  ITEM_FAIRY_FEATHER = 415;
  ITEM_FROST_ORB = 416;
  ITEM_TACTICAL_VEST = 417;
  ITEM_BOOSTER_ENERGY = 418;
  ITEM_SWIRLY_GLASSES = 419;
  ITEM_TM01_FOCUS_PUNCH = 420;
  ITEM_TM02_DRAGON_CLAW = 421;
  ITEM_TM03_WATER_PULSE = 422;
  ITEM_TM04_CALM_MIND = 423;
  ITEM_TM05_ROAR = 424;
  ITEM_TM06_TOXIC = 425;
  ITEM_TM07_HAIL = 426;
  ITEM_TM08_BULK_UP = 427;
  ITEM_TM09_BULLET_SEED = 428;
  ITEM_TM10_HIDDEN_POWER = 429;
  ITEM_TM11_SUNNY_DAY = 430;
  ITEM_TM12_TAUNT = 431;
  ITEM_TM13_ICE_BEAM = 432;
  ITEM_TM14_BLIZZARD = 433;
  ITEM_TM15_HYPER_BEAM = 434;
  ITEM_TM16_LIGHT_SCREEN = 435;
  ITEM_TM17_PROTECT = 436;
  ITEM_TM18_RAIN_DANCE = 437;
  ITEM_TM19_GIGA_DRAIN = 438;
  ITEM_TM20_SAFEGUARD = 439;
  ITEM_TM21_FRUSTRATION = 440;
  ITEM_TM22_SOLARBEAM = 441;
  ITEM_TM23_IRON_TAIL = 442;
  ITEM_TM24_THUNDERBOLT = 443;
  ITEM_TM25_THUNDER = 444;
  ITEM_TM26_EARTHQUAKE = 445;
  ITEM_TM27_RETURN = 446;
  ITEM_TM28_DIG = 447;
  ITEM_TM29_PSYCHIC = 448;
  ITEM_TM30_SHADOW_BALL = 449;
  ITEM_TM31_BRICK_BREAK = 450;
  ITEM_TM32_DOUBLE_TEAM = 451;
  ITEM_TM33_REFLECT = 452;
  ITEM_TM34_SLUDGE_WAVE = 453;
  ITEM_TM35_FLAMETHROWER = 454;
  ITEM_TM36_SLUDGE_BOMB = 455;
  ITEM_TM37_SANDSTORM = 456;
  ITEM_TM38_FIRE_BLAST = 457;
  ITEM_TM39_ROCK_TOMB = 458;
  ITEM_TM40_AERIAL_ACE = 459;
  ITEM_TM41_TORMENT = 460;
  ITEM_TM42_FACADE = 461;
  ITEM_TM43_SECRET_POWER = 462;
  ITEM_TM44_REST = 463;
  ITEM_TM45_ATTRACT = 464;
  ITEM_TM46_THIEF = 465;
  ITEM_TM47_STEEL_WING = 466;
  ITEM_TM48_SKILL_SWAP = 467;
  ITEM_TM49_SLEEP_TALK = 468;
  ITEM_TM50_OVERHEAT = 469;
  ITEM_TM51_ROOST = 470;
  ITEM_TM52_FOCUS_BLAST = 471;
  ITEM_TM53_ENERGY_BALL = 472;
  ITEM_TM54_PSYSHOCK = 473;
  ITEM_TM55_SCALD = 474;
  ITEM_TM56_LEECH_LIFE = 475;
  ITEM_TM57_CHARGE_BEAM = 476;
  ITEM_TM58_ENDURE = 477;
  ITEM_TM59_DRAGON_PULSE = 478;
  ITEM_TM60_DRAIN_PUNCH = 479;
  ITEM_TM61_WILL_O_WISP = 480;
  ITEM_TM62_ACROBATICS = 481;
  ITEM_TM63_ROCK_SLIDE = 482;
  ITEM_TM64_EXPLOSION = 483;
  ITEM_TM65_SHADOW_CLAW = 484;
  ITEM_TM66_PAYBACK = 485;
  ITEM_TM67_RECYCLE = 486;
  ITEM_TM68_GIGA_IMPACT = 487;
  ITEM_TM69_ROCK_POLISH = 488;
  ITEM_TM70_AURORA_VEIL = 489;
  ITEM_TM71_STONE_EDGE = 490;
  ITEM_TM72_VOLT_SWITCH = 491;
  ITEM_TM73_THUNDER_WAVE = 492;
  ITEM_TM74_GYRO_BALL = 493;
  ITEM_TM75_SWORDS_DANCE = 494;
  ITEM_TM76_STEALTH_ROCK = 495;
  ITEM_TM77_STRUGGLE_BUG = 496;
  ITEM_TM78_BULLDOZE = 497;
  ITEM_TM79_FREEZE_DRY = 498;
  ITEM_TM80_VENOSHOCK = 499;
  ITEM_TM81_X_SCISSOR = 500;
  ITEM_TM82_DRAGON_TAIL = 501;
  ITEM_TM83_FLAME_CHARGE = 502;
  ITEM_TM84_POISON_JAB = 503;
  ITEM_TM85_DREAM_EATER = 504;
  ITEM_TM86_GRASS_KNOT = 505;
  ITEM_TM87_SMACK_DOWN = 506;
  ITEM_TM88_LOW_SWEEP = 507;
  ITEM_TM89_U_TURN = 508;
  ITEM_TM90_SUBSTITUTE = 509;
  ITEM_TM91_FLASH_CANNON = 510;
  ITEM_TM92_TRICK_ROOM = 511;
  ITEM_TM93_WILD_CHARGE = 512;
  ITEM_TM94_SUCKER_PUNCH = 513;
  ITEM_TM95_SNARL = 514;
  ITEM_TM96_AVALANCHE = 515;
  ITEM_TM97_DARK_PULSE = 516;
  ITEM_TM98_FALSE_SWIPE = 517;
  ITEM_TM99_DAZZLING_GLEAM = 518;
  ITEM_TM100_CURSE = 519;
  ITEM_HM01_CUT = 520;
  ITEM_HM02_FLY = 521;
  ITEM_HM03_SURF = 522;
  ITEM_HM04_STRENGTH = 523;
  ITEM_HM05_FLASH = 524;
  ITEM_HM06_ROCK_SMASH = 525;
  ITEM_HM07_WATERFALL = 526;
  ITEM_HM08_DIVE = 527;
  ITEM_ODD_KEYSTONE = 528;
  ITEM_GRACIDEA = 529;
  ITEM_MEGA_BRACELET = 530;
  ITEM_MACH_BIKE = 531;
  ITEM_COIN_CASE = 532;
  ITEM_ITEMFINDER = 533;
  ITEM_OLD_ROD = 534;
  ITEM_GOOD_ROD = 535;
  ITEM_SUPER_ROD = 536;
  ITEM_SS_TICKET = 537;
  ITEM_CONTEST_PASS = 538;
  ITEM_WAILMER_PAIL = 539;
  ITEM_DEVON_GOODS = 540;
  ITEM_SOOT_SACK = 541;
  ITEM_BASEMENT_KEY = 542;
  ITEM_ACRO_BIKE = 543;
  ITEM_EGG_INCUBATOR = 544;
  ITEM_LETTER = 545;
  ITEM_EON_TICKET = 546;
  ITEM_EXP_CHARM = 547;
  ITEM_PRISON_BOTTLE = 548;
  ITEM_SCANNER = 549;
  ITEM_GO_GOGGLES = 550;
  ITEM_METEORITE = 551;
  ITEM_ROOM_1_KEY = 552;
  ITEM_ROOM_2_KEY = 553;
  ITEM_ROOM_4_KEY = 554;
  ITEM_ROOM_6_KEY = 555;
  ITEM_STORAGE_KEY = 556;
  ITEM_DEVON_SCOPE = 557;
  ITEM_MAGMA_STONE = 558;
  ITEM_LUNAR_WING = 559;
  ITEM_SHINY_CHARM = 560;
  ITEM_OVAL_CHARM = 561;
  ITEM_MAGMA_EMBLEM = 562;
  ITEM_OLD_SEA_MAP = 563;
  ITEM_MYSTIC_TICKET = 564;
  ITEM_AURORA_TICKET = 565;
  ITEM_POWDER_JAR = 566;
  ITEM_REVEAL_GLASS = 567;
  ITEM_DNA_SPLICERS = 568;
  ITEM_POKE_VIAL = 569;
  ITEM_CATCHING_CHARM = 570;
  ITEM_ROTOM_CATALOG = 571;
  ITEM_REINS_OF_UNITY = 572;
  ITEM_ICEROOT_CARROT = 573;
  ITEM_SHADEROOT_CARROT = 574;
  ITEM_WOODEN_CROWN = 575;
  ITEM_N_LUNARIZER = 576;
  ITEM_N_SOLARIZER = 577;
  ITEM_ABOMASITE = 578;
  ITEM_ABSOLITE = 579;
  ITEM_AERODACTYLITE = 580;
  ITEM_AGGRONITE = 581;
  ITEM_ALAKAZITE = 582;
  ITEM_ALTARIANITE = 583;
  ITEM_AMPHAROSITE = 584;
  ITEM_AUDINITE = 585;
  ITEM_BANETTITE = 586;
  ITEM_BEEDRILLITE = 587;
  ITEM_BLASTOISINITE = 588;
  ITEM_BLAZIKENITE = 589;
  ITEM_CAMERUPTITE = 590;
  ITEM_CHARIZARDITE_X = 591;
  ITEM_CHARIZARDITE_Y = 592;
  ITEM_DIANCITE = 593;
  ITEM_GALLADITE = 594;
  ITEM_GARCHOMPITE = 595;
  ITEM_GARDEVOIRITE = 596;
  ITEM_GENGARITE = 597;
  ITEM_GLALITITE = 598;
  ITEM_GYARADOSITE = 599;
  ITEM_HERACRONITE = 600;
  ITEM_HOUNDOOMINITE = 601;
  ITEM_KANGASKHANITE = 602;
  ITEM_LATIASITE = 603;
  ITEM_LATIOSITE = 604;
  ITEM_LOPUNNITE = 605;
  ITEM_LUCARIONITE = 606;
  ITEM_MANECTITE = 607;
  ITEM_MAWILITE = 608;
  ITEM_MEDICHAMITE = 609;
  ITEM_METAGROSSITE = 610;
  ITEM_MEWTWONITE_X = 611;
  ITEM_MEWTWONITE_Y = 612;
  ITEM_PIDGEOTITE = 613;
  ITEM_PINSIRITE = 614;
  ITEM_SABLENITE = 615;
  ITEM_SALAMENCITE = 616;
  ITEM_SCEPTILITE = 617;
  ITEM_SCIZORITE = 618;
  ITEM_SHARPEDONITE = 619;
  ITEM_SLOWBRONITE = 620;
  ITEM_STEELIXITE = 621;
  ITEM_SWAMPERTITE = 622;
  ITEM_TYRANITARITE = 623;
  ITEM_VENUSAURITE = 624;
  ITEM_MILOTICITE = 625;
  ITEM_RED_ORB = 626;
  ITEM_BLUE_ORB = 627;
  ITEM_FLYGONITE = 628;
  ITEM_BUTTERFRENITE = 629;
  ITEM_LAPRASITE_Y = 630;
  ITEM_MACHAMPITE = 631;
  ITEM_KINGLERITE = 632;
  ITEM_KINGDRANITE = 633;
  ITEM_DEWGONGITE = 634;
  ITEM_HITMONCHANITE = 635;
  ITEM_HITMONLEENITE = 636;
  ITEM_HITMONTOPITE = 637;
  ITEM_CROBATITE = 638;
  ITEM_SKARMORITE = 639;
  ITEM_BRUXISHITE = 640;
  ITEM_TORTERRANITE = 641;
  ITEM_INFERNAPENITE = 642;
  ITEM_EMPOLEONITE = 643;
  ITEM_SHUCKLENITE = 644;
  ITEM_RELICANTHITE = 645;
  ITEM_QUAGSIRENITE = 646;
  ITEM_JELLICENTITE = 647;
  ITEM_TOUCANNONITE = 648;
  ITEM_DRAGONINITE = 649;
  ITEM_BRELOOMITE = 650;
  ITEM_SLAKINGITE = 651;
  ITEM_PURPLE_ORB = 652;
  ITEM_SLOWKINGITE = 653;
  ITEM_GYARADOSITE_Y = 654;
  ITEM_FERALIGITE_X = 655;
  ITEM_FERALIGITE_Y = 656;
  ITEM_HAXORUSITE = 657;
  ITEM_LUXRAYNITE = 658;
  ITEM_GRANBULLITE = 659;
  ITEM_TYPHLOSIONITE = 660;
  ITEM_NIDOQUEENITE = 661;
  ITEM_NIDOKINGITE = 662;
  ITEM_SANDSLASHITE = 663;
  ITEM_MEGANIUMITE = 664;
  ITEM_KROOKODILENITE = 665;
  ITEM_MAGNEZONITE = 666;
  ITEM_SHEDINJITE = 667;
  ITEM_SWALOTITE = 668;
  ITEM_LANTURNITE = 669;
  ITEM_LAPRASITE_X = 670;
  ITEM_KINGAMBITITE_R = 671;
  ITEM_RIBOMBITE = 672;
  ITEM_GARCHOMPITE_R = 673;
  ITEM_SKARMORITE_R = 674;
  ITEM_MACHAMPITE_R = 675;
  ITEM_ALAKAZITE_R = 676;
  ITEM_BEEDRILLITE_R = 677;
  ITEM_HOUNDOOMINITE_R = 678;
  ITEM_FROSLASSITE = 679;
  ITEM_SCRAFTINITE = 680;
  ITEM_MAWILITE_R = 681;
  ITEM_SABLENITE_R = 682;
  ITEM_URSALUNITE = 683;
  ITEM_ARCANITE_R = 684;
  ITEM_TYRANITARITE_R = 685;
  ITEM_WIGGLYTUFFITE = 686;
  ITEM_TINKATITE = 687;
  ITEM_GYARADEATHITE_X = 688;
  ITEM_GYARADEATHITE_Y = 689;
  ITEM_SENZU = 690;
  ITEM_AEGISLASHITE_R = 691;
  ITEM_ARBOKITE = 692;
  ITEM_CLEFABLITE_R = 693;
  ITEM_FLYGONITE_R = 694;
  ITEM_EMPOLEONITE_R = 695;
  ITEM_INFERNAPENITE_R = 696;
  ITEM_FROSLASSITE_R = 697;
  ITEM_GLALITITE_R = 698;
  ITEM_RAPIDASHITE_G = 699;
  ITEM_GOLISOPODITE = 700;
  ITEM_HYDREIGONITE_R = 701;
  ITEM_TORTERRANITE_R = 702;
  ITEM_RAPIDASHITE = 703;
  ITEM_CORMOTHITE = 704;
  ITEM_POPCORMITE = 705;
  ITEM_REUNICLUSITE_R = 706;
  ITEM_TOXTRICITITE_R = 707;
  ITEM_ORICORIONITE = 708;
  ITEM_TSAREENITE_R = 709;
  ITEM_URSHIFITE = 710;
  ITEM_AMPHYBUZZITE = 711;
  ITEM_MELMETALITE = 712;
  ITEM_DYNAMAX_ORB = 713;
  ITEM_TERA_ORB = 714;
  ITEM_VENUSAURITE_X = 715;
  ITEM_CHARIZARDITE_Z = 716;
  ITEM_BLASTOISINITE_X = 717;
  ITEM_GENGARITE_X = 718;
  ITEM_SNORLAXITE = 719;
  ITEM_RILLABOOMITE = 720;
  ITEM_CINDERACEITE = 721;
  ITEM_INTELEONITE = 722;
  ITEM_CORVINITE = 723;
  ITEM_DREDNAWITE = 724;
  ITEM_COALOSSITE = 725;
  ITEM_SANDACONDITE = 726;
  ITEM_COPPERAJITE = 727;
  ITEM_HATTERENITE = 728;
  ITEM_GARBODORITE = 729;
  ITEM_ORBEETITE = 730;
  ITEM_GRIMMSNARLITE = 731;
  ITEM_CENTISKITE = 732;
  ITEM_ALCREMITE = 733;
  ITEM_TOXTRICITITE = 734;
  ITEM_PIKANITE = 735;
  ITEM_MEOWTHITE = 736;
  ITEM_EEVITE = 737;
  ITEM_DURALUDITE = 738;
  ITEM_ULTRANECROZIUM_P = 739;
  ITEM_FIDOUGHITE = 740;
  ITEM_WIGGLYTUFFITE_X = 741;
  ITEM_SERPERIORITE = 742;
  ITEM_EMBOARITE = 743;
  ITEM_SAMUROTTITE = 744;
  ITEM_DECIDUITE = 745;
  ITEM_WEAVILEITE = 746;
  ITEM_DECIDUITE_H = 747;
  ITEM_INCINERITE = 748;
  ITEM_MEOWSCARADITE = 749;
  ITEM_PRIMARINITE = 750;
  ITEM_QUAQUAVITE = 751;
  ITEM_SAMUROTTITE_H = 752;
  ITEM_SKELEDIRGEITE = 753;
  ITEM_TYPHLOSIONITE_H = 754;
  ITEM_MIENSHAOITE = 755;
  ITEM_GOODRITE = 756;
  ITEM_SLOWBRONITE_G = 757;
  ITEM_SLOWKINGITE_G = 758;
  ITEM_ROSERADEITE = 759;
  ITEM_ARCANITE = 760;
  ITEM_KINGDRANITE_Y = 761;
  ITEM_PHANTOM_METEOR = 762;
  ITEM_YVELTALITE = 763;
  ITEM_GALACTIC_ORB = 764;
  ITEM_CHIEN_PAOITE = 765;
  ITEM_DRACOVISHITE = 766;
  ITEM_MAWILITE_R_B = 767;
  ITEM_RIBOMBITE_R = 768;
  ITEM_WEAVILEITE_R = 769;
  ITEM_FLYGONITE_R_B = 770;
  ITEM_SNORLAX_ORB = 771;
  ITEM_VICTINI_ORB = 772;
  ITEM_WIGGLITUFF_ORB = 773;
  ITEM_ABOMASITE_S = 774;
  ITEM_FAB_MAIL = 799;
  ITEM_RETRO_MAIL = 800;
  ITEM_BUG_MEMORY = 801;
  ITEM_DARK_MEMORY = 802;
  ITEM_DRAGON_MEMORY = 803;
  ITEM_ELECTRIC_MEMORY = 804;
  ITEM_FAIRY_MEMORY = 805;
  ITEM_FIGHTING_MEMORY = 806;
  ITEM_FIRE_MEMORY = 807;
  ITEM_FLYING_MEMORY = 808;
  ITEM_GHOST_MEMORY = 809;
  ITEM_GRASS_MEMORY = 810;
  ITEM_GROUND_MEMORY = 811;
  ITEM_ICE_MEMORY = 812;
  ITEM_POISON_MEMORY = 813;
  ITEM_PSYCHIC_MEMORY = 814;
  ITEM_ROCK_MEMORY = 815;
  ITEM_STEEL_MEMORY = 816;
  ITEM_WATER_MEMORY = 817;
  ITEM_OAKS_PARCEL = 818;
  ITEM_POKE_FLUTE = 819;
  ITEM_SECRET_KEY = 820;
  ITEM_BIKE_VOUCHER = 821;
  ITEM_GOLD_TEETH = 822;
  ITEM_CARD_KEY = 823;
  ITEM_LIFT_KEY = 824;
  ITEM_SILPH_SCOPE = 825;
  ITEM_BICYCLE = 826;
  ITEM_TOWN_MAP = 827;
  ITEM_VS_SEEKER = 828;
  ITEM_FAME_CHECKER = 829;
  ITEM_TM_CASE = 830;
  ITEM_BERRY_POUCH = 831;
  ITEM_TEACHY_TV = 832;
  ITEM_TRI_PASS = 833;
  ITEM_RAINBOW_PASS = 834;
  ITEM_TEA = 835;
  ITEM_RUBY = 836;
  ITEM_SAPPHIRE = 837;
  ITEM_Z_RING = 838;
  ITEM_NORMALIUM_Z = 839;
  ITEM_FIGHTINIUM_Z = 840;
  ITEM_FLYINIUM_Z = 841;
  ITEM_POISONIUM_Z = 842;
  ITEM_GROUNDIUM_Z = 843;
  ITEM_ROCKIUM_Z = 844;
  ITEM_BUGINIUM_Z = 845;
  ITEM_GHOSTIUM_Z = 846;
  ITEM_STEELIUM_Z = 847;
  ITEM_FIRIUM_Z = 848;
  ITEM_WATERIUM_Z = 849;
  ITEM_GRASSIUM_Z = 850;
  ITEM_ELECTRIUM_Z = 851;
  ITEM_PSYCHIUM_Z = 852;
  ITEM_ICIUM_Z = 853;
  ITEM_DRAGONIUM_Z = 854;
  ITEM_DARKINIUM_Z = 855;
  ITEM_FAIRIUM_Z = 856;
  ITEM_ALORAICHIUM_Z = 857;
  ITEM_DECIDIUM_Z = 858;
  ITEM_EEVIUM_Z = 859;
  ITEM_INCINIUM_Z = 860;
  ITEM_KOMMONIUM_Z = 861;
  ITEM_LUNALIUM_Z = 862;
  ITEM_LYCANIUM_Z = 863;
  ITEM_MARSHADIUM_Z = 864;
  ITEM_MEWNIUM_Z = 865;
  ITEM_MIMIKIUM_Z = 866;
  ITEM_PIKANIUM_Z = 867;
  ITEM_PIKASHUNIUM_Z = 868;
  ITEM_PRIMARIUM_Z = 869;
  ITEM_SNORLIUM_Z = 870;
  ITEM_SOLGANIUM_Z = 871;
  ITEM_TAPUNIUM_Z = 872;
  ITEM_ULTRANECROZIUM_Z = 873;
  ITEM_DUDUDUNITE = 404;
  ITEM_TEAL_MASK = 405;
  ITEM_HEARTHFLAME_MASK = 406;
  ITEM_WELLSPRING_MASK = 407;
  ITEM_CORNERSTONE_MASK = 408;
  ITEM_TINKATITE_R = 775;
  ITEM_SCIZORITE_R = 776;
  ITEM_SCYTHERITE_R = 777;
  ITEM_KLEAVITE_R = 778;
  ITEM_KINGLERITE_R = 779;
  ITEM_LUXRAYNITE_R = 780;
  ITEM_KILOZUNITE = 781;
  ITEM_AGGRONITE_R = 782;
  ITEM_GARDEVOIRITE_R = 783;
  ITEM_GALLADITE_R = 784;
  ITEM_CLODSITE = 785;
  ITEM_GOTHITITE = 786;
  ITEM_SNORLAXITE_R = 787;
  ITEM_ARCANITE_H = 788;
  ITEM_REUNICLUSITE = 789;
  ITEM_SWAMPAGEITE = 790;
  ITEM_CHANDELURITE = 791;
  ITEM_ZAPDOSITE = 792;
  ITEM_ARTICUNITE = 793;
  ITEM_MOLTRESITE = 794;
  ITEM_CARBONIXITE = 795;
  ITEM_DRAGAPULTITE = 796;
  ITEM_SANDSLASHITE_A = 797;
  ITEM_KLEAVITE = 798;
  ITEM_SCYTHERITE = 874;
  ITEM_HYDREIGONITE = 875;
  ITEM_VANILLUXEITE = 876;
  ITEM_HERACREUSITE = 877;
  ITEM_EXCADRILLITE_R = 878;
  ITEM_MAMOSWINITE_R = 879;
  ITEM_VANILLUXEITE_R = 880;
  ITEM_CHANDELURITE_R = 881;
  ITEM_SNEASLERITE = 882;
  ITEM_CLEFABLITE = 883;
  ITEM_GOODRITE_H = 884;
  ITEM_TSAREENITE = 885;
  ITEM_ALTARIANITE_R = 886;
  ITEM_HARIYAMITE = 887;
  ITEM_LUXZERITE = 888;
  ITEM_TALONFLAMEITE = 889;
  ITEM_CHESNAUGHTITE = 890;
  ITEM_GRENINJITE = 891;
  ITEM_DELPHOXITE = 892;
  ITEM_CLEFABLITE_Y = 893;
  ITEM_VICTREEBELITE = 894;
  ITEM_STARMINITE = 895;
  ITEM_DRAGONINITE_Y = 896;
  ITEM_EXCADRITE = 897;
  ITEM_SCOLIPITE = 898;
  ITEM_EELEKTROSSITE = 899;
  ITEM_CHANDELURITE_Y = 900;
  ITEM_PYROARITE = 901;
  ITEM_MALAMARITE = 902;
  ITEM_BARBARACITE = 903;
  ITEM_DRAGALGITE = 904;
  ITEM_HAWLUCHANITE = 905;
  ITEM_ZYGARDITE = 906;
  ITEM_DRAMPANITE = 907;
  ITEM_FALINKSITE = 908;
  ITEM_RAICHUNITE_X = 909;
  ITEM_RAICHUNITE_Y = 910;
  ITEM_EYE_OF_ENDER = 911;
  ITEM_FLOETTITE = 912;
  ITEM_SKARMORITE_Y = 913;
  ITEM_FROSLASSITE_Y = 914;
}
