syntax = "proto3";

package er;

option java_package = "er.proto";
option java_multiple_files = true;

enum LandType {
  CLIMATE_NONE = 0;
  CLIMATE_TEMPERATE = 1;
  CLIMATE_FOREST = 2;
  CLIMATE_FOREST_ENTRANCE = 3;
  CLIMATE_CAVE_ENTRANCE = 4;
  CLIMATE_URBAN = 5;
  CLIMATE_CAVE = 6;
  CLIMATE_GHOST = 7;
  CLIMATE_DEEP_CAVE = 8;
  CLIMATE_ICE = 9;
  CLIMATE_TROPICAL = 10;
  CLIMATE_BEACH = 11;
  CLIMATE_MEADOW = 12;
  CLIMATE_OUTSIDE_GHOST = 13;
  CLIMATE_ARID = 14;
  CLIMATE_HOT_CAVE = 15;
  CLIMATE_ASH = 16;
  CLIMATE_DESERT_CAVE = 17;
  CLIMATE_DESERT = 18;
  CLIMATE_DEEP_DESERT = 19;
  CLIMATE_POWER_PLANT = 20;
  CLIMATE_POWER_PLANT_INSIDE = 21;
  CLIMATE_JUNGLE = 22;
  CLIMATE_PYRE_SUMMIT = 23;
  CLIMATE_MAGMA_HIDEOUT = 24;
  CLIMATE_DIVE = 25;
  CLIMATE_ARCTIC = 26;
  CLIMATE_MIRAGE_ISLAND = 27;
  CLIMATE_SEAFLOOR_CAVERN = 28;
  CLIMATE_SKY_PILLAR = 29;
  CLIMATE_CAVE_OF_ORIGIN = 30;
  CLIMATE_VICTORY_ROAD = 31;
  CLIMATE_COLD_CAVE = 32;
}

enum WaterType {
  WATER_NONE = 0;
  WATER_OCEAN_COAST = 1;
  WATER_POND = 2;
  WATER_CAVE = 3;
  WATER_GHOST_OUTSIDE = 4;
  WATER_OCEAN = 5;
  WATER_RIVER = 6;
  WATER_ARCTIC = 7;
  WATER_COLD_CAVE = 8;
  WATER_DEEP_OCEAN = 9;
  WATER_EVER_GRANDE = 10;
  WATER_RAPIDS = 11;
  WATER_DIVE = 12;
  WATER_SEAFLOOR_CAVERN = 13;
  WATER_SOOTOPOLIS = 14;
  WATER_VICTORY_ROAD = 15;
  WATER_TROPICAL = 16;
}

enum RandomizerCategory {
  RANDOMIZER_NONE = 0;
  RANDOMIZER_GRASS_STARTER = 1;
  RANDOMIZER_WATER_STARTER = 2;
  RANDOMIZER_FIRE_STARTER = 3;
  RANDOMIZER_PSEUDO_LEGENDARY = 4;
  RANDOMIZER_BOX_LEGENDARY_PAIR = 5;
  RANDOMIZER_BOX_LEGENDARY_SOLO = 6;
  RANDOMIZER_MYTHICAL = 7;
  RANDOMIZER_PARADOX = 8;
  RANDOMIZER_STANDARD = 9;
  RANDOMIZER_TBD = 10;
  RANDOMIZER_FOSSIL = 11;
  RANDOMIZER_LEGENDARY_TRIO = 12;
}

enum RandomizerRegion {
  REGION_NONE = 0;
  REGION_LITTLEROOT = 1;
  REGION_RUSTBORO = 2;
  REGION_POST_ROXANNE = 3;
  REGION_DEWFORD = 4;
  REGION_SLATEPORT = 5;
  REGION_MAUVILLE = 6;
  REGION_POST_WATTSON = 7;
  REGION_METEOR_FALLS = 8;
  REGION_JAGGED_PASS = 9;
  REGION_SUNHOME = 10;
  REGION_DEWFORD_SURF_ONLY_ROUTES = 11;
  REGION_POWER_PLANT = 12;
  REGION_FORTREE = 13;
  REGION_MT_PYRE = 14;
  REGION_MAGMA_HIDEOUT = 15;
  REGION_MOSSDEEP = 16;
  REGION_POST_MOSDEEP_OCEAN = 17;
  REGION_DIVE = 18;
  REGION_SKY_PILLAR = 19;
  REGION_POST_JUAN = 20;
  REGION_VICTORY_ROAD = 21;
  REGION_POSTGAME = 22;
}

message LimitedRandomizerConfig {
  message Area {

    repeated string name = 1;
    repeated RandomizerRegion region = 2;
    int32 adoption_center_id = 3;
    repeated LandType land_type = 4;
    repeated WaterType water_type = 5;
    bool has_berries = 6;
    bool has_cut = 7;
    bool has_rock_smash = 8;
  }
  repeated Area area = 1;
}

