syntax = "proto3";

package er;

import "google/protobuf/descriptor.proto";

option java_package = "er.proto";
option java_multiple_files = true;

extend google.protobuf.EnumValueOptions {
  optional bool no_sheer_force = 1001000;
  optional bool flinch_effect = 1001001;
  optional bool no_kings_rock = 1001002;
  optional bool two_turn = 1001003;
  optional bool no_parental_bond = 1001004;
}

enum MoveBehavior {
  EFFECT_HIT = 0;
  EFFECT_SLEEP = 1;
  EFFECT_POISON_HIT = 2;
  EFFECT_ABSORB = 3;
  EFFECT_BURN_HIT = 4;
  EFFECT_FREEZE_HIT = 5;
  EFFECT_PARALYZE_HIT = 6;
  EFFECT_EXPLOSION = 7 [(no_parental_bond) = true];
  EFFECT_DREAM_EATER = 8;
  EFFECT_MIRROR_MOVE = 9;
  EFFECT_ATTACK_UP = 10;
  EFFECT_DEFENSE_UP = 11;
  EFFECT_SPEED_UP = 12;
  EFFECT_SPECIAL_ATTACK_UP = 13;
  EFFECT_SPECIAL_DEFENSE_UP = 14;
  EFFECT_ACCURACY_UP = 15;
  EFFECT_EVASION_UP = 16;
  EFFECT_SPECIAL_ATTACK_UP_3 = 17;
  EFFECT_ATTACK_DOWN = 18;
  EFFECT_DEFENSE_DOWN = 19;
  EFFECT_SPEED_DOWN = 20;
  EFFECT_SPECIAL_ATTACK_DOWN = 21;
  EFFECT_SPECIAL_DEFENSE_DOWN = 22;
  EFFECT_ACCURACY_DOWN = 23;
  EFFECT_EVASION_DOWN = 24;
  EFFECT_HAZE = 25;
  EFFECT_BIDE = 26;
  EFFECT_RAMPAGE = 27 [(no_sheer_force) = true];
  EFFECT_ROAR = 28;
  EFFECT_MULTI_HIT = 29 [(no_parental_bond) = true];
  EFFECT_CONVERSION = 30;
  EFFECT_FLINCH_HIT = 31 [(flinch_effect) = true];
  EFFECT_RESTORE_HP = 32;
  EFFECT_TOXIC = 33;
  EFFECT_PAY_DAY = 34 [(no_sheer_force) = true];
  EFFECT_LIGHT_SCREEN = 35;
  EFFECT_TRI_ATTACK = 36;
  EFFECT_REST = 37;
  EFFECT_OHKO = 38;
  EFFECT_FUSION_COMBO = 39;
  EFFECT_SUPER_FANG = 40;
  EFFECT_DRAGON_RAGE = 41;
  EFFECT_TRAP = 42 [(no_sheer_force) = true];
  EFFECT_HEAL_BLOCK = 43;
  EFFECT_DOUBLE_HIT = 44 [(no_parental_bond) = true];
  EFFECT_RECOIL_IF_MISS = 45;
  EFFECT_MIST = 46;
  EFFECT_FOCUS_ENERGY = 47;
  EFFECT_RECOIL_25 = 48;
  EFFECT_CONFUSE = 49;
  EFFECT_ATTACK_UP_2 = 50;
  EFFECT_DEFENSE_UP_2 = 51;
  EFFECT_SPEED_UP_2 = 52;
  EFFECT_SPECIAL_ATTACK_UP_2 = 53;
  EFFECT_SPECIAL_DEFENSE_UP_2 = 54;
  EFFECT_ACCURACY_UP_2 = 55;
  EFFECT_EVASION_UP_2 = 56;
  EFFECT_TRANSFORM = 57;
  EFFECT_ATTACK_DOWN_2 = 58;
  EFFECT_DEFENSE_DOWN_2 = 59;
  EFFECT_SPEED_DOWN_2 = 60;
  EFFECT_SPECIAL_ATTACK_DOWN_2 = 61;
  EFFECT_SPECIAL_DEFENSE_DOWN_2 = 62;
  EFFECT_ACCURACY_DOWN_2 = 63;
  EFFECT_EVASION_DOWN_2 = 64;
  EFFECT_REFLECT = 65;
  EFFECT_POISON = 66;
  EFFECT_PARALYZE = 67;
  EFFECT_ATTACK_DOWN_HIT = 68;
  EFFECT_DEFENSE_DOWN_HIT = 69;
  EFFECT_SPEED_DOWN_HIT = 70;
  EFFECT_SPECIAL_ATTACK_DOWN_HIT = 71;
  EFFECT_SPECIAL_DEFENSE_DOWN_HIT = 72;
  EFFECT_ACCURACY_DOWN_HIT = 73;
  EFFECT_EVASION_DOWN_HIT = 74;
  EFFECT_TWO_TURNS_ATTACK = 75 [(two_turn) = true];
  EFFECT_CONFUSE_HIT = 76;
  EFFECT_TWINEEDLE = 77;
  EFFECT_VITAL_THROW = 78;
  EFFECT_SUBSTITUTE = 79;
  EFFECT_RECHARGE = 80;
  EFFECT_RAGE = 81;
  EFFECT_MIMIC = 82;
  EFFECT_METRONOME = 83;
  EFFECT_LEECH_SEED = 84;
  EFFECT_DO_NOTHING = 85;
  EFFECT_DISABLE = 86;
  EFFECT_LEVEL_DAMAGE = 87;
  EFFECT_PSYWAVE = 88;
  EFFECT_COUNTER = 89 [(no_kings_rock) = true];
  EFFECT_ENCORE = 90;
  EFFECT_PAIN_SPLIT = 91;
  EFFECT_SNORE = 92 [(flinch_effect) = true];
  EFFECT_CONVERSION_2 = 93;
  EFFECT_LOCK_ON = 94;
  EFFECT_SKETCH = 95;
  EFFECT_HAMMER_ARM = 96 [(no_sheer_force) = true];
  EFFECT_SLEEP_TALK = 97;
  EFFECT_DESTINY_BOND = 98;
  EFFECT_FLAIL = 99;
  EFFECT_SPITE = 100;
  EFFECT_FALSE_SWIPE = 101;
  EFFECT_HEAL_BELL = 102;
  EFFECT_ALWAYS_CRIT = 103;
  EFFECT_TRIPLE_KICK = 104 [(no_parental_bond) = true];
  EFFECT_THIEF = 105 [(no_sheer_force) = true];
  EFFECT_MEAN_LOOK = 106;
  EFFECT_NIGHTMARE = 107 [(no_sheer_force) = true];
  EFFECT_MINIMIZE = 108;
  EFFECT_CURSE = 109;
  EFFECT_HEALING_WISH = 110;
  EFFECT_PROTECT = 111;
  EFFECT_SPIKES = 112;
  EFFECT_FORESIGHT = 113;
  EFFECT_PERISH_SONG = 114;
  EFFECT_SANDSTORM = 115;
  EFFECT_ENDURE = 116;
  EFFECT_ROLLOUT = 117;
  EFFECT_SWAGGER = 118;
  EFFECT_FURY_CUTTER = 119;
  EFFECT_ATTRACT = 120;
  EFFECT_RETURN = 121;
  EFFECT_PRESENT = 122;
  EFFECT_FRUSTRATION = 123;
  EFFECT_SAFEGUARD = 124;
  EFFECT_UNUSED_125 = 125;
  EFFECT_MAGNITUDE = 126;
  EFFECT_BATON_PASS = 127;
  EFFECT_PURSUIT = 128;
  EFFECT_RAPID_SPIN = 129;
  EFFECT_SONICBOOM = 130;
  EFFECT_CAPTIVATE = 131;
  EFFECT_MORNING_SUN = 132;
  EFFECT_SYNTHESIS = 133;
  EFFECT_MOONLIGHT = 134;
  EFFECT_HIDDEN_POWER = 135;
  EFFECT_RAIN_DANCE = 136;
  EFFECT_SUNNY_DAY = 137;
  EFFECT_DEFENSE_UP_HIT = 138;
  EFFECT_ATTACK_UP_HIT = 139;
  EFFECT_ALL_STATS_UP_HIT = 140;
  EFFECT_FELL_STINGER = 141;
  EFFECT_BELLY_DRUM = 142;
  EFFECT_PSYCH_UP = 143;
  EFFECT_MIRROR_COAT = 144 [(no_kings_rock) = true];
  EFFECT_SKULL_BASH = 145;
  EFFECT_TWISTER = 146 [(flinch_effect) = true];
  EFFECT_EARTHQUAKE = 147;
  EFFECT_FUTURE_SIGHT = 148 [(no_kings_rock) = true];
  EFFECT_GUST = 149;
  EFFECT_FLINCH_MINIMIZE_HIT = 150 [(flinch_effect) = true];
  EFFECT_SOLARBEAM = 151 [(two_turn) = true];
  EFFECT_THUNDER = 152;
  EFFECT_SWITCH_ARGUMENT = 153;
  EFFECT_BEAT_UP = 154 [(no_parental_bond) = true];
  EFFECT_SEMI_INVULNERABLE = 155 [(two_turn) = true];
  EFFECT_DEFENSE_CURL = 156;
  EFFECT_SOFTBOILED = 157;
  EFFECT_FAKE_OUT = 158 [(flinch_effect) = true];
  EFFECT_UPROAR = 159;
  EFFECT_STOCKPILE = 160;
  EFFECT_SPIT_UP = 161;
  EFFECT_SWALLOW = 162;
  EFFECT_WORRY_SEED = 163;
  EFFECT_HAIL = 164;
  EFFECT_TORMENT = 165;
  EFFECT_FLATTER = 166;
  EFFECT_WILL_O_WISP = 167;
  EFFECT_MEMENTO = 168;
  EFFECT_FACADE = 169;
  EFFECT_FOCUS_PUNCH = 170;
  EFFECT_SMELLINGSALT = 171;
  EFFECT_FOLLOW_ME = 172;
  EFFECT_NATURE_POWER = 173;
  EFFECT_CHARGE = 174;
  EFFECT_TAUNT = 175;
  EFFECT_HELPING_HAND = 176;
  EFFECT_TRICK = 177;
  EFFECT_ROLE_PLAY = 178;
  EFFECT_WISH = 179;
  EFFECT_ASSIST = 180;
  EFFECT_INGRAIN = 181;
  EFFECT_SUPERPOWER = 182;
  EFFECT_MAGIC_COAT = 183;
  EFFECT_RECYCLE = 184;
  EFFECT_REVENGE = 185;
  EFFECT_BRICK_BREAK = 186;
  EFFECT_YAWN = 187;
  EFFECT_KNOCK_OFF = 188 [(no_sheer_force) = true];
  EFFECT_ENDEAVOR = 189 [(no_parental_bond) = true];
  EFFECT_ERUPTION = 190;
  EFFECT_SKILL_SWAP = 191;
  EFFECT_IMPRISON = 192;
  EFFECT_REFRESH = 193;
  EFFECT_GRUDGE = 194;
  EFFECT_SNATCH = 195;
  EFFECT_LOW_KICK = 196;
  EFFECT_SECRET_POWER = 197;
  EFFECT_RECOIL_33 = 198;
  EFFECT_TEETER_DANCE = 199;
  EFFECT_HIT_ESCAPE = 200;
  EFFECT_MUD_SPORT = 201;
  EFFECT_POISON_FANG = 202;
  EFFECT_WEATHER_BALL = 203;
  EFFECT_OVERHEAT = 204 [(no_sheer_force) = true];
  EFFECT_TICKLE = 205;
  EFFECT_COSMIC_POWER = 206;
  EFFECT_SKY_UPPERCUT = 207;
  EFFECT_BULK_UP = 208;
  EFFECT_PLACEHOLDER = 209 [(no_sheer_force) = true, (no_kings_rock) = true];
  EFFECT_WATER_SPORT = 210;
  EFFECT_CALM_MIND = 211;
  EFFECT_DRAGON_DANCE = 212;
  EFFECT_CAMOUFLAGE = 213;
  EFFECT_PLEDGE = 214;
  EFFECT_FLING = 215 [(no_sheer_force) = true, (no_kings_rock) = true, (no_parental_bond) = true];
  EFFECT_NATURAL_GIFT = 216 [(no_kings_rock) = true, (no_parental_bond) = true, (no_sheer_force) = true];
  EFFECT_WAKE_UP_SLAP = 217 [(no_sheer_force) = true];
  EFFECT_WRING_OUT = 218;
  EFFECT_HEX = 219;
  EFFECT_ASSURANCE = 220;
  EFFECT_TRUMP_CARD = 221;
  EFFECT_ACROBATICS = 222;
  EFFECT_HEAT_CRASH = 223;
  EFFECT_PUNISHMENT = 224;
  EFFECT_STORED_POWER = 225;
  EFFECT_ELECTRO_BALL = 226;
  EFFECT_GYRO_BALL = 227;
  EFFECT_ECHOED_VOICE = 228;
  EFFECT_PAYBACK = 229;
  EFFECT_ROUND = 230;
  EFFECT_BRINE = 231;
  EFFECT_VENOSHOCK = 232;
  EFFECT_RETALIATE = 233;
  EFFECT_BULLDOZE = 234;
  EFFECT_FOUL_PLAY = 235;
  EFFECT_PSYSHOCK = 236;
  EFFECT_ROOST = 237;
  EFFECT_GRAVITY = 238;
  EFFECT_MIRACLE_EYE = 239;
  EFFECT_TAILWIND = 240;
  EFFECT_EMBARGO = 241;
  EFFECT_AQUA_RING = 242;
  EFFECT_TRICK_ROOM = 243;
  EFFECT_WONDER_ROOM = 244;
  EFFECT_MAGIC_ROOM = 245;
  EFFECT_MAGNET_RISE = 246;
  EFFECT_TOXIC_SPIKES = 247;
  EFFECT_GASTRO_ACID = 248;
  EFFECT_STEALTH_ROCK = 249;
  EFFECT_TELEKINESIS = 250;
  EFFECT_POWER_SWAP = 251;
  EFFECT_GUARD_SWAP = 252;
  EFFECT_HEART_SWAP = 253;
  EFFECT_POWER_SPLIT = 254;
  EFFECT_GUARD_SPLIT = 255;
  EFFECT_STICKY_WEB = 256;
  EFFECT_METAL_BURST = 257 [(no_kings_rock) = true];
  EFFECT_LUCKY_CHANT = 258;
  EFFECT_SUCKER_PUNCH = 259;
  EFFECT_SPECIAL_DEFENSE_DOWN_HIT_2 = 260;
  EFFECT_SIMPLE_BEAM = 261;
  EFFECT_ENTRAINMENT = 262;
  EFFECT_HEAL_PULSE = 263;
  EFFECT_QUASH = 264;
  EFFECT_ION_DELUGE = 265;
  EFFECT_FREEZE_DRY = 266;
  EFFECT_TOPSY_TURVY = 267;
  EFFECT_MISTY_TERRAIN = 268;
  EFFECT_GRASSY_TERRAIN = 269;
  EFFECT_ELECTRIC_TERRAIN = 270;
  EFFECT_PSYCHIC_TERRAIN = 271;
  EFFECT_ATTACK_ACCURACY_UP = 272;
  EFFECT_ATTACK_SPATK_UP = 273;
  EFFECT_HURRICANE = 274;
  EFFECT_TWO_TYPED_MOVE = 275;
  EFFECT_ME_FIRST = 276;
  EFFECT_SPEED_UP_HIT = 277;
  EFFECT_QUIVER_DANCE = 278;
  EFFECT_COIL = 279;
  EFFECT_ELECTRIFY = 280;
  EFFECT_SCALD = 281;
  EFFECT_REFLECT_TYPE = 282;
  EFFECT_SOAK = 283;
  EFFECT_GROWTH = 284;
  EFFECT_CLOSE_COMBAT = 285 [(no_sheer_force) = true];
  EFFECT_LAST_RESORT = 286;
  EFFECT_RECOIL_33_STATUS = 287;
  EFFECT_FLINCH_STATUS = 288 [(flinch_effect) = true];
  EFFECT_RECOIL_50 = 289;
  EFFECT_SHELL_SMASH = 290;
  EFFECT_SHIFT_GEAR = 291;
  EFFECT_DEFENSE_UP_3 = 292;
  EFFECT_NOBLE_ROAR = 293;
  EFFECT_VENOM_DRENCH = 294;
  EFFECT_TOXIC_THREAD = 295;
  EFFECT_CLEAR_SMOG = 296 [(no_sheer_force) = true];
  EFFECT_HIT_SWITCH_TARGET = 297;
  EFFECT_FINAL_GAMBIT = 298 [(no_parental_bond) = true];
  EFFECT_CHANGE_TYPE_ON_ITEM = 299;
  EFFECT_AUTOTOMIZE = 300;
  EFFECT_COPYCAT = 301;
  EFFECT_DEFOG = 302;
  EFFECT_HIT_ENEMY_HEAL_ALLY = 303;
  EFFECT_SMACK_DOWN = 304 [(no_sheer_force) = true];
  EFFECT_SYNCHRONOISE = 305;
  EFFECT_PSYCHO_SHIFT = 306;
  EFFECT_POWER_TRICK = 307;
  EFFECT_FLAME_BURST = 308 [(no_sheer_force) = true];
  EFFECT_AFTER_YOU = 309;
  EFFECT_BESTOW = 310;
  EFFECT_ROTOTILLER = 311;
  EFFECT_FLOWER_SHIELD = 312;
  EFFECT_HIT_PREVENT_ESCAPE = 313 [(no_sheer_force) = true];
  EFFECT_SPEED_SWAP = 314;
  EFFECT_DEFENSE_UP2_HIT = 315;
  EFFECT_REVELATION_DANCE = 316;
  EFFECT_AURORA_VEIL = 317;
  EFFECT_THIRD_TYPE = 318;
  EFFECT_FEINT = 319 [(no_sheer_force) = true];
  EFFECT_SPARKLING_ARIA = 320;
  EFFECT_ACUPRESSURE = 321;
  EFFECT_AROMATIC_MIST = 322;
  EFFECT_POWDER = 323;
  EFFECT_SP_ATTACK_UP_HIT = 324;
  EFFECT_BELCH = 325;
  EFFECT_PARTING_SHOT = 326;
  EFFECT_SPECTRAL_THIEF = 327 [(no_sheer_force) = true];
  EFFECT_V_CREATE = 328 [(no_sheer_force) = true];
  EFFECT_MAT_BLOCK = 329;
  EFFECT_STOMPING_TANTRUM = 330;
  EFFECT_CORE_ENFORCER = 331;
  EFFECT_INSTRUCT = 332;
  EFFECT_THROAT_CHOP = 333;
  EFFECT_LASER_FOCUS = 334;
  EFFECT_MAGNETIC_FLUX = 335;
  EFFECT_GEAR_UP = 336;
  EFFECT_INCINERATE = 337 [(no_sheer_force) = true];
  EFFECT_BUG_BITE = 338 [(no_sheer_force) = true];
  EFFECT_STRENGTH_SAP = 339;
  EFFECT_MIND_BLOWN = 340;
  EFFECT_PURIFY = 341;
  EFFECT_BURN_UP = 342 [(no_sheer_force) = true];
  EFFECT_SHORE_UP = 343;
  EFFECT_GEOMANCY = 344 [(two_turn) = true];
  EFFECT_FAIRY_LOCK = 345;
  EFFECT_ALLY_SWITCH = 346;
  EFFECT_RELIC_SONG = 347;
  EFFECT_ATTACKER_DEFENSE_DOWN_HIT = 348;
  EFFECT_BODY_PRESS = 349;
  EFFECT_EERIE_SPELL = 350;
  EFFECT_JUNGLE_HEALING = 351;
  EFFECT_COACHING = 352;
  EFFECT_LASH_OUT = 353;
  EFFECT_GRASSY_GLIDE = 354;
  EFFECT_REMOVE_TERRAIN = 355;
  EFFECT_DYNAMAX_DOUBLE_DMG = 356;
  EFFECT_DECORATE = 357;
  EFFECT_SNIPE_SHOT = 358;
  EFFECT_TRIPLE_HIT = 359;
  EFFECT_RECOIL_HP_25 = 360;
  EFFECT_STUFF_CHEEKS = 361;
  EFFECT_GRAV_APPLE = 362;
  EFFECT_EVASION_UP_HIT = 363;
  EFFECT_GLITZY_GLOW = 364;
  EFFECT_BADDY_BAD = 365;
  EFFECT_SAPPY_SEED = 366;
  EFFECT_FREEZY_FROST = 367;
  EFFECT_SPARKLY_SWIRL = 368;
  EFFECT_PLASMA_FISTS = 369;
  EFFECT_HYPERSPACE_FURY = 370 [(no_sheer_force) = true];
  EFFECT_AURA_WHEEL = 371;
  EFFECT_PHOTON_GEYSER = 372;
  EFFECT_SHELL_SIDE_ARM = 373;
  EFFECT_TERRAIN_PULSE = 374;
  EFFECT_JAW_LOCK = 375;
  EFFECT_NO_RETREAT = 376;
  EFFECT_TAR_SHOT = 377;
  EFFECT_POLTERGEIST = 378;
  EFFECT_OCTOLOCK = 379;
  EFFECT_CLANGOROUS_SOUL = 380;
  EFFECT_BOLT_BEAK = 381;
  EFFECT_RISING_VOLTAGE = 382;
  EFFECT_SCALE_SHOT = 383;
  EFFECT_BEAK_BLAST = 384;
  EFFECT_EXCALIBUR = 385;
  EFFECT_FROSTBITE_HIT = 386;
  EFFECT_EXPANDING_FORCE = 387;
  EFFECT_STEEL_BEAM = 388;
  EFFECT_HOWL = 389;
  EFFECT_ATTRACT_HIT = 390;
  EFFECT_CURSE_HIT = 391;
  EFFECT_FLINCH_RECOIL_33 = 392 [(flinch_effect) = true];
  EFFECT_FLINCH_RECOIL_50 = 393 [(flinch_effect) = true];
  EFFECT_IGNORE_TYPE_IMMUNITY = 394;
  EFFECT_SE_AGAINST_TYPE_HIT = 395;
  EFFECT_DOUBLE_DMG_IF_STATUS1 = 396;
  EFFECT_STEALTH_ROCK_HIT = 397 [(no_sheer_force) = true];
  EFFECT_LEECH_SEED_HIT = 398;
  EFFECT_STICKY_WEB_HIT = 399 [(no_sheer_force) = true];
  EFFECT_BLEED_HIT = 400;
  EFFECT_SLEEP_HIT = 401;
  EFFECT_BLEED = 402;
  EFFECT_FROSTBITE = 403;
  EFFECT_FREEZE = 404;
  EFFECT_INFERNAL_PARADE = 405;
  EFFECT_WYRM_WIND = 406;
  EFFECT_MISTY_TERRAIN_BOOST = 407;
  EFFECT_BERRY_SMASH = 408;
  EFFECT_INVERSE_ROOM = 409;
  EFFECT_DRAIN_BRAIN = 410;
  EFFECT_TRIPLE_ARROWS = 411 [(flinch_effect) = true];
  EFFECT_RECOIL_25_STATUS = 412;
  EFFECT_WEATHER_BOOST = 413;
  EFFECT_MORTAL_SPIN = 414;
  EFFECT_KARMA = 415;
  EFFECT_REMOVE_TERRAIN_NO_FAIL = 416 [(no_sheer_force) = true];
  EFFECT_TEN_HITS = 417 [(no_sheer_force) = true];
  EFFECT_TWO_TURN_SECONDARY = 418 [(two_turn) = true];
  EFFECT_SPECIAL_ATTACK_UP_HIT = 419;
  EFFECT_ARGUMENT_HIT = 420;
  EFFECT_EVERY_OTHER_TURN = 421;
  EFFECT_MISC_HIT = 422 [(no_sheer_force) = true];
  EFFECT_FILLET_AWAY = 423;
  EFFECT_COURT_CHANGE = 424;
  EFFECT_CHILLY_RECEPTION = 425;
  EFFECT_SHED_TAIL = 426;
  EFFECT_GHASTLY_ECHO = 427;
  EFFECT_REVIVAL_BLESSING = 428;
  EFFECT_TIDY_UP = 429;
  EFFECT_ACID = 430;
  EFFECT_SLUDGE = 431;
  EFFECT_POISON_GAS = 432;
  EFFECT_PARALYZE_IGNORE_TYPE = 433;
  EFFECT_SUPER_FANG_HAZE = 434;
  EFFECT_SPICY_EXTRACT = 435;
  EFFECT_CLEAR_WEATHER_AND_TERRAIN_HIT = 436;
  EFFECT_MATCHA_GOTCHA = 437;
  EFFECT_DOODLE = 438;
  EFFECT_SPIKE_HIT = 439 [(no_sheer_force) = true];
  EFFECT_VICTORY_DANCE = 440;
  EFFECT_DRAGON_CHEER = 441;
  EFFECT_SHELTER = 442;
  EFFECT_ARGUMENT_HIT_IF_STAT_UP = 443;
  EFFECT_UPPER_HAND = 444 [(no_kings_rock) = true];
  EFFECT_ELECTRO_SHOT = 445;
  EFFECT_SHARPEN = 446;
  EFFECT_SCARY_FACE = 447;
  EFFECT_SMOKESCREEN = 448;
  EFFECT_EERIE_FOG = 449;
  EFFECT_MYSTIC_DANCE = 450;
  EFFECT_SNAP_JAW = 451;
  EFFECT_RIP_AND_TEAR = 452;
  EFFECT_SKY_DROP = 453 [(two_turn) = true];
  EFFECT_TERROR_CHARGE = 454;
  EFFECT_TAILWIND_HIT = 455;
  EFFECT_SANDSTORM_HIT = 456;
  EFFECT_RAIN_HIT = 457;
  EFFECT_FAIRY_TERRAIN_HIT = 458;
  EFFECT_CREEPING_THORNS_HIT = 459 [(no_sheer_force) = true];
  EFFECT_TAKE_HEART = 460;
  EFFECT_CLEAR_SKIES = 461;
  EFFECT_SHOWTIME = 462;
  EFFECT_TREPIDATION = 463 [(no_sheer_force) = true];
  EFFECT_CHIP_AWAY = 464;
  EFFECT_MEDITATE = 465;
  EFFECT_BARRIER = 466;
  EFFECT_KINESIS = 467;
  EFFECT_CORROSIVE_GAS = 468 [(no_sheer_force) = true];
  EFFECT_CALTROPS = 469;
  EFFECT_SWEET_KISS = 470;
  EFFECT_QUICK_GUARD = 471;
  EFFECT_TWO_TURN_RETALIATION = 472 [(two_turn) = true];
  EFFECT_SHELL_TRAP = 473;
  EFFECT_GRASSY_TERRAIN_HIT = 474;
  EFFECT_TOXIC_TERRAIN = 475;
  EFFECT_SEPTIC_SWITCH = 476;
  EFFECT_WHIRLPOOL = 477;
  EFFECT_PARTY_FAVORS = 478;
  EFFECT_PRISM_BLAST = 479;
  EFFECT_WATERLOG = 480;
}