syntax = "proto3";

package er;

option java_package = "er.proto";
option java_multiple_files = true;

enum SpeciesEnum {
  SPECIES_NONE = 0;
  SPECIES_BULBASAUR = 1;
  SPECIES_IVYSAUR = 2;
  SPECIES_VENUSAUR = 3;
  SPECIES_CHARMANDER = 4;
  SPECIES_CHARMELEON = 5;
  SPECIES_CHARIZARD = 6;
  SPECIES_SQUIRTLE = 7;
  SPECIES_WARTORTLE = 8;
  SPECIES_BLASTOISE = 9;
  SPECIES_CATERPIE = 10;
  SPECIES_METAPOD = 11;
  SPECIES_BUTTERFREE = 12;
  SPECIES_WEEDLE = 13;
  SPECIES_KAKUNA = 14;
  SPECIES_BEEDRILL = 15;
  SPECIES_PIDGEY = 16;
  SPECIES_PIDGEOTTO = 17;
  SPECIES_PIDGEOT = 18;
  SPECIES_RATTATA = 19;
  SPECIES_RATICATE = 20;
  SPECIES_SPEAROW = 21;
  SPECIES_FEAROW = 22;
  SPECIES_EKANS = 23;
  SPECIES_ARBOK = 24;
  SPECIES_PIKACHU = 25;
  SPECIES_RAICHU = 26;
  SPECIES_SANDSHREW = 27;
  SPECIES_SANDSLASH = 28;
  SPECIES_NIDORAN_F = 29;
  SPECIES_NIDORINA = 30;
  SPECIES_NIDOQUEEN = 31;
  SPECIES_NIDORAN_M = 32;
  SPECIES_NIDORINO = 33;
  SPECIES_NIDOKING = 34;
  SPECIES_CLEFAIRY = 35;
  SPECIES_CLEFABLE = 36;
  SPECIES_VULPIX = 37;
  SPECIES_NINETALES = 38;
  SPECIES_JIGGLYPUFF = 39;
  SPECIES_WIGGLYTUFF = 40;
  SPECIES_ZUBAT = 41;
  SPECIES_GOLBAT = 42;
  SPECIES_ODDISH = 43;
  SPECIES_GLOOM = 44;
  SPECIES_VILEPLUME = 45;
  SPECIES_PARAS = 46;
  SPECIES_PARASECT = 47;
  SPECIES_VENONAT = 48;
  SPECIES_VENOMOTH = 49;
  SPECIES_DIGLETT = 50;
  SPECIES_DUGTRIO = 51;
  SPECIES_MEOWTH = 52;
  SPECIES_PERSIAN = 53;
  SPECIES_PSYDUCK = 54;
  SPECIES_GOLDUCK = 55;
  SPECIES_MANKEY = 56;
  SPECIES_PRIMEAPE = 57;
  SPECIES_GROWLITHE = 58;
  SPECIES_ARCANINE = 59;
  SPECIES_POLIWAG = 60;
  SPECIES_POLIWHIRL = 61;
  SPECIES_POLIWRATH = 62;
  SPECIES_ABRA = 63;
  SPECIES_KADABRA = 64;
  SPECIES_ALAKAZAM = 65;
  SPECIES_MACHOP = 66;
  SPECIES_MACHOKE = 67;
  SPECIES_MACHAMP = 68;
  SPECIES_BELLSPROUT = 69;
  SPECIES_WEEPINBELL = 70;
  SPECIES_VICTREEBEL = 71;
  SPECIES_TENTACOOL = 72;
  SPECIES_TENTACRUEL = 73;
  SPECIES_GEODUDE = 74;
  SPECIES_GRAVELER = 75;
  SPECIES_GOLEM = 76;
  SPECIES_PONYTA = 77;
  SPECIES_RAPIDASH = 78;
  SPECIES_SLOWPOKE = 79;
  SPECIES_SLOWBRO = 80;
  SPECIES_MAGNEMITE = 81;
  SPECIES_MAGNETON = 82;
  SPECIES_FARFETCHD = 83;
  SPECIES_DODUO = 84;
  SPECIES_DODRIO = 85;
  SPECIES_SEEL = 86;
  SPECIES_DEWGONG = 87;
  SPECIES_GRIMER = 88;
  SPECIES_MUK = 89;
  SPECIES_SHELLDER = 90;
  SPECIES_CLOYSTER = 91;
  SPECIES_GASTLY = 92;
  SPECIES_HAUNTER = 93;
  SPECIES_GENGAR = 94;
  SPECIES_ONIX = 95;
  SPECIES_DROWZEE = 96;
  SPECIES_HYPNO = 97;
  SPECIES_KRABBY = 98;
  SPECIES_KINGLER = 99;
  SPECIES_VOLTORB = 100;
  SPECIES_ELECTRODE = 101;
  SPECIES_EXEGGCUTE = 102;
  SPECIES_EXEGGUTOR = 103;
  SPECIES_CUBONE = 104;
  SPECIES_MAROWAK = 105;
  SPECIES_HITMONLEE = 106;
  SPECIES_HITMONCHAN = 107;
  SPECIES_LICKITUNG = 108;
  SPECIES_KOFFING = 109;
  SPECIES_WEEZING = 110;
  SPECIES_RHYHORN = 111;
  SPECIES_RHYDON = 112;
  SPECIES_CHANSEY = 113;
  SPECIES_TANGELA = 114;
  SPECIES_KANGASKHAN = 115;
  SPECIES_HORSEA = 116;
  SPECIES_SEADRA = 117;
  SPECIES_GOLDEEN = 118;
  SPECIES_SEAKING = 119;
  SPECIES_STARYU = 120;
  SPECIES_STARMIE = 121;
  SPECIES_MR_MIME = 122;
  SPECIES_SCYTHER = 123;
  SPECIES_JYNX = 124;
  SPECIES_ELECTABUZZ = 125;
  SPECIES_MAGMAR = 126;
  SPECIES_PINSIR = 127;
  SPECIES_TAUROS = 128;
  SPECIES_MAGIKARP = 129;
  SPECIES_GYARADOS = 130;
  SPECIES_LAPRAS = 131;
  SPECIES_DITTO = 132;
  SPECIES_EEVEE = 133;
  SPECIES_VAPOREON = 134;
  SPECIES_JOLTEON = 135;
  SPECIES_FLAREON = 136;
  SPECIES_PORYGON = 137;
  SPECIES_OMANYTE = 138;
  SPECIES_OMASTAR = 139;
  SPECIES_KABUTO = 140;
  SPECIES_KABUTOPS = 141;
  SPECIES_AERODACTYL = 142;
  SPECIES_SNORLAX = 143;
  SPECIES_ARTICUNO = 144;
  SPECIES_ZAPDOS = 145;
  SPECIES_MOLTRES = 146;
  SPECIES_DRATINI = 147;
  SPECIES_DRAGONAIR = 148;
  SPECIES_DRAGONITE = 149;
  SPECIES_MEWTWO = 150;
  SPECIES_MEW = 151;
  SPECIES_CHIKORITA = 152;
  SPECIES_BAYLEEF = 153;
  SPECIES_MEGANIUM = 154;
  SPECIES_CYNDAQUIL = 155;
  SPECIES_QUILAVA = 156;
  SPECIES_TYPHLOSION = 157;
  SPECIES_TOTODILE = 158;
  SPECIES_CROCONAW = 159;
  SPECIES_FERALIGATR = 160;
  SPECIES_SENTRET = 161;
  SPECIES_FURRET = 162;
  SPECIES_HOOTHOOT = 163;
  SPECIES_NOCTOWL = 164;
  SPECIES_LEDYBA = 165;
  SPECIES_LEDIAN = 166;
  SPECIES_SPINARAK = 167;
  SPECIES_ARIADOS = 168;
  SPECIES_CROBAT = 169;
  SPECIES_CHINCHOU = 170;
  SPECIES_LANTURN = 171;
  SPECIES_PICHU = 172;
  SPECIES_CLEFFA = 173;
  SPECIES_IGGLYBUFF = 174;
  SPECIES_TOGEPI = 175;
  SPECIES_TOGETIC = 176;
  SPECIES_NATU = 177;
  SPECIES_XATU = 178;
  SPECIES_MAREEP = 179;
  SPECIES_FLAAFFY = 180;
  SPECIES_AMPHAROS = 181;
  SPECIES_BELLOSSOM = 182;
  SPECIES_MARILL = 183;
  SPECIES_AZUMARILL = 184;
  SPECIES_SUDOWOODO = 185;
  SPECIES_POLITOED = 186;
  SPECIES_HOPPIP = 187;
  SPECIES_SKIPLOOM = 188;
  SPECIES_JUMPLUFF = 189;
  SPECIES_AIPOM = 190;
  SPECIES_SUNKERN = 191;
  SPECIES_SUNFLORA = 192;
  SPECIES_YANMA = 193;
  SPECIES_WOOPER = 194;
  SPECIES_QUAGSIRE = 195;
  SPECIES_ESPEON = 196;
  SPECIES_UMBREON = 197;
  SPECIES_MURKROW = 198;
  SPECIES_SLOWKING = 199;
  SPECIES_MISDREAVUS = 200;
  SPECIES_UNOWN = 201;
  SPECIES_WOBBUFFET = 202;
  SPECIES_GIRAFARIG = 203;
  SPECIES_PINECO = 204;
  SPECIES_FORRETRESS = 205;
  SPECIES_DUNSPARCE = 206;
  SPECIES_GLIGAR = 207;
  SPECIES_STEELIX = 208;
  SPECIES_SNUBBULL = 209;
  SPECIES_GRANBULL = 210;
  SPECIES_QWILFISH = 211;
  SPECIES_SCIZOR = 212;
  SPECIES_SHUCKLE = 213;
  SPECIES_HERACROSS = 214;
  SPECIES_SNEASEL = 215;
  SPECIES_TEDDIURSA = 216;
  SPECIES_URSARING = 217;
  SPECIES_SLUGMA = 218;
  SPECIES_MAGCARGO = 219;
  SPECIES_SWINUB = 220;
  SPECIES_PILOSWINE = 221;
  SPECIES_CORSOLA = 222;
  SPECIES_REMORAID = 223;
  SPECIES_OCTILLERY = 224;
  SPECIES_DELIBIRD = 225;
  SPECIES_MANTINE = 226;
  SPECIES_SKARMORY = 227;
  SPECIES_HOUNDOUR = 228;
  SPECIES_HOUNDOOM = 229;
  SPECIES_KINGDRA = 230;
  SPECIES_PHANPY = 231;
  SPECIES_DONPHAN = 232;
  SPECIES_PORYGON2 = 233;
  SPECIES_STANTLER = 234;
  SPECIES_SMEARGLE = 235;
  SPECIES_TYROGUE = 236;
  SPECIES_HITMONTOP = 237;
  SPECIES_SMOOCHUM = 238;
  SPECIES_ELEKID = 239;
  SPECIES_MAGBY = 240;
  SPECIES_MILTANK = 241;
  SPECIES_BLISSEY = 242;
  SPECIES_RAIKOU = 243;
  SPECIES_ENTEI = 244;
  SPECIES_SUICUNE = 245;
  SPECIES_LARVITAR = 246;
  SPECIES_PUPITAR = 247;
  SPECIES_TYRANITAR = 248;
  SPECIES_LUGIA = 249;
  SPECIES_HO_OH = 250;
  SPECIES_CELEBI = 251;
  SPECIES_TREECKO = 252;
  SPECIES_GROVYLE = 253;
  SPECIES_SCEPTILE = 254;
  SPECIES_TORCHIC = 255;
  SPECIES_COMBUSKEN = 256;
  SPECIES_BLAZIKEN = 257;
  SPECIES_MUDKIP = 258;
  SPECIES_MARSHTOMP = 259;
  SPECIES_SWAMPERT = 260;
  SPECIES_POOCHYENA = 261;
  SPECIES_MIGHTYENA = 262;
  SPECIES_ZIGZAGOON = 263;
  SPECIES_LINOONE = 264;
  SPECIES_WURMPLE = 265;
  SPECIES_SILCOON = 266;
  SPECIES_BEAUTIFLY = 267;
  SPECIES_CASCOON = 268;
  SPECIES_DUSTOX = 269;
  SPECIES_LOTAD = 270;
  SPECIES_LOMBRE = 271;
  SPECIES_LUDICOLO = 272;
  SPECIES_SEEDOT = 273;
  SPECIES_NUZLEAF = 274;
  SPECIES_SHIFTRY = 275;
  SPECIES_TAILLOW = 276;
  SPECIES_SWELLOW = 277;
  SPECIES_WINGULL = 278;
  SPECIES_PELIPPER = 279;
  SPECIES_RALTS = 280;
  SPECIES_KIRLIA = 281;
  SPECIES_GARDEVOIR = 282;
  SPECIES_SURSKIT = 283;
  SPECIES_MASQUERAIN = 284;
  SPECIES_SHROOMISH = 285;
  SPECIES_BRELOOM = 286;
  SPECIES_SLAKOTH = 287;
  SPECIES_VIGOROTH = 288;
  SPECIES_SLAKING = 289;
  SPECIES_NINCADA = 290;
  SPECIES_NINJASK = 291;
  SPECIES_SHEDINJA = 292;
  SPECIES_WHISMUR = 293;
  SPECIES_LOUDRED = 294;
  SPECIES_EXPLOUD = 295;
  SPECIES_MAKUHITA = 296;
  SPECIES_HARIYAMA = 297;
  SPECIES_AZURILL = 298;
  SPECIES_NOSEPASS = 299;
  SPECIES_SKITTY = 300;
  SPECIES_DELCATTY = 301;
  SPECIES_SABLEYE = 302;
  SPECIES_MAWILE = 303;
  SPECIES_ARON = 304;
  SPECIES_LAIRON = 305;
  SPECIES_AGGRON = 306;
  SPECIES_MEDITITE = 307;
  SPECIES_MEDICHAM = 308;
  SPECIES_ELECTRIKE = 309;
  SPECIES_MANECTRIC = 310;
  SPECIES_PLUSLE = 311;
  SPECIES_MINUN = 312;
  SPECIES_VOLBEAT = 313;
  SPECIES_ILLUMISE = 314;
  SPECIES_ROSELIA = 315;
  SPECIES_GULPIN = 316;
  SPECIES_SWALOT = 317;
  SPECIES_CARVANHA = 318;
  SPECIES_SHARPEDO = 319;
  SPECIES_WAILMER = 320;
  SPECIES_WAILORD = 321;
  SPECIES_NUMEL = 322;
  SPECIES_CAMERUPT = 323;
  SPECIES_TORKOAL = 324;
  SPECIES_SPOINK = 325;
  SPECIES_GRUMPIG = 326;
  SPECIES_SPINDA = 327;
  SPECIES_TRAPINCH = 328;
  SPECIES_VIBRAVA = 329;
  SPECIES_FLYGON = 330;
  SPECIES_CACNEA = 331;
  SPECIES_CACTURNE = 332;
  SPECIES_SWABLU = 333;
  SPECIES_ALTARIA = 334;
  SPECIES_ZANGOOSE = 335;
  SPECIES_SEVIPER = 336;
  SPECIES_LUNATONE = 337;
  SPECIES_SOLROCK = 338;
  SPECIES_BARBOACH = 339;
  SPECIES_WHISCASH = 340;
  SPECIES_CORPHISH = 341;
  SPECIES_CRAWDAUNT = 342;
  SPECIES_BALTOY = 343;
  SPECIES_CLAYDOL = 344;
  SPECIES_LILEEP = 345;
  SPECIES_CRADILY = 346;
  SPECIES_ANORITH = 347;
  SPECIES_ARMALDO = 348;
  SPECIES_FEEBAS = 349;
  SPECIES_MILOTIC = 350;
  SPECIES_CASTFORM = 351;
  SPECIES_KECLEON = 352;
  SPECIES_SHUPPET = 353;
  SPECIES_BANETTE = 354;
  SPECIES_DUSKULL = 355;
  SPECIES_DUSCLOPS = 356;
  SPECIES_TROPIUS = 357;
  SPECIES_CHIMECHO = 358;
  SPECIES_ABSOL = 359;
  SPECIES_WYNAUT = 360;
  SPECIES_SNORUNT = 361;
  SPECIES_GLALIE = 362;
  SPECIES_SPHEAL = 363;
  SPECIES_SEALEO = 364;
  SPECIES_WALREIN = 365;
  SPECIES_CLAMPERL = 366;
  SPECIES_HUNTAIL = 367;
  SPECIES_GOREBYSS = 368;
  SPECIES_RELICANTH = 369;
  SPECIES_LUVDISC = 370;
  SPECIES_BAGON = 371;
  SPECIES_SHELGON = 372;
  SPECIES_SALAMENCE = 373;
  SPECIES_BELDUM = 374;
  SPECIES_METANG = 375;
  SPECIES_METAGROSS = 376;
  SPECIES_REGIROCK = 377;
  SPECIES_REGICE = 378;
  SPECIES_REGISTEEL = 379;
  SPECIES_LATIAS = 380;
  SPECIES_LATIOS = 381;
  SPECIES_KYOGRE = 382;
  SPECIES_GROUDON = 383;
  SPECIES_RAYQUAZA = 384;
  SPECIES_JIRACHI = 385;
  SPECIES_DEOXYS = 386;
  SPECIES_TURTWIG = 387;
  SPECIES_GROTLE = 388;
  SPECIES_TORTERRA = 389;
  SPECIES_CHIMCHAR = 390;
  SPECIES_MONFERNO = 391;
  SPECIES_INFERNAPE = 392;
  SPECIES_PIPLUP = 393;
  SPECIES_PRINPLUP = 394;
  SPECIES_EMPOLEON = 395;
  SPECIES_STARLY = 396;
  SPECIES_STARAVIA = 397;
  SPECIES_STARAPTOR = 398;
  SPECIES_BIDOOF = 399;
  SPECIES_BIBAREL = 400;
  SPECIES_KRICKETOT = 401;
  SPECIES_KRICKETUNE = 402;
  SPECIES_SHINX = 403;
  SPECIES_LUXIO = 404;
  SPECIES_LUXRAY = 405;
  SPECIES_BUDEW = 406;
  SPECIES_ROSERADE = 407;
  SPECIES_CRANIDOS = 408;
  SPECIES_RAMPARDOS = 409;
  SPECIES_SHIELDON = 410;
  SPECIES_BASTIODON = 411;
  SPECIES_BURMY = 412;
  SPECIES_WORMADAM = 413;
  SPECIES_MOTHIM = 414;
  SPECIES_COMBEE = 415;
  SPECIES_VESPIQUEN = 416;
  SPECIES_PACHIRISU = 417;
  SPECIES_BUIZEL = 418;
  SPECIES_FLOATZEL = 419;
  SPECIES_CHERUBI = 420;
  SPECIES_CHERRIM = 421;
  SPECIES_SHELLOS = 422;
  SPECIES_GASTRODON = 423;
  SPECIES_AMBIPOM = 424;
  SPECIES_DRIFLOON = 425;
  SPECIES_DRIFBLIM = 426;
  SPECIES_BUNEARY = 427;
  SPECIES_LOPUNNY = 428;
  SPECIES_MISMAGIUS = 429;
  SPECIES_HONCHKROW = 430;
  SPECIES_GLAMEOW = 431;
  SPECIES_PURUGLY = 432;
  SPECIES_CHINGLING = 433;
  SPECIES_STUNKY = 434;
  SPECIES_SKUNTANK = 435;
  SPECIES_BRONZOR = 436;
  SPECIES_BRONZONG = 437;
  SPECIES_BONSLY = 438;
  SPECIES_MIME_JR = 439;
  SPECIES_HAPPINY = 440;
  SPECIES_CHATOT = 441;
  SPECIES_SPIRITOMB = 442;
  SPECIES_GIBLE = 443;
  SPECIES_GABITE = 444;
  SPECIES_GARCHOMP = 445;
  SPECIES_MUNCHLAX = 446;
  SPECIES_RIOLU = 447;
  SPECIES_LUCARIO = 448;
  SPECIES_HIPPOPOTAS = 449;
  SPECIES_HIPPOWDON = 450;
  SPECIES_SKORUPI = 451;
  SPECIES_DRAPION = 452;
  SPECIES_CROAGUNK = 453;
  SPECIES_TOXICROAK = 454;
  SPECIES_CARNIVINE = 455;
  SPECIES_FINNEON = 456;
  SPECIES_LUMINEON = 457;
  SPECIES_MANTYKE = 458;
  SPECIES_SNOVER = 459;
  SPECIES_ABOMASNOW = 460;
  SPECIES_WEAVILE = 461;
  SPECIES_MAGNEZONE = 462;
  SPECIES_LICKILICKY = 463;
  SPECIES_RHYPERIOR = 464;
  SPECIES_TANGROWTH = 465;
  SPECIES_ELECTIVIRE = 466;
  SPECIES_MAGMORTAR = 467;
  SPECIES_TOGEKISS = 468;
  SPECIES_YANMEGA = 469;
  SPECIES_LEAFEON = 470;
  SPECIES_GLACEON = 471;
  SPECIES_GLISCOR = 472;
  SPECIES_MAMOSWINE = 473;
  SPECIES_PORYGON_Z = 474;
  SPECIES_GALLADE = 475;
  SPECIES_PROBOPASS = 476;
  SPECIES_DUSKNOIR = 477;
  SPECIES_FROSLASS = 478;
  SPECIES_ROTOM = 479;
  SPECIES_UXIE = 480;
  SPECIES_MESPRIT = 481;
  SPECIES_AZELF = 482;
  SPECIES_DIALGA = 483;
  SPECIES_PALKIA = 484;
  SPECIES_HEATRAN = 485;
  SPECIES_REGIGIGAS = 486;
  SPECIES_GIRATINA = 487;
  SPECIES_CRESSELIA = 488;
  SPECIES_PHIONE = 489;
  SPECIES_MANAPHY = 490;
  SPECIES_DARKRAI = 491;
  SPECIES_SHAYMIN = 492;
  SPECIES_ARCEUS = 493;
  SPECIES_VICTINI = 494;
  SPECIES_SNIVY = 495;
  SPECIES_SERVINE = 496;
  SPECIES_SERPERIOR = 497;
  SPECIES_TEPIG = 498;
  SPECIES_PIGNITE = 499;
  SPECIES_EMBOAR = 500;
  SPECIES_OSHAWOTT = 501;
  SPECIES_DEWOTT = 502;
  SPECIES_SAMUROTT = 503;
  SPECIES_PATRAT = 504;
  SPECIES_WATCHOG = 505;
  SPECIES_LILLIPUP = 506;
  SPECIES_HERDIER = 507;
  SPECIES_STOUTLAND = 508;
  SPECIES_PURRLOIN = 509;
  SPECIES_LIEPARD = 510;
  SPECIES_PANSAGE = 511;
  SPECIES_SIMISAGE = 512;
  SPECIES_PANSEAR = 513;
  SPECIES_SIMISEAR = 514;
  SPECIES_PANPOUR = 515;
  SPECIES_SIMIPOUR = 516;
  SPECIES_MUNNA = 517;
  SPECIES_MUSHARNA = 518;
  SPECIES_PIDOVE = 519;
  SPECIES_TRANQUILL = 520;
  SPECIES_UNFEZANT = 521;
  SPECIES_BLITZLE = 522;
  SPECIES_ZEBSTRIKA = 523;
  SPECIES_ROGGENROLA = 524;
  SPECIES_BOLDORE = 525;
  SPECIES_GIGALITH = 526;
  SPECIES_WOOBAT = 527;
  SPECIES_SWOOBAT = 528;
  SPECIES_DRILBUR = 529;
  SPECIES_EXCADRILL = 530;
  SPECIES_AUDINO = 531;
  SPECIES_TIMBURR = 532;
  SPECIES_GURDURR = 533;
  SPECIES_CONKELDURR = 534;
  SPECIES_TYMPOLE = 535;
  SPECIES_PALPITOAD = 536;
  SPECIES_SEISMITOAD = 537;
  SPECIES_THROH = 538;
  SPECIES_SAWK = 539;
  SPECIES_SEWADDLE = 540;
  SPECIES_SWADLOON = 541;
  SPECIES_LEAVANNY = 542;
  SPECIES_VENIPEDE = 543;
  SPECIES_WHIRLIPEDE = 544;
  SPECIES_SCOLIPEDE = 545;
  SPECIES_COTTONEE = 546;
  SPECIES_WHIMSICOTT = 547;
  SPECIES_PETILIL = 548;
  SPECIES_LILLIGANT = 549;
  SPECIES_BASCULIN = 550;
  SPECIES_SANDILE = 551;
  SPECIES_KROKOROK = 552;
  SPECIES_KROOKODILE = 553;
  SPECIES_DARUMAKA = 554;
  SPECIES_DARMANITAN = 555;
  SPECIES_MARACTUS = 556;
  SPECIES_DWEBBLE = 557;
  SPECIES_CRUSTLE = 558;
  SPECIES_SCRAGGY = 559;
  SPECIES_SCRAFTY = 560;
  SPECIES_SIGILYPH = 561;
  SPECIES_YAMASK = 562;
  SPECIES_COFAGRIGUS = 563;
  SPECIES_TIRTOUGA = 564;
  SPECIES_CARRACOSTA = 565;
  SPECIES_ARCHEN = 566;
  SPECIES_ARCHEOPS = 567;
  SPECIES_TRUBBISH = 568;
  SPECIES_GARBODOR = 569;
  SPECIES_ZORUA = 570;
  SPECIES_ZOROARK = 571;
  SPECIES_MINCCINO = 572;
  SPECIES_CINCCINO = 573;
  SPECIES_GOTHITA = 574;
  SPECIES_GOTHORITA = 575;
  SPECIES_GOTHITELLE = 576;
  SPECIES_SOLOSIS = 577;
  SPECIES_DUOSION = 578;
  SPECIES_REUNICLUS = 579;
  SPECIES_DUCKLETT = 580;
  SPECIES_SWANNA = 581;
  SPECIES_VANILLITE = 582;
  SPECIES_VANILLISH = 583;
  SPECIES_VANILLUXE = 584;
  SPECIES_DEERLING = 585;
  SPECIES_SAWSBUCK = 586;
  SPECIES_EMOLGA = 587;
  SPECIES_KARRABLAST = 588;
  SPECIES_ESCAVALIER = 589;
  SPECIES_FOONGUS = 590;
  SPECIES_AMOONGUSS = 591;
  SPECIES_FRILLISH = 592;
  SPECIES_JELLICENT = 593;
  SPECIES_ALOMOMOLA = 594;
  SPECIES_JOLTIK = 595;
  SPECIES_GALVANTULA = 596;
  SPECIES_FERROSEED = 597;
  SPECIES_FERROTHORN = 598;
  SPECIES_KLINK = 599;
  SPECIES_KLANG = 600;
  SPECIES_KLINKLANG = 601;
  SPECIES_TYNAMO = 602;
  SPECIES_EELEKTRIK = 603;
  SPECIES_EELEKTROSS = 604;
  SPECIES_ELGYEM = 605;
  SPECIES_BEHEEYEM = 606;
  SPECIES_LITWICK = 607;
  SPECIES_LAMPENT = 608;
  SPECIES_CHANDELURE = 609;
  SPECIES_AXEW = 610;
  SPECIES_FRAXURE = 611;
  SPECIES_HAXORUS = 612;
  SPECIES_CUBCHOO = 613;
  SPECIES_BEARTIC = 614;
  SPECIES_CRYOGONAL = 615;
  SPECIES_SHELMET = 616;
  SPECIES_ACCELGOR = 617;
  SPECIES_STUNFISK = 618;
  SPECIES_MIENFOO = 619;
  SPECIES_MIENSHAO = 620;
  SPECIES_DRUDDIGON = 621;
  SPECIES_GOLETT = 622;
  SPECIES_GOLURK = 623;
  SPECIES_PAWNIARD = 624;
  SPECIES_BISHARP = 625;
  SPECIES_BOUFFALANT = 626;
  SPECIES_RUFFLET = 627;
  SPECIES_BRAVIARY = 628;
  SPECIES_VULLABY = 629;
  SPECIES_MANDIBUZZ = 630;
  SPECIES_HEATMOR = 631;
  SPECIES_DURANT = 632;
  SPECIES_DEINO = 633;
  SPECIES_ZWEILOUS = 634;
  SPECIES_HYDREIGON = 635;
  SPECIES_LARVESTA = 636;
  SPECIES_VOLCARONA = 637;
  SPECIES_COBALION = 638;
  SPECIES_TERRAKION = 639;
  SPECIES_VIRIZION = 640;
  SPECIES_TORNADUS = 641;
  SPECIES_THUNDURUS = 642;
  SPECIES_RESHIRAM = 643;
  SPECIES_ZEKROM = 644;
  SPECIES_LANDORUS = 645;
  SPECIES_KYUREM = 646;
  SPECIES_KELDEO = 647;
  SPECIES_MELOETTA = 648;
  SPECIES_GENESECT = 649;
  SPECIES_CHESPIN = 650;
  SPECIES_QUILLADIN = 651;
  SPECIES_CHESNAUGHT = 652;
  SPECIES_FENNEKIN = 653;
  SPECIES_BRAIXEN = 654;
  SPECIES_DELPHOX = 655;
  SPECIES_FROAKIE = 656;
  SPECIES_FROGADIER = 657;
  SPECIES_GRENINJA = 658;
  SPECIES_BUNNELBY = 659;
  SPECIES_DIGGERSBY = 660;
  SPECIES_FLETCHLING = 661;
  SPECIES_FLETCHINDER = 662;
  SPECIES_TALONFLAME = 663;
  SPECIES_SCATTERBUG = 664;
  SPECIES_SPEWPA = 665;
  SPECIES_VIVILLON = 666;
  SPECIES_LITLEO = 667;
  SPECIES_PYROAR = 668;
  SPECIES_FLABEBE = 669;
  SPECIES_FLOETTE = 670;
  SPECIES_FLORGES = 671;
  SPECIES_SKIDDO = 672;
  SPECIES_GOGOAT = 673;
  SPECIES_PANCHAM = 674;
  SPECIES_PANGORO = 675;
  SPECIES_FURFROU = 676;
  SPECIES_ESPURR = 677;
  SPECIES_MEOWSTIC = 678;
  SPECIES_HONEDGE = 679;
  SPECIES_DOUBLADE = 680;
  SPECIES_AEGISLASH = 681;
  SPECIES_SPRITZEE = 682;
  SPECIES_AROMATISSE = 683;
  SPECIES_SWIRLIX = 684;
  SPECIES_SLURPUFF = 685;
  SPECIES_INKAY = 686;
  SPECIES_MALAMAR = 687;
  SPECIES_BINACLE = 688;
  SPECIES_BARBARACLE = 689;
  SPECIES_SKRELP = 690;
  SPECIES_DRAGALGE = 691;
  SPECIES_CLAUNCHER = 692;
  SPECIES_CLAWITZER = 693;
  SPECIES_HELIOPTILE = 694;
  SPECIES_HELIOLISK = 695;
  SPECIES_TYRUNT = 696;
  SPECIES_TYRANTRUM = 697;
  SPECIES_AMAURA = 698;
  SPECIES_AURORUS = 699;
  SPECIES_SYLVEON = 700;
  SPECIES_HAWLUCHA = 701;
  SPECIES_DEDENNE = 702;
  SPECIES_CARBINK = 703;
  SPECIES_GOOMY = 704;
  SPECIES_SLIGGOO = 705;
  SPECIES_GOODRA = 706;
  SPECIES_KLEFKI = 707;
  SPECIES_PHANTUMP = 708;
  SPECIES_TREVENANT = 709;
  SPECIES_PUMPKABOO = 710;
  SPECIES_GOURGEIST = 711;
  SPECIES_BERGMITE = 712;
  SPECIES_AVALUGG = 713;
  SPECIES_NOIBAT = 714;
  SPECIES_NOIVERN = 715;
  SPECIES_XERNEAS = 716;
  SPECIES_YVELTAL = 717;
  SPECIES_ZYGARDE = 718;
  SPECIES_DIANCIE = 719;
  SPECIES_HOOPA = 720;
  SPECIES_VOLCANION = 721;
  SPECIES_ROWLET = 722;
  SPECIES_DARTRIX = 723;
  SPECIES_DECIDUEYE = 724;
  SPECIES_LITTEN = 725;
  SPECIES_TORRACAT = 726;
  SPECIES_INCINEROAR = 727;
  SPECIES_POPPLIO = 728;
  SPECIES_BRIONNE = 729;
  SPECIES_PRIMARINA = 730;
  SPECIES_PIKIPEK = 731;
  SPECIES_TRUMBEAK = 732;
  SPECIES_TOUCANNON = 733;
  SPECIES_YUNGOOS = 734;
  SPECIES_GUMSHOOS = 735;
  SPECIES_GRUBBIN = 736;
  SPECIES_CHARJABUG = 737;
  SPECIES_VIKAVOLT = 738;
  SPECIES_CRABRAWLER = 739;
  SPECIES_CRABOMINABLE = 740;
  SPECIES_ORICORIO = 741;
  SPECIES_CUTIEFLY = 742;
  SPECIES_RIBOMBEE = 743;
  SPECIES_ROCKRUFF = 744;
  SPECIES_LYCANROC = 745;
  SPECIES_WISHIWASHI = 746;
  SPECIES_MAREANIE = 747;
  SPECIES_TOXAPEX = 748;
  SPECIES_MUDBRAY = 749;
  SPECIES_MUDSDALE = 750;
  SPECIES_DEWPIDER = 751;
  SPECIES_ARAQUANID = 752;
  SPECIES_FOMANTIS = 753;
  SPECIES_LURANTIS = 754;
  SPECIES_MORELULL = 755;
  SPECIES_SHIINOTIC = 756;
  SPECIES_SALANDIT = 757;
  SPECIES_SALAZZLE = 758;
  SPECIES_STUFFUL = 759;
  SPECIES_BEWEAR = 760;
  SPECIES_BOUNSWEET = 761;
  SPECIES_STEENEE = 762;
  SPECIES_TSAREENA = 763;
  SPECIES_COMFEY = 764;
  SPECIES_ORANGURU = 765;
  SPECIES_PASSIMIAN = 766;
  SPECIES_WIMPOD = 767;
  SPECIES_GOLISOPOD = 768;
  SPECIES_SANDYGAST = 769;
  SPECIES_PALOSSAND = 770;
  SPECIES_PYUKUMUKU = 771;
  SPECIES_TYPE_NULL = 772;
  SPECIES_SILVALLY = 773;
  SPECIES_MINIOR = 774;
  SPECIES_KOMALA = 775;
  SPECIES_TURTONATOR = 776;
  SPECIES_TOGEDEMARU = 777;
  SPECIES_MIMIKYU = 778;
  SPECIES_BRUXISH = 779;
  SPECIES_DRAMPA = 780;
  SPECIES_DHELMISE = 781;
  SPECIES_JANGMO_O = 782;
  SPECIES_HAKAMO_O = 783;
  SPECIES_KOMMO_O = 784;
  SPECIES_TAPU_KOKO = 785;
  SPECIES_TAPU_LELE = 786;
  SPECIES_TAPU_BULU = 787;
  SPECIES_TAPU_FINI = 788;
  SPECIES_COSMOG = 789;
  SPECIES_COSMOEM = 790;
  SPECIES_SOLGALEO = 791;
  SPECIES_LUNALA = 792;
  SPECIES_NIHILEGO = 793;
  SPECIES_BUZZWOLE = 794;
  SPECIES_PHEROMOSA = 795;
  SPECIES_XURKITREE = 796;
  SPECIES_CELESTEELA = 797;
  SPECIES_KARTANA = 798;
  SPECIES_GUZZLORD = 799;
  SPECIES_NECROZMA = 800;
  SPECIES_MAGEARNA = 801;
  SPECIES_MARSHADOW = 802;
  SPECIES_POIPOLE = 803;
  SPECIES_NAGANADEL = 804;
  SPECIES_STAKATAKA = 805;
  SPECIES_BLACEPHALON = 806;
  SPECIES_ZERAORA = 807;
  SPECIES_MELTAN = 808;
  SPECIES_MELMETAL = 809;
  SPECIES_GROOKEY = 810;
  SPECIES_THWACKEY = 811;
  SPECIES_RILLABOOM = 812;
  SPECIES_SCORBUNNY = 813;
  SPECIES_RABOOT = 814;
  SPECIES_CINDERACE = 815;
  SPECIES_SOBBLE = 816;
  SPECIES_DRIZZILE = 817;
  SPECIES_INTELEON = 818;
  SPECIES_SKWOVET = 819;
  SPECIES_GREEDENT = 820;
  SPECIES_ROOKIDEE = 821;
  SPECIES_CORVISQUIRE = 822;
  SPECIES_CORVIKNIGHT = 823;
  SPECIES_BLIPBUG = 824;
  SPECIES_DOTTLER = 825;
  SPECIES_ORBEETLE = 826;
  SPECIES_NICKIT = 827;
  SPECIES_THIEVUL = 828;
  SPECIES_GOSSIFLEUR = 829;
  SPECIES_ELDEGOSS = 830;
  SPECIES_WOOLOO = 831;
  SPECIES_DUBWOOL = 832;
  SPECIES_CHEWTLE = 833;
  SPECIES_DREDNAW = 834;
  SPECIES_YAMPER = 835;
  SPECIES_BOLTUND = 836;
  SPECIES_ROLYCOLY = 837;
  SPECIES_CARKOL = 838;
  SPECIES_COALOSSAL = 839;
  SPECIES_APPLIN = 840;
  SPECIES_FLAPPLE = 841;
  SPECIES_APPLETUN = 842;
  SPECIES_SILICOBRA = 843;
  SPECIES_SANDACONDA = 844;
  SPECIES_CRAMORANT = 845;
  SPECIES_ARROKUDA = 846;
  SPECIES_BARRASKEWDA = 847;
  SPECIES_TOXEL = 848;
  SPECIES_TOXTRICITY = 849;
  SPECIES_SIZZLIPEDE = 850;
  SPECIES_CENTISKORCH = 851;
  SPECIES_CLOBBOPUS = 852;
  SPECIES_GRAPPLOCT = 853;
  SPECIES_SINISTEA = 854;
  SPECIES_POLTEAGEIST = 855;
  SPECIES_HATENNA = 856;
  SPECIES_HATTREM = 857;
  SPECIES_HATTERENE = 858;
  SPECIES_IMPIDIMP = 859;
  SPECIES_MORGREM = 860;
  SPECIES_GRIMMSNARL = 861;
  SPECIES_OBSTAGOON = 862;
  SPECIES_PERRSERKER = 863;
  SPECIES_CURSOLA = 864;
  SPECIES_SIRFETCHD = 865;
  SPECIES_MR_RIME = 866;
  SPECIES_RUNERIGUS = 867;
  SPECIES_MILCERY = 868;
  SPECIES_ALCREMIE = 869;
  SPECIES_FALINKS = 870;
  SPECIES_PINCURCHIN = 871;
  SPECIES_SNOM = 872;
  SPECIES_FROSMOTH = 873;
  SPECIES_STONJOURNER = 874;
  SPECIES_EISCUE = 875;
  SPECIES_INDEEDEE = 876;
  SPECIES_MORPEKO = 877;
  SPECIES_CUFANT = 878;
  SPECIES_COPPERAJAH = 879;
  SPECIES_DRACOZOLT = 880;
  SPECIES_ARCTOZOLT = 881;
  SPECIES_DRACOVISH = 882;
  SPECIES_ARCTOVISH = 883;
  SPECIES_DURALUDON = 884;
  SPECIES_DREEPY = 885;
  SPECIES_DRAKLOAK = 886;
  SPECIES_DRAGAPULT = 887;
  SPECIES_ZACIAN = 888;
  SPECIES_ZAMAZENTA = 889;
  SPECIES_ETERNATUS = 890;
  SPECIES_KUBFU = 891;
  SPECIES_URSHIFU = 892;
  SPECIES_ZARUDE = 893;
  SPECIES_REGIELEKI = 894;
  SPECIES_REGIDRAGO = 895;
  SPECIES_GLASTRIER = 896;
  SPECIES_SPECTRIER = 897;
  SPECIES_CALYREX = 898;
  SPECIES_WYRDEER = 899;
  SPECIES_KLEAVOR = 900;
  SPECIES_URSALUNA = 901;
  SPECIES_BASCULEGION = 902;
  SPECIES_SNEASLER = 903;
  SPECIES_OVERQWIL = 904;
  SPECIES_ENAMORUS = 905;
  SPECIES_SPRIGATITO = 906;
  SPECIES_FLORAGATO = 907;
  SPECIES_MEOWSCARADA = 908;
  SPECIES_FUECOCO = 909;
  SPECIES_CROCALOR = 910;
  SPECIES_SKELEDIRGE = 911;
  SPECIES_QUAXLY = 912;
  SPECIES_QUAXWELL = 913;
  SPECIES_QUAQUAVAL = 914;
  SPECIES_LECHONK = 915;
  SPECIES_OINKOLOGNE = 916;
  SPECIES_TAROUNTULA = 917;
  SPECIES_SPIDOPS = 918;
  SPECIES_NYMBLE = 919;
  SPECIES_LOKIX = 920;
  SPECIES_PAWMI = 921;
  SPECIES_PAWMO = 922;
  SPECIES_PAWMOT = 923;
  SPECIES_TANDEMAUS = 924;
  SPECIES_MAUSHOLD = 925;
  SPECIES_FIDOUGH = 926;
  SPECIES_DACHSBUN = 927;
  SPECIES_SMOLIV = 928;
  SPECIES_DOLLIV = 929;
  SPECIES_ARBOLIVA = 930;
  SPECIES_SQUAWKABILLY = 931;
  SPECIES_NACLI = 932;
  SPECIES_NACLSTACK = 933;
  SPECIES_GARGANACL = 934;
  SPECIES_CHARCADET = 935;
  SPECIES_ARMAROUGE = 936;
  SPECIES_CERULEDGE = 937;
  SPECIES_TADBULB = 938;
  SPECIES_BELLIBOLT = 939;
  SPECIES_WATTREL = 940;
  SPECIES_KILOWATTREL = 941;
  SPECIES_MASCHIFF = 942;
  SPECIES_MABOSSTIFF = 943;
  SPECIES_SHROODLE = 944;
  SPECIES_GRAFAIAI = 945;
  SPECIES_BRAMBLIN = 946;
  SPECIES_BRAMBLEGHAST = 947;
  SPECIES_TOEDSCOOL = 948;
  SPECIES_TOEDSCRUEL = 949;
  SPECIES_KLAWF = 950;
  SPECIES_CAPSAKID = 951;
  SPECIES_SCOVILLAIN = 952;
  SPECIES_RELLOR = 953;
  SPECIES_RABSCA = 954;
  SPECIES_FLITTLE = 955;
  SPECIES_ESPATHRA = 956;
  SPECIES_TINKATINK = 957;
  SPECIES_TINKATUFF = 958;
  SPECIES_TINKATON = 959;
  SPECIES_WIGLETT = 960;
  SPECIES_WUGTRIO = 961;
  SPECIES_BOMBIRDIER = 962;
  SPECIES_FINIZEN = 963;
  SPECIES_PALAFIN = 964;
  SPECIES_VAROOM = 965;
  SPECIES_REVAVROOM = 966;
  SPECIES_CYCLIZAR = 967;
  SPECIES_ORTHWORM = 968;
  SPECIES_GLIMMET = 969;
  SPECIES_GLIMMORA = 970;
  SPECIES_GREAVARD = 971;
  SPECIES_HOUNDSTONE = 972;
  SPECIES_FLAMIGO = 973;
  SPECIES_CETODDLE = 974;
  SPECIES_CETITAN = 975;
  SPECIES_VELUZA = 976;
  SPECIES_DONDOZO = 977;
  SPECIES_TATSUGIRI = 978;
  SPECIES_ANNIHILAPE = 979;
  SPECIES_CLODSIRE = 980;
  SPECIES_FARIGIRAF = 981;
  SPECIES_DUDUNSPARCE = 982;
  SPECIES_KINGAMBIT = 983;
  SPECIES_GREAT_TUSK = 984;
  SPECIES_SCREAM_TAIL = 985;
  SPECIES_BRUTE_BONNET = 986;
  SPECIES_FLUTTER_MANE = 987;
  SPECIES_SLITHER_WING = 988;
  SPECIES_SANDY_SHOCKS = 989;
  SPECIES_IRON_TREADS = 990;
  SPECIES_IRON_BUNDLE = 991;
  SPECIES_IRON_HANDS = 992;
  SPECIES_IRON_JUGULIS = 993;
  SPECIES_IRON_MOTH = 994;
  SPECIES_IRON_THORNS = 995;
  SPECIES_FRIGIBAX = 996;
  SPECIES_ARCTIBAX = 997;
  SPECIES_BAXCALIBUR = 998;
  SPECIES_GIMMIGHOUL = 999;
  SPECIES_GHOLDENGO = 1000;
  SPECIES_WO_CHIEN = 1001;
  SPECIES_CHIEN_PAO = 1002;
  SPECIES_TING_LU = 1003;
  SPECIES_CHI_YU = 1004;
  SPECIES_ROARING_MOON = 1005;
  SPECIES_IRON_VALIANT = 1006;
  SPECIES_KORAIDON = 1007;
  SPECIES_MIRAIDON = 1008;
  SPECIES_WALKING_WAKE = 1009;
  SPECIES_IRON_LEAVES = 1010;
  SPECIES_DIPPLIN = 1011;
  SPECIES_POLTCHAGEIST = 1012;
  SPECIES_SINISTCHA = 1013;
  SPECIES_OKIDOGI = 1014;
  SPECIES_MUNKIDORI = 1015;
  SPECIES_FEZANDIPITI = 1016;
  SPECIES_OGERPON = 1017;
  SPECIES_ARCHALUDON = 1018;
  SPECIES_HYDRAPPLE = 1019;
  SPECIES_GOUGING_FIRE = 1020;
  SPECIES_RAGING_BOLT = 1021;
  SPECIES_IRON_BOULDER = 1022;
  SPECIES_IRON_CROWN = 1023;
  SPECIES_TERAPAGOS = 1024;
  SPECIES_PECHARUNT = 1025;
  SPECIES_PHANTOWL = 1026;
  SPECIES_DUELUMBER = 1027;
  SPECIES_ESCARGINITE = 1028;
  SPECIES_ARACHTRES = 1029;
  SPECIES_FLAIRGRANCE = 1030;
  SPECIES_POLARTIC = 1031;
  SPECIES_ARASHINNE = 1032;
  SPECIES_DREADNAUT = 1033;
  SPECIES_BOARLOCK = 1034;
  SPECIES_HELIOSUNNY = 1035;
  SPECIES_SOPRANICE = 1036;
  SPECIES_BEEFENDER = 1037;
  SPECIES_SALAZARUS = 1038;
  SPECIES_GOOSCHASE = 1039;
  SPECIES_LEPASTRY = 1040;
  SPECIES_GYARADEATH = 1041;
  SPECIES_TORTEMPLE = 1042;
  SPECIES_BRONTONANA = 1043;
  SPECIES_DREDWOOD = 1044;
  SPECIES_CORM = 1045;
  SPECIES_CORMOTH = 1046;
  SPECIES_POPCORM = 1047;
  SPECIES_BLIZZARD_MAW = 1048;
  SPECIES_LUMBERING_SLOTH = 1049;
  SPECIES_IRON_CARAPACE = 1050;
  SPECIES_MAGMENOUS = 1051;
  SPECIES_KAIOSEA = 1052;
  SPECIES_SLYDUCK = 1053;
  SPECIES_SHYDUCK = 1054;
  SPECIES_MARBEEP = 1055;
  SPECIES_FLUFFBEE = 1056;
  SPECIES_AMPHYBUZZ = 1057;
  SPECIES_BARIONG = 1058;
  SPECIES_CRABONINATION = 1059;
  SPECIES_PHANFERNAL = 1060;
  SPECIES_SKULBERUS = 1061;
  SPECIES_VELOZEL = 1062;
  SPECIES_BEWARDEN = 1063;
  SPECIES_BUBBLEO = 1064;
  SPECIES_HYDROAR = 1065;
  SPECIES_GRANITUN = 1066;
  SPECIES_FUJIFLAP = 1067;
  SPECIES_BURMY_ETERNA = 1068;
  SPECIES_KNAIVER = 1069;
  SPECIES_SAGARACAS = 1070;
  SPECIES_LUMINOSITEON = 1071;
  SPECIES_CRAWDAUNTLES = 1072;
  SPECIES_SCRAFTY_MEGA = 1073;
  SPECIES_IRON_VOCA = 1074;
  SPECIES_MORPEKYLL = 1075;
  SPECIES_FROSTULA = 1076;
  // INSERT NEW SPECIES HERE
  SPECIES_VENUSAUR_MEGA = 1501;
  SPECIES_CHARIZARD_MEGA_X = 1502;
  SPECIES_CHARIZARD_MEGA_Y = 1503;
  SPECIES_BLASTOISE_MEGA = 1504;
  SPECIES_BEEDRILL_MEGA = 1505;
  SPECIES_PIDGEOT_MEGA = 1506;
  SPECIES_ALAKAZAM_MEGA = 1507;
  SPECIES_SLOWBRO_MEGA = 1508;
  SPECIES_GENGAR_MEGA = 1509;
  SPECIES_KANGASKHAN_MEGA = 1510;
  SPECIES_PINSIR_MEGA = 1511;
  SPECIES_GYARADOS_MEGA = 1512;
  SPECIES_AERODACTYL_MEGA = 1513;
  SPECIES_MEWTWO_MEGA_X = 1514;
  SPECIES_MEWTWO_MEGA_Y = 1515;
  SPECIES_AMPHAROS_MEGA = 1516;
  SPECIES_STEELIX_MEGA = 1517;
  SPECIES_SCIZOR_MEGA = 1518;
  SPECIES_HERACROSS_MEGA = 1519;
  SPECIES_HOUNDOOM_MEGA = 1520;
  SPECIES_TYRANITAR_MEGA = 1521;
  SPECIES_SCEPTILE_MEGA = 1522;
  SPECIES_BLAZIKEN_MEGA = 1523;
  SPECIES_SWAMPERT_MEGA = 1524;
  SPECIES_GARDEVOIR_MEGA = 1525;
  SPECIES_SABLEYE_MEGA = 1526;
  SPECIES_MAWILE_MEGA = 1527;
  SPECIES_AGGRON_MEGA = 1528;
  SPECIES_MEDICHAM_MEGA = 1529;
  SPECIES_MANECTRIC_MEGA = 1530;
  SPECIES_SHARPEDO_MEGA = 1531;
  SPECIES_CAMERUPT_MEGA = 1532;
  SPECIES_ALTARIA_MEGA = 1533;
  SPECIES_BANETTE_MEGA = 1534;
  SPECIES_ABSOL_MEGA = 1535;
  SPECIES_GLALIE_MEGA = 1536;
  SPECIES_SALAMENCE_MEGA = 1537;
  SPECIES_METAGROSS_MEGA = 1538;
  SPECIES_LATIAS_MEGA = 1539;
  SPECIES_LATIOS_MEGA = 1540;
  SPECIES_LOPUNNY_MEGA = 1541;
  SPECIES_GARCHOMP_MEGA = 1542;
  SPECIES_LUCARIO_MEGA = 1543;
  SPECIES_ABOMASNOW_MEGA = 1544;
  SPECIES_GALLADE_MEGA = 1545;
  SPECIES_AUDINO_MEGA = 1546;
  SPECIES_DIANCIE_MEGA = 1547;
  SPECIES_RAYQUAZA_MEGA = 1548;
  SPECIES_KYOGRE_PRIMAL = 1549;
  SPECIES_GROUDON_PRIMAL = 1550;
  SPECIES_RATTATA_ALOLAN = 1551;
  SPECIES_RATICATE_ALOLAN = 1552;
  SPECIES_RAICHU_ALOLAN = 1553;
  SPECIES_SANDSHREW_ALOLAN = 1554;
  SPECIES_SANDSLASH_ALOLAN = 1555;
  SPECIES_VULPIX_ALOLAN = 1556;
  SPECIES_NINETALES_ALOLAN = 1557;
  SPECIES_DIGLETT_ALOLAN = 1558;
  SPECIES_DUGTRIO_ALOLAN = 1559;
  SPECIES_MEOWTH_ALOLAN = 1560;
  SPECIES_PERSIAN_ALOLAN = 1561;
  SPECIES_GEODUDE_ALOLAN = 1562;
  SPECIES_GRAVELER_ALOLAN = 1563;
  SPECIES_GOLEM_ALOLAN = 1564;
  SPECIES_GRIMER_ALOLAN = 1565;
  SPECIES_MUK_ALOLAN = 1566;
  SPECIES_EXEGGUTOR_ALOLAN = 1567;
  SPECIES_MAROWAK_ALOLAN = 1568;
  SPECIES_MEOWTH_GALARIAN = 1569;
  SPECIES_PONYTA_GALARIAN = 1570;
  SPECIES_RAPIDASH_GALARIAN = 1571;
  SPECIES_SLOWPOKE_GALARIAN = 1572;
  SPECIES_SLOWBRO_GALARIAN = 1573;
  SPECIES_FARFETCHD_GALARIAN = 1574;
  SPECIES_WEEZING_GALARIAN = 1575;
  SPECIES_MR_MIME_GALARIAN = 1576;
  SPECIES_ARTICUNO_GALARIAN = 1577;
  SPECIES_ZAPDOS_GALARIAN = 1578;
  SPECIES_MOLTRES_GALARIAN = 1579;
  SPECIES_SLOWKING_GALARIAN = 1580;
  SPECIES_CORSOLA_GALARIAN = 1581;
  SPECIES_ZIGZAGOON_GALARIAN = 1582;
  SPECIES_LINOONE_GALARIAN = 1583;
  SPECIES_DARUMAKA_GALARIAN = 1584;
  SPECIES_DARMANITAN_GALARIAN = 1585;
  SPECIES_YAMASK_GALARIAN = 1586;
  SPECIES_STUNFISK_GALARIAN = 1587;
  SPECIES_PIKACHU_COSPLAY = 1588;
  SPECIES_PIKACHU_ROCK_STAR = 1589;
  SPECIES_PIKACHU_BELLE = 1590;
  SPECIES_PIKACHU_POP_STAR = 1591;
  SPECIES_PIKACHU_PH_D = 1592;
  SPECIES_PIKACHU_LIBRE = 1593;
  SPECIES_PIKACHU_ORIGINAL_CAP = 1594;
  SPECIES_PIKACHU_HOENN_CAP = 1595;
  SPECIES_PIKACHU_SINNOH_CAP = 1596;
  SPECIES_PIKACHU_UNOVA_CAP = 1597;
  SPECIES_PIKACHU_KALOS_CAP = 1598;
  SPECIES_PIKACHU_ALOLA_CAP = 1599;
  SPECIES_PIKACHU_PARTNER_CAP = 1600;
  SPECIES_PIKACHU_WORLD_CAP = 1601;
  SPECIES_PICHU_SPIKY_EARED = 1602;
  SPECIES_UNOWN_B = 1603;
  SPECIES_UNOWN_C = 1604;
  SPECIES_UNOWN_D = 1605;
  SPECIES_UNOWN_E = 1606;
  SPECIES_UNOWN_F = 1607;
  SPECIES_UNOWN_G = 1608;
  SPECIES_UNOWN_H = 1609;
  SPECIES_UNOWN_I = 1610;
  SPECIES_UNOWN_J = 1611;
  SPECIES_UNOWN_K = 1612;
  SPECIES_UNOWN_L = 1613;
  SPECIES_UNOWN_M = 1614;
  SPECIES_UNOWN_N = 1615;
  SPECIES_UNOWN_O = 1616;
  SPECIES_UNOWN_P = 1617;
  SPECIES_UNOWN_Q = 1618;
  SPECIES_UNOWN_R = 1619;
  SPECIES_UNOWN_S = 1620;
  SPECIES_UNOWN_T = 1621;
  SPECIES_UNOWN_U = 1622;
  SPECIES_UNOWN_V = 1623;
  SPECIES_UNOWN_W = 1624;
  SPECIES_UNOWN_X = 1625;
  SPECIES_UNOWN_Y = 1626;
  SPECIES_UNOWN_Z = 1627;
  SPECIES_UNOWN_EMARK = 1628;
  SPECIES_UNOWN_QMARK = 1629;
  SPECIES_CASTFORM_SUNNY = 1630;
  SPECIES_CASTFORM_RAINY = 1631;
  SPECIES_CASTFORM_SNOWY = 1632;
  SPECIES_DEOXYS_ATTACK = 1633;
  SPECIES_DEOXYS_DEFENSE = 1634;
  SPECIES_DEOXYS_SPEED = 1635;
  SPECIES_BURMY_SANDY_CLOAK = 1636;
  SPECIES_BURMY_TRASH_CLOAK = 1637;
  SPECIES_WORMADAM_SANDY_CLOAK = 1638;
  SPECIES_WORMADAM_TRASH_CLOAK = 1639;
  SPECIES_CHERRIM_SUNSHINE = 1640;
  SPECIES_SHELLOS_EAST_SEA = 1641;
  SPECIES_GASTRODON_EAST_SEA = 1642;
  SPECIES_ROTOM_HEAT = 1643;
  SPECIES_ROTOM_WASH = 1644;
  SPECIES_ROTOM_FROST = 1645;
  SPECIES_ROTOM_FAN = 1646;
  SPECIES_ROTOM_MOW = 1647;
  SPECIES_GIRATINA_ORIGIN = 1648;
  SPECIES_SHAYMIN_SKY = 1649;
  SPECIES_ARCEUS_FIGHTING = 1650;
  SPECIES_ARCEUS_FLYING = 1651;
  SPECIES_ARCEUS_POISON = 1652;
  SPECIES_ARCEUS_GROUND = 1653;
  SPECIES_ARCEUS_ROCK = 1654;
  SPECIES_ARCEUS_BUG = 1655;
  SPECIES_ARCEUS_GHOST = 1656;
  SPECIES_ARCEUS_STEEL = 1657;
  SPECIES_ARCEUS_FIRE = 1658;
  SPECIES_ARCEUS_WATER = 1659;
  SPECIES_ARCEUS_GRASS = 1660;
  SPECIES_ARCEUS_ELECTRIC = 1661;
  SPECIES_ARCEUS_PSYCHIC = 1662;
  SPECIES_ARCEUS_ICE = 1663;
  SPECIES_ARCEUS_DRAGON = 1664;
  SPECIES_ARCEUS_DARK = 1665;
  SPECIES_ARCEUS_FAIRY = 1666;
  SPECIES_BASCULIN_BLUE_STRIPED = 1667;
  SPECIES_DARMANITAN_ZEN_MODE = 1668;
  SPECIES_DARMANITAN_ZEN_MODE_GALARIAN = 1669;
  SPECIES_DEERLING_SUMMER = 1670;
  SPECIES_DEERLING_AUTUMN = 1671;
  SPECIES_DEERLING_WINTER = 1672;
  SPECIES_SAWSBUCK_SUMMER = 1673;
  SPECIES_SAWSBUCK_AUTUMN = 1674;
  SPECIES_SAWSBUCK_WINTER = 1675;
  SPECIES_TORNADUS_THERIAN = 1676;
  SPECIES_THUNDURUS_THERIAN = 1677;
  SPECIES_LANDORUS_THERIAN = 1678;
  SPECIES_KYUREM_WHITE = 1679;
  SPECIES_KYUREM_BLACK = 1680;
  SPECIES_KELDEO_RESOLUTE = 1681;
  SPECIES_MELOETTA_PIROUETTE = 1682;
  SPECIES_GENESECT_DOUSE_DRIVE = 1683;
  SPECIES_GENESECT_SHOCK_DRIVE = 1684;
  SPECIES_GENESECT_BURN_DRIVE = 1685;
  SPECIES_GENESECT_CHILL_DRIVE = 1686;
  SPECIES_GRENINJA_BATTLE_BOND = 1687;
  SPECIES_GRENINJA_ASH = 1688;
  SPECIES_VIVILLON_POLAR = 1689;
  SPECIES_VIVILLON_TUNDRA = 1690;
  SPECIES_VIVILLON_CONTINENTAL = 1691;
  SPECIES_VIVILLON_GARDEN = 1692;
  SPECIES_VIVILLON_ELEGANT = 1693;
  SPECIES_VIVILLON_MEADOW = 1694;
  SPECIES_VIVILLON_MODERN = 1695;
  SPECIES_VIVILLON_MARINE = 1696;
  SPECIES_VIVILLON_ARCHIPELAGO = 1697;
  SPECIES_VIVILLON_HIGH_PLAINS = 1698;
  SPECIES_VIVILLON_SANDSTORM = 1699;
  SPECIES_VIVILLON_RIVER = 1700;
  SPECIES_VIVILLON_MONSOON = 1701;
  SPECIES_VIVILLON_SAVANNA = 1702;
  SPECIES_VIVILLON_SUN = 1703;
  SPECIES_VIVILLON_OCEAN = 1704;
  SPECIES_VIVILLON_JUNGLE = 1705;
  SPECIES_VIVILLON_FANCY = 1706;
  SPECIES_VIVILLON_POKE_BALL = 1707;
  SPECIES_FLABEBE_YELLOW_FLOWER = 1708;
  SPECIES_FLABEBE_ORANGE_FLOWER = 1709;
  SPECIES_FLABEBE_BLUE_FLOWER = 1710;
  SPECIES_FLABEBE_WHITE_FLOWER = 1711;
  SPECIES_FLOETTE_YELLOW_FLOWER = 1712;
  SPECIES_FLOETTE_ORANGE_FLOWER = 1713;
  SPECIES_FLOETTE_BLUE_FLOWER = 1714;
  SPECIES_FLOETTE_WHITE_FLOWER = 1715;
  SPECIES_FLOETTE_ETERNAL_FLOWER = 1716;
  SPECIES_FLORGES_YELLOW_FLOWER = 1717;
  SPECIES_FLORGES_ORANGE_FLOWER = 1718;
  SPECIES_FLORGES_BLUE_FLOWER = 1719;
  SPECIES_FLORGES_WHITE_FLOWER = 1720;
  SPECIES_FURFROU_HEART_TRIM = 1721;
  SPECIES_FURFROU_STAR_TRIM = 1722;
  SPECIES_FURFROU_DIAMOND_TRIM = 1723;
  SPECIES_FURFROU_DEBUTANTE_TRIM = 1724;
  SPECIES_FURFROU_MATRON_TRIM = 1725;
  SPECIES_FURFROU_DANDY_TRIM = 1726;
  SPECIES_FURFROU_LA_REINE_TRIM = 1727;
  SPECIES_FURFROU_KABUKI_TRIM = 1728;
  SPECIES_FURFROU_PHARAOH_TRIM = 1729;
  SPECIES_MEOWSTIC_FEMALE = 1730;
  SPECIES_AEGISLASH_BLADE = 1731;
  SPECIES_PUMPKABOO_SMALL = 1732;
  SPECIES_PUMPKABOO_LARGE = 1733;
  SPECIES_PUMPKABOO_SUPER = 1734;
  SPECIES_GOURGEIST_SMALL = 1735;
  SPECIES_GOURGEIST_LARGE = 1736;
  SPECIES_GOURGEIST_SUPER = 1737;
  SPECIES_XERNEAS_ACTIVE = 1738;
  SPECIES_ZYGARDE_10 = 1739;
  SPECIES_ZYGARDE_10_POWER_CONSTRUCT = 1740;
  SPECIES_ZYGARDE_50_POWER_CONSTRUCT = 1741;
  SPECIES_ZYGARDE_COMPLETE = 1742;
  SPECIES_HOOPA_UNBOUND = 1743;
  SPECIES_ORICORIO_POM_POM = 1744;
  SPECIES_ORICORIO_PAU = 1745;
  SPECIES_ORICORIO_SENSU = 1746;
  SPECIES_ROCKRUFF_OWN_TEMPO = 1747;
  SPECIES_LYCANROC_MIDNIGHT = 1748;
  SPECIES_LYCANROC_DUSK = 1749;
  SPECIES_WISHIWASHI_SCHOOL = 1750;
  SPECIES_SILVALLY_FIGHTING = 1751;
  SPECIES_SILVALLY_FLYING = 1752;
  SPECIES_SILVALLY_POISON = 1753;
  SPECIES_SILVALLY_GROUND = 1754;
  SPECIES_SILVALLY_ROCK = 1755;
  SPECIES_SILVALLY_BUG = 1756;
  SPECIES_SILVALLY_GHOST = 1757;
  SPECIES_SILVALLY_STEEL = 1758;
  SPECIES_SILVALLY_FIRE = 1759;
  SPECIES_SILVALLY_WATER = 1760;
  SPECIES_SILVALLY_GRASS = 1761;
  SPECIES_SILVALLY_ELECTRIC = 1762;
  SPECIES_SILVALLY_PSYCHIC = 1763;
  SPECIES_SILVALLY_ICE = 1764;
  SPECIES_SILVALLY_DRAGON = 1765;
  SPECIES_SILVALLY_DARK = 1766;
  SPECIES_SILVALLY_FAIRY = 1767;
  SPECIES_MINIOR_METEOR_ORANGE = 1768;
  SPECIES_MINIOR_METEOR_YELLOW = 1769;
  SPECIES_MINIOR_METEOR_GREEN = 1770;
  SPECIES_MINIOR_METEOR_BLUE = 1771;
  SPECIES_MINIOR_METEOR_INDIGO = 1772;
  SPECIES_MINIOR_METEOR_VIOLET = 1773;
  SPECIES_MINIOR_CORE_RED = 1774;
  SPECIES_MINIOR_CORE_ORANGE = 1775;
  SPECIES_MINIOR_CORE_YELLOW = 1776;
  SPECIES_MINIOR_CORE_GREEN = 1777;
  SPECIES_MINIOR_CORE_BLUE = 1778;
  SPECIES_MINIOR_CORE_INDIGO = 1779;
  SPECIES_MINIOR_CORE_VIOLET = 1780;
  SPECIES_MIMIKYU_BUSTED = 1781;
  SPECIES_NECROZMA_DUSK_MANE = 1782;
  SPECIES_NECROZMA_DAWN_WINGS = 1783;
  SPECIES_NECROZMA_ULTRA = 1784;
  SPECIES_MAGEARNA_ORIGINAL_COLOR = 1785;
  SPECIES_CRAMORANT_GULPING = 1786;
  SPECIES_CRAMORANT_GORGING = 1787;
  SPECIES_TOXTRICITY_LOW_KEY = 1788;
  SPECIES_SINISTEA_ANTIQUE = 1789;
  SPECIES_POLTEAGEIST_ANTIQUE = 1790;
  SPECIES_ALCREMIE_RUBY_CREAM = 1791;
  SPECIES_ALCREMIE_MATCHA_CREAM = 1792;
  SPECIES_ALCREMIE_MINT_CREAM = 1793;
  SPECIES_ALCREMIE_LEMON_CREAM = 1794;
  SPECIES_ALCREMIE_SALTED_CREAM = 1795;
  SPECIES_ALCREMIE_RUBY_SWIRL = 1796;
  SPECIES_ALCREMIE_CARAMEL_SWIRL = 1797;
  SPECIES_ALCREMIE_RAINBOW_SWIRL = 1798;
  SPECIES_EISCUE_NOICE_FACE = 1799;
  SPECIES_INDEEDEE_FEMALE = 1800;
  SPECIES_MORPEKO_HANGRY = 1801;
  SPECIES_ZACIAN_CROWNED_SWORD = 1802;
  SPECIES_ZAMAZENTA_CROWNED_SHIELD = 1803;
  SPECIES_ETERNATUS_ETERNAMAX = 1804;
  SPECIES_URSHIFU_RAPID_STRIKE_STYLE = 1805;
  SPECIES_ZARUDE_DADA = 1806;
  SPECIES_CALYREX_ICE_RIDER = 1807;
  SPECIES_CALYREX_SHADOW_RIDER = 1808;
  SPECIES_QWILFISH_HISUIAN = 1809;
  SPECIES_GROWLITHE_HISUIAN = 1810;
  SPECIES_ARCANINE_HISUIAN = 1811;
  SPECIES_VOLTORB_HISUIAN = 1812;
  SPECIES_ELECTRODE_HISUIAN = 1813;
  SPECIES_TYPHLOSION_HISUIAN = 1814;
  SPECIES_SNEASEL_HISUIAN = 1815;
  SPECIES_SAMUROTT_HISUIAN = 1816;
  SPECIES_LILLIGANT_HISUIAN = 1817;
  SPECIES_BRAVIARY_HISUIAN = 1818;
  SPECIES_SLIGGOO_HISUIAN = 1819;
  SPECIES_GOODRA_HISUIAN = 1820;
  SPECIES_AVALUGG_HISUIAN = 1821;
  SPECIES_DECIDUEYE_HISUIAN = 1822;
  SPECIES_ZORUA_HISUIAN = 1823;
  SPECIES_ZOROARK_HISUIAN = 1824;
  SPECIES_TAUROS_PALDEAN_AQUA_BREED = 1825;
  SPECIES_TAUROS_PALDEAN_BLAZE_BREED = 1826;
  SPECIES_TAUROS_PALDEAN_COMBAT_BREED = 1827;
  SPECIES_URSALUNA_BLOODMOON = 1828;
  SPECIES_PALAFIN_HERO = 1829;
  SPECIES_DUDUNSPARCE_THREE_SEGMENT = 1830;
  SPECIES_MAUSHOLD_FOUR = 1831;
  SPECIES_TATSUGIRI_CURLY = 1832;
  SPECIES_TATSUGIRI_STRETCHY = 1833;
  SPECIES_TATSUGIRI_DROOPY = 1834;
  SPECIES_SQUAWKABILLY_GREEN_PLUMAGE = 1835;
  SPECIES_SQUAWKABILLY_BLUE_PLUMAGE = 1836;
  SPECIES_SQUAWKABILLY_YELLOW_PLUMAGE = 1837;
  SPECIES_SQUAWKABILLY_WHITE_PLUMAGE = 1838;
  SPECIES_OGERPON_WELLSPRING_MASK = 1839;
  SPECIES_OGERPON_HEARTHFLAME_MASK = 1840;
  SPECIES_OGERPON_CORNERSTONE_MASK = 1841;
  SPECIES_DIALGA_ORIGIN = 1842;
  SPECIES_PALKIA_ORIGIN = 1843;
  SPECIES_ENAMORUS_THERIAN = 1844;
  SPECIES_CASTFORM_SANDY = 1845;
  SPECIES_POLARTIC_BLUEMOON = 1846;
  SPECIES_LUMBERING_SLOTH_ENGULFED = 1847;
  SPECIES_GIMMIGHOUL_ROAMING = 1848;
  SPECIES_BASCULEGION_F = 1849;
  SPECIES_TERAPAGOS_STELLAR = 1850;
  SPECIES_HYDROAR_F = 1851;
  SPECIES_PIKACHU_PARTNER = 1852;
  SPECIES_EEVEE_PARTNER = 1853;
  SPECIES_MEOWTH_PARTNER = 1854;
  SPECIES_MIMIKYU_RAYQUAZA_BUSTED = 1855;
  SPECIES_SLAKING_MEGA_APE_SHIFT = 1856;
  SPECIES_DURALUDON_PARTNER = 1857;
  SPECIES_CASTFORM_FOGGY = 1858;
  SPECIES_FIDOUGH_PARTNER = 1859;
  SPECIES_CHESNAUGHT_BATTLE_BOND = 1860;
  SPECIES_CHESNAUGHT_CLEMONT = 1861;
  SPECIES_DELPHOX_BATTLE_BOND = 1862;
  SPECIES_DELPHOX_SERENA = 1863;
  SPECIES_MORPEKYLL_HANGRY = 1864;
  SPECIES_UNOWN_REVELATION = 1865;
  SPECIES_LYCANROC_ECLIPSE = 1866;
  SPECIES_LYCANROC_TWILIGHT = 1867;
  // INSERT NEW SPECIES HERE
  SPECIES_HITMONCHAN_PARTNER = 1952;
  SPECIES_HITMONCHAN_PARTNER_MEGA = 1953;
  SPECIES_AMPHAROS_PARTNER = 1954;
  SPECIES_AMPHAROS_PARTNER_MEGA = 1955;
  SPECIES_VOLCARONA_PARTNER = 1956;
  SPECIES_KANGASKHAN_PARTNER = 1957;
  SPECIES_KANGASKHAN_PARTNER_MEGA = 1958;
  SPECIES_DRAGONITE_PARTNER = 1959;
  SPECIES_DRAGONITE_PARTNER_MEGA = 1960;
  SPECIES_REUNICLUS_PARTNER = 1961;
  SPECIES_KINGDRA_PARTNER = 1962;
  SPECIES_KINGDRA_PARTNER_MEGA = 1963;
  SPECIES_AMAURA_PARTNER_B = 1964;
  SPECIES_AURORUS_PARTNER_B = 1965;
  SPECIES_HITMONCHAN_PARTNER_B = 1966;
  SPECIES_HITMONCHAN_PARTNER_MEGA_B = 1967;
  SPECIES_AMPHAROS_PARTNER_B = 1968;
  SPECIES_AMPHAROS_PARTNER_MEGA_B = 1969;
  SPECIES_VOLCARONA_PARTNER_B = 1970;
  SPECIES_KANGASKHAN_PARTNER_B = 1971;
  SPECIES_KANGASKHAN_PARTNER_MEGA_B = 1972;
  SPECIES_DRAGONITE_PARTNER_B = 1973;
  SPECIES_DRAGONITE_PARTNER_MEGA_B = 1974;
  SPECIES_REUNICLUS_PARTNER_B = 1975;
  SPECIES_KINGDRA_PARTNER_B = 1976;
  SPECIES_KINGDRA_PARTNER_MEGA_B = 1977;
  SPECIES_AMAURA_PARTNER_C = 1978;
  SPECIES_AURORUS_PARTNER_C = 1979;
  SPECIES_HITMONCHAN_PARTNER_C = 1980;
  SPECIES_HITMONCHAN_PARTNER_MEGA_C = 1981;
  SPECIES_AMPHAROS_PARTNER_C = 1982;
  SPECIES_AMPHAROS_PARTNER_MEGA_C = 1983;
  SPECIES_VOLCARONA_PARTNER_C = 1984;
  SPECIES_KANGASKHAN_PARTNER_C = 1985;
  SPECIES_KANGASKHAN_PARTNER_MEGA_C = 1986;
  SPECIES_DRAGONITE_PARTNER_C = 1987;
  SPECIES_DRAGONITE_PARTNER_MEGA_C = 1988;
  SPECIES_REUNICLUS_PARTNER_C = 1989;
  SPECIES_KINGDRA_PARTNER_C = 1990;
  SPECIES_KINGDRA_PARTNER_MEGA_C = 1991;
  SPECIES_AMAURA_PARTNER = 1992;
  SPECIES_AURORUS_PARTNER = 1993;
  SPECIES_MILOTIC_MEGA = 2101;
  SPECIES_BUTTERFREE_MEGA = 2102;
  SPECIES_MACHAMP_MEGA = 2103;
  SPECIES_KINGLER_MEGA = 2104;
  SPECIES_LAPRAS_MEGA = 2105;
  SPECIES_FLYGON_MEGA = 2106;
  SPECIES_KINGDRA_MEGA = 2107;
  SPECIES_DEWGONG_MEGA = 2108;
  SPECIES_HITMONCHAN_MEGA = 2109;
  SPECIES_HITMONLEE_MEGA = 2110;
  SPECIES_HITMONTOP_MEGA = 2111;
  SPECIES_CROBAT_MEGA = 2112;
  SPECIES_SKARMORY_MEGA = 2113;
  SPECIES_BRUXISH_MEGA = 2114;
  SPECIES_TORTERRA_MEGA = 2115;
  SPECIES_INFERNAPE_MEGA = 2116;
  SPECIES_EMPOLEON_MEGA = 2117;
  SPECIES_SHUCKLE_MEGA = 2118;
  SPECIES_RELICANTH_MEGA = 2119;
  SPECIES_TOUCANNON_MEGA = 2120;
  SPECIES_DRAGONITE_MEGA = 2121;
  SPECIES_BRELOOM_MEGA = 2122;
  SPECIES_SLAKING_MEGA = 2123;
  SPECIES_FERALIGATR_MEGA_X = 2124;
  SPECIES_FERALIGATR_MEGA_Y = 2125;
  SPECIES_GRANBULL_MEGA = 2126;
  SPECIES_JELLICENT_MEGA = 2127;
  SPECIES_QUAGSIRE_MEGA = 2128;
  SPECIES_GYARADOS_MEGA_Y = 2129;
  SPECIES_HAXORUS_MEGA = 2130;
  SPECIES_KINGDRA_MEGA_Y = 2131;
  SPECIES_MEGANIUM_MEGA = 2132;
  SPECIES_LUXRAY_MEGA = 2133;
  SPECIES_NIDOKING_MEGA = 2134;
  SPECIES_NIDOQUEEN_MEGA = 2135;
  SPECIES_SANDSLASH_MEGA = 2136;
  SPECIES_TYPHLOSION_MEGA = 2137;
  SPECIES_KROOKODILE_MEGA = 2138;
  SPECIES_MAGNEZONE_MEGA = 2139;
  SPECIES_SHEDINJA_MEGA = 2140;
  SPECIES_SWALOT_MEGA = 2141;
  SPECIES_LANTURN_MEGA = 2142;
  SPECIES_LAPRAS_MEGA_X = 2143;
  SPECIES_SLOWKING_MEGA = 2144;
  SPECIES_RIBOMBEE_MEGA = 2145;
  SPECIES_ALAKAZAM_MEGA_REDUX = 2146;
  SPECIES_BEEDRILL_MEGA_REDUX = 2147;
  SPECIES_MACHAMP_MEGA_REDUX = 2148;
  SPECIES_SKARMORY_MEGA_REDUX = 2149;
  SPECIES_ARCANINE_MEGA_REDUX = 2150;
  SPECIES_GARCHOMP_MEGA_REDUX = 2151;
  SPECIES_MAWILE_MEGA_REDUX = 2152;
  SPECIES_SABLEYE_MEGA_REDUX = 2153;
  SPECIES_HOUNDOOM_MEGA_REDUX = 2154;
  SPECIES_FROSLASS_MEGA = 2155;
  SPECIES_WIGGLYTUFF_MEGA_X = 2156;
  SPECIES_CASCOON_PRIMAL = 2157;
  SPECIES_WIGGLYTUFF_MEGA = 2158;
  SPECIES_LUCARIO_MEGA_Y = 2159;
  SPECIES_GYARADEATH_MEGA_X = 2160;
  SPECIES_GYARADEATH_MEGA_Y = 2161;
  SPECIES_ARBOK_MEGA = 2162;
  SPECIES_KINGAMBIT_REDUX_MEGA = 2163;
  SPECIES_GOLISOPOD_MEGA = 2164;
  SPECIES_RAPIDASH_MEGA = 2165;
  SPECIES_RAPIDASH_MEGA_GALARIAN = 2166;
  SPECIES_ORICORIO_MEGA = 2167;
  SPECIES_AEGISLASH_REDUX_MEGA = 2168;
  SPECIES_AEGISLASH_BLADE_REDUX_MEGA = 2169;
  SPECIES_REUNICLUS_REDUX_MEGA = 2170;
  SPECIES_HYDREIGON_REDUX_MEGA = 2171;
  SPECIES_CORMOTH_MEGA = 2172;
  SPECIES_POPCORM_MEGA = 2173;
  SPECIES_TORTERRA_REDUX_MEGA = 2174;
  SPECIES_INFERNAPE_REDUX_MEGA = 2175;
  SPECIES_EMPOLEON_REDUX_MEGA = 2176;
  SPECIES_TSAREENA_REDUX_MEGA = 2177;
  SPECIES_TOXTRICITY_REDUX_MEGA = 2178;
  SPECIES_TOXTRICITY_REDUX_FUZZ_MEGA = 2179;
  SPECIES_FLYGON_REDUX_MEGA = 2180;
  SPECIES_CLEFABLE_REDUX_MEGA = 2181;
  SPECIES_GLALIE_REDUX_MEGA = 2182;
  SPECIES_FROSLASS_REDUX_MEGA = 2183;
  SPECIES_AMPHYBUZZ_MEGA = 2184;
  SPECIES_URSHIFU_MEGA = 2185;
  SPECIES_URSHIFU_RAPID_STRIKE_STYLE_MEGA = 2186;
  SPECIES_MELMETAL_MEGA = 2187;
  SPECIES_VENUSAUR_MEGA_X = 2188;
  SPECIES_BLASTOISE_MEGA_X = 2189;
  SPECIES_GENGAR_MEGA_X = 2190;
  SPECIES_CHARIZARD_MEGA_Z = 2191;
  SPECIES_SNORLAX_MEGA = 2192;
  SPECIES_RILLABOOM_MEGA = 2193;
  SPECIES_CINDERACE_MEGA = 2194;
  SPECIES_INTELEON_MEGA = 2195;
  SPECIES_CORVIKNIGHT_MEGA = 2196;
  SPECIES_DREDNAW_MEGA = 2197;
  SPECIES_COALOSSAL_MEGA = 2198;
  SPECIES_SANDACONDA_MEGA = 2199;
  SPECIES_COPPERAJAH_MEGA = 2200;
  SPECIES_HATTERENE_MEGA = 2201;
  SPECIES_GARBODOR_MEGA = 2202;
  SPECIES_ORBEETLE_MEGA = 2203;
  SPECIES_GRIMMSNARL_MEGA = 2204;
  SPECIES_CENTISKORCH_MEGA = 2205;
  SPECIES_ALCREMIE_MEGA = 2206;
  SPECIES_TOXTRICITY_MEGA = 2207;
  SPECIES_PIKACHU_PARTNER_MEGA = 2208;
  SPECIES_EEVEE_PARTNER_MEGA = 2209;
  SPECIES_MEOWTH_PARTNER_MEGA = 2210;
  SPECIES_DURALUDON_PARTNER_MEGA = 2211;
  SPECIES_FIDOUGH_PARTNER_MEGA = 2212;
  SPECIES_WEAVILE_MEGA = 2213;
  SPECIES_SERPERIOR_MEGA = 2214;
  SPECIES_EMBOAR_MEGA = 2215;
  SPECIES_SAMUROTT_MEGA = 2216;
  SPECIES_DECIDUEYE_MEGA = 2217;
  SPECIES_DECIDUEYE_HISUIAN_MEGA = 2218;
  SPECIES_INCINEROAR_MEGA = 2219;
  SPECIES_MEOWSCARADA_MEGA = 2220;
  SPECIES_PRIMARINA_MEGA = 2221;
  SPECIES_QUAQUAVAL_MEGA = 2222;
  SPECIES_SAMUROTT_HISUIAN_MEGA = 2223;
  SPECIES_SKELEDIRGE_MEGA = 2224;
  SPECIES_TYPHLOSION_HISUIAN_MEGA = 2225;
  SPECIES_MIENSHAO_MEGA = 2226;
  SPECIES_ARCANINE_MEGA = 2227;
  SPECIES_GOODRA_MEGA = 2228;
  SPECIES_SLOWBRO_MEGA_GALARIAN = 2229;
  SPECIES_SLOWKING_MEGA_GALARIAN = 2230;
  SPECIES_ROSERADE_MEGA = 2231;
  // INSERT NEW SPECIES HERE
  SPECIES_KECLEONG = 2501;
  SPECIES_INFERNAPE_REDUX_B = 2502;
  SPECIES_NOIBAT_REDUX = 2503;
  SPECIES_NOIVERN_REDUX = 2504;
  SPECIES_LUXRAY_REDUX = 2505;
  SPECIES_CLAWITZER_REDUX = 2506;
  SPECIES_HONEDGE_REDUX = 2507;
  SPECIES_DOUBLADE_REDUX = 2508;
  SPECIES_AEGISLASH_REDUX = 2509;
  SPECIES_AEGISLASH_BLADE_REDUX = 2510;
  SPECIES_ABRA_REDUX = 2511;
  SPECIES_KADABRA_REDUX = 2512;
  SPECIES_ALAKAZAM_REDUX = 2513;
  SPECIES_WEEDLE_REDUX = 2514;
  SPECIES_KAKUNA_REDUX = 2515;
  SPECIES_BEEDRILL_REDUX = 2516;
  SPECIES_STUFFUL_REDUX = 2517;
  SPECIES_BEWEAR_REDUX = 2518;
  SPECIES_PANPOUR_REDUX = 2519;
  SPECIES_SIMIPOUR_REDUX = 2520;
  SPECIES_PANSAGE_REDUX = 2521;
  SPECIES_SIMISAGE_REDUX = 2522;
  SPECIES_PANSEAR_REDUX = 2523;
  SPECIES_SIMISEAR_REDUX = 2524;
  SPECIES_SLUGMA_REDUX = 2525;
  SPECIES_MAGCARGO_REDUX = 2526;
  SPECIES_BUIZEL_REDUX = 2527;
  SPECIES_FLOATZEL_REDUX = 2528;
  SPECIES_AZELF_REDUX = 2529;
  SPECIES_MESPRIT_REDUX = 2530;
  SPECIES_UXIE_REDUX = 2531;
  SPECIES_MACHOP_REDUX = 2532;
  SPECIES_MACHOKE_REDUX = 2533;
  SPECIES_MACHAMP_REDUX = 2534;
  SPECIES_SOLOSIS_REDUX = 2535;
  SPECIES_DUOSION_REDUX = 2536;
  SPECIES_REUNICLUS_REDUX = 2537;
  SPECIES_SKARMORY_REDUX = 2538;
  SPECIES_GROWLITHE_REDUX = 2539;
  SPECIES_ARCANINE_REDUX = 2540;
  SPECIES_WHISMUR_REDUX = 2541;
  SPECIES_LOUDRED_REDUX = 2542;
  SPECIES_EXPLOUD_REDUX = 2543;
  SPECIES_GIBLE_REDUX = 2544;
  SPECIES_GABITE_REDUX = 2545;
  SPECIES_GARCHOMP_REDUX = 2546;
  SPECIES_DEINO_REDUX = 2547;
  SPECIES_ZWEILOUS_REDUX = 2548;
  SPECIES_HYDREIGON_REDUX = 2549;
  SPECIES_PAWNIARD_REDUX = 2550;
  SPECIES_BISHARP_REDUX = 2551;
  SPECIES_MAWILE_REDUX = 2552;
  SPECIES_SABLEYE_REDUX = 2553;
  SPECIES_HOUNDOUR_REDUX = 2554;
  SPECIES_HOUNDOOM_REDUX = 2555;
  SPECIES_DODUO_REDUX = 2556;
  SPECIES_DODRIO_REDUX = 2557;
  SPECIES_KINGAMBIT_REDUX = 2558;
  SPECIES_LARVITAR_REDUX = 2559;
  SPECIES_PUPITAR_REDUX = 2560;
  SPECIES_TYRANITAR_REDUX = 2561;
  SPECIES_TYRANITAR_MEGA_REDUX = 2562;
  SPECIES_URSALUNA_MEGA = 2563;
  SPECIES_IRON_EXO = 2564;
  SPECIES_SCIZOR_REDUX = 2565;
  SPECIES_WOOPER_PALDEAN = 2566;
  SPECIES_BASCULIN_WHITESTRIPED = 2567;
  SPECIES_ESCARGINITE_REDUX = 2568;
  SPECIES_DRAGONITE_DELIVERY = 2569;
  SPECIES_CHIEN_PAO_MEGA = 2570;
  SPECIES_DRACOVISH_MEGA = 2571;
  SPECIES_LEDIAN_PARADOX = 2572;
  SPECIES_SNORLAX_PRIMAL = 2573;
  SPECIES_VICTINI_PRIMAL = 2574;
  SPECIES_WIGGLYTUFF_PRIMAL = 2575;
  SPECIES_FLYGON_REDUX_B = 2576;
  SPECIES_FLYGON_REDUX_B_MEGA = 2577;
  SPECIES_RIBOMBEE_REDUX = 2578;
  SPECIES_RIBOMBEE_REDUX_MEGA = 2579;
  SPECIES_WEAVILE_REDUX = 2580;
  SPECIES_WEAVILE_REDUX_MEGA = 2581;
  SPECIES_ABOMASNOW_SANTA = 2582;
  SPECIES_BEWEAR_ANGRY = 2583;
  SPECIES_MIMIKYU_RAYQUAZA = 2584;
  SPECIES_ESPEON_GALAXY = 2585;
  SPECIES_DARKRAI_NIGHTMARE = 2586;
  SPECIES_SOLROCK_SYSTEM = 2587;
  SPECIES_SPECTRIER_CLOUD = 2588;
  SPECIES_CALYREX_CLOUD_RIDER = 2589;
  SPECIES_MAWILE_REDUX_B = 2590;
  SPECIES_MAWILE_REDUX_B_MEGA = 2591;
  SPECIES_WIGGLYTUFF_APEX = 2592;
  SPECIES_YVELTAL_MEGA = 2593;
  SPECIES_KARTANA_FALLEN = 2594;
  SPECIES_TINKATON_MEGA = 2595;
  SPECIES_TURTWIG_REDUX = 2596;
  SPECIES_GROTLE_REDUX = 2597;
  SPECIES_TORTERRA_REDUX = 2598;
  SPECIES_CHIMCHAR_REDUX = 2599;
  SPECIES_MONFERNO_REDUX = 2600;
  SPECIES_INFERNAPE_REDUX = 2601;
  SPECIES_PIPLUP_REDUX = 2602;
  SPECIES_PRINPLUP_REDUX = 2603;
  SPECIES_EMPOLEON_REDUX = 2604;
  SPECIES_BOUNSWEET_REDUX = 2605;
  SPECIES_STEENEE_REDUX = 2606;
  SPECIES_TSAREENA_REDUX = 2607;
  SPECIES_TOXEL_REDUX = 2608;
  SPECIES_TOXTRICITY_REDUX = 2609;
  SPECIES_TOXTRICITY_REDUX_FUZZ = 2610;
  SPECIES_TRAPINCH_REDUX = 2611;
  SPECIES_VIBRAVA_REDUX = 2612;
  SPECIES_FLYGON_REDUX = 2613;
  SPECIES_CRABRAWLER_REDUX = 2614;
  SPECIES_CRABOMINABLE_REDUX = 2615;
  SPECIES_CLEFFA_REDUX = 2616;
  SPECIES_CLEFAIRY_REDUX = 2617;
  SPECIES_CLEFABLE_REDUX = 2618;
  SPECIES_GLIGAR_REDUX = 2619;
  SPECIES_GLISCOR_REDUX = 2620;
  SPECIES_PSYDUCK_REDUX = 2621;
  SPECIES_SEEL_REDUX = 2622;
  SPECIES_DEWGONG_REDUX = 2623;
  SPECIES_SNORUNT_REDUX = 2624;
  SPECIES_GLALIE_REDUX = 2625;
  SPECIES_FROSLASS_REDUX = 2626;
  SPECIES_DARUMAKA_REDUX = 2627;
  SPECIES_DARMANITAN_REDUX = 2628;
  SPECIES_DARMANITAN_REDUX_AURA = 2629;
  SPECIES_DARMANITAN_REDUX_BOND = 2630;
  SPECIES_HAPPINY_REDUX = 2631;
  SPECIES_CHANSEY_REDUX = 2632;
  SPECIES_BLISSEY_REDUX = 2633;
  SPECIES_SPIRITOMB_REDUX = 2634;
  SPECIES_DARMANITAN_REDUX_BLUNDER = 2635;
  SPECIES_DEWPIDER_REDUX = 2636;
  SPECIES_ARAQUANID_REDUX = 2637;
  SPECIES_MIMIKYU_APEX = 2638;
  SPECIES_MIMIKYU_APEX_BUSTED = 2639;
  SPECIES_TOXAPEX_MEGA = 1077;
  SPECIES_DUDUDUNSPARCE = 1078;
  SPECIES_DUDUDUNSPARCE_MEGA = 1079;
  SPECIES_OGERPON_MEGA = 1080;
  SPECIES_OGERPON_HEARTHFLAME_MASK_MEGA = 1081;
  SPECIES_OGERPON_CORNERSTONE_MASK_MEGA = 1082;
  SPECIES_OGERPON_WELLSPRING_MASK_MEGA = 1083;
  SPECIES_SEERKAT = 1084;
  SPECIES_TENTAGREWL = 1085;
  SPECIES_CACJACK = 1086;
  SPECIES_TYRANJOULA = 1087;
  SPECIES_JAGGED_CHUNGULIS = 1088;
  SPECIES_TINKATINK_REDUX = 2640;
  SPECIES_TINKATUFF_REDUX = 2641;
  SPECIES_TINKATON_REDUX = 2642;
  SPECIES_TINKATON_REDUX_MEGA = 2643;
  SPECIES_KNAIVER_REDUX = 2644;
  SPECIES_SCYTHER_REDUX = 2645;
  SPECIES_SCYTHER_REDUX_MEGA = 2646;
  SPECIES_SCIZOR_REDUX_MEGA = 2647;
  SPECIES_KLEAVOR_REDUX = 2648;
  SPECIES_KLEAVOR_REDUX_MEGA = 2649;
  SPECIES_KRABBY_REDUX = 2650;
  SPECIES_KINGLER_REDUX = 2651;
  SPECIES_KINGLER_REDUX_MEGA = 2652;
  SPECIES_SHINX_REDUX = 2653;
  SPECIES_LUXIO_REDUX = 2654;
  SPECIES_LUXRAY_REDUX_B = 2655;
  SPECIES_LUXRAY_REDUX_B_MEGA = 2656;
  SPECIES_ARON_REDUX = 2657;
  SPECIES_LAIRON_REDUX = 2658;
  SPECIES_AGGRON_REDUX = 2659;
  SPECIES_AGGRON_REDUX_MEGA = 2660;
  SPECIES_MAKUHITA_REDUX = 2661;
  SPECIES_HARIYAMA_REDUX = 2662;
  SPECIES_KILOZUNA = 2663;
  SPECIES_KILOZUNA_MEGA = 2664;
  SPECIES_FOGGING = 2665;
  SPECIES_BREEZING = 2666;
  SPECIES_STORMING = 2667;
  SPECIES_RALTS_REDUX = 2668;
  SPECIES_KIRLIA_REDUX = 2669;
  SPECIES_GARDEVOIR_REDUX = 2670;
  SPECIES_GALLADE_REDUX = 2671;
  SPECIES_GARDEVOIR_REDUX_MEGA = 2672;
  SPECIES_GALLADE_REDUX_MEGA = 2673;
  SPECIES_MERRYKARP = 2674;
  SPECIES_GYAREVALRY = 2675;
  SPECIES_MUNCHLAX_REDUX = 2676;
  SPECIES_SNORLAX_REDUX = 2677;
  SPECIES_SNORLAX_REDUX_MEGA = 2678;
  SPECIES_CLODSIRE_MEGA = 2232;
  SPECIES_GOTHITELLE_MEGA = 2233;
  SPECIES_ARCANINE_HISUIAN_MEGA = 2234;
  SPECIES_REUNICLUS_MEGA = 2235;
  SPECIES_KIPMODO = 2236;
  SPECIES_MARSHMODO = 2237;
  SPECIES_SWAMPAGE = 2238;
  SPECIES_SWAMPAGE_MEGA = 2239;
  SPECIES_CHANDELURE_MEGA = 2240;
  SPECIES_SLATE = 2900;
  SPECIES_EGG = 2901;
}