# proto-file: TrainerBattleSkillList.proto
# proto-message: er.TrainerBattleSkillList

# Made this a separate file rather than adding to the TrainerList protos for
# ease of editing and separation of concerns, but can change in future maybe

# ==== Route 103 Rival Fight ====
trainer_skill {
    trainer_id: TRAINER_BRENDAN_ROUTE_103_MUDKIP
    skill {
        skill_id: SKILL_EVIOLITE
        target { all {} }
    }
}
trainer_skill {
    trainer_id: TRAINER_BRENDAN_ROUTE_103_TORCHIC
    skill {
        skill_id: SKILL_EVIOLITE
        target { all {} }
    }
}
trainer_skill {
    trainer_id: TRAINER_BRENDAN_ROUTE_103_TREECKO
    skill {
        skill_id: SKILL_EVIOLITE
        target { all {} }
    }
}
trainer_skill {
    trainer_id: TRAINER_MAY_ROUTE_103_MUDKIP
    skill {
        skill_id: SKILL_EVIOLITE
        target { all {} }
    }
}
trainer_skill {
    trainer_id: TRAINER_MAY_ROUTE_103_TORCHIC
    skill {
        skill_id: SKILL_EVIOLITE
        target { all {} }
    }
}
trainer_skill {
    trainer_id: TRAINER_MAY_ROUTE_103_TREECKO
    skill {
        skill_id: SKILL_EVIOLITE
        target { all {} }
    }
}
# ==== Route 102 ====
trainer_skill {
    trainer_id: TRAINER_CALVIN_1
    skill {
        skill_id: SKILL_NONE
        target { all {} }
    }
}
trainer_skill {
    trainer_id: TRAINER_RICK
    skill {
        skill_id: SKILL_PERMANENT_STICKY_WEB
        target { all {} }
    }
}
trainer_skill {
    trainer_id: TRAINER_ALLEN
    skill {
        skill_id: SKILL_SPIKES_1_LAYER
        target { all {} }
    }
}
trainer_skill {
    trainer_id: TRAINER_TIANA
    skill {
        skill_id: SKILL_ON_ENTRY_LEECH_SEED
        target { all {} }
    }
}
# ==== Route 104 (South of Petalburg Woods) ====
trainer_skill {
    trainer_id: TRAINER_BILLY
    skill {
        skill_id: SKILL_EXTRA_ABILITY_UNNERVE
        target { all {} }
    }
}
trainer_skill {
    trainer_id: TRAINER_DARIAN
    skill {
        skill_id: SKILL_EXTRA_ABILITY_INNARDS_OUT
        target { all {} }
    }
}
trainer_skill {
    trainer_id: TRAINER_CINDY_1
    skill {
        skill_id: SKILL_EXTRA_ABILITY_CUTE_CHARM
        target { all {} }
    }
}
# ==== Petalburg Woods ====
trainer_skill {
    trainer_id: TRAINER_JAMES_1
    skill {
        skill_id: SKILL_TOXIC_SPIKES_2_LAYERS
        target { all {} }
    }
}
trainer_skill {
    trainer_id: TRAINER_GRUNT_PETALBURG_WOODS
    skill {
        skill_id: SKILL_EXTRA_ABILITY_FILTER
        target { all {} }
    }
}
trainer_skill {
    trainer_id: TRAINER_LYLE
    skill {
        skill_id: SKILL_EXTRA_ABILITY_SWORD_OF_RUIN
        target { all {} }
    }
}
trainer_skill {
    trainer_id: TRAINER_BANEFUL_PETALBURG_WOODS
    skill {
        skill_id: SKILL_HAZARDS_ALL
        target { all {} }
    }
    skill {
        skill_id: SKILL_ON_END_TURN_MOVE_JUDGEMENT_60_BP
        target { all {} }
    }
    skill {
        skill_id: SKILL_EXTRA_ABILITY_SWARM
        target { all {} }
    }
}
# ==== Route 104 (North of Petalburg Woods) ====
trainer_skill {
    trainer_id: TRAINER_IVAN
    skill {
        skill_id: SKILL_EXTRA_ABILITY_SUPER_LUCK
        target { all {} }
    }
}
trainer_skill {
    trainer_id: TRAINER_WINSTON_1
    skill {
        # Says "A mon switches", not sure if this is any mon switching or only when player or trainer mon switches
        skill_id: SKILL_ON_SWITCH_MOVE_PAYDAY
        target { all {} }
    }
}
trainer_skill {
    trainer_id: TRAINER_GINA_AND_MIA_1
    skill {
        skill_id: SKILL_EXTRA_ABILITY_FLASH_FIRE
        target { all {} }
    }
}
trainer_skill {
    trainer_id: TRAINER_HALEY_1
    skill {
        skill_id: SKILL_NO_CRIT
        target { all {} }
    }
}
trainer_skill {
    trainer_id: TRAINER_HALEY_1
    skill {
        skill_id: SKILL_NO_CRIT
        target { all {} }
    }
}
# ==== Rustboro Gym ====
trainer_skill {
    trainer_id: TRAINER_JOSH
    # Skill description in doc says "+4 Def on entry for the lead & +1 Def every turn",
    # not sure if +1 Def is only for lead or not
    skill {
        skill_id: SKILL_ON_ENTRY_DEF_UP_4
        target { first_n { n: 1 } }
    }
    skill {
        skill_id: SKILL_ON_END_TURN_DEF_UP_1
        target { first_n { n: 1 } }
    }
}
trainer_skill {
    trainer_id: TRAINER_TOMMY
    skill {
        skill_id: SKILL_STEALTH_ROCKS
        target { all {} }
    }
    skill {
        skill_id: SKILL_PLAYER_BLEED
        target { last_n { n: 2 } }
    }
}
trainer_skill {
    trainer_id: TRAINER_MARC
    skill {
        skill_id: SKILL_ON_ENTRY_OMNIBOOST_2
        target { last_n { n: 2 } }
    }
}
trainer_skill {
    trainer_id: TRAINER_ROXANNE_1
    skill {
        skill_id: SKILL_LEFTOVERS
        target { all {} }
    }
    skill {
        skill_id: SKILL_EXTRA_ABILITY_PRESSURE
        target { all {} }
    }
    skill {
        skill_id: SKILL_ON_END_TURN_HEAL_STATUS_30_PERCENT
        target { all {} }
    }
}
# ==== Route 116 ====
trainer_skill {
    trainer_id: TRAINER_JOSE
    skill {
        skill_id: SKILL_EXTRA_ABILITY_SHIELD_DUST
        target { all {} }
    }
}
trainer_skill {
    trainer_id: TRAINER_JOSE
    skill {
        skill_id: SKILL_BURN_BOTH_SIDES
        target { first_n { n: 3 } }
        target { last_n { n: 3 } }
    }
}
trainer_skill {
    trainer_id: TRAINER_JERRY_1
    skill {
        skill_id: SKILL_ON_ENTRY_SPDEF_UP_1
        target { all {} }
    }
}
trainer_skill {
    trainer_id: TRAINER_DAWSON
    skill {
        skill_id: SKILL_PERMANENT_SUN
        target { all {} }
    }
}
trainer_skill {
    trainer_id: TRAINER_SARAH
    skill {
        skill_id: SKILL_PERMANENT_INVERSE_ROOM
        target { all {} }
    }
}
trainer_skill {
    trainer_id: TRAINER_CLARK
    skill {
        skill_id: SKILL_EVIOLITE
        target { all {} }
    }
}
trainer_skill {
    trainer_id: TRAINER_JANICE
    skill {
        skill_id: SKILL_FOCUS_SASH
        target { all {} }
    }
}
trainer_skill {
    trainer_id: TRAINER_KAREN_1
    skill {
        skill_id: SKILL_STICKY_WEB_BOTH_SIDES
        target { all {} }
    }
}
trainer_skill {
    trainer_id: TRAINER_JOHNSON
    skill {
        skill_id: SKILL_PERMANENT_RAINBOW
        target { all {} }
    }
}
trainer_skill {
    trainer_id: TRAINER_DEVAN
    skill {
        skill_id: SKILL_PERMANENT_SANDSTORM
        target { all {} }
    }
}
trainer_skill {
    trainer_id: TRAINER_NIDO_MEGAS_ROUTE116_RUSTURF
    skill {
        skill_id: SKILL_ON_END_TURN_MOVE_TICKLE
        target { all {} }
    }
    skill {
        skill_id: SKILL_EXTRA_ABILITY_EMPERORS_WRATH
        target { all {} }
    }
    skill {
        skill_id: SKILL_ON_FAINT_TAILWIND
        target { all {} }
    }
}
# ==== Rusturf Tunnel ====
trainer_skill {
    trainer_id: TRAINER_GRUNT_RUSTURF_TUNNEL
    skill {
        skill_id: SKILL_EXTRA_ABILITY_SMOKEY_MANEUVERS
        target { all {} }
    }
}
trainer_skill {
    trainer_id: TRAINER_MIKE_2
    skill {
        skill_id: SKILL_ON_ENTRY_POWER_TRICK_BOTH_SIDES
        target { all {} }
    }
}
# ==== Rustboro City Rival Fight ====
trainer_skill {
    trainer_id: TRAINER_BRENDAN_RUSTBORO_TREECKO
    skill {
        skill_id: SKILL_FOCUS_SASH
        target { all {} }
    }
}
trainer_skill {
    trainer_id: TRAINER_BRENDAN_RUSTBORO_TORCHIC
    skill {
        skill_id: SKILL_FOCUS_SASH
        target { all {} }
    }
}
trainer_skill {
    trainer_id: TRAINER_BRENDAN_RUSTBORO_MUDKIP
    skill {
        skill_id: SKILL_FOCUS_SASH
        target { all {} }
    }
}
trainer_skill {
    trainer_id: TRAINER_MAY_RUSTBORO_TREECKO
    skill {
        skill_id: SKILL_FOCUS_SASH
        target { all {} }
    }
}
trainer_skill {
    trainer_id: TRAINER_MAY_RUSTBORO_TORCHIC
    skill {
        skill_id: SKILL_FOCUS_SASH
        target { all {} }
    }
}
trainer_skill {
    trainer_id: TRAINER_MAY_RUSTBORO_MUDKIP
    skill {
        skill_id: SKILL_FOCUS_SASH
        target { all {} }
    }
}
# ==== Route 105 ====
trainer_skill {
    trainer_id: TRAINER_IMANI
    skill {
        skill_id: SKILL_EXTRA_ABILITY_COMATOSE
        target { all {} }
    }
    skill {
        skill_id: SKILL_EXTRA_ABILITY_SWEET_DREAMS
        target { all {} }
    }
    skill {
        skill_id: SKILL_ON_HIT_DEFENDER_SLEEP_ATTACKER
        target { all {} }
    }
}
trainer_skill {
    trainer_id: TRAINER_DOMINIK
    skill {
        skill_id: SKILL_PERMANENT_SUN
        target { all {} }
    }
    skill {
        skill_id: SKILL_EXTRA_ABILITY_CATASTROPHE
        target { all {} }
    }
    skill {
        skill_id: SKILL_EXTRA_ABILITY_SUN_WORSHIP
        target { all {} }
    }
}
trainer_skill {
    trainer_id: TRAINER_FOSTER
    skill {
        skill_id: SKILL_EXTRA_ABILITY_ACCELERATE
        target { all {} }
    }
    skill {
        skill_id: SKILL_EXTRA_ABILITY_ANALYTIC
        target { all {} }
    }
    skill {
        skill_id: SKILL_ON_ENTRY_OMNIBOOST_1
        target { last_n { n: 1 } }
    }
}
trainer_skill {
    trainer_id: TRAINER_BEVERLY
    skill {
        skill_id: SKILL_DOUBLE_POWER_WATER
        target { all {} }
    }
    skill {
        skill_id: SKILL_PLAYER_SUPPRESS_ABILITIES_AFTER_2_TURNS
        target { all {} }
    }
    skill {
        skill_id: SKILL_HALF_HP_SPEED_UP_1
        target { all {} }
    }
}
trainer_skill {
    trainer_id: TRAINER_JOSUE
    skill {
        skill_id: SKILL_PERMANENT_RAINBOW
        target { all {} }
    }
    skill {
        skill_id: SKILL_ALLY_SHARE_STAT_CHANGES
        target { all {} }
    }
    skill {
        # This was intended to be pre-nerf Friend Guard I assume?
        skill_id: SKILL_ALLY_50_PERCENT_DAMAGE_REDUCTION
        target { all {} }
    }
}
trainer_skill {
    trainer_id: TRAINER_LUIS
    skill {
        skill_id: SKILL_DOUBLE_POWER_FIGHTING
        target { all {} }
    }
    skill {
        skill_id: SKILL_SPDEF_DEF_UP_4
        target { last_n { n: 1 } }
    }
    skill {
        skill_id: SKILL_EXTRA_ABILITY_KNOW_YOUR_PLACE
        target { all {} }
    }
}
trainer_skill {
    trainer_id: TRAINER_ANDRES_1
    skill {
        skill_id: SKILL_FOLLOWUP_MOVE_PEBBLE_SHOWER
        target { all {} }
    }
    skill {
        skill_id: SKILL_ON_END_TURN_MOVE_ANCIENT_POWER
        target { all {} }
    }
    skill {
        skill_id: SKILL_ON_CONTACT_DEFENDER_SPEED_UP_2
        target { all {} }
    }
}
trainer_skill {
    trainer_id: TRAINER_FERALIGATRITEX_ROUTE105
    skill {
        skill_id: SKILL_PERMANENT_SWAMP
        target { all {} }
    }
    skill {
        skill_id: SKILL_SUPER_EFFECTIVE_50_PERCENT_DAMAGE_REDUCTION
        target { all {} }
    }
    skill {
        skill_id: SKILL_ON_KO_HEAL_50_PERCENT_HP
        target { all {} }
    }
}
# ==== Route 106 ====
trainer_skill {
    trainer_id: TRAINER_ELLIOT_1
    skill {
        skill_id: SKILL_ON_ENTRY_MOVE_MEAN_LOOK
        target { all {} }
    }
}
trainer_skill {
    trainer_id: TRAINER_NED
    skill {
        skill_id: SKILL_PERMANENT_RAIN
        target { all {} }
    }
}
trainer_skill {
    trainer_id: TRAINER_DOUGLAS
    skill {
        skill_id: SKILL_ON_END_TURN_MOVE_RECYCLE
        target { all {} }
    }
    skill {
        skill_id: SKILL_EXTRA_ABILITY_STICKY_HOLD
        target { all {} }
    }
}
trainer_skill {
    trainer_id: TRAINER_KYLA
    skill {
        skill_id: SKILL_PERMANENT_HAZARDS
        target { all {} }
    }
    skill {
        skill_id: SKILL_EXTRA_ABILITY_MYSTIC_POWER
        target { all {} }
    }
}
# ==== Granite Cave ====
trainer_skill {
    trainer_id: TRAINER_STEVEN_GRANITE_CAVE
    skill {
        skill_id: SKILL_PERMANENT_PRIMORDIAL_SEA
        target { all {} }
    }
}
# TODO: Steven Stone Post-Brawly (not sure what the trainer ID is)
# TODO: Trainer Hitmonstone (not sure what the trainer ID is, not sure how to implement the 3v6)
# ==== Route 107 ====
trainer_skill {
    trainer_id: TRAINER_DENISE
    skill {
        skill_id: SKILL_ROOM_ROULETTE
        target { all {} }
    }
}
trainer_skill {
    trainer_id: TRAINER_TONY_1
    skill {
        skill_id: SKILL_FOLLOWUP_MOVE_NIGHT_SHADE
        target { all {} }
    }
    skill {
        skill_id: SKILL_PERMANENT_RAIN
        target { all {} }
    }
    skill {
        skill_id: SKILL_ON_END_EVERY_2_TURNS_MOVE_WATER_PLEDGE
        target { all {} }
    }
}
trainer_skill {
    trainer_id: TRAINER_BETH
    skill {
        skill_id: SKILL_PERMANENT_MIST
        target { all {} }
    }
    skill {
        skill_id: SKILL_ON_ENTRY_MOVE_MAGNET_RISE
        target { all {} }
    }
    skill {
        skill_id: SKILL_EXPERT_BELT
        target { all {} }
    }
}
trainer_skill {
    trainer_id: TRAINER_CAMRON
    skill {
        skill_id: SKILL_QUICK_CLAW_100_PERCENT
        target { all {} }
    }
    skill {
        skill_id: SKILL_STAB_MOVES_ARE_STATUS_MOVES
        target { all {} }
    }
    skill {
        # Should this be 1/16 instead?
        skill_id: SKILL_ON_END_TURN_PLAYER_DAMAGE_ONE_EIGHTEENTH
        target { all {} }
    }
}
trainer_skill {
    trainer_id: TRAINER_DARRIN
    skill {
        skill_id: SKILL_ON_END_TURN_MOVE_REFRESH
        target { all {} }
    }
    skill {
        skill_id: SKILL_ON_START_TURN_BADLY_POISON_BOTH_SIDES
        target { all {} }
    }
    skill {
        skill_id: SKILL_ON_ENTRY_PLAYER_HEAL_BLOCK
        target { all {} }
    }
}
trainer_skill {
    trainer_id: TRAINER_LISA_AND_RAY
    skill {
        skill_id: SKILL_ON_PLAYER_STAT_BOOSTING_MOVE_MOVE_SCRATCH
        target { all {} }
    }
    skill {
        skill_id: SKILL_COPY_DANCE_MOVES_BOTH_SIDES
        target { all {} }
    }
    skill {
        skill_id: SKILL_PLAYER_RING_TARGET
        target { all {} }
    }
}
# ==== Route 108 ====
trainer_skill {
    trainer_id: TRAINER_MATTHEW
    skill {
        skill_id: SKILL_EXTRA_ABILITY_COMATOSE
        target { all {} }
    }
    skill {
        skill_id: SKILL_PLAYER_SUPPRESS_ABILITIES
        target { all {} }
    }
    skill {
        skill_id: SKILL_PERMANENT_TAILWIND
        target { all {} }
    }
}
trainer_skill {
    trainer_id: TRAINER_TARA
    skill {
        skill_id: SKILL_PLAYER_SALT_CURE_AND_CURSE
        target { all {} }
    }
    skill {
        skill_id: SKILL_PLAYER_ACCURATE_MOVE_25_PERCENT_LOWER_ACCURACY
        target { all {} }
    }
    skill {
        skill_id: SKILL_PLAYER_TORMENT
        target { all {} }
    }
}
trainer_skill {
    trainer_id: TRAINER_CAROLINA
    skill {
        skill_id: SKILL_NO_ITEM_50_PERCENT_DAMAGE_BOOST
        target { all {} }
    }
    skill {
        skill_id: SKILL_ON_SWITCH_RECOVER_ITEM
        target { all {} }
    }
    skill {
        skill_id: SKILL_ON_USE_ITEM_DOUBLE_SPEED
        target { all {} }
    }
}
trainer_skill {
    trainer_id: TRAINER_JEROME
    skill {
        skill_id: SKILL_PERMANENT_ELECTRIC_TERRAIN
        target { all {} }
    }
    skill {
        skill_id: SKILL_PERMANENT_PRIMORDIAL_SEA
        target { all {} }
    }
    skill {
        skill_id: SKILL_ELECTRIC_SUPER_EFFECTIVE_ON_GROUND
        target { all {} }
    }
}
trainer_skill {
    trainer_id: TRAINER_MISSY
    skill {
        skill_id: SKILL_STAT_INCREASES_DOUBLED
        target { all {} }
    }
    skill {
        skill_id: SKILL_STAT_DECREASES_RESTORED_INSTANTLY
        target { all {} }
    }
    skill {
        skill_id: SKILL_HIT_LOWEST_DEF
        target { all {} }
    }
}
trainer_skill {
    trainer_id: TRAINER_CORY_1
    skill {
        skill_id: SKILL_PERMANENT_SWAMP
        target { all {} }
    }
    skill {
        skill_id: SKILL_FIRST_PLAYER_SUPER_EFFECTIVE_IMMUNE_UP_OFFENSE_1
        target { all {} }
    }
    skill {
        skill_id: SKILL_RED_CARD
        target { all {} }
    }
}
# ==== Route 108 Abandoned Ship ====
trainer_skill {
    trainer_id: TRAINER_THALIA_1
    skill {
        skill_id: SKILL_EXTRA_ABILITY_PURE_LOVE
        target { all {} }
    }
    skill {
        skill_id: SKILL_ON_HIT_DEFENDER_MOVE_SWEET_KISS
        target { all {} }
    }
    skill {
        skill_id: SKILL_EXTRA_ABILITY_PIXIE_POWER
        target { all {} }
    }
}
trainer_skill {
    trainer_id: TRAINER_DEMETRIUS
    skill {
        skill_id: SKILL_EXTRA_ABILITY_ANGELS_WRATH
        target { all {} }
    }
    skill {
        skill_id: SKILL_25_PERCENT_DAMAGE_BOOST_AND_HIT_LOWEST_DEF_VS_STATUSED
        target { all {} }
    }
    skill {
        skill_id: SKILL_STATUS_MOVES_IGNORE_ABILITIES
        target { all {} }
    }
}
trainer_skill {
    trainer_id: TRAINER_DUNCAN
    skill {
        skill_id: SKILL_BADLY_POISON_BOTH_SIDES
        target { all {} }
    }
    skill {
        skill_id: SKILL_EXTRA_ABILITY_POISON_HEAL
        target { all {} }
    }
    skill {
        skill_id: SKILL_ON_SWITCH_PLAYER_MOVE_ANCHOR_SHOT
        target { all {} }
    }
}
trainer_skill {
    trainer_id: TRAINER_CHARLIE
    skill {
        skill_id: SKILL_ON_END_EVERY_2_TURNS_MOVE_WHIRLWIND
        target { all {} }
    }
    skill {
        skill_id: SKILL_EXTRA_ABILITY_COSMIC_DAZE
        target { all {} }
    }
    skill {
        skill_id: SKILL_ON_ENTRY_PLAYER_MOVE_CONFUSE_RAY
        target { all {} }
    }
}
trainer_skill {
    trainer_id: TRAINER_GARRISON
    skill {
        skill_id: SKILL_EXTRA_ABILITY_BONE_ZONE
        target { all {} }
    }
    skill {
        skill_id: SKILL_ALL_MOVES_ARE_BONE_MOVES
        target { all {} }
    }
    skill {
        skill_id: SKILL_EXTRA_ABILITY_HAUNTING_FRENZY
        target { all {} }
    }
}
trainer_skill {
    trainer_id: TRAINER_JANI
    skill {
        skill_id: SKILL_ON_FAINT_MOVE_EXPLOSION_OR_OUTBURST_50_BP
        target { all {} }
    }
    skill {
        skill_id: SKILL_EXTRA_ABILITY_INFLATABLE
        target { all {} }
    }
    skill {
        skill_id: SKILL_RED_CARD
        target { all {} }
    }
    skill {
        skill_id: SKILL_EXTRA_ABILITY_LEVITATE
        target { all {} }
    }
}
trainer_skill {
    trainer_id: TRAINER_KIRA_AND_DAN_1
    skill {
        skill_id: SKILL_PERMANENT_FIRE_SEA
        target { all {} }
    }
    skill {
        skill_id: SKILL_ON_END_EVERY_2_TURNS_MOVE_BURNING_JEALOUSY
        target { all {} }
    }
    skill {
        skill_id: SKILL_ON_FAINT_MOVE_RAGE_FIST
        target { all {} }
    }
}
trainer_skill {
    trainer_id: TRAINER_SHEDINJITE_ABANDONED_SHIP
    skill {
        skill_id: SKILL_ON_ENTRY_SUBSTITUTE
        target { all {} }
    }
    skill {
        skill_id: SKILL_HEAVY_DUTY_BOOTS
        target { all {} }
    }
    skill {
        skill_id: SKILL_EXTRA_ABILITY_TERA_SHELL
        target { all {} }
    }
}
# ==== Route 109 ====
trainer_skill {
    trainer_id: TRAINER_LOLA_1
    skill {
        skill_id: SKILL_EXTRA_ABILITY_COMATOSE
        target { all {} }
    }
}
trainer_skill {
    trainer_id: TRAINER_CHANDLER
    skill {
        skill_id: SKILL_STEALTH_ROCKS
        target { all {} }
    }
}
trainer_skill {
    trainer_id: TRAINER_ELIJAH
    skill {
        skill_id: SKILL_EXTRA_ABILITY_MOUNTAINEER
        target { all {} }
    }
}
trainer_skill {
    trainer_id: TRAINER_CARTER
    skill {
        # description says "uses substitute on switch in", surely it's ok to just give it a substitute instead of using the move
        skill_id: SKILL_ON_ENTRY_SUBSTITUTE
        target { all {} }
    }
}
trainer_skill {
    trainer_id: TRAINER_GWEN
    skill {
        skill_id: SKILL_PERMANENT_SUN
        target { all {} }
    }
}
trainer_skill {
    trainer_id: TRAINER_AUSTINA
    skill {
        skill_id: SKILL_EXTRA_ABILITY_TECHNICIAN
        target { all {} }
    }
}
trainer_skill {
    trainer_id: TRAINER_EDMOND
    skill {
        skill_id: SKILL_ON_ENTRY_MOVE_BUBBLE_10_BP
        target { all {} }
    }
}
trainer_skill {
    trainer_id: TRAINER_HUEY
    skill {
        skill_id: SKILL_TRAINER_FROSTBITE
        target { all {} }
    }
}
trainer_skill {
    trainer_id: TRAINER_HAILEY
    skill {
        skill_id: SKILL_FOCUS_BAND_30_PERCENT
        target { all {} }
    }
}
trainer_skill {
    trainer_id: TRAINER_RICKY_1
    skill {
        skill_id: SKILL_PLAYER_SOAK
        target { all {} }
    }
}
trainer_skill {
    trainer_id: TRAINER_MEL_AND_PAUL
    skill {
        skill_id: SKILL_EXTRA_ABILITY_VOLT_ABSORB
        target { all {} }
    }
    skill {
        skill_id: SKILL_EXTRA_ABILITY_WATER_ABSORB
        target { all {} }
    }
}
trainer_skill {
    trainer_id: TRAINER_ALICE
    skill {
        skill_id: SKILL_PLAYER_LEECH_SEED
        target { all {} }
    }
    skill {
        skill_id: SKILL_LEFTOVERS
        target { all {} }
    }
}
trainer_skill {
    trainer_id: TRAINER_DAVID
    skill {
        skill_id: SKILL_EXTRA_ABILITY_REGENERATOR
        target { all {} }
    }
    skill {
        skill_id: SKILL_ON_END_EVERY_2_TURNS_MOVE_TELEPORT
        target { all {} }
    }
}
# ==== Route 109 Seahouse ====
# TODO: Trainer Simon (what is the "old" mud sport effect?)
trainer_skill {
    trainer_id: TRAINER_JOHANNA
    skill {
        skill_id: SKILL_EXTRA_ABILITY_CUTE_CHARM
        target { all {} }
    }
}
trainer_skill {
    trainer_id: TRAINER_DWAYNE
    skill {
        skill_id: SKILL_EXTRA_ABILITY_MERCILESS
        target { all {} }
    }
}
# ==== DEWFORD MANOR ====
trainer_skill {
    trainer_id: TRAINER_CROBATITE_DEWFORD_MANOR
    skill {
        skill_id: SKILL_SPEED_FOR_DAMAGE_CALC
        target { all {} }
    }
    skill {
        skill_id: SKILL_EXTRA_ABILITY_PLAYER_NORMALIZE
        target { all {} }
    }
    skill {
        # could also use Trickster ability
        skill_id: SKILL_ON_ENTRY_MOVE_DISABLE
        target { all {} }
    }
}
# ==== Dewford Gym ====
trainer_skill {
    trainer_id: TRAINER_TAKAO
    skill {
        skill_id: SKILL_FROSTBITE_BOTH_SIDES
        target { all {} }
    }
}
trainer_skill {
    trainer_id: TRAINER_LAURA
    skill {
        skill_id: SKILL_PUNCH_KICK_MOVES_50_PERCENT_DAMAGE_BOOST
        target { all {} }
    }
}
trainer_skill {
    trainer_id: TRAINER_CRISTIAN
    skill {
        skill_id: SKILL_ON_END_TURN_HIGHEST_STAT_UP_2
        target { all {} }
    }
}
trainer_skill {
    trainer_id: TRAINER_JOCELYN
    skill {
        skill_id: SKILL_EXTRA_ABILITY_SCRAPPY
        target { all {} }
    }
}
trainer_skill {
    trainer_id: TRAINER_BRENDEN
    skill {
        skill_id: SKILL_PERMANENT_RAIN
        target { all {} }
    }
}
trainer_skill {
    trainer_id: TRAINER_LILITH
    skill {
        skill_id: SKILL_ALLY_UP_SPDEF_25_PERCENT
        target { all {} }
    }
}
trainer_skill {
    trainer_id: TRAINER_BRAWLY_1
    skill {
        skill_id: SKILL_PLAYER_NO_PRIORITY_MOVES
        target { all {} }
    }
    skill {
        skill_id: SKILL_EXTRA_ABILITY_OLE
        target { all {} }
    }
    skill {
        skill_id: SKILL_BRIGHTPOWDER
        target { all {} }
    }
}
# ==== Slateport City ====
trainer_skill {
    # I'm not sure how doable these skills are, might be difficult to implement
    trainer_id: TRAINER_GRETA_SLATEPORT
    skill {
        skill_id: SKILL_PLAYER_NO_SWITCH
        target { all {} }
    }
    skill {
        skill_id: SKILL_PLAYER_FAINT_IF_NO_KO_WITHIN_3_TURNS
        target { all {} }
    }
    skill {
        skill_id: SKILL_PLAYER_POKEMON_SENT_OUT_IN_SLOT_ORDER
        target { all {} }
    }
}
# ==== Slateport Museum ====
trainer_skill {
    trainer_id: TRAINER_GRUNT_MUSEUM_1
    skill {
        skill_id: SKILL_CALTROPS
        target { all {} }
    }
}
trainer_skill {
    trainer_id: TRAINER_GRUNT_MUSEUM_2
    skill {
        skill_id: SKILL_PERMANENT_HAIL
        target { all {} }
    }
}
trainer_skill {
    trainer_id: TRAINER_ARCHIE_SLATEPORT
    skill {
        skill_id: SKILL_PERMANENT_RAIN
        target { all {} }
    }
}
# ==== Route 103 East ====
trainer_skill {
    trainer_id: TRAINER_ISABELLE
    skill {
        skill_id: SKILL_PERMANENT_PRIMORDIAL_SEA
        target { all {} }
    }
    skill {
        skill_id: SKILL_PERMANENT_SWAMP
        target { all {} }
    }
    skill {
        skill_id: SKILL_NO_ROOMS
        target { all {} }
    }
}
trainer_skill {
    trainer_id: TRAINER_PETE
    skill {
        skill_id: SKILL_PERMANENT_PRIMORDIAL_SEA
        target { all {} }
    }
    skill {
        skill_id: SKILL_EXTRA_ABILITY_SWIFT_SWIM
        target { all {} }
    }
    skill {
        skill_id: SKILL_EXTRA_ABILITY_SAP_SIPPER
        target { all {} }
    }
}
trainer_skill {
    trainer_id: TRAINER_RHETT
    skill {
        skill_id: SKILL_EXTRA_ABILITY_LONG_REACH
        target { all {} }
    }
}
trainer_skill {
    trainer_id: TRAINER_MARCOS
    skill {
        skill_id: SKILL_IGNORE_SOUNDPROOF
        target { all {} }
    }
}
trainer_skill {
    trainer_id: TRAINER_AMY_AND_LIV_1
    skill {
        skill_id: SKILL_ON_ENTRY_MOVE_LIFE_DEW
        target { all {} }
    }
}
trainer_skill {
    trainer_id: TRAINER_ANDREW
    skill {
        skill_id: SKILL_PERMANENT_RAIN
        target { all {} }
    }
}
trainer_skill {
    trainer_id: TRAINER_DAISY
    skill {
        # Originally Lax Incense but this is the same effect as BrightPowder
        skill_id: SKILL_BRIGHTPOWDER
        target { all {} }
    }
}
trainer_skill {
    trainer_id: TRAINER_MIGUEL_1
    skill {
        skill_id: SKILL_EXTRA_ABILITY_PRETTY_PRINCESS
        target { all {} }
    }
}
# ==== Altering Cave ====
trainer_skill {
    trainer_id: TRAINER_LEAF_ALTERING_CAVE
    # TODO: Player can only use Kanto mons (excluding forms)
    skill {
        skill_id: SKILL_SPDEF_FOR_SPECIAL_DAMAGE_CALC
        target { all {} }
    }
    skill {
        skill_id: SKILL_EXTRA_ABILITY_NEUTRALIZING_GAS
        target { all {} }
    }
}
# ==== Route 110 ====
trainer_skill {
    trainer_id: TRAINER_ISABEL_1
    skill {
        skill_id: SKILL_EXTRA_ABILITY_FRIEND_GUARD
        target { all {} }
    }
}
trainer_skill {
    trainer_id: TRAINER_KALEB
    skill {
        skill_id: SKILL_PLAYER_QUASH
        target { all {} }
    }
}
trainer_skill {
    trainer_id: TRAINER_TIMMY
    skill {
        skill_id: SKILL_SPIKES_1_LAYER
        target { all {} }
    }
    skill {
        skill_id: SKILL_MOVES_HEAL_200_PERCENT_DAMAGE
        target { all {} }
    }
}
trainer_skill {
    trainer_id: TRAINER_DALE
    skill {
        skill_id: SKILL_IMMUNE_TO_ELECTRIC
        target { all {} }
    }
    skill {
        skill_id: SKILL_ON_SWITCH_HELPING_HAND_BOOST
        target { all {} }
    }
}
trainer_skill {
    trainer_id: TRAINER_JOSEPH
    skill {
        skill_id: SKILL_EXTRA_ABILITY_MOLD_BREAKER
        target { all {} }
    }
}
trainer_skill {
    trainer_id: TRAINER_ALYSSA
    skill {
        skill_id: SKILL_EXTRA_ABILITY_SPEED_BOOST
        target { all {} }
    }
}
trainer_skill {
    trainer_id: TRAINER_EDWIN_1
    skill {
        skill_id: SKILL_IGNORE_IMMUNITIES
        target { all {} }
    }
}
trainer_skill {
    trainer_id: TRAINER_EDWARD
    skill {
        skill_id: SKILL_PERMANENT_TRICK_ROOM
        target { all {} }
    }
}
# ==== Route 110 Rival Fight ====
trainer_skill {
    trainer_id: TRAINER_BRENDAN_ROUTE_110_TREECKO
    skill {
        skill_id: SKILL_TRAINER_POKEMON_BENEFIT_FROM_FOG
        target { all {} }
    }
    skill {
        skill_id: SKILL_PERMANENT_FOG
        target { all {} }
    }
}
trainer_skill {
    trainer_id: TRAINER_BRENDAN_ROUTE_110_TORCHIC
    skill {
        skill_id: SKILL_TRAINER_POKEMON_BENEFIT_FROM_FOG
        target { all {} }
    }
    skill {
        skill_id: SKILL_PERMANENT_FOG
        target { all {} }
    }
}
trainer_skill {
    trainer_id: TRAINER_BRENDAN_ROUTE_110_MUDKIP
    skill {
        skill_id: SKILL_TRAINER_POKEMON_BENEFIT_FROM_FOG
        target { all {} }
    }
    skill {
        skill_id: SKILL_PERMANENT_FOG
        target { all {} }
    }
}
trainer_skill {
    trainer_id: TRAINER_MAY_ROUTE_110_TREECKO
    skill {
        skill_id: SKILL_TRAINER_POKEMON_BENEFIT_FROM_FOG
        target { all {} }
    }
    skill {
        skill_id: SKILL_PERMANENT_FOG
        target { all {} }
    }
}
trainer_skill {
    trainer_id: TRAINER_MAY_ROUTE_110_TORCHIC
    skill {
        skill_id: SKILL_TRAINER_POKEMON_BENEFIT_FROM_FOG
        target { all {} }
    }
    skill {
        skill_id: SKILL_PERMANENT_FOG
        target { all {} }
    }
}
trainer_skill {
    trainer_id: TRAINER_MAY_ROUTE_110_MUDKIP
    skill {
        skill_id: SKILL_TRAINER_POKEMON_BENEFIT_FROM_FOG
        target { all {} }
    }
    skill {
        skill_id: SKILL_PERMANENT_FOG
        target { all {} }
    }
}
# ==== Route 110 (After Rival Fight) ====
trainer_skill {
    trainer_id: TRAINER_JACLYN
    skill {
        skill_id: SKILL_EXTRA_ABILITY_GIFTED_MIND
        target { all {} }
    }
}
trainer_skill {
    trainer_id: TRAINER_ABIGAIL_1
    skill {
        skill_id: SKILL_ON_ENTRY_BOOST_ATTACK_50_PERCENT_SPEED_20_PERCENT
        target { all {} }
    }
}
trainer_skill {
    trainer_id: TRAINER_BENJAMIN_1
    # Might be better to combine these into one skill, idk
    skill {
        skill_id: SKILL_PERMANENT_ELECTRIC_TERRAIN
        target { all {} }
    }
    skill {
        skill_id: SKILL_EXTRA_ABILITY_HADRON_ENGINE
        target { all {} }
    }
}
trainer_skill {
    trainer_id: TRAINER_JACOB
    skill {
        skill_id: SKILL_EXTRA_ABILITY_GUARD_DOG
        target { all {} }
    }
}
trainer_skill {
    trainer_id: TRAINER_ANTHONY
    skill {
        skill_id: SKILL_PERMANENT_MISTY_TERRAIN
        target { all {} }
    }
}
trainer_skill {
    trainer_id: TRAINER_JASMINE
    skill {
        skill_id: SKILL_ON_ENTRY_SPEED_UP_2_CANNOT_BE_DROPPED
        target { all {} }
    }
}
# ==== Mauville City ====
trainer_skill {
    trainer_id: TRAINER_WALLY_MAUVILLE
    skill {
        skill_id: SKILL_ABILITY_SHIELD
        target { all {} }
    }
    skill {
        skill_id: SKILL_ON_ENTRY_PLAYER_ABILITY_LETHARGY
        target { all {} }
    }
}
# ==== Mauville Game Corner ====
trainer_skill {
    # 4 skills
    trainer_id: TRAINER_SINNOH_MEGAS_MAUVILLE_GAME_CORNER
    skill {
        skill_id: SKILL_IMMUNE_TO_STAT_DROPS
        target { all {} }
    }
    skill {
        skill_id: SKILL_ON_ENTRY_HIGHEST_ATTACK_UP_1
        target { all {} }
    }
    skill {
        skill_id: SKILL_MOVES_NEVER_MISS
        target { all {} }
    }
    skill {
        skill_id: SKILL_NO_ROOMS
        target { all {} }
    }
}
# ==== Route 111 South (pre-Wattson) ====
trainer_skill {
    trainer_id: TRAINER_BIANCA
    skill {
        skill_id: SKILL_CRIT_OHKO
        target { all {} }
    }
}
trainer_skill {
    trainer_id: TRAINER_CELINA
    skill {
        skill_id: SKILL_PLAYER_30_PERCENT_MISS_CHANCE
        target { all {} }
    }
}
trainer_skill {
    trainer_id: TRAINER_HAYDEN
    skill {
        skill_id: SKILL_PERMANENT_SUN
        target { all {} }
    }
}
trainer_skill {
    trainer_id: TRAINER_TYRON
    skill {
        skill_id: SKILL_EXTRA_ABILITY_FLOWER_GIFT_ONLY_USER
        target { all {} }
    }
}
# ==== (post Winona) ====
trainer_skill {
    trainer_id: TRAINER_VICTOR
    skill {
        skill_id: SKILL_PERMANENT_SANDSTORM
        target { all {} }
    }
    skill {
        skill_id: SKILL_LEFTOVERS
        target { all {} }
    }
    skill {
        skill_id: SKILL_EXTRA_ABILITY_INNER_FOCUS
        target { all {} }
    }
}
trainer_skill {
    trainer_id: TRAINER_VICTORIA
    skill {
        skill_id: SKILL_EXTRA_ABILITY_GRASS_PELT
        target { all {} }
    }
    skill {
        skill_id: SKILL_EXTRA_ABILITY_FLOURISH
        target { all {} }
    }
    skill {
        skill_id: SKILL_EXTRA_ABILITY_SELF_SUFFICIENT
        target { all {} }
    }
}
trainer_skill {
    trainer_id: TRAINER_VIVI
    skill {
        skill_id: SKILL_PERMANENT_TOXIC_TERRAIN
        target { all {} }
    }
    skill {
        skill_id: SKILL_EXTRA_ABILITY_BIOFILM
        target { all {} }
    }
    skill {
        skill_id: SKILL_EXTRA_ABILITY_POISON_ABSORB
        target { all {} }
    }
}
trainer_skill {
    trainer_id: TRAINER_VICKY
    skill {
        skill_id: SKILL_PLAYER_SUPPRESS_ABILITIES
        target { all {} }
    }
    skill {
        # Doc does not specify how many layers
        skill_id: SKILL_TOXIC_SPIKES_2_LAYERS
        target { all {} }
    }
    skill {
        # Doc does not specify how many layers
        skill_id: SKILL_SPIKES_1_LAYER
        target { all {} }
    }
}
# ==== Route 118 West ====
trainer_skill {
    trainer_id: TRAINER_DEANDRE
    skill {
        skill_id: SKILL_EXTRA_ABILITY_GALLANTRY
        target { all {} }
    }
}
trainer_skill {
    # TODO: Double check this trainer's sets (Politoed Damp Rock but no Drizzle?)
    trainer_id: TRAINER_WADE
    skill {
        skill_id: SKILL_RAIN_SETS_AURORA_VEIL
        target { all {} }
    }
}
trainer_skill {
    trainer_id: TRAINER_DALTON_1
    skill {
        skill_id: SKILL_SOUND_MOVES_ALWAYS_CRIT
        target { all {} }
    }
}
trainer_skill {
    trainer_id: TRAINER_ROSE_1
    skill {
        skill_id: SKILL_ON_END_TURN_PLAYER_LOWER_HIGHEST_ATTACK
        target { all {} }
    }
}
# ==== Route 117 ====
trainer_skill {
    trainer_id: TRAINER_DEREK
    skill {
        skill_id: SKILL_EXTRA_ABILITY_TINTED_LENS
        target { all {} }
    }
}
trainer_skill {
    trainer_id: TRAINER_AISHA
    skill {
        skill_id: SKILL_EXTRA_ABILITY_HYPER_AGGRESSIVE
        target { all {} }
    }
}
trainer_skill {
    trainer_id: TRAINER_ANNA_AND_MEG_1
    skill {
        skill_id: SKILL_EXTRA_ABILITY_FRIEND_GUARD
        target { all {} }
    }
}
trainer_skill {
    trainer_id: TRAINER_DYLAN_1
    skill {
        skill_id: SKILL_EXTRA_ABILITY_MOMENTUM
        target { all {} }
    }
}
trainer_skill {
    trainer_id: TRAINER_MARIA_1
    skill {
        skill_id: SKILL_EXTRA_ABILITY_IMPULSE
        target { all {} }
    }
}
trainer_skill {
    trainer_id: TRAINER_ISAAC_1
    skill {
        skill_id: SKILL_EXTRA_ABILITY_HUBRIS
        target { all {} }
    }
}
trainer_skill {
    trainer_id: TRAINER_LYDIA_1
    skill {
        skill_id: SKILL_EXTRA_ABILITY_MOXIE
        target { all {} }
    }
}
trainer_skill {
    trainer_id: TRAINER_BRANDI
    skill {
        skill_id: SKILL_EXTRA_ABILITY_PSYCHIC_SURGE
        target { all {} }
    }
}
trainer_skill {
    trainer_id: TRAINER_MELINA
    skill {
        skill_id: SKILL_PERMANENT_TAILWIND
        target { all {} }
    }
}
# ==== Verdanturf Meadow ====
trainer_skill {
    trainer_id: TRAINER_MEGANIUMITE_VERDANTURF_MEADOW
    skill {
        skill_id: SKILL_EXTRA_ABILITY_TRIAGE
        target { all {} }
    }
    skill {
        skill_id: SKILL_EXTRA_ABILITY_DAZZLING
        target { all {} }
    }
    skill {
        skill_id: SKILL_PERMANENT_SAFEGUARD
        target { all {} }
    }
}
# ==== Mauville Gym ====
trainer_skill {
    trainer_id: TRAINER_VIVIAN
    skill {
        skill_id: SKILL_PERMANENT_ELECTRIC_TERRAIN
        target { all {} }
    }
    skill {
        skill_id: SKILL_FLOURISH_ELECTRIC_TERRAIN
        target { all {} }
    }
}
trainer_skill {
    trainer_id: TRAINER_BEN
    skill {
        skill_id: SKILL_PERMANENT_ELECTRIC_TERRAIN
        target { all {} }
    }
    skill {
        skill_id: SKILL_EXTRA_ABILITY_SURGE_SURFER
        target { all {} }
    }
}
trainer_skill {
    trainer_id: TRAINER_KIRK
    skill {
        skill_id: SKILL_PERMANENT_ELECTRIC_TERRAIN
        target { all {} }
    }
    skill {
        skill_id: SKILL_EXTRA_ABILITY_TRANSISTOR
        target { all {} }
    }
}
trainer_skill {
    trainer_id: TRAINER_SHAWN
    skill {
        skill_id: SKILL_PERMANENT_ELECTRIC_TERRAIN
        target { all {} }
    }
    skill {
        skill_id: SKILL_EXTRA_ABILITY_FRIEND_GUARD
        target { all {} }
    }
}
trainer_skill {
    trainer_id: TRAINER_ANGELO
    skill {
        skill_id: SKILL_PERMANENT_ELECTRIC_TERRAIN
        target { all {} }
    }
    skill {
        skill_id: SKILL_EXTRA_ABILITY_POWER_SPOT
        target { all {} }
    }
}
trainer_skill {
    # 4 skills because of gym-wide permanent electric terrain
    trainer_id: TRAINER_WATTSON_1
    skill {
        skill_id: SKILL_PERMANENT_ELECTRIC_TERRAIN
        target { all {} }
    }
    skill {
        skill_id: SKILL_PLAYER_PARALYSIS
        target { all {} }
    }
    skill {
        skill_id: SKILL_EXTRA_ABILITY_SURGE_SURFER
        target { all {} }
    }
    skill {
        skill_id: SKILL_NO_ROOMS
        target { all {} }
    }
}