# proto-file: ItemList.proto
# proto-message: er.ItemList

item {
  id: ITEM_EVIOLITE
  name: "Eviolite"
  description: "Raises the Def and Sp. Def of Pok\303\251mon that can evolve."
  grouping: POCKET_BATTLE
  hold_effect: HOLD_EFFECT_CUSTOM
  hold_effect_strength: 50
  image: "eviolite"
  palette: "eviolite"
  talk_to_nurse_joy: true
}
item {
  id: ITEM_LEFTOVERS
  name: "Leftovers"
  description: "A hold item that gradually restores HP in battle."
  grouping: POCKET_BATTLE
  hold_effect: HOLD_EFFECT_CUSTOM
  hold_effect_strength: 10
  image: "leftovers"
  palette: "leftovers"
  talk_to_nurse_joy: true
}
item {
  id: ITEM_BLACK_SLUDGE
  name: "Black Sludge"
  description: "Gradually restores HP of Poison-types. Damages others."
  grouping: POCKET_BATTLE
  hold_effect: HOLD_EFFECT_CUSTOM
  image: "black_sludge"
  palette: "black_sludge"
  talk_to_nurse_joy: true
}
item {
  id: ITEM_FOCUS_SASH
  name: "Focus Sash"
  description: "If the holder has full HP, it endures KO hits with 1 HP."
  grouping: POCKET_BATTLE
  hold_effect: HOLD_EFFECT_CUSTOM
  image: "focus_sash"
  palette: "focus_sash"
  talk_to_nurse_joy: true
}
item {
  id: ITEM_TOXIC_ORB
  name: "Toxic Orb"
  description: "A bizarre orb that badly poisons the holder in battle."
  grouping: POCKET_BATTLE
  hold_effect: HOLD_EFFECT_CUSTOM
  image: "toxic_orb"
  palette: "toxic_orb"
  talk_to_nurse_joy: true
}
item {
  id: ITEM_FLAME_ORB
  name: "Flame Orb"
  description: "A bizarre orb that inflicts a burn on holder in battle."
  grouping: POCKET_BATTLE
  hold_effect: HOLD_EFFECT_CUSTOM
  image: "flame_orb"
  palette: "flame_orb"
  talk_to_nurse_joy: true
}
item {
  id: ITEM_FROST_ORB
  name: "Frost Orb"
  description: "A bizarre orb that inflicts frostbite on holder in battle."
  grouping: POCKET_BATTLE
  hold_effect: HOLD_EFFECT_CUSTOM
  image: "frost_orb"
  palette: "frost_orb"
  talk_to_nurse_joy: true
}
item {
  id: ITEM_LIFE_ORB
  name: "Life Orb"
  description: "Boosts the power of moves at the cost of HP."
  grouping: POCKET_BATTLE
  hold_effect: HOLD_EFFECT_CUSTOM
  image: "life_orb"
  palette: "life_orb"
  talk_to_nurse_joy: true
}
item {
  id: ITEM_CHOICE_BAND
  name: "Choice Band"
  description: "Raises a move\'s power, but permits only that move."
  grouping: POCKET_BATTLE
  hold_effect: HOLD_EFFECT_CUSTOM
  image: "choice_band"
  palette: "choice_band"
  talk_to_nurse_joy: true
}
item {
  id: ITEM_CHOICE_SPECS
  name: "Choice Specs"
  description: "Boosts Sp. Atk, but allows the use of only one move."
  grouping: POCKET_BATTLE
  hold_effect: HOLD_EFFECT_CUSTOM
  image: "choice_specs"
  palette: "choice_specs"
  talk_to_nurse_joy: true
}
item {
  id: ITEM_CHOICE_SCARF
  name: "Choice Scarf"
  description: "Boosts Speed, but allows the use of only one move."
  grouping: POCKET_BATTLE
  hold_effect: HOLD_EFFECT_CUSTOM
  image: "choice_scarf"
  palette: "choice_scarf"
  talk_to_nurse_joy: true
}
item {
  id: ITEM_ROCKY_HELMET
  name: "Rocky Helmet"
  description: "Hurts the foe if they touch its holder."
  grouping: POCKET_BATTLE
  hold_effect: HOLD_EFFECT_CUSTOM
  image: "rocky_helmet"
  palette: "rocky_helmet"
  talk_to_nurse_joy: true
}
item {
  id: ITEM_ASSAULT_VEST
  name: "Assault Vest"
  description: "Raises Sp. Def but prevents the use of status moves."
  grouping: POCKET_BATTLE
  hold_effect: HOLD_EFFECT_CUSTOM
  hold_effect_strength: 50
  image: "assault_vest"
  palette: "assault_vest"
  talk_to_nurse_joy: true
}
item {
  id: ITEM_TACTICAL_VEST
  name: "Tactical Vest"
  description: "Raises Def but prevents the use of status moves."
  grouping: POCKET_BATTLE
  hold_effect: HOLD_EFFECT_CUSTOM
  hold_effect_strength: 50
  image: "physical_vest"
  palette: "physical_vest"
  talk_to_nurse_joy: true
}
item {
  id: ITEM_LIGHT_CLAY
  name: "Light Clay"
  description: "Extends the length of barrier moves used by the holder."
  grouping: POCKET_BATTLE
  hold_effect: HOLD_EFFECT_CUSTOM
  image: "light_clay"
  palette: "light_clay"
  talk_to_nurse_joy: true
}
item {
  id: ITEM_HEAVY_DUTY_BOOTS
  name: "Heavy-Duty Boots"
  description: "Makes the wearer immune to battle hazards."
  grouping: POCKET_BATTLE
  hold_effect: HOLD_EFFECT_CUSTOM
  image: "heavy_duty_boots"
  palette: "heavy_duty_boots"
  talk_to_nurse_joy: true
}
item {
  id: ITEM_AIR_BALLOON
  name: "Air Balloon"
  description: "Elevates the holder in the air. If hit, this item will burst."
  grouping: POCKET_BATTLE
  hold_effect: HOLD_EFFECT_CUSTOM
  image: "air_balloon"
  palette: "air_balloon"
  talk_to_nurse_joy: true
}
item {
  id: ITEM_WEAKNESS_POLICY
  name: "Weakness Policy"
  description: "If hit by a Super Effective move, ups Atk and Sp. Atk."
  grouping: POCKET_BATTLE
  hold_effect: HOLD_EFFECT_CUSTOM
  image: "weakness_policy"
  palette: "weakness_policy"
  talk_to_nurse_joy: true
}
item {
  id: ITEM_WIDE_LENS
  name: "Wide Lens"
  description: "A magnifying lens that boosts the accuracy of moves."
  grouping: POCKET_BATTLE
  hold_effect: HOLD_EFFECT_CUSTOM
  hold_effect_strength: 10
  image: "wide_lens"
  palette: "wide_lens"
  talk_to_nurse_joy: true
}
item {
  id: ITEM_DAMP_ROCK
  name: "Damp Rock"
  description: "Extends the length of Rain Dance if used by the holder."
  grouping: POCKET_BATTLE
  hold_effect: HOLD_EFFECT_CUSTOM
  image: "damp_rock"
  palette: "damp_rock"
  talk_to_nurse_joy: true
}
item {
  id: ITEM_HEAT_ROCK
  name: "Heat Rock"
  description: "Extends the length of Sunny Day if used by the holder."
  grouping: POCKET_BATTLE
  hold_effect: HOLD_EFFECT_CUSTOM
  image: "heat_rock"
  palette: "heat_rock"
  talk_to_nurse_joy: true
}
item {
  id: ITEM_ICY_ROCK
  name: "Icy Rock"
  description: "Extends the length of the move Hail used by the holder."
  grouping: POCKET_BATTLE
  hold_effect: HOLD_EFFECT_CUSTOM
  image: "icy_rock"
  palette: "icy_rock"
  talk_to_nurse_joy: true
}
item {
  id: ITEM_SMOOTH_ROCK
  name: "Smooth Rock"
  description: "Extends the length of Sandstorm if used by the holder."
  grouping: POCKET_BATTLE
  hold_effect: HOLD_EFFECT_CUSTOM
  image: "smooth_rock"
  palette: "smooth_rock"
  talk_to_nurse_joy: true
}
item {
  id: ITEM_SMOKE_BALL
  name: "Smoke Ball"
  description: "Extends the length of Eerie Fog if used by the holder."
  grouping: POCKET_BATTLE
  hold_effect: HOLD_EFFECT_CUSTOM
  image: "smoke_ball"
  palette: "smoke_ball"
  talk_to_nurse_joy: true
}
item {
  id: ITEM_EXPERT_BELT
  name: "Expert Belt"
  description: "A belt that boosts the power of super effective moves."
  grouping: POCKET_BATTLE
  hold_effect: HOLD_EFFECT_CUSTOM
  hold_effect_strength: 30
  image: "expert_belt"
  palette: "expert_belt"
  talk_to_nurse_joy: true
}
item {
  id: ITEM_SCOPE_LENS
  name: "Scope Lens"
  description: "A hold item that improves the critical-hit rate."
  grouping: POCKET_BATTLE
  hold_effect: HOLD_EFFECT_SCOPE_LENS
  image: "scope_lens"
  palette: "scope_lens"
  talk_to_nurse_joy: true
}
item {
  id: ITEM_PROTECTIVE_PADS
  name: "Protective Pads"
  description: "Guard the holder from contact move effects."
  grouping: POCKET_BATTLE
  hold_effect: HOLD_EFFECT_CUSTOM
  image: "protective_pads"
  palette: "protective_pads"
  talk_to_nurse_joy: true
}
item {
  id: ITEM_SHELL_BELL
  name: "Shell Bell"
  description: "A hold item that restores HP upon striking the foe."
  grouping: POCKET_BATTLE
  hold_effect: HOLD_EFFECT_CUSTOM
  hold_effect_strength: 2
  image: "shell_bell"
  palette: "shell"
  talk_to_nurse_joy: true
}
item {
  id: ITEM_LAGGING_TAIL
  name: "Lagging Tail"
  description: "A held item that makes the holder move slower."
  grouping: POCKET_BATTLE
  hold_effect: HOLD_EFFECT_LAGGING_TAIL
  image: "lagging_tail"
  palette: "lagging_tail"
  talk_to_nurse_joy: true
}
item {
  id: ITEM_SHED_SHELL
  name: "Shed Shell"
  description: "Enables the holder to switch out of battle without fail."
  grouping: POCKET_BATTLE
  hold_effect: HOLD_EFFECT_CUSTOM
  image: "shed_shell"
  palette: "shed_shell"
  talk_to_nurse_joy: true
}
item {
  id: ITEM_TERRAIN_EXTENDER
  name: "Terrain Extender"
  description: "Extends the length of the active battle terrain."
  grouping: POCKET_BATTLE
  hold_effect: HOLD_EFFECT_CUSTOM
  image: "terrain_extender"
  palette: "terrain_extender"
  talk_to_nurse_joy: true
}
item {
  id: ITEM_BRIGHT_POWDER
  name: "Bright Powder"
  description: "A hold item that casts a glare to reduce accuracy."
  grouping: POCKET_BATTLE
  hold_effect: HOLD_EFFECT_EVASION_UP
  hold_effect_strength: 10
  image: "bright_powder"
  palette: "bright_powder"
  talk_to_nurse_joy: true
}
item {
  id: ITEM_BINDING_BAND
  name: "Binding Band"
  description: "Increases the power of binding moves when held."
  grouping: POCKET_BATTLE
  hold_effect: HOLD_EFFECT_CUSTOM
  image: "binding_band"
  palette: "binding_band"
  talk_to_nurse_joy: true
}
item {
  id: ITEM_SAFETY_GOGGLES
  name: "Safety Goggles"
  description: "Protect from weather damage and powder moves."
  grouping: POCKET_BATTLE
  hold_effect: HOLD_EFFECT_CUSTOM
  image: "safety_goggles"
  palette: "safety_goggles"
  talk_to_nurse_joy: true
}
item {
  id: ITEM_EJECT_BUTTON
  name: "Eject Button"
  description: "Switches out the user if they\'re hit by the foe."
  grouping: POCKET_BATTLE
  hold_effect: HOLD_EFFECT_CUSTOM
  image: "eject_button"
  palette: "eject_button"
  talk_to_nurse_joy: true
}
item {
  id: ITEM_EJECT_PACK
  name: "Eject Pack"
  description: "Switches out the holder if its stats are lowered."
  grouping: POCKET_BATTLE
  hold_effect: HOLD_EFFECT_CUSTOM
  image: "eject_pack"
  palette: "eject_pack"
  talk_to_nurse_joy: true
}
item {
  id: ITEM_RED_CARD
  name: "Red Card"
  description: "Switches out the foe if they hit the holder."
  grouping: POCKET_BATTLE
  hold_effect: HOLD_EFFECT_CUSTOM
  image: "red_card"
  palette: "red_card"
  talk_to_nurse_joy: true
}
item {
  id: ITEM_IRON_BALL
  name: "Iron Ball"
  description: "Cuts Speed and lets Flying-types be hit by Ground moves."
  grouping: POCKET_BATTLE
  hold_effect: HOLD_EFFECT_CUSTOM
  image: "iron_ball"
  palette: "iron_ball"
  talk_to_nurse_joy: true
}
item {
  id: ITEM_QUICK_CLAW
  name: "Quick Claw"
  description: "A hold item that occasionally allows the first strike."
  grouping: POCKET_BATTLE
  hold_effect: HOLD_EFFECT_CUSTOM
  hold_effect_strength: 20
  image: "quick_claw"
  palette: "quick_claw"
  talk_to_nurse_joy: true
}
item {
  id: ITEM_KINGS_ROCK
  name: "King\'s Rock"
  description: "A hold item that may cause flinching when the foe is hit."
  grouping: POCKET_BATTLE
  hold_effect: HOLD_EFFECT_FLINCH
  hold_effect_strength: 10
  use_type: ITEM_USE_PARTY_MENU
  image: "kings_rock"
  palette: "kings_rock"
  field_use_func: "EvolutionStone"
  talk_to_nurse_joy: true
}
item {
  id: ITEM_MUSCLE_BAND
  name: "Muscle Band"
  description: "A headband that boosts the power of physical moves."
  grouping: POCKET_BATTLE
  hold_effect: HOLD_EFFECT_CUSTOM
  hold_effect_strength: 15
  image: "muscle_band"
  palette: "muscle_band"
  talk_to_nurse_joy: true
}
item {
  id: ITEM_WISE_GLASSES
  name: "Wise Glasses"
  description: "A pair of glasses that ups the power of special moves."
  grouping: POCKET_BATTLE
  hold_effect: HOLD_EFFECT_CUSTOM
  hold_effect_strength: 15
  image: "wise_glasses"
  palette: "wise_glasses"
  talk_to_nurse_joy: true
}
item {
  id: ITEM_ABILITY_SHIELD
  name: "Ability Shield"
  description: "Ability changes are prevented for this items\'s holder."
  grouping: POCKET_BATTLE
  hold_effect: HOLD_EFFECT_CUSTOM
  image: "ability_shield"
  palette: "ability_shield"
  talk_to_nurse_joy: true
}
item {
  id: ITEM_CLEAR_AMULET
  name: "Clear Amulet"
  description: "Stat lowering is prevented for this items\'s holder."
  grouping: POCKET_BATTLE
  hold_effect: HOLD_EFFECT_CUSTOM
  image: "clear_amulet"
  palette: "clear_amulet"
  talk_to_nurse_joy: true
}
item {
  id: ITEM_PUNCHING_GLOVE
  name: "Punching Glove"
  description: "Powers up punching moves and removes their contact."
  grouping: POCKET_BATTLE
  hold_effect: HOLD_EFFECT_CUSTOM
  image: "punching_glove"
  palette: "punching_glove"
  talk_to_nurse_joy: true
}
item {
  id: ITEM_COVERT_CLOAK
  name: "Covert Cloak"
  description: "Protects from secondary move effects."
  grouping: POCKET_BATTLE
  hold_effect: HOLD_EFFECT_CUSTOM
  image: "covert_cloak"
  palette: "covert_cloak"
  talk_to_nurse_joy: true
}
item {
  id: ITEM_LOADED_DICE
  name: "Loaded Dice"
  description: "Rolls high numbers. Multihit strikes hit more times."
  grouping: POCKET_BATTLE
  hold_effect: HOLD_EFFECT_CUSTOM
  image: "loaded_dice"
  palette: "loaded_dice"
  talk_to_nurse_joy: true
}
item {
  id: ITEM_SWIRLY_GLASSES
  name: "Swirly Glasses"
  description: "Swaps the split of attacking moves."
  grouping: POCKET_BATTLE
  hold_effect: HOLD_EFFECT_CUSTOM
  image: "swirly_glasses"
  palette: "swirly_glasses"
  talk_to_nurse_joy: true
}
item {
  id: ITEM_SILK_SCARF
  name: "Silk Scarf"
  description: "A hold item that raises the power of Normal-type moves."
  grouping: POCKET_BATTLE
  hold_effect: HOLD_EFFECT_TYPE_POWER
  hold_effect_strength: 30
  hold_effect_type: TYPE_NORMAL
  image: "silk_scarf"
  palette: "silk_scarf"
  talk_to_nurse_joy: true
}
item {
  id: ITEM_BLACK_BELT
  name: "Black Belt"
  description: "A hold item that boosts Fighting-type moves."
  grouping: POCKET_BATTLE
  hold_effect: HOLD_EFFECT_TYPE_POWER
  hold_effect_strength: 30
  hold_effect_type: TYPE_FIGHTING
  image: "black_belt"
  palette: "black_type_enhancing_item"
  talk_to_nurse_joy: true
}
item {
  id: ITEM_SHARP_BEAK
  name: "Sharp Beak"
  description: "A hold item that raises the power of Flying-type moves."
  grouping: POCKET_BATTLE
  hold_effect: HOLD_EFFECT_TYPE_POWER
  hold_effect_strength: 30
  hold_effect_type: TYPE_FLYING
  image: "sharp_beak"
  palette: "sharp_beak"
  talk_to_nurse_joy: true
}
item {
  id: ITEM_POISON_BARB
  name: "Poison Barb"
  description: "A hold item that raises the power of Poison-type moves."
  grouping: POCKET_BATTLE
  hold_effect: HOLD_EFFECT_TYPE_POWER
  hold_effect_strength: 30
  hold_effect_type: TYPE_POISON
  image: "poison_barb"
  palette: "poison_barb"
  talk_to_nurse_joy: true
}
item {
  id: ITEM_SOFT_SAND
  name: "Soft Sand"
  description: "A hold item that raises the power of Ground-type moves."
  grouping: POCKET_BATTLE
  hold_effect: HOLD_EFFECT_TYPE_POWER
  hold_effect_strength: 30
  hold_effect_type: TYPE_GROUND
  image: "soft_sand"
  palette: "soft_sand"
  talk_to_nurse_joy: true
}
item {
  id: ITEM_ROCK_INCENSE
  name: "Rock Incense"
  description: "A hold item that raises the power of Rock-type moves."
  grouping: POCKET_BATTLE
  hold_effect: HOLD_EFFECT_TYPE_POWER
  hold_effect_strength: 30
  hold_effect_type: TYPE_ROCK
  image: "rock_incense"
  palette: "rock_incense"
}
item {
  id: ITEM_HARD_STONE
  name: "Hard Stone"
  description: "A hold item that raises the power of Rock-type moves."
  grouping: POCKET_BATTLE
  hold_effect: HOLD_EFFECT_TYPE_POWER
  hold_effect_strength: 30
  hold_effect_type: TYPE_ROCK
  image: "hard_stone"
  palette: "hard_stone"
  talk_to_nurse_joy: true
}
item {
  id: ITEM_SILVER_POWDER
  name: "Silver Powder"
  description: "A hold item that raises the power of Bug-type moves."
  grouping: POCKET_BATTLE
  hold_effect: HOLD_EFFECT_TYPE_POWER
  hold_effect_strength: 30
  hold_effect_type: TYPE_BUG
  image: "silver_powder"
  palette: "silver_powder"
  talk_to_nurse_joy: true
}
item {
  id: ITEM_SPELL_TAG
  name: "Spell Tag"
  description: "A hold item that raises the power of Ghost-type moves."
  grouping: POCKET_BATTLE
  hold_effect: HOLD_EFFECT_TYPE_POWER
  hold_effect_strength: 30
  hold_effect_type: TYPE_GHOST
  image: "spell_tag"
  palette: "spell_tag"
  talk_to_nurse_joy: true
}
item {
  id: ITEM_METAL_COAT
  name: "Metal Coat"
  description: "A hold item that raises the power of Steel-type moves."
  grouping: POCKET_BATTLE
  hold_effect: HOLD_EFFECT_TYPE_POWER
  hold_effect_strength: 30
  hold_effect_type: TYPE_STEEL
  use_type: ITEM_USE_PARTY_MENU
  image: "metal_coat"
  palette: "metal_coat"
  field_use_func: "EvolutionStone"
  talk_to_nurse_joy: true
}
item {
  id: ITEM_CHARCOAL
  name: "Charcoal"
  description: "A hold item that raises the power of Fire-type moves."
  grouping: POCKET_BATTLE
  hold_effect: HOLD_EFFECT_TYPE_POWER
  hold_effect_strength: 30
  hold_effect_type: TYPE_FIRE
  image: "charcoal"
  palette: "charcoal"
  talk_to_nurse_joy: true
}
item {
  id: ITEM_SEA_INCENSE
  name: "Sea Incense"
  description: "A hold item that slightly boosts Water-type moves."
  grouping: POCKET_BATTLE
  hold_effect: HOLD_EFFECT_TYPE_POWER
  hold_effect_strength: 30
  hold_effect_type: TYPE_WATER
  image: "sea_incense"
  palette: "sea_incense"
}
item {
  id: ITEM_WAVE_INCENSE
  name: "Wave Incense"
  description: "A hold item that slightly boosts Water-type moves."
  grouping: POCKET_BATTLE
  hold_effect: HOLD_EFFECT_TYPE_POWER
  hold_effect_strength: 30
  hold_effect_type: TYPE_WATER
  image: "wave_incense"
  palette: "wave_incense"
}
item {
  id: ITEM_MYSTIC_WATER
  name: "Mystic Water"
  description: "A hold item that raises the power of Water-type moves."
  grouping: POCKET_BATTLE
  hold_effect: HOLD_EFFECT_TYPE_POWER
  hold_effect_strength: 30
  hold_effect_type: TYPE_WATER
  image: "mystic_water"
  palette: "mystic_water"
  talk_to_nurse_joy: true
}
item {
  id: ITEM_ROSE_INCENSE
  name: "Rose Incense"
  description: "A hold item that raises the power of Grass-type moves."
  grouping: POCKET_BATTLE
  hold_effect: HOLD_EFFECT_TYPE_POWER
  hold_effect_strength: 30
  hold_effect_type: TYPE_GRASS
  image: "rose_incense"
  palette: "rose_incense"
}
item {
  id: ITEM_MIRACLE_SEED
  name: "Miracle Seed"
  description: "A hold item that raises the power of Grass-type moves."
  grouping: POCKET_BATTLE
  hold_effect: HOLD_EFFECT_TYPE_POWER
  hold_effect_strength: 30
  hold_effect_type: TYPE_GRASS
  image: "miracle_seed"
  palette: "miracle_seed"
  talk_to_nurse_joy: true
}
item {
  id: ITEM_MAGNET
  name: "Magnet"
  description: "A hold item that boosts Electric-type moves."
  grouping: POCKET_BATTLE
  hold_effect: HOLD_EFFECT_TYPE_POWER
  hold_effect_strength: 30
  hold_effect_type: TYPE_ELECTRIC
  image: "magnet"
  palette: "magnet"
  talk_to_nurse_joy: true
}
item {
  id: ITEM_ODD_INCENSE
  name: "Odd Incense"
  description: "A hold item that boosts Psychic-type moves."
  grouping: POCKET_BATTLE
  hold_effect: HOLD_EFFECT_TYPE_POWER
  hold_effect_strength: 30
  hold_effect_type: TYPE_PSYCHIC
  image: "odd_incense"
  palette: "odd_incense"
}
item {
  id: ITEM_TWISTED_SPOON
  name: "Twisted Spoon"
  description: "A hold item that boosts Psychic-type moves."
  grouping: POCKET_BATTLE
  hold_effect: HOLD_EFFECT_TYPE_POWER
  hold_effect_strength: 30
  hold_effect_type: TYPE_PSYCHIC
  image: "twisted_spoon"
  palette: "twisted_spoon"
  talk_to_nurse_joy: true
}
item {
  id: ITEM_NEVER_MELT_ICE
  name: "Never-MeltIce"
  description: "A hold item that raises the power of Ice-type moves."
  grouping: POCKET_BATTLE
  hold_effect: HOLD_EFFECT_TYPE_POWER
  hold_effect_strength: 30
  hold_effect_type: TYPE_ICE
  image: "never_melt_ice"
  palette: "never_melt_ice"
  talk_to_nurse_joy: true
}
item {
  id: ITEM_DRAGON_FANG
  name: "Dragon Fang"
  description: "A hold item that raises the power of Dragon-type moves."
  grouping: POCKET_BATTLE
  hold_effect: HOLD_EFFECT_TYPE_POWER
  hold_effect_strength: 30
  hold_effect_type: TYPE_DRAGON
  image: "dragon_fang"
  palette: "dragon_fang"
  talk_to_nurse_joy: true
}
item {
  id: ITEM_BLACK_GLASSES
  name: "Black Glasses"
  description: "A hold item that raises the power of Dark-type moves."
  grouping: POCKET_BATTLE
  hold_effect: HOLD_EFFECT_TYPE_POWER
  hold_effect_strength: 30
  hold_effect_type: TYPE_DARK
  image: "black_glasses"
  palette: "black_type_enhancing_item"
  talk_to_nurse_joy: true
}
item {
  id: ITEM_FAIRY_FEATHER
  name: "Fairy Feather"
  description: "A hold item that raises the power of Fairy-type moves."
  grouping: POCKET_BATTLE
  hold_effect: HOLD_EFFECT_TYPE_POWER
  hold_effect_strength: 30
  hold_effect_type: TYPE_FAIRY
  image: "fairy_feather"
  palette: "fairy_feather"
  talk_to_nurse_joy: true
}
item {
  id: ITEM_BURN_DRIVE
  name: "Burn Drive"
  description: "Changes Genesect\'s Techno Blast to Fire-type."
  grouping: POCKET_BATTLE
  hold_effect: HOLD_EFFECT_DRIVE
  hold_effect_type: TYPE_FIRE
  image: "burn_drive"
  palette: "burn_drive"
  talk_to_legendary_sage: true
}
item {
  id: ITEM_DOUSE_DRIVE
  name: "Douse Drive"
  description: "Changes Genesect\'s Techno Blast to Water-type."
  grouping: POCKET_BATTLE
  hold_effect: HOLD_EFFECT_DRIVE
  hold_effect_type: TYPE_WATER
  image: "douse_drive"
  palette: "douse_drive"
  talk_to_legendary_sage: true
}
item {
  id: ITEM_SHOCK_DRIVE
  name: "Shock Drive"
  description: "Changes Genesect\'s Techno Blast to Electric-type."
  grouping: POCKET_BATTLE
  hold_effect: HOLD_EFFECT_DRIVE
  hold_effect_type: TYPE_ELECTRIC
  image: "shock_drive"
  palette: "shock_drive"
  talk_to_legendary_sage: true
}
item {
  id: ITEM_CHILL_DRIVE
  name: "Chill Drive"
  description: "Changes Genesect\'s Techno Blast to Ice-type."
  grouping: POCKET_BATTLE
  hold_effect: HOLD_EFFECT_DRIVE
  hold_effect_type: TYPE_ICE
  image: "chill_drive"
  palette: "chill_drive"
  talk_to_legendary_sage: true
}
item {
  id: ITEM_FIST_PLATE
  name: "Fist Plate"
  description: "A tablet that ups the power of Fight-ing-type moves."
  grouping: POCKET_BATTLE
  hold_effect: HOLD_EFFECT_PLATE
  hold_effect_strength: 30
  hold_effect_type: TYPE_FIGHTING
  image: "fist_plate"
  palette: "fist_plate"
  talk_to_legendary_sage: true
}
item {
  id: ITEM_SKY_PLATE
  name: "Sky Plate"
  description: "A tablet that ups the power of Flying-type moves."
  grouping: POCKET_BATTLE
  hold_effect: HOLD_EFFECT_PLATE
  hold_effect_strength: 30
  hold_effect_type: TYPE_FLYING
  image: "sky_plate"
  palette: "sky_plate"
  talk_to_legendary_sage: true
}
item {
  id: ITEM_TOXIC_PLATE
  name: "Toxic Plate"
  description: "A tablet that ups the power of Poison-type moves."
  grouping: POCKET_BATTLE
  hold_effect: HOLD_EFFECT_PLATE
  hold_effect_strength: 30
  hold_effect_type: TYPE_POISON
  image: "toxic_plate"
  palette: "toxic_plate"
  talk_to_legendary_sage: true
}
item {
  id: ITEM_EARTH_PLATE
  name: "Earth Plate"
  description: "A tablet that ups the power of Ground-type moves."
  grouping: POCKET_BATTLE
  hold_effect: HOLD_EFFECT_PLATE
  hold_effect_strength: 30
  hold_effect_type: TYPE_GROUND
  image: "earth_plate"
  palette: "earth_plate"
  talk_to_legendary_sage: true
}
item {
  id: ITEM_STONE_PLATE
  name: "Stone Plate"
  description: "A tablet that ups the power of Rock-type moves."
  grouping: POCKET_BATTLE
  hold_effect: HOLD_EFFECT_PLATE
  hold_effect_strength: 30
  hold_effect_type: TYPE_ROCK
  image: "stone_plate"
  palette: "stone_plate"
  talk_to_legendary_sage: true
}
item {
  id: ITEM_INSECT_PLATE
  name: "Insect Plate"
  description: "A tablet that ups the power of Bug-type moves."
  grouping: POCKET_BATTLE
  hold_effect: HOLD_EFFECT_PLATE
  hold_effect_strength: 30
  hold_effect_type: TYPE_BUG
  image: "insect_plate"
  palette: "insect_plate"
  talk_to_legendary_sage: true
}
item {
  id: ITEM_SPOOKY_PLATE
  name: "Spooky Plate"
  description: "A tablet that ups the power of Ghost-type moves."
  grouping: POCKET_BATTLE
  hold_effect: HOLD_EFFECT_PLATE
  hold_effect_strength: 30
  hold_effect_type: TYPE_GHOST
  image: "spooky_plate"
  palette: "spooky_plate"
  talk_to_legendary_sage: true
}
item {
  id: ITEM_IRON_PLATE
  name: "Iron Plate"
  description: "A tablet that ups the power of Steel-type moves."
  grouping: POCKET_BATTLE
  hold_effect: HOLD_EFFECT_PLATE
  hold_effect_strength: 30
  hold_effect_type: TYPE_STEEL
  image: "iron_plate"
  palette: "iron_plate"
  talk_to_legendary_sage: true
}
item {
  id: ITEM_FLAME_PLATE
  name: "Flame Plate"
  description: "A tablet that ups the power of Fire-type moves."
  grouping: POCKET_BATTLE
  hold_effect: HOLD_EFFECT_PLATE
  hold_effect_strength: 30
  hold_effect_type: TYPE_FIRE
  image: "flame_plate"
  palette: "flame_plate"
  talk_to_legendary_sage: true
}
item {
  id: ITEM_SPLASH_PLATE
  name: "Splash Plate"
  description: "A tablet that ups the power of Water-type moves."
  grouping: POCKET_BATTLE
  hold_effect: HOLD_EFFECT_PLATE
  hold_effect_strength: 30
  hold_effect_type: TYPE_WATER
  image: "splash_plate"
  palette: "splash_plate"
  talk_to_legendary_sage: true
}
item {
  id: ITEM_MEADOW_PLATE
  name: "Meadow Plate"
  description: "A tablet that ups the power of Grass-type moves."
  grouping: POCKET_BATTLE
  hold_effect: HOLD_EFFECT_PLATE
  hold_effect_strength: 30
  hold_effect_type: TYPE_GRASS
  image: "meadow_plate"
  palette: "meadow_plate"
  talk_to_legendary_sage: true
}
item {
  id: ITEM_ZAP_PLATE
  name: "Zap Plate"
  description: "A tablet that ups the power of Elec-tric-type moves."
  grouping: POCKET_BATTLE
  hold_effect: HOLD_EFFECT_PLATE
  hold_effect_strength: 30
  hold_effect_type: TYPE_ELECTRIC
  image: "zap_plate"
  palette: "zap_plate"
  talk_to_legendary_sage: true
}
item {
  id: ITEM_MIND_PLATE
  name: "Mind Plate"
  description: "A tablet that ups the power of Psy-chic-type moves."
  grouping: POCKET_BATTLE
  hold_effect: HOLD_EFFECT_PLATE
  hold_effect_strength: 30
  hold_effect_type: TYPE_PSYCHIC
  image: "mind_plate"
  palette: "mind_plate"
  talk_to_legendary_sage: true
}
item {
  id: ITEM_ICICLE_PLATE
  name: "Icicle Plate"
  description: "A tablet that ups the power of Ice-type moves."
  grouping: POCKET_BATTLE
  hold_effect: HOLD_EFFECT_PLATE
  hold_effect_strength: 30
  hold_effect_type: TYPE_ICE
  image: "icicle_plate"
  palette: "icicle_plate"
  talk_to_legendary_sage: true
}
item {
  id: ITEM_DRACO_PLATE
  name: "Draco Plate"
  description: "A tablet that ups the power of Dragon-type moves."
  grouping: POCKET_BATTLE
  hold_effect: HOLD_EFFECT_PLATE
  hold_effect_strength: 30
  hold_effect_type: TYPE_DRAGON
  image: "draco_plate"
  palette: "draco_plate"
  talk_to_legendary_sage: true
}
item {
  id: ITEM_DREAD_PLATE
  name: "Dread Plate"
  description: "A tablet that ups the power of Dark-type moves."
  grouping: POCKET_BATTLE
  hold_effect: HOLD_EFFECT_PLATE
  hold_effect_strength: 30
  hold_effect_type: TYPE_DARK
  image: "dread_plate"
  palette: "dread_plate"
  talk_to_legendary_sage: true
}
item {
  id: ITEM_PIXIE_PLATE
  name: "Pixie Plate"
  description: "A tablet that ups the power of Fairy-type moves."
  grouping: POCKET_BATTLE
  hold_effect: HOLD_EFFECT_PLATE
  hold_effect_strength: 30
  hold_effect_type: TYPE_FAIRY
  image: "pixie_plate"
  palette: "pixie_plate"
  talk_to_legendary_sage: true
}
item {
  id: ITEM_FIGHTING_MEMORY
  name: "FightngMemory"
  description: "A disc with Fighting type data. It swaps Silvally\'s type."
  grouping: POCKET_BATTLE
  hold_effect: HOLD_EFFECT_MEMORY
  hold_effect_type: TYPE_FIGHTING
  image: "fighting_memory"
  palette: "fighting_memory"
  talk_to_legendary_sage: true
}
item {
  id: ITEM_FLYING_MEMORY
  name: "Flying Memory"
  description: "A disc with Flying type data. It swaps Silvally\'s type."
  grouping: POCKET_BATTLE
  hold_effect: HOLD_EFFECT_MEMORY
  hold_effect_type: TYPE_FLYING
  image: "flying_memory"
  palette: "flying_memory"
  talk_to_legendary_sage: true
}
item {
  id: ITEM_POISON_MEMORY
  name: "Poison Memory"
  description: "A disc with Poison type data. It swaps Silvally\'s type."
  grouping: POCKET_BATTLE
  hold_effect: HOLD_EFFECT_MEMORY
  hold_effect_type: TYPE_POISON
  image: "poison_memory"
  palette: "poison_memory"
  talk_to_legendary_sage: true
}
item {
  id: ITEM_GROUND_MEMORY
  name: "Ground Memory"
  description: "A disc with Ground type data. It swaps Silvally\'s type."
  grouping: POCKET_BATTLE
  hold_effect: HOLD_EFFECT_MEMORY
  hold_effect_type: TYPE_GROUND
  image: "ground_memory"
  palette: "ground_memory"
  talk_to_legendary_sage: true
}
item {
  id: ITEM_ROCK_MEMORY
  name: "Rock Memory"
  description: "A disc with Rock type data. It swaps Silvally\'s type."
  grouping: POCKET_BATTLE
  hold_effect: HOLD_EFFECT_MEMORY
  hold_effect_type: TYPE_ROCK
  image: "rock_memory"
  palette: "rock_memory"
  talk_to_legendary_sage: true
}
item {
  id: ITEM_BUG_MEMORY
  name: "Bug Memory"
  description: "A disc with Bug type data. It swaps Silvally\'s type."
  grouping: POCKET_BATTLE
  hold_effect: HOLD_EFFECT_MEMORY
  hold_effect_type: TYPE_BUG
  image: "bug_memory"
  palette: "bug_memory"
  talk_to_legendary_sage: true
}
item {
  id: ITEM_GHOST_MEMORY
  name: "Ghost Memory"
  description: "A disc with Ghost type data. It swaps Silvally\'s type."
  grouping: POCKET_BATTLE
  hold_effect: HOLD_EFFECT_MEMORY
  hold_effect_type: TYPE_GHOST
  image: "ghost_memory"
  palette: "ghost_memory"
  talk_to_legendary_sage: true
}
item {
  id: ITEM_STEEL_MEMORY
  name: "Steel Memory"
  description: "A disc with Steel type data. It swaps Silvally\'s type."
  grouping: POCKET_BATTLE
  hold_effect: HOLD_EFFECT_MEMORY
  hold_effect_type: TYPE_STEEL
  image: "steel_memory"
  palette: "steel_memory"
  talk_to_legendary_sage: true
}
item {
  id: ITEM_FIRE_MEMORY
  name: "Fire Memory"
  description: "A disc with Fire type data. It swaps Silvally\'s type."
  grouping: POCKET_BATTLE
  hold_effect: HOLD_EFFECT_MEMORY
  hold_effect_type: TYPE_FIRE
  image: "fire_memory"
  palette: "fire_memory"
  talk_to_legendary_sage: true
}
item {
  id: ITEM_WATER_MEMORY
  name: "Water Memory"
  description: "A disc with Water type data. It swaps Silvally\'s type."
  grouping: POCKET_BATTLE
  hold_effect: HOLD_EFFECT_MEMORY
  hold_effect_type: TYPE_WATER
  image: "water_memory"
  palette: "water_memory"
  talk_to_legendary_sage: true
}
item {
  id: ITEM_GRASS_MEMORY
  name: "Grass Memory"
  description: "A disc with Grass type data. It swaps Silvally\'s type."
  grouping: POCKET_BATTLE
  hold_effect: HOLD_EFFECT_MEMORY
  hold_effect_type: TYPE_GRASS
  image: "grass_memory"
  palette: "grass_memory"
  talk_to_legendary_sage: true
}
item {
  id: ITEM_ELECTRIC_MEMORY
  name: "ElectrcMemory"
  description: "A disc with Electric type data. It swaps Silvally\'s type."
  grouping: POCKET_BATTLE
  hold_effect: HOLD_EFFECT_MEMORY
  hold_effect_type: TYPE_ELECTRIC
  image: "electric_memory"
  palette: "electric_memory"
  talk_to_legendary_sage: true
}
item {
  id: ITEM_PSYCHIC_MEMORY
  name: "PsychicMemory"
  description: "A disc with Psychic type data. It swaps Silvally\'s type."
  grouping: POCKET_BATTLE
  hold_effect: HOLD_EFFECT_MEMORY
  hold_effect_type: TYPE_PSYCHIC
  image: "psychic_memory"
  palette: "psychic_memory"
  talk_to_legendary_sage: true
}
item {
  id: ITEM_ICE_MEMORY
  name: "Ice Memory"
  description: "A disc with Ice type data. It swaps Silvally\'s type."
  grouping: POCKET_BATTLE
  hold_effect: HOLD_EFFECT_MEMORY
  hold_effect_type: TYPE_ICE
  image: "ice_memory"
  palette: "ice_memory"
  talk_to_legendary_sage: true
}
item {
  id: ITEM_DRAGON_MEMORY
  name: "Dragon Memory"
  description: "A disc with Dragon type data. It swaps Silvally\'s type."
  grouping: POCKET_BATTLE
  hold_effect: HOLD_EFFECT_MEMORY
  hold_effect_type: TYPE_DRAGON
  image: "dragon_memory"
  palette: "dragon_memory"
  talk_to_legendary_sage: true
}
item {
  id: ITEM_DARK_MEMORY
  name: "Dark Memory"
  description: "A disc with Dark type data. It swaps Silvally\'s type."
  grouping: POCKET_BATTLE
  hold_effect: HOLD_EFFECT_MEMORY
  hold_effect_type: TYPE_DARK
  image: "dark_memory"
  palette: "dark_memory"
  talk_to_legendary_sage: true
}
item {
  id: ITEM_FAIRY_MEMORY
  name: "Fairy Memory"
  description: "A disc with Fairy type data. It swaps Silvally\'s type."
  grouping: POCKET_BATTLE
  hold_effect: HOLD_EFFECT_MEMORY
  hold_effect_type: TYPE_FAIRY
  image: "fairy_memory"
  palette: "fairy_memory"
  talk_to_legendary_sage: true
}