# proto-file: ItemList.proto
# proto-message: er.ItemList

item {
  id: ITEM_CHERI_BERRY
  name: "Cheri Berry"
  description: "A hold item that heals paralysis in battle."
  grouping: POCKET_BERRIES
  hold_effect: HOLD_EFFECT_CUSTOM
  hold_effect_alias: "CURE_PAR"
  use_type: ITEM_USE_PARTY_MENU
  image: "cheri_berry"
  palette: "cheri_berry"
  field_use_func: "Medicine"
  battle_use_func: "Medicine"
  talk_to_nurse_joy: true
  natural_gift {
    power: 80
    type: TYPE_ELECTRIC
    effect: MOVE_EFFECT_PARALYSIS
  }
}
item {
  id: ITEM_CHESTO_BERRY
  name: "Chesto Berry"
  description: "A hold item that awakens Pok\303\251mon in battle."
  grouping: POCKET_BERRIES
  hold_effect: HOLD_EFFECT_CUSTOM
  hold_effect_alias: "CURE_SLP"
  use_type: ITEM_USE_PARTY_MENU
  image: "chesto_berry"
  palette: "chesto_berry"
  field_use_func: "Medicine"
  battle_use_func: "Medicine"
  talk_to_nurse_joy: true
  natural_gift {
    power: 80
    type: TYPE_PSYCHIC
    effect: MOVE_EFFECT_SLEEP
  }
}
item {
  id: ITEM_PECHA_BERRY
  name: "Pecha Berry"
  description: "A hold item that heals poisoning in battle."
  grouping: POCKET_BERRIES
  hold_effect: HOLD_EFFECT_CUSTOM
  hold_effect_alias: "CURE_PSN"
  use_type: ITEM_USE_PARTY_MENU
  image: "pecha_berry"
  palette: "pecha_berry"
  field_use_func: "Medicine"
  battle_use_func: "Medicine"
  talk_to_nurse_joy: true
  natural_gift {
    power: 80
    type: TYPE_POISON
    effect: MOVE_EFFECT_TOXIC
  }
}
item {
  id: ITEM_RAWST_BERRY
  name: "Rawst Berry"
  description: "A hold item that heals a burn in battle."
  grouping: POCKET_BERRIES
  hold_effect: HOLD_EFFECT_CUSTOM
  hold_effect_alias: "CURE_BRN"
  use_type: ITEM_USE_PARTY_MENU
  image: "rawst_berry"
  palette: "rawst_berry"
  field_use_func: "Medicine"
  battle_use_func: "Medicine"
  talk_to_nurse_joy: true
  natural_gift {
    power: 80
    type: TYPE_FIRE
    effect: MOVE_EFFECT_BURN
  }
}
item {
  id: ITEM_ASPEAR_BERRY
  name: "Aspear Berry"
  description: "A hold item that defrosts Pok\303\251mon in battle."
  grouping: POCKET_BERRIES
  hold_effect: HOLD_EFFECT_CUSTOM
  hold_effect_alias: "CURE_FRZ"
  use_type: ITEM_USE_PARTY_MENU
  image: "aspear_berry"
  palette: "aspear_berry"
  field_use_func: "Medicine"
  battle_use_func: "Medicine"
  talk_to_nurse_joy: true
  natural_gift {
    power: 80
    type: TYPE_ICE
    effect: MOVE_EFFECT_FROSTBITE
  }
}
item {
  id: ITEM_LEPPA_BERRY
  name: "Leppa Berry"
  description: "A hold item that restores 10 PP in battle."
  grouping: POCKET_BERRIES
  hold_effect: HOLD_EFFECT_CUSTOM
  hold_effect_alias: "RESTORE_PP"
  hold_effect_strength: 10
  use_type: ITEM_USE_PARTY_MENU
  image: "leppa_berry"
  palette: "leppa_berry"
  field_use_func: "PPRecovery"
  battle_use_func: "PPRecovery"
  natural_gift {
    power: 80
    type: TYPE_FIRE
    effect: MOVE_EFFECT_DISABLE
  }
}
item {
  id: ITEM_ORAN_BERRY
  name: "Oran Berry"
  description: "A hold item that restores 10 HP in battle."
  grouping: POCKET_BERRIES
  hold_effect: HOLD_EFFECT_RESTORE_HP
  hold_effect_strength: 10
  use_type: ITEM_USE_PARTY_MENU
  image: "oran_berry"
  palette: "oran_berry"
  field_use_func: "Medicine"
  battle_use_func: "Medicine"
  natural_gift {
    power: 90
    type: TYPE_NORMAL
    effect: MOVE_EFFECT_WRAP
  }
}
item {
  id: ITEM_PERSIM_BERRY
  name: "Persim Berry"
  description: "A hold item that heals confusion in battle."
  grouping: POCKET_BERRIES
  hold_effect: HOLD_EFFECT_CUSTOM
  hold_effect_alias: "CURE_CONFUSION"
  image: "persim_berry"
  palette: "persim_berry"
  battle_use_func: "Medicine"
  talk_to_nurse_joy: true
  natural_gift {
    power: 90
    type: TYPE_FAIRY
    effect: MOVE_EFFECT_CONFUSION
  }
}
item {
  id: ITEM_LUM_BERRY
  name: "Lum Berry"
  description: "A hold item that heals any status problem in battle."
  grouping: POCKET_BERRIES
  hold_effect: HOLD_EFFECT_CUSTOM
  hold_effect_alias: "CURE_STATUS"
  use_type: ITEM_USE_PARTY_MENU
  image: "lum_berry"
  palette: "lum_berry"
  field_use_func: "Medicine"
  battle_use_func: "Medicine"
  natural_gift {
    power: 90
    type: TYPE_GRASS
    effect: MOVE_EFFECT_TRI_ATTACK
  }
}
item {
  id: ITEM_SITRUS_BERRY
  name: "Sitrus Berry"
  description: "A hold item that restores up to 1/4 of max HP in battle."
  grouping: POCKET_BERRIES
  hold_effect: HOLD_EFFECT_CUSTOM
  hold_effect_alias: "RESTORE_PCT_HP"
  hold_effect_strength: 25
  use_type: ITEM_USE_PARTY_MENU
  image: "sitrus_berry"
  palette: "sitrus_berry"
  field_use_func: "Medicine"
  battle_use_func: "Medicine"
  talk_to_nurse_joy: true
  natural_gift {
    power: 90
    type: TYPE_NORMAL
    effect: MOVE_EFFECT_PSYCHIC_NOISE
  }
}
item {
  id: ITEM_FIGY_BERRY
  name: "Figy Berry"
  description: "A hold item that restores HP but may confuse."
  grouping: POCKET_BERRIES
  hold_effect: HOLD_EFFECT_CUSTOM
  hold_effect_alias: "CONFUSE_SPICY"
  hold_effect_strength: 2
  image: "figy_berry"
  palette: "figy_berry"
  talk_to_nurse_joy: true
  natural_gift {
    power: 90
    type: TYPE_FIRE
    effect: MOVE_EFFECT_CONFUSION
  }
}
item {
  id: ITEM_WIKI_BERRY
  name: "Wiki Berry"
  description: "A hold item that restores HP but may confuse."
  grouping: POCKET_BERRIES
  hold_effect: HOLD_EFFECT_CUSTOM
  hold_effect_alias: "CONFUSE_DRY"
  hold_effect_strength: 2
  image: "wiki_berry"
  palette: "wiki_berry"
  talk_to_nurse_joy: true
  natural_gift {
    power: 90
    type: TYPE_WATER
    effect: MOVE_EFFECT_CONFUSION
  }
}
item {
  id: ITEM_MAGO_BERRY
  name: "Mago Berry"
  description: "A hold item that restores HP but may confuse."
  grouping: POCKET_BERRIES
  hold_effect: HOLD_EFFECT_CUSTOM
  hold_effect_alias: "CONFUSE_SWEET"
  hold_effect_strength: 2
  image: "mago_berry"
  palette: "mago_berry"
  talk_to_nurse_joy: true
  natural_gift {
    power: 90
    type: TYPE_FAIRY
    effect: MOVE_EFFECT_CONFUSION
  }
}
item {
  id: ITEM_AGUAV_BERRY
  name: "Aguav Berry"
  description: "A hold item that restores HP but may confuse."
  grouping: POCKET_BERRIES
  hold_effect: HOLD_EFFECT_CUSTOM
  hold_effect_alias: "CONFUSE_BITTER"
  hold_effect_strength: 2
  image: "aguav_berry"
  palette: "aguav_berry"
  talk_to_nurse_joy: true
  natural_gift {
    power: 90
    type: TYPE_GROUND
    effect: MOVE_EFFECT_CONFUSION
  }
}
item {
  id: ITEM_IAPAPA_BERRY
  name: "Iapapa Berry"
  description: "A hold item that restores HP but may confuse."
  grouping: POCKET_BERRIES
  hold_effect: HOLD_EFFECT_CUSTOM
  hold_effect_alias: "CONFUSE_SOUR"
  hold_effect_strength: 2
  image: "iapapa_berry"
  palette: "iapapa_berry"
  talk_to_nurse_joy: true
  natural_gift {
    power: 90
    type: TYPE_BUG
    effect: MOVE_EFFECT_CONFUSION
  }
}
item {
  id: ITEM_RAZZ_BERRY
  name: "Razz Berry"
  description: "Plant in loamy soil to grow Razz."
  grouping: POCKET_BERRIES
  image: "razz_berry"
  palette: "razz_berry"
  natural_gift {
    power: 80
    type: TYPE_GRASS
    effect: MOVE_EFFECT_PREVENT_ESCAPE
  }
}
item {
  id: ITEM_BLUK_BERRY
  name: "Bluk Berry"
  description: "Plant in loamy soil to grow Bluk."
  grouping: POCKET_BERRIES
  image: "bluk_berry"
  palette: "bluk_berry"
  natural_gift {
    power: 80
    type: TYPE_DARK
    effect: MOVE_EFFECT_BLEED
  }
}
item {
  id: ITEM_NANAB_BERRY
  name: "Nanab Berry"
  description: "Plant in loamy soil to grow Nanab."
  grouping: POCKET_BERRIES
  image: "nanab_berry"
  palette: "nanab_berry"
  natural_gift {
    power: 80
    type: TYPE_WATER
    effect: MOVE_EFFECT_EVS_MINUS_2
  }
}
item {
  id: ITEM_WEPEAR_BERRY
  name: "Wepear Berry"
  description: "Plant in loamy soil to grow Wepear."
  grouping: POCKET_BERRIES
  image: "wepear_berry"
  palette: "wepear_berry"
}
item {
  id: ITEM_PINAP_BERRY
  name: "Pinap Berry"
  description: "Plant in loamy soil to grow Pinap."
  grouping: POCKET_BERRIES
  image: "pinap_berry"
  palette: "pinap_berry"
  natural_gift {
    power: 80
    type: TYPE_ELECTRIC
    effect: MOVE_EFFECT_STEAL_ITEM
  }
}
item {
  id: ITEM_POMEG_BERRY
  name: "Pomeg Berry"
  description: "Makes a Pok\303\251mon friendly but lowers base HP."
  grouping: POCKET_BERRIES
  use_type: ITEM_USE_PARTY_MENU
  image: "pomeg_berry"
  palette: "pomeg_berry"
  field_use_func: "ReduceEV"
}
item {
  id: ITEM_KELPSY_BERRY
  name: "Kelpsy Berry"
  description: "Makes a Pok\303\251mon friendly but lowers base Attack."
  grouping: POCKET_BERRIES
  use_type: ITEM_USE_PARTY_MENU
  image: "kelpsy_berry"
  palette: "kelpsy_berry"
  field_use_func: "ReduceEV"
}
item {
  id: ITEM_QUALOT_BERRY
  name: "Qualot Berry"
  description: "Makes a Pok\303\251mon friendly but lowers base Defense."
  grouping: POCKET_BERRIES
  use_type: ITEM_USE_PARTY_MENU
  image: "qualot_berry"
  palette: "qualot_berry"
  field_use_func: "ReduceEV"
}
item {
  id: ITEM_HONDEW_BERRY
  name: "Hondew Berry"
  description: "Makes a Pok\303\251mon friendly but lowers base Sp. Atk."
  grouping: POCKET_BERRIES
  use_type: ITEM_USE_PARTY_MENU
  image: "hondew_berry"
  palette: "hondew_berry"
  field_use_func: "ReduceEV"
}
item {
  id: ITEM_GREPA_BERRY
  name: "Grepa Berry"
  description: "Makes a Pok\303\251mon friendly but lowers base Sp. Def."
  grouping: POCKET_BERRIES
  use_type: ITEM_USE_PARTY_MENU
  image: "grepa_berry"
  palette: "grepa_berry"
  field_use_func: "ReduceEV"
}
item {
  id: ITEM_TAMATO_BERRY
  name: "Tamato Berry"
  description: "Makes a Pok\303\251mon friendly but lowers base Speed."
  grouping: POCKET_BERRIES
  use_type: ITEM_USE_PARTY_MENU
  image: "tamato_berry"
  palette: "tamato_berry"
  field_use_func: "ReduceEV"
}
item {
  id: ITEM_CORNN_BERRY
  name: "Cornn Berry"
  description: "Plant in loamy soil to grow Cornn."
  grouping: POCKET_BERRIES
  image: "cornn_berry"
  palette: "cornn_berry"
}
item {
  id: ITEM_MAGOST_BERRY
  name: "Magost Berry"
  description: "Plant in loamy soil to grow Magost."
  grouping: POCKET_BERRIES
  image: "magost_berry"
  palette: "magost_berry"
}
item {
  id: ITEM_RABUTA_BERRY
  name: "Rabuta Berry"
  description: "Plant in loamy soil to grow Rabuta."
  grouping: POCKET_BERRIES
  image: "rabuta_berry"
  palette: "rabuta_berry"
}
item {
  id: ITEM_NOMEL_BERRY
  name: "Nomel Berry"
  description: "Plant in loamy soil to grow Nomel."
  grouping: POCKET_BERRIES
  image: "nomel_berry"
  palette: "nomel_berry"
}
item {
  id: ITEM_SPELON_BERRY
  name: "Spelon Berry"
  description: "Plant in loamy soil to grow Spelon."
  grouping: POCKET_BERRIES
  image: "spelon_berry"
  palette: "spelon_berry"
}
item {
  id: ITEM_PAMTRE_BERRY
  name: "Pamtre Berry"
  description: "Plant in loamy soil to grow Pamtre."
  grouping: POCKET_BERRIES
  image: "pamtre_berry"
  palette: "pamtre_berry"
}
item {
  id: ITEM_WATMEL_BERRY
  name: "Watmel Berry"
  description: "Plant in loamy soil to grow Watmel."
  grouping: POCKET_BERRIES
  image: "watmel_berry"
  palette: "watmel_berry"
}
item {
  id: ITEM_DURIN_BERRY
  name: "Durin Berry"
  description: "Plant in loamy soil to grow Durin."
  grouping: POCKET_BERRIES
  image: "durin_berry"
  palette: "durin_berry"
}
item {
  id: ITEM_BELUE_BERRY
  name: "Belue Berry"
  description: "Plant in loamy soil to grow Belue."
  grouping: POCKET_BERRIES
  image: "belue_berry"
  palette: "belue_berry"
}
item {
  id: ITEM_OCCA_BERRY
  name: "Occa Berry"
  description: "A hold item that weakens a Fire move if weak to it."
  grouping: POCKET_BERRIES
  hold_effect: HOLD_EFFECT_RESIST_BERRY
  hold_effect_type: TYPE_FIRE
  image: "occa_berry"
  palette: "occa_berry"
  talk_to_nurse_joy: true
  natural_gift {
    power: 95
    type: TYPE_FIRE
    effect: MOVE_EFFECT_FLAME_BURST
  }
}
item {
  id: ITEM_PASSHO_BERRY
  name: "Passho Berry"
  description: "A hold item that weakens a Water move if weak to it."
  grouping: POCKET_BERRIES
  hold_effect: HOLD_EFFECT_RESIST_BERRY
  hold_effect_type: TYPE_WATER
  image: "passho_berry"
  palette: "passho_berry"
  talk_to_nurse_joy: true
  natural_gift {
    power: 95
    type: TYPE_WATER
    effect: MOVE_EFFECT_SPD_MINUS_1
  }
}
item {
  id: ITEM_WACAN_BERRY
  name: "Wacan Berry"
  description: "A hold item that weakens a Electric move if weak to it."
  grouping: POCKET_BERRIES
  hold_effect: HOLD_EFFECT_RESIST_BERRY
  hold_effect_type: TYPE_ELECTRIC
  image: "wacan_berry"
  palette: "wacan_berry"
  talk_to_nurse_joy: true
  natural_gift {
    power: 95
    type: TYPE_ELECTRIC
    effect: MOVE_EFFECT_DISABLE
  }
}
item {
  id: ITEM_RINDO_BERRY
  name: "Rindo Berry"
  description: "A hold item that weakens a Grass move if weak to it."
  grouping: POCKET_BERRIES
  hold_effect: HOLD_EFFECT_RESIST_BERRY
  hold_effect_type: TYPE_GRASS
  image: "rindo_berry"
  palette: "rindo_berry"
  talk_to_nurse_joy: true
  natural_gift {
    power: 95
    type: TYPE_GRASS
    effect: MOVE_EFFECT_SYRUP
  }
}
item {
  id: ITEM_YACHE_BERRY
  name: "Yache Berry"
  description: "A hold item that weakens a Ice move if weak to it."
  grouping: POCKET_BERRIES
  hold_effect: HOLD_EFFECT_RESIST_BERRY
  hold_effect_type: TYPE_ICE
  image: "yache_berry"
  palette: "yache_berry"
  talk_to_nurse_joy: true
  natural_gift {
    power: 95
    type: TYPE_ICE
    effect: MOVE_EFFECT_SP_DEF_MINUS_1
  }
}
item {
  id: ITEM_CHOPLE_BERRY
  name: "Chople Berry"
  description: "A hold item that weakens a Fighting move if weak to it."
  grouping: POCKET_BERRIES
  hold_effect: HOLD_EFFECT_RESIST_BERRY
  hold_effect_type: TYPE_FIGHTING
  image: "chople_berry"
  palette: "chople_berry"
  talk_to_nurse_joy: true
  natural_gift {
    power: 95
    type: TYPE_FIGHTING
    effect: MOVE_EFFECT_ATK_MINUS_1
  }
}
item {
  id: ITEM_KEBIA_BERRY
  name: "Kebia Berry"
  description: "A hold item that weakens a Poison move if weak to it."
  grouping: POCKET_BERRIES
  hold_effect: HOLD_EFFECT_RESIST_BERRY
  hold_effect_type: TYPE_POISON
  image: "kebia_berry"
  palette: "kebia_berry"
  talk_to_nurse_joy: true
  natural_gift {
    power: 95
    type: TYPE_POISON
    effect: MOVE_EFFECT_POISON
  }
}
item {
  id: ITEM_SHUCA_BERRY
  name: "Shuca Berry"
  description: "A hold item that weakens a Ground move if weak to it."
  grouping: POCKET_BERRIES
  hold_effect: HOLD_EFFECT_RESIST_BERRY
  hold_effect_type: TYPE_GROUND
  image: "shuca_berry"
  palette: "shuca_berry"
  talk_to_nurse_joy: true
  natural_gift {
    power: 95
    type: TYPE_GROUND
    effect: MOVE_EFFECT_SMACK_DOWN
  }
}
item {
  id: ITEM_COBA_BERRY
  name: "Coba Berry"
  description: "A hold item that weakens a Flying move if weak to it."
  grouping: POCKET_BERRIES
  hold_effect: HOLD_EFFECT_RESIST_BERRY
  hold_effect_type: TYPE_FLYING
  image: "coba_berry"
  palette: "coba_berry"
  talk_to_nurse_joy: true
  natural_gift {
    power: 95
    type: TYPE_FLYING
    effect: MOVE_EFFECT_DEF_MINUS_1
  }
}
item {
  id: ITEM_PAYAPA_BERRY
  name: "Payapa Berry"
  description: "A hold item that weakens a Psychic move if weak to it."
  grouping: POCKET_BERRIES
  hold_effect: HOLD_EFFECT_RESIST_BERRY
  hold_effect_type: TYPE_PSYCHIC
  image: "payapa_berry"
  palette: "payapa_berry"
  talk_to_nurse_joy: true
  natural_gift {
    power: 95
    type: TYPE_PSYCHIC
    effect: MOVE_EFFECT_CONFUSION
  }
}
item {
  id: ITEM_TANGA_BERRY
  name: "Tanga Berry"
  description: "A hold item that weakens a Bug move if weak to it."
  grouping: POCKET_BERRIES
  hold_effect: HOLD_EFFECT_RESIST_BERRY
  hold_effect_type: TYPE_BUG
  image: "tanga_berry"
  palette: "tanga_berry"
  talk_to_nurse_joy: true
  natural_gift {
    power: 95
    type: TYPE_BUG
    effect: MOVE_EFFECT_KNOCK_OFF
  }
}
item {
  id: ITEM_CHARTI_BERRY
  name: "Charti Berry"
  description: "A hold item that weakens a Rock move if weak to it."
  grouping: POCKET_BERRIES
  hold_effect: HOLD_EFFECT_RESIST_BERRY
  hold_effect_type: TYPE_ROCK
  image: "charti_berry"
  palette: "charti_berry"
  talk_to_nurse_joy: true
  natural_gift {
    power: 95
    type: TYPE_ROCK
    effect: MOVE_EFFECT_DEF_PLUS_1
    affects_user: true
  }
}
item {
  id: ITEM_KASIB_BERRY
  name: "Kasib Berry"
  description: "A hold item that weakens a Ghost move if weak to it."
  grouping: POCKET_BERRIES
  hold_effect: HOLD_EFFECT_RESIST_BERRY
  hold_effect_type: TYPE_GHOST
  image: "kasib_berry"
  palette: "kasib_berry"
  talk_to_nurse_joy: true
  natural_gift {
    power: 95
    type: TYPE_GHOST
    effect: MOVE_EFFECT_FEAR
  }
}
item {
  id: ITEM_HABAN_BERRY
  name: "Haban Berry"
  description: "A hold item that weakens a Dragon move if weak to it."
  grouping: POCKET_BERRIES
  hold_effect: HOLD_EFFECT_RESIST_BERRY
  hold_effect_type: TYPE_DRAGON
  image: "haban_berry"
  palette: "haban_berry"
  talk_to_nurse_joy: true
  natural_gift {
    power: 95
    type: TYPE_DRAGON
    effect: MOVE_EFFECT_SP_ATK_MINUS_1
  }
}
item {
  id: ITEM_COLBUR_BERRY
  name: "Colbur Berry"
  description: "A hold item that weakens a Dark move if weak to it."
  grouping: POCKET_BERRIES
  hold_effect: HOLD_EFFECT_RESIST_BERRY
  hold_effect_type: TYPE_DARK
  image: "colbur_berry"
  palette: "colbur_berry"
  talk_to_nurse_joy: true
  natural_gift {
    power: 95
    type: TYPE_DARK
    effect: MOVE_EFFECT_STEAL_ITEM
  }
}
item {
  id: ITEM_BABIRI_BERRY
  name: "Babiri Berry"
  description: "A hold item that weakens a Steel move if weak to it."
  grouping: POCKET_BERRIES
  hold_effect: HOLD_EFFECT_RESIST_BERRY
  hold_effect_type: TYPE_STEEL
  image: "babiri_berry"
  palette: "babiri_berry"
  talk_to_nurse_joy: true
  natural_gift {
    power: 95
    type: TYPE_STEEL
    effect: MOVE_EFFECT_BLEED
  }
}
item {
  id: ITEM_CHILAN_BERRY
  name: "Chilan Berry"
  description: "A hold item that weakens a Normal move."
  grouping: POCKET_BERRIES
  hold_effect: HOLD_EFFECT_RESIST_BERRY
  hold_effect_type: TYPE_NORMAL
  image: "chilan_berry"
  palette: "chilan_berry"
  talk_to_nurse_joy: true
  natural_gift {
    power: 150
    type: TYPE_NORMAL
    effect: MOVE_EFFECT_NONE
  }
}
item {
  id: ITEM_ROSELI_BERRY
  name: "Roseli Berry"
  description: "A hold item that weakens a Fairy move if weak to it."
  grouping: POCKET_BERRIES
  hold_effect: HOLD_EFFECT_RESIST_BERRY
  hold_effect_type: TYPE_FAIRY
  image: "roseli_berry"
  palette: "roseli_berry"
  talk_to_nurse_joy: true
  natural_gift {
    power: 95
    type: TYPE_FAIRY
    effect: MOVE_EFFECT_ATTRACT
  }
}
item {
  id: ITEM_LIECHI_BERRY
  name: "Liechi Berry"
  description: "A hold item that raises Attack in a pinch."
  grouping: POCKET_BERRIES
  hold_effect: HOLD_EFFECT_CUSTOM
  hold_effect_alias: "ATTACK_UP"
  hold_effect_strength: 4
  image: "liechi_berry"
  palette: "liechi_berry"
  talk_to_nurse_joy: true
  natural_gift {
    power: 80
    type: TYPE_NORMAL
    effect: MOVE_EFFECT_ATK_PLUS_1
    affects_user: true
  }
}
item {
  id: ITEM_GANLON_BERRY
  name: "Ganlon Berry"
  description: "A hold item that raises Defense in a pinch."
  grouping: POCKET_BERRIES
  hold_effect: HOLD_EFFECT_CUSTOM
  hold_effect_alias: "DEFENSE_UP"
  hold_effect_strength: 4
  image: "ganlon_berry"
  palette: "ganlon_berry"
  talk_to_nurse_joy: true
  natural_gift {
    power: 80
    type: TYPE_STEEL
    effect: MOVE_EFFECT_DEF_PLUS_1
    affects_user: true
  }
}
item {
  id: ITEM_SALAC_BERRY
  name: "Salac Berry"
  description: "A hold item that raises Speed in a pinch."
  grouping: POCKET_BERRIES
  hold_effect: HOLD_EFFECT_CUSTOM
  hold_effect_alias: "SPEED_UP"
  hold_effect_strength: 4
  image: "salac_berry"
  palette: "salac_berry"
  talk_to_nurse_joy: true
  natural_gift {
    power: 80
    type: TYPE_FLYING
    effect: MOVE_EFFECT_SPD_PLUS_1
    affects_user: true
  }
}
item {
  id: ITEM_PETAYA_BERRY
  name: "Petaya Berry"
  description: "A hold item that raises Sp. Atk in a pinch."
  grouping: POCKET_BERRIES
  hold_effect: HOLD_EFFECT_CUSTOM
  hold_effect_alias: "SP_ATTACK_UP"
  hold_effect_strength: 4
  image: "petaya_berry"
  palette: "petaya_berry"
  talk_to_nurse_joy: true
  natural_gift {
    power: 80
    type: TYPE_DRAGON
    effect: MOVE_EFFECT_SP_ATK_PLUS_1
    affects_user: true
  }
}
item {
  id: ITEM_APICOT_BERRY
  name: "Apicot Berry"
  description: "A hold item that raises Sp. Def in a pinch."
  grouping: POCKET_BERRIES
  hold_effect: HOLD_EFFECT_CUSTOM
  hold_effect_alias: "SP_DEFENSE_UP"
  hold_effect_strength: 4
  image: "apicot_berry"
  palette: "apicot_berry"
  talk_to_nurse_joy: true
  natural_gift {
    power: 80
    type: TYPE_ROCK
    effect: MOVE_EFFECT_SP_DEF_PLUS_1
    affects_user: true
  }
}
item {
  id: ITEM_LANSAT_BERRY
  name: "Lansat Berry"
  description: "A hold item that ups the critical-hit rate in a pinch."
  grouping: POCKET_BERRIES
  hold_effect: HOLD_EFFECT_CUSTOM
  hold_effect_alias: "CRITICAL_UP"
  hold_effect_strength: 4
  image: "lansat_berry"
  palette: "lansat_berry"
  natural_gift {
    power: 80
    type: TYPE_DARK
    effect: MOVE_EFFECT_CRIT_PLUS_1
    affects_user: true
  }
}
item {
  id: ITEM_STARF_BERRY
  name: "Starf Berry"
  description: "A hold item that sharply boosts a stat in a pinch."
  grouping: POCKET_BERRIES
  hold_effect: HOLD_EFFECT_CUSTOM
  hold_effect_alias: "RANDOM_STAT_UP"
  hold_effect_strength: 4
  image: "starf_berry"
  palette: "starf_berry"
  natural_gift {
    power: 80
    type: TYPE_FAIRY
    effect: MOVE_EFFECT_HIGHEST_STAT_EXCEPT_SPEED_PLUS_1
    affects_user: true
  }
}
item {
  id: ITEM_MICLE_BERRY
  name: "Micle Berry"
  description: "When held, it ups the Accuracy of a move in a pinch."
  grouping: POCKET_BERRIES
  hold_effect: HOLD_EFFECT_CUSTOM
  hold_effect_strength: 4
  image: "micle_berry"
  palette: "micle_berry"
  natural_gift {
    power: 80
    type: TYPE_BUG
    effect: MOVE_EFFECT_ACC_PLUS_1
    affects_user: true
  }
}
item {
  id: ITEM_CUSTAP_BERRY
  name: "Custap Berry"
  description: "It allows a Pok\303\251mon in a pinch to move first just once."
  grouping: POCKET_BERRIES
  hold_effect: HOLD_EFFECT_CUSTOM
  hold_effect_strength: 4
  image: "custap_berry"
  palette: "custap_berry"
  talk_to_nurse_joy: true
  natural_gift {
    power: 95
    type: TYPE_NORMAL
    priority: 1
  }
}
item {
  id: ITEM_JABOCA_BERRY
  name: "Jaboca Berry"
  description: "If hit by a physical move, it will hurt the attacker a bit."
  grouping: POCKET_BERRIES
  hold_effect: HOLD_EFFECT_CUSTOM
  image: "jaboca_berry"
  palette: "jaboca_berry"
}
item {
  id: ITEM_ROWAP_BERRY
  name: "Rowap Berry"
  description: "If hit by a special move, it will hurt the attacker a bit."
  grouping: POCKET_BERRIES
  hold_effect: HOLD_EFFECT_CUSTOM
  image: "rowap_berry"
  palette: "rowap_berry"
}
item {
  id: ITEM_KEE_BERRY
  name: "Kee Berry"
  description: "If hit by a physical move, it raises the Defense a bit."
  grouping: POCKET_BERRIES
  hold_effect: HOLD_EFFECT_CUSTOM
  image: "kee_berry"
  palette: "kee_berry"
  talk_to_nurse_joy: true
}
item {
  id: ITEM_MARANGA_BERRY
  name: "Maranga Berry"
  description: "If hit by a special move, it raises the Sp. Def. a bit."
  grouping: POCKET_BERRIES
  hold_effect: HOLD_EFFECT_CUSTOM
  image: "maranga_berry"
  palette: "maranga_berry"
  talk_to_nurse_joy: true
}
item {
  id: ITEM_ENIGMA_BERRY
  name: "Enigma Berry"
  description: "Plant in loamy soil to grow a mystery."
  grouping: POCKET_BERRIES
  image: "enigma_berry"
  palette: "enigma_berry"
  field_use_func: "EnigmaBerry"
  battle_use_func: "EnigmaBerry"
  natural_gift {
    power: 80
    type: TYPE_GHOST
    effect: MOVE_EFFECT_RAINBOW
    affects_user: true
  }
}
