# proto-file: ItemList.proto
# proto-message: er.ItemList

item {
  id: ITEM_BERRY_JUICE
  name: "Berry Juice"
  description: "A 100% pure juice that restores HP by 20 points."
  grouping: POCKET_MEDICINE
  hold_effect: HOLD_EFFECT_RESTORE_HP
  hold_effect_strength: 20
  use_type: ITEM_USE_PARTY_MENU
  image: "berry_juice"
  palette: "berry_juice"
  field_use_func: "Medicine"
  battle_use_func: "Medicine"
  talk_to_nurse_joy: true
}
item {
  id: ITEM_THROAT_SPRAY
  name: "Throat Spray"
  description: "Raises Sp. Atk when the holder uses a sound move."
  grouping: POCKET_MEDICINE
  hold_effect: HOLD_EFFECT_CUSTOM
  image: "throat_spray"
  palette: "throat_spray"
  talk_to_nurse_joy: true
}
item {
  id: ITEM_BIG_ROOT
  name: "Big Root"
  description: "Boosts the power of the holder's HP-stealing moves."
  grouping: POCKET_MEDICINE
  hold_effect: HOLD_EFFECT_CUSTOM
  hold_effect_strength: 30
  image: "big_root"
  palette: "big_root"
  talk_to_nurse_joy: true
}
item {
  id: ITEM_MENTAL_HERB
  name: "Mental Herb"
  description: "Cures the Pok\303\251mon of some status effects."
  grouping: POCKET_MEDICINE
  hold_effect: HOLD_EFFECT_CUSTOM
  image: "in_battle_herb"
  palette: "mental_herb"
  talk_to_nurse_joy: true
}
item {
  id: ITEM_POWER_HERB
  name: "Power Herb"
  description: "Allows immediate use of a move that charges first."
  grouping: POCKET_MEDICINE
  hold_effect: HOLD_EFFECT_CUSTOM
  image: "power_herb"
  palette: "power_herb"
  talk_to_nurse_joy: true
}
item {
  id: ITEM_WHITE_HERB
  name: "White Herb"
  description: "A hold item that restores any lowered stat."
  grouping: POCKET_MEDICINE
  hold_effect: HOLD_EFFECT_CUSTOM
  hold_effect_alias: "RESTORE_STATS"
  image: "in_battle_herb"
  palette: "white_herb"
  talk_to_nurse_joy: true
}
item {
  id: ITEM_MIRROR_HERB
  name: "Mirror Herb"
  description: "Mirrors an enemy\'s stat increases but only once."
  grouping: POCKET_MEDICINE
  hold_effect: HOLD_EFFECT_CUSTOM
  image: "mirror_herb"
  palette: "mirror_herb"
  talk_to_nurse_joy: true
}
item {
  id: ITEM_ELECTRIC_SEED
  name: "Electric Seed"
  description: "Boosts Defense on Electric Terrain, but only one time."
  grouping: POCKET_MEDICINE
  hold_effect: HOLD_EFFECT_SEEDS
  hold_effect_misc_param: "HOLD_EFFECT_PARAM_ELECTRIC_TERRAIN"
  image: "electric_seed"
  palette: "electric_seed"
  talk_to_nurse_joy: true
}
item {
  id: ITEM_PSYCHIC_SEED
  name: "Psychic Seed"
  description: "Boosts Sp. Def. on Psychic Terrain, but only one time."
  grouping: POCKET_MEDICINE
  hold_effect: HOLD_EFFECT_SEEDS
  hold_effect_misc_param: "HOLD_EFFECT_PARAM_PSYCHIC_TERRAIN"
  image: "psychic_seed"
  palette: "psychic_seed"
  talk_to_nurse_joy: true
}
item {
  id: ITEM_MISTY_SEED
  name: "Misty Seed"
  description: "Boosts Sp. Def. on Misty Terrain, but only one time."
  grouping: POCKET_MEDICINE
  hold_effect: HOLD_EFFECT_SEEDS
  hold_effect_misc_param: "HOLD_EFFECT_PARAM_MISTY_TERRAIN"
  image: "misty_seed"
  palette: "misty_seed"
  talk_to_nurse_joy: true
}
item {
  id: ITEM_GRASSY_SEED
  name: "Grassy Seed"
  description: "Boosts Defense on Grassy Terrain, but only one time."
  grouping: POCKET_MEDICINE
  hold_effect: HOLD_EFFECT_SEEDS
  hold_effect_misc_param: "HOLD_EFFECT_PARAM_GRASSY_TERRAIN"
  image: "grassy_seed"
  palette: "grassy_seed"
  talk_to_nurse_joy: true
}
item {
  id: ITEM_BOOSTER_ENERGY
  name: "Booster Energy"
  description: "Encapsuled energy ups Pok\303\251mon with certain Abilities."
  grouping: POCKET_MEDICINE
  hold_effect: HOLD_EFFECT_CUSTOM
  image: "booster_energy"
  palette: "booster_energy"
  talk_to_nurse_joy: true
}