# proto-file: ItemList.proto
# proto-message: er.ItemList

item {
  id: ITEM_ABOMASITE
  name: "Abomasite"
  description: "Enables Abomasnow to Mega Evolve."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_MEGA_STONE
  image: "abomasite"
  palette: "abomasite"
  talk_to_nurse_joy: true
}
item {
  id: ITEM_ABSOLITE
  name: "Absolite"
  description: "Enables Absol to Mega Evolve."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_MEGA_STONE
  image: "absolite"
  palette: "absolite"
  talk_to_nurse_joy: true
}
item {
  id: ITEM_AERODACTYLITE
  name: "Aerodactylite"
  description: "Enables Aerodactyl to Mega Evolve."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_MEGA_STONE
  image: "aerodactylite"
  palette: "aerodactylite"
  talk_to_nurse_joy: true
}
item {
  id: ITEM_AGGRONITE
  name: "Aggronite"
  description: "Enables Aggron to Mega Evolve."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_MEGA_STONE
  image: "aggronite"
  palette: "aggronite"
  talk_to_nurse_joy: true
}
item {
  id: ITEM_ALAKAZITE
  name: "Alakazite"
  description: "Enables Alakazam to Mega Evolve."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_MEGA_STONE
  image: "alakazite"
  palette: "alakazite"
  talk_to_nurse_joy: true
}
item {
  id: ITEM_ALTARIANITE
  name: "Altarianite"
  description: "Enables Altaria to Mega Evolve."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_MEGA_STONE
  image: "altarianite"
  palette: "altarianite"
  talk_to_nurse_joy: true
}
item {
  id: ITEM_AMPHAROSITE
  name: "Ampharosite"
  description: "Enables Ampharos to Mega Evolve."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_MEGA_STONE
  image: "ampharosite"
  palette: "ampharosite"
  talk_to_nurse_joy: true
}
item {
  id: ITEM_AUDINITE
  name: "Audinite"
  description: "Enables Audino to Mega Evolve."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_MEGA_STONE
  image: "audinite"
  palette: "audinite"
  talk_to_nurse_joy: true
}
item {
  id: ITEM_BANETTITE
  name: "Banettite"
  description: "Enables Banette to Mega Evolve."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_MEGA_STONE
  image: "banettite"
  palette: "banettite"
  talk_to_nurse_joy: true
}
item {
  id: ITEM_BEEDRILLITE
  name: "Beedrillite"
  description: "Enables Beedrill to Mega Evolve."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_MEGA_STONE
  image: "beedrillite"
  palette: "beedrillite"
  talk_to_nurse_joy: true
}
item {
  id: ITEM_BLASTOISINITE
  name: "Blastoisinite Y"
  description: "Enables Blastoise to Mega Evolve."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_MEGA_STONE
  image: "blastoisinite"
  palette: "blastoisinite"
  talk_to_nurse_joy: true
}
item {
  id: ITEM_BLAZIKENITE
  name: "Blazikenite"
  description: "Enables Blaziken to Mega Evolve."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_MEGA_STONE
  image: "blazikenite"
  palette: "blazikenite"
  talk_to_nurse_joy: true
}
item {
  id: ITEM_CAMERUPTITE
  name: "Cameruptite"
  description: "Enables Camerupt to Mega Evolve."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_MEGA_STONE
  image: "cameruptite"
  palette: "cameruptite"
  talk_to_nurse_joy: true
}
item {
  id: ITEM_CHARIZARDITE_X
  name: "Charizardite X"
  description: "Enables Charizard to Mega Evolve."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_MEGA_STONE
  image: "charizardite_x"
  palette: "charizardite_x"
  talk_to_nurse_joy: true
}
item {
  id: ITEM_CHARIZARDITE_Y
  name: "Charizardite Y"
  description: "Enables Charizard to Mega Evolve."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_MEGA_STONE
  image: "charizardite_y"
  palette: "charizardite_y"
  talk_to_nurse_joy: true
}
item {
  id: ITEM_DIANCITE
  name: "Diancite"
  description: "Enables Diancie to Mega Evolve."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_MEGA_STONE
  image: "diancite"
  palette: "diancite"
  talk_to_nurse_joy: true
}
item {
  id: ITEM_GALLADITE
  name: "Galladite"
  description: "Enables Gallade to Mega Evolve."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_MEGA_STONE
  image: "galladite"
  palette: "galladite"
  talk_to_nurse_joy: true
}
item {
  id: ITEM_GARCHOMPITE
  name: "Garchompite"
  description: "Enables Garchomp to Mega Evolve."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_MEGA_STONE
  image: "garchompite"
  palette: "garchompite"
  talk_to_nurse_joy: true
}
item {
  id: ITEM_GARDEVOIRITE
  name: "Gardevoirite"
  description: "Enables Gardevoir to Mega Evolve."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_MEGA_STONE
  image: "gardevoirite"
  palette: "gardevoirite"
  talk_to_nurse_joy: true
}
item {
  id: ITEM_GENGARITE
  name: "Gengarite Y"
  description: "Enables Gengar to Mega Evolve."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_MEGA_STONE
  image: "gengarite"
  palette: "gengarite"
  talk_to_nurse_joy: true
}
item {
  id: ITEM_GLALITITE
  name: "Glalitite"
  description: "Enables Glalie to Mega Evolve."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_MEGA_STONE
  image: "glalitite"
  palette: "glalitite"
  talk_to_nurse_joy: true
}
item {
  id: ITEM_GYARADOSITE
  name: "Gyaradosite"
  description: "Enables Gyarados to Mega Evolve."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_MEGA_STONE
  image: "gyaradosite"
  palette: "gyaradosite"
  talk_to_nurse_joy: true
}
item {
  id: ITEM_HERACRONITE
  name: "Heracronite"
  description: "Enables Heracross to Mega Evolve."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_MEGA_STONE
  image: "heracronite"
  palette: "heracronite"
  talk_to_nurse_joy: true
}
item {
  id: ITEM_HOUNDOOMINITE
  name: "Houndoominite"
  description: "Enables Houndoom to Mega Evolve."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_MEGA_STONE
  image: "houndoominite"
  palette: "houndoominite"
  talk_to_nurse_joy: true
}
item {
  id: ITEM_KANGASKHANITE
  name: "Kangaskhanite"
  description: "Enables Kangaskhan to Mega Evolve."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_MEGA_STONE
  image: "kangaskhanite"
  palette: "kangaskhanite"
  talk_to_nurse_joy: true
}
item {
  id: ITEM_LATIASITE
  name: "Latiasite"
  description: "Enables Latias to Mega Evolve."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_MEGA_STONE
  image: "latiasite"
  palette: "latiasite"
  talk_to_nurse_joy: true
}
item {
  id: ITEM_LATIOSITE
  name: "Latiosite"
  description: "Enables Latios to Mega Evolve."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_MEGA_STONE
  image: "latiosite"
  palette: "latiosite"
  talk_to_nurse_joy: true
}
item {
  id: ITEM_LOPUNNITE
  name: "Lopunnite"
  description: "Enables Lopunny to Mega Evolve."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_MEGA_STONE
  image: "lopunnite"
  palette: "lopunnite"
  talk_to_nurse_joy: true
}
item {
  id: ITEM_LUCARIONITE
  name: "Lucarionite"
  description: "Enables Lucario to Mega Evolve."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_MEGA_STONE
  image: "lucarionite"
  palette: "lucarionite"
  talk_to_nurse_joy: true
}
item {
  id: ITEM_MANECTITE
  name: "Manectite"
  description: "Enables Manectric to Mega Evolve."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_MEGA_STONE
  image: "manectite"
  palette: "manectite"
  talk_to_nurse_joy: true
}
item {
  id: ITEM_MAWILITE
  name: "Mawilite"
  description: "Enables Mawile to Mega Evolve."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_MEGA_STONE
  image: "mawilite"
  palette: "mawilite"
  talk_to_nurse_joy: true
}
item {
  id: ITEM_MEDICHAMITE
  name: "Medichamite"
  description: "Enables Medicham to Mega Evolve."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_MEGA_STONE
  image: "medichamite"
  palette: "medichamite"
  talk_to_nurse_joy: true
}
item {
  id: ITEM_METAGROSSITE
  name: "Metagrossite"
  description: "Enables Metagross to Mega Evolve."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_MEGA_STONE
  image: "metagrossite"
  palette: "metagrossite"
  talk_to_nurse_joy: true
}
item {
  id: ITEM_MEWTWONITE_X
  name: "Mewtwonite X"
  description: "Enables Mewtwo to Mega Evolve."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_MEGA_STONE
  image: "mewtwonite_x"
  palette: "mewtwonite_x"
  talk_to_nurse_joy: true
}
item {
  id: ITEM_MEWTWONITE_Y
  name: "Mewtwonite Y"
  description: "Enables Mewtwo to Mega Evolve."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_MEGA_STONE
  image: "mewtwonite_y"
  palette: "mewtwonite_y"
  talk_to_nurse_joy: true
}
item {
  id: ITEM_PIDGEOTITE
  name: "Pidgeotite"
  description: "Enables Pidgeot to Mega Evolve."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_MEGA_STONE
  image: "pidgeotite"
  palette: "pidgeotite"
  talk_to_nurse_joy: true
}
item {
  id: ITEM_PINSIRITE
  name: "Pinsirite"
  description: "Enables Pinsir to Mega Evolve."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_MEGA_STONE
  image: "pinsirite"
  palette: "pinsirite"
  talk_to_nurse_joy: true
}
item {
  id: ITEM_SABLENITE
  name: "Sablenite"
  description: "Enables Sableye to Mega Evolve."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_MEGA_STONE
  image: "sablenite"
  palette: "sablenite"
  talk_to_nurse_joy: true
}
item {
  id: ITEM_SALAMENCITE
  name: "Salamencite"
  description: "Enables Salamence to Mega Evolve."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_MEGA_STONE
  image: "salamencite"
  palette: "salamencite"
  talk_to_nurse_joy: true
}
item {
  id: ITEM_SCEPTILITE
  name: "Sceptilite"
  description: "Enables Sceptile to Mega Evolve."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_MEGA_STONE
  image: "sceptilite"
  palette: "sceptilite"
  talk_to_nurse_joy: true
}
item {
  id: ITEM_SCIZORITE
  name: "Scizorite"
  description: "Enables Scizor to Mega Evolve."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_MEGA_STONE
  image: "scizorite"
  palette: "scizorite"
  talk_to_nurse_joy: true
}
item {
  id: ITEM_SHARPEDONITE
  name: "Sharpedonite"
  description: "Enables Sharpedo to Mega Evolve."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_MEGA_STONE
  image: "sharpedonite"
  palette: "sharpedonite"
  talk_to_nurse_joy: true
}
item {
  id: ITEM_SLOWBRONITE
  name: "Slowbronite"
  description: "Enables Slowbro to Mega Evolve."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_MEGA_STONE
  image: "slowbronite"
  palette: "slowbronite"
  talk_to_nurse_joy: true
}
item {
  id: ITEM_STEELIXITE
  name: "Steelixite"
  description: "Enables Steelix to Mega Evolve."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_MEGA_STONE
  image: "steelixite"
  palette: "steelixite"
  talk_to_nurse_joy: true
}
item {
  id: ITEM_SWAMPERTITE
  name: "Swampertite"
  description: "Enables Swampert to Mega Evolve."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_MEGA_STONE
  image: "swampertite"
  palette: "swampertite"
  talk_to_nurse_joy: true
}
item {
  id: ITEM_TYRANITARITE
  name: "Tyranitarite"
  description: "Enables Tyranitar to Mega Evolve."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_MEGA_STONE
  image: "tyranitarite"
  palette: "tyranitarite"
  talk_to_nurse_joy: true
}
item {
  id: ITEM_VENUSAURITE
  name: "Venusaurite Y"
  description: "Enables Venusaur to Mega Evolve."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_MEGA_STONE
  image: "venusaurite"
  palette: "venusaurite"
  talk_to_nurse_joy: true
}
item {
  id: ITEM_MILOTICITE
  name: "Miloticite"
  description: "Enables Milotic to Mega Evolve."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_MEGA_STONE
  image: "miloticite"
  palette: "miloticite"
  talk_to_nurse_joy: true
}
item {
  id: ITEM_RED_ORB
  name: "Red Orb"
  description: "A red, glowing orb said to contain an ancient power."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_PRIMAL_ORB
  image: "orb"
  palette: "red_orb"
  talk_to_legendary_sage: true
}
item {
  id: ITEM_BLUE_ORB
  name: "Blue Orb"
  description: "A blue, glowing orb said to contain an ancient power."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_PRIMAL_ORB
  image: "orb"
  palette: "blue_orb"
  talk_to_legendary_sage: true
}
item {
  id: ITEM_FLYGONITE
  name: "Flygonite"
  description: "Enables Flygon to Mega Evolve."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_MEGA_STONE
  image: "flygonite"
  palette: "flygonite"
  talk_to_nurse_joy: true
}
item {
  id: ITEM_BUTTERFRENITE
  name: "Butterfrenite"
  description: "Enables Butterfree to Mega Evolve."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_MEGA_STONE
  image: "butterfrenite"
  palette: "butterfrenite"
  talk_to_nurse_joy: true
}
item {
  id: ITEM_LAPRASITE_Y
  name: "Laprasite Y"
  description: "Enables Lapras to Mega Evolve."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_MEGA_STONE
  image: "laprasite"
  palette: "laprasite"
  talk_to_nurse_joy: true
}
item {
  id: ITEM_MACHAMPITE
  name: "Machampite"
  description: "Enables Machamp to Mega Evolve."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_MEGA_STONE
  image: "machampite"
  palette: "machampite"
  talk_to_nurse_joy: true
}
item {
  id: ITEM_KINGLERITE
  name: "Kinglerite"
  description: "Enables Kingler to Mega Evolve."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_MEGA_STONE
  image: "kinglerite"
  palette: "kinglerite"
  talk_to_nurse_joy: true
}
item {
  id: ITEM_KINGDRANITE
  name: "Kingdranite"
  description: "Enables Kingdra to Mega Evolve."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_MEGA_STONE
  image: "kingdranite"
  palette: "kingdranite"
  talk_to_nurse_joy: true
}
item {
  id: ITEM_DEWGONGITE
  name: "Dewgongite"
  description: "Enables Dewgong to Mega Evolve."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_MEGA_STONE
  image: "dewgongite"
  palette: "dewgongite"
  mega_badge_requirement: 7
  unique_mega_location: "Defeat Totem Dewgong in Seafoam Cave B1F."
}
item {
  id: ITEM_HITMONCHANITE
  name: "Hitmonchanite"
  description: "Enables Hitmonchan to Mega Evolve."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_MEGA_STONE
  image: "generic_megastone"
  palette: "hitmonchanite"
  mega_badge_requirement: 6
  unique_mega_location: "Defeat Blackbelt John in Granite Cave B2F."
}
item {
  id: ITEM_HITMONLEENITE
  name: "Hitmonleenite"
  description: "Enables Hitmonlee to Mega Evolve."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_MEGA_STONE
  image: "generic_megastone"
  palette: "hitmonlite"
  mega_badge_requirement: 6
  unique_mega_location: "Defeat Blackbelt John in Granite Cave B2F."
}
item {
  id: ITEM_HITMONTOPITE
  name: "Hitmontopite"
  description: "Enables Hitmontop to Mega Evolve."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_MEGA_STONE
  image: "generic_megastone"
  palette: "hitmontopite"
  mega_badge_requirement: 6
  unique_mega_location: "Defeat Blackbelt John in Granite Cave B2F."
}
item {
  id: ITEM_CROBATITE
  name: "Crobatite"
  description: "Enables Crobat to Mega Evolve."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_MEGA_STONE
  image: "crobatite"
  palette: "crobatite"
  mega_badge_requirement: 7
  unique_mega_location: "Defeat Expert Morticia in Dewford Manor."
}
item {
  id: ITEM_SKARMORITE
  name: "Skarmorite"
  description: "Enables Skarmory to Mega Evolve."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_MEGA_STONE
  image: "generic_megastone"
  palette: "generic_megastone"
  talk_to_nurse_joy: true
}
item {
  id: ITEM_BRUXISHITE
  name: "Bruxishite"
  description: "Enables Bruxish to Mega Evolve."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_MEGA_STONE
  image: "bruxishite"
  palette: "bruxishite"
}
item {
  id: ITEM_TORTERRANITE
  name: "Torterranite"
  description: "Enables Torterra to Mega Evolve."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_MEGA_STONE
  image: "generic_megastone"
  palette: "generic_megastone"
  mega_badge_requirement: 5
  unique_mega_location: "Defeat Youngster Kaixer in the Game Corner."
}
item {
  id: ITEM_INFERNAPENITE
  name: "Infernapite"
  description: "Enables Infernape to Mega Evolve."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_MEGA_STONE
  image: "generic_megastone"
  palette: "infernapenite"
  mega_badge_requirement: 5
  unique_mega_location: "Defeat Youngster Kaixer in the Game Corner."
}
item {
  id: ITEM_EMPOLEONITE
  name: "Empoleonite"
  description: "Enables Empoleon to Mega Evolve."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_MEGA_STONE
  image: "empoleonite"
  palette: "empoleonite"
  mega_badge_requirement: 5
  unique_mega_location: "Defeat Youngster Kaixer in the Game Corner."
}
item {
  id: ITEM_SHUCKLENITE
  name: "Shucklenite"
  description: "Enables Shuckle to Mega Evolve."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_MEGA_STONE
  image: "generic_megastone"
  palette: "generic_megastone"
  unique_mega_location: "Find in Route 110."
}
item {
  id: ITEM_RELICANTHITE
  name: "Relicanthite"
  description: "Enables Relicanth to Mega Evolve."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_MEGA_STONE
  image: "generic_megastone"
  palette: "generic_megastone"
  talk_to_nurse_joy: true
}
item {
  id: ITEM_QUAGSIRENITE
  name: "Quagsirenite"
  description: "Enables Quagsire to Mega Evolve."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_MEGA_STONE
  image: "generic_megastone"
  palette: "generic_megastone"
  talk_to_nurse_joy: true
}
item {
  id: ITEM_JELLICENTITE
  name: "Jellicentite"
  description: "Enables Jellicent to Mega Evolve."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_MEGA_STONE
  image: "generic_megastone"
  palette: "generic_megastone"
}
item {
  id: ITEM_TOUCANNONITE
  name: "Toucannonite"
  description: "Enables Toucannon to Mega Evolve."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_MEGA_STONE
  image: "generic_megastone"
  palette: "generic_megastone"
  mega_badge_requirement: 5
  unique_mega_location: "Defeat Leader Winona."
}
item {
  id: ITEM_DRAGONITENITE
  name: "Dragonitenite"
  description: "Enables Dragonite to Mega Evolve."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_MEGA_STONE
  image: "dragonitenite"
  palette: "dragonitenite"
  mega_badge_requirement: 7
  unique_mega_location: "Defeat the three sages at Sky Pillar."
}
item {
  id: ITEM_BRELOOMITE
  name: "Breloomite"
  description: "Enables Breloom to Mega Evolve."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_MEGA_STONE
  image: "breloomite"
  palette: "breloomite"
  mega_badge_requirement: 5
  unique_mega_location: "Defeat Totem Breloom in Petalburg Woods."
}
item {
  id: ITEM_SLAKINGITE
  name: "Slakingite"
  description: "Enables Slaking to Mega Evolve."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_MEGA_STONE
  image: "generic_megastone"
  palette: "generic_megastone"
  mega_badge_requirement: 6
  unique_mega_location: "Speak to Leader Norman."
}
item {
  id: ITEM_PURPLE_ORB
  name: "Purple Orb"
  description: "A purple, glowing orb said to contain an ancient power."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_PRIMAL_ORB
  image: "purple_orb"
  palette: "purple_orb"
  mega_badge_requirement: 9
  unique_mega_location: "Defeat Cooltrainer Baneful in Petalburg Woods."
}
item {
  id: ITEM_SLOWKINGITE
  name: "Slowkingite"
  description: "Enables Slowking to Mega Evolve."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_MEGA_STONE
  image: "generic_megastone"
  palette: "generic_megastone"
  mega_badge_requirement: 5
  unique_mega_location: "Defeat Tate & Liza."
}
item {
  id: ITEM_GYARADOSITE_Y
  name: "Gyaradosite Y"
  description: "Enables Gyarados to Mega Evolve."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_MEGA_STONE
  image: "generic_megastone"
  palette: "gyaradosite_y"
  mega_badge_requirement: 7
  unique_mega_location: "Defeat Totem Gyarados on Route 132."
}
item {
  id: ITEM_FERALIGATRITE_X
  name: "Feraligatrite X"
  description: "Enables Feraligatr to Mega Evolve."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_MEGA_STONE
  image: "feraligatrite_x"
  palette: "feraligatrite_x"
  mega_badge_requirement: 5
  unique_mega_location: "Defeat Sailor Caleb on Route 105."
}
item {
  id: ITEM_FERALIGATRITE_Y
  name: "Feraligatrite Y"
  description: "Enables Feraligatr to Mega Evolve."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_MEGA_STONE
  image: "feraligatrite_y"
  palette: "feraligatrite_y"
  mega_badge_requirement: 5
  unique_mega_location: "Defeat Totem Feraligatr on Route 114."
}
item {
  id: ITEM_HAXORUSITE
  name: "Haxorusite"
  description: "Enables Haxorus to Mega Evolve."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_MEGA_STONE
  image: "generic_megastone"
  palette: "haxorusite"
  mega_badge_requirement: 7
  unique_mega_location: "Defeat Totem Haxorus in Meteor Falls."
}
item {
  id: ITEM_LUXRAYNITE
  name: "Luxraynite"
  description: "Enables Luxray to Mega Evolve."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_MEGA_STONE
  image: "generic_megastone"
  palette: "generic_megastone"
  talk_to_nurse_joy: true
}
item {
  id: ITEM_GRANBULLITE
  name: "Granbullite"
  description: "Enables Granbull to Mega Evolve."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_MEGA_STONE
  image: "generic_megastone"
  palette: "granbullite"
  mega_badge_requirement: 7
  unique_mega_location: "Defeat Lady Amelia on Route 123."
}
item {
  id: ITEM_TYPHLOSIONITE
  name: "Typhlosionite"
  description: "Enables Typhlosion to Mega Evolve."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_MEGA_STONE
  image: "generic_megastone"
  palette: "generic_megastone"
  mega_badge_requirement: 5
  unique_mega_location: "Defeat Kindler Ignatius in Ashen Woods."
}
item {
  id: ITEM_NIDOQUEENITE
  name: "Nidoqueenite"
  description: "Enables Nidoqueen to Mega Evolve."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_MEGA_STONE
  image: "generic_megastone"
  palette: "generic_megastone"
  mega_badge_requirement: 6
  unique_mega_location: "Defeat Cooltrainer Prince on Route 116."
}
item {
  id: ITEM_NIDOKINGITE
  name: "Nidokingite"
  description: "Enables Nidoking to Mega Evolve."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_MEGA_STONE
  image: "generic_megastone"
  palette: "generic_megastone"
  mega_badge_requirement: 6
  unique_mega_location: "Defeat Cooltrainer Prince on Route 116."
}
item {
  id: ITEM_SANDSLASHITE
  name: "Sandslashite"
  description: "Enables Sandslash to Mega Evolve."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_MEGA_STONE
  image: "generic_megastone"
  palette: "generic_megastone"
  mega_badge_requirement: 5
  unique_mega_location: "Defeat Totem Sandslash on Route 111."
}
item {
  id: ITEM_MEGANIUMITE
  name: "Meganiumite"
  description: "Enables Meganium to Mega Evolve."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_MEGA_STONE
  image: "generic_megastone"
  palette: "generic_megastone"
  mega_badge_requirement: 5
  unique_mega_location: "Defeat Aroma Lady Lily in Verdanturf Meadow."
}
item {
  id: ITEM_KROOKODILENITE
  name: "Krookodilenite"
  description: "Enables Krookodile to Mega Evolve."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_MEGA_STONE
  image: "generic_megastone"
  palette: "generic_megastone"
  mega_badge_requirement: 5
  unique_mega_location: "Defeat Ruin Maniac Jones outside Mirage Tower."
}
item {
  id: ITEM_MAGNEZONITE
  name: "Magnezonite"
  description: "Enables Magnezone to Mega Evolve."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_MEGA_STONE
  image: "generic_megastone"
  palette: "generic_megastone"
  talk_to_nurse_joy: true
}
item {
  id: ITEM_SHEDINJITE
  name: "Shedinjite"
  description: "Enables Shedinja to Mega Evolve."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_MEGA_STONE
  image: "generic_megastone"
  palette: "generic_megastone"
  mega_badge_requirement: 7
  unique_mega_location: "Find in Abandoned Ship."
}
item {
  id: ITEM_SWALOTITE
  name: "Swalotite"
  description: "Enables Swalot to Mega Evolve."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_MEGA_STONE
  image: "generic_megastone"
  palette: "generic_megastone"
  talk_to_nurse_joy: true
}
item {
  id: ITEM_LANTURNITE
  name: "Lanturnite"
  description: "Enables Lanturn to Mega Evolve."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_MEGA_STONE
  image: "generic_megastone"
  palette: "generic_megastone"
  mega_badge_requirement: 5
  unique_mega_location: "Solve the mystery at New Mauville."
}
item {
  id: ITEM_LAPRASITE_X
  name: "Laprasite X"
  description: "Enables Lapras to Mega Evolve."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_MEGA_STONE
  image: "laprasite"
  palette: "laprasite"
  unique_mega_location: "Find at Oceanic Museam 2F."
}
item {
  id: ITEM_KINGAMBITITE_R
  name: "Kingambitite R"
  description: "Enables Kingambit R to Mega Evolve."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_MEGA_STONE
  image: "generic_megastone"
  palette: "generic_megastone"
  adoption_center: true
}
item {
  id: ITEM_RIBOMBITE
  name: "Ribombite"
  description: "Enables Ribombee to Mega Evolve."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_MEGA_STONE
  image: "generic_megastone"
  palette: "generic_megastone"
  adoption_center: true
}
item {
  id: ITEM_GARCHOMPITE_R
  name: "Garchompite R"
  description: "Enables Garchomp to Mega Evolve."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_MEGA_STONE
  image: "generic_megastone"
  palette: "garchompite_r"
  adoption_center: true
}
item {
  id: ITEM_SKARMORITE_R
  name: "Skarmorite R"
  description: "Enables Skarmory R to Mega Evolve."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_MEGA_STONE
  image: "generic_megastone"
  palette: "generic_megastone"
  adoption_center: true
}
item {
  id: ITEM_MACHAMPITE_R
  name: "Machampite R"
  description: "Enables Machamp R to Mega Evolve."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_MEGA_STONE
  image: "generic_megastone"
  palette: "generic_megastone"
  adoption_center: true
}
item {
  id: ITEM_ALAKAZITE_R
  name: "Alakazite R"
  description: "Enables Alakazam R to Mega Evolve."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_MEGA_STONE
  image: "alakazite_r"
  palette: "alakazite_r"
  adoption_center: true
}
item {
  id: ITEM_BEEDRILLITE_R
  name: "Beedrillite R"
  description: "Enables Beedrill R to Mega Evolve."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_MEGA_STONE
  image: "beedrillite_r"
  palette: "beedrillite_r"
  adoption_center: true
}
item {
  id: ITEM_HOUNDOOMINITE_R
  name: "Houndoominite R"
  description: "Enables Houndoom R to Mega Evolve."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_MEGA_STONE
  image: "generic_megastone"
  palette: "houndoomite_r"
  adoption_center: true
}
item {
  id: ITEM_FROSLASSITE
  name: "Froslassite"
  description: "Enables Froslass to Mega Evolve."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_MEGA_STONE
  image: "froslassite"
  palette: "froslassite"
  adoption_center: true
}
item {
  id: ITEM_SCRAFTITE
  name: "Scraftite"
  description: "Enables Scrafty to Mega Evolve."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_MEGA_STONE
  image: "generic_megastone"
  palette: "generic_megastone"
}
item {
  id: ITEM_MAWILITE_R
  name: "Mawilite R"
  description: "Enables Mawile R to Mega Evolve."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_MEGA_STONE
  image: "generic_megastone"
  palette: "generic_megastone"
  adoption_center: true
}
item {
  id: ITEM_SABLENITE_R
  name: "Sablenite R"
  description: "Enables Sableye R to Mega Evolve."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_MEGA_STONE
  image: "generic_megastone"
  palette: "generic_megastone"
  adoption_center: true
}
item {
  id: ITEM_URSALUNITE
  name: "Ursalunite"
  description: "Enables Ursaring to Mega Evolve."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_MEGA_STONE
  image: "generic_megastone"
  palette: "generic_megastone"
  adoption_center: true
}
item {
  id: ITEM_ARCANITE_R
  name: "Arcanite R"
  description: "Enables Arcanine R to Mega Evolve."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_MEGA_STONE
  image: "generic_megastone"
  palette: "generic_megastone"
  adoption_center: true
}
item {
  id: ITEM_TYRANITARITE_R
  name: "Tyranitarite R"
  description: "Enables Tyranitar R to Mega Evolve."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_MEGA_STONE
  image: "generic_megastone"
  palette: "generic_megastone"
  adoption_center: true
}
item {
  id: ITEM_WIGGLYTUFFITE
  name: "Wigglytuffite Y"
  description: "Enables Wigglytuff to Mega Evolve."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_MEGA_STONE
  image: "wigglytuffite"
  palette: "wigglytuffite"
  talk_to_nurse_joy: true
}
item {
  id: ITEM_TINKATITE
  name: "Tinkatite"
  description: "Enables Tinkaton to Mega Evolve."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_MEGA_STONE
  image: "tinkatite"
  palette: "tinkatite"
  adoption_center: true
}
item {
  id: ITEM_GYARADEATHITE_X
  name: "Gyaradeathite"
  description: "Enables Gyaradeath to Mega Evolve."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_MEGA_STONE
  image: "gyaradeathite_x"
  palette: "gyaradeathite_x"
  adoption_center: true
}
item {
  id: ITEM_GYARADEATHITE_Y
  name: "Gyaradeathite Y"
  description: "Enables Gyaradeath to Mega Evolve."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_MEGA_STONE
  image: "gyaradeathite_y"
  palette: "gyaradeathite_y"
  adoption_center: true
}
item {
  id: ITEM_SENZU
  name: "Senzu Bean"
  description: "This bean enables Lucario to Mega Evolve."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_MEGA_STONE
  image: "senzu"
  palette: "senzu"
  adoption_center: true
}
item {
  id: ITEM_AEGISLASHITE_R
  name: "Aegislashite R"
  description: "Enables Aegislash R to Mega Evolve."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_MEGA_STONE
  image: "aegislashite_R"
  palette: "aegislashite_R"
  adoption_center: true
}
item {
  id: ITEM_ARBOKITE
  name: "Arbokite"
  description: "Enables Arbok to Mega Evolve."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_MEGA_STONE
  image: "arbokite"
  palette: "arbokite"
  adoption_center: true
}
item {
  id: ITEM_CLEFABITE_R
  name: "Clefabite R"
  description: "Enables Clefable R to Mega Evolve."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_MEGA_STONE
  image: "clefabite_R"
  palette: "clefabite_R"
  adoption_center: true
}
item {
  id: ITEM_FLYGONITE_R
  name: "Flygonite R"
  description: "Enables Flygon R to Mega Evolve."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_MEGA_STONE
  image: "flygonite_R"
  palette: "flygonite_R"
  adoption_center: true
}
item {
  id: ITEM_EMPOLEONITE_R
  name: "Empoleonite R"
  description: "Enables Empoleon R to Mega Evolve."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_MEGA_STONE
  image: "empoleonite_R"
  palette: "empoleonite_R"
  adoption_center: true
}
item {
  id: ITEM_INFERNAPENITE_R
  name: "Infernapite R"
  description: "Enables Infernape R to Mega Evolve."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_MEGA_STONE
  image: "infernapenite_R"
  palette: "infernapenite_R"
  adoption_center: true
}
item {
  id: ITEM_FROSLASSITE_R
  name: "Froslassite R"
  description: "Enables Froslass R to Mega Evolve."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_MEGA_STONE
  image: "froslassite_R"
  palette: "froslassite_R"
  adoption_center: true
}
item {
  id: ITEM_GLALITITE_R
  name: "Glalitite R"
  description: "Enables Glalie R to Mega Evolve."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_MEGA_STONE
  image: "glalitite_R"
  palette: "glalitite_R"
  adoption_center: true
}
item {
  id: ITEM_RAPIDASHITE_G
  name: "Rapidashite G"
  description: "Enables Rapidash G to Mega Evolve."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_MEGA_STONE
  image: "rapidashite_G"
  palette: "rapidashite_G"
  adoption_center: true
}
item {
  id: ITEM_GOLISOPODITE
  name: "Golisopodite"
  description: "Enables Golisopod to Mega Evolve."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_MEGA_STONE
  image: "golisopodite"
  palette: "golisopodite"
  adoption_center: true
}
item {
  id: ITEM_HYDREIGONITE_R
  name: "Hydreigonite R"
  description: "Enables Hydreigon R to Mega Evolve."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_MEGA_STONE
  image: "hydreigonite_R"
  palette: "hydreigonite_R"
  adoption_center: true
}
item {
  id: ITEM_TORTERRANITE_R
  name: "Torterranite R"
  description: "Enables Torterra R to Mega Evolve."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_MEGA_STONE
  image: "torterranite_R"
  palette: "torterranite_R"
  adoption_center: true
}
item {
  id: ITEM_RAPIDASHITE
  name: "Rapidashite"
  description: "Enables Rapidash to Mega Evolve."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_MEGA_STONE
  image: "rapidashite"
  palette: "rapidashite"
  adoption_center: true
}
item {
  id: ITEM_CORMOTHITE
  name: "Cormothite"
  description: "Enables Cormoth to Mega Evolve."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_MEGA_STONE
  image: "cormothite"
  palette: "cormothite"
  adoption_center: true
}
item {
  id: ITEM_POPCORMITE
  name: "Popcormite"
  description: "Enables Popcorm to Mega Evolve."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_MEGA_STONE
  image: "popcormite"
  palette: "popcormite"
  adoption_center: true
}
item {
  id: ITEM_REUNICLUSITE_R
  name: "Reuniclusite R"
  description: "Enables Reuniclus R to Mega Evolve."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_MEGA_STONE
  image: "reuniclusite_R"
  palette: "reuniclusite_R"
  adoption_center: true
}
item {
  id: ITEM_TOXTRICITITE_R
  name: "Toxtricitite R"
  description: "Enables Toxtricity R to Mega Evolve."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_MEGA_STONE
  image: "toxtricitite_R"
  palette: "toxtricitite_R"
  adoption_center: true
}
item {
  id: ITEM_ORICORIONITE
  name: "Oricorionite"
  description: "Enables Oricorio to Mega Evolve."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_MEGA_STONE
  image: "oricorionite"
  palette: "oricorionite"
  adoption_center: true
}
item {
  id: ITEM_TSAREENITE_R
  name: "Tsareenite R"
  description: "Enables Tsareena R to Mega Evolve."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_MEGA_STONE
  image: "tsareenite_R"
  palette: "tsareenite_R"
  adoption_center: true
}
item {
  id: ITEM_URSHIFITE
  name: "Urshifite"
  description: "Enables Urshifu to Mega Evolve."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_MEGA_STONE
  image: "urshifite"
  palette: "urshifite"
  talk_to_legendary_sage: true
}
item {
  id: ITEM_AMPHYBUZZITE
  name: "Amphybuzzite"
  description: "Enables Amphybuzz to Mega Evolve."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_MEGA_STONE
  image: "amphybuzzite"
  palette: "amphybuzzite"
  adoption_center: true
}
item {
  id: ITEM_MELMETALITE
  name: "Melmetalite"
  description: "Enables Melmetal to Mega Evolve."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_MEGA_STONE
  image: "melmetalite"
  palette: "melmetalite"
  mega_badge_requirement: 9
  unique_mega_location: "Get Meltan from Steven's House in Mossdeep."
}
item {
  id: ITEM_DYNAMAX_ORB
  name: "Dynamax Orb"
  description: "Enables Eternatus to Primal Revert."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_PRIMAL_ORB
  image: "purple_orb"
  palette: "purple_orb"
  talk_to_legendary_sage: true
}
item {
  id: ITEM_TERA_ORB
  name: "Tera Orb"
  description: "Enables Terapagos to Primal Revert."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_PRIMAL_ORB
  image: "tera_orb"
  palette: "tera_orb"
  talk_to_legendary_sage: true
}
item {
  id: ITEM_VENUSAURITE_X
  name: "Venusaurite X"
  description: "Enables Venusaur to Mega Evolve."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_MEGA_STONE
  image: "venusaurite"
  palette: "venusaurite"
  adoption_center: true
}
item {
  id: ITEM_CHARIZARDITE_Z
  name: "Charizardite Z"
  description: "Enables Charizard to Mega Evolve."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_MEGA_STONE
  image: "charizardite_y"
  palette: "charizardite_y"
  adoption_center: true
}
item {
  id: ITEM_BLASTOISINITE_X
  name: "Blastoisinite X"
  description: "Enables Blastoise to Mega Evolve."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_MEGA_STONE
  image: "blastoisinite"
  palette: "blastoisinite"
  adoption_center: true
}
item {
  id: ITEM_GENGARITE_X
  name: "Gengarite X"
  description: "Enables Gengar to Mega Evolve."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_MEGA_STONE
  image: "gengarite"
  palette: "gengarite"
  adoption_center: true
}
item {
  id: ITEM_SNORLAXITE
  name: "Snorlaxite"
  description: "Enables Snorlax to Mega Evolve."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_MEGA_STONE
  image: "generic_megastone"
  palette: "hitmonchanite"
  adoption_center: true
}
item {
  id: ITEM_RILLABOOMITE
  name: "Rillaboomite"
  description: "Enables Rillaboom to Mega Evolve."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_MEGA_STONE
  image: "generic_megastone"
  palette: "hitmonchanite"
  adoption_center: true
}
item {
  id: ITEM_CINDERACEITE
  name: "Cinderaceite"
  description: "Enables Cinderace to Mega Evolve."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_MEGA_STONE
  image: "generic_megastone"
  palette: "hitmonchanite"
  adoption_center: true
}
item {
  id: ITEM_INTELEONITE
  name: "Inteleonite"
  description: "Enables Inteleon to Mega Evolve."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_MEGA_STONE
  image: "generic_megastone"
  palette: "hitmonchanite"
  adoption_center: true
}
item {
  id: ITEM_CORVINITE
  name: "Corvinite"
  description: "Enables Corviknight to Mega Evolve."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_MEGA_STONE
  image: "generic_megastone"
  palette: "hitmonchanite"
  adoption_center: true
}
item {
  id: ITEM_DREDNAWITE
  name: "Drednawite"
  description: "Enables Drednaw to Mega Evolve."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_MEGA_STONE
  image: "generic_megastone"
  palette: "hitmonchanite"
  adoption_center: true
}
item {
  id: ITEM_COALOSSITE
  name: "Coalossite"
  description: "Enables Coalossal to Mega Evolve."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_MEGA_STONE
  image: "generic_megastone"
  palette: "hitmonchanite"
  adoption_center: true
}
item {
  id: ITEM_SANDACONDITE
  name: "Sandacondite"
  description: "Enables Sandaconda to Mega Evolve."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_MEGA_STONE
  image: "generic_megastone"
  palette: "hitmonchanite"
  adoption_center: true
}
item {
  id: ITEM_COPPERAJITE
  name: "Copperajite"
  description: "Enables Copperajah to Mega Evolve."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_MEGA_STONE
  image: "generic_megastone"
  palette: "hitmonchanite"
  adoption_center: true
}
item {
  id: ITEM_HATTERENITE
  name: "Hatterenite"
  description: "Enables Hatterene to Mega Evolve."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_MEGA_STONE
  image: "generic_megastone"
  palette: "hitmonchanite"
  adoption_center: true
}
item {
  id: ITEM_GARBODORITE
  name: "Garbodorite"
  description: "Enables Garbodor to Mega Evolve."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_MEGA_STONE
  image: "generic_megastone"
  palette: "hitmonchanite"
  adoption_center: true
}
item {
  id: ITEM_ORBEETITE
  name: "Orbeetite"
  description: "Enables Orbeetle to Mega Evolve."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_MEGA_STONE
  image: "generic_megastone"
  palette: "hitmonchanite"
  adoption_center: true
}
item {
  id: ITEM_GRIMMSNARLITE
  name: "Grimmsnarlite"
  description: "Enables Grimmsnarl to Mega Evolve."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_MEGA_STONE
  image: "generic_megastone"
  palette: "hitmonchanite"
  adoption_center: true
}
item {
  id: ITEM_CENTISKITE
  name: "Centiskite"
  description: "Enables Centiskorch to Mega Evolve."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_MEGA_STONE
  image: "generic_megastone"
  palette: "hitmonchanite"
  adoption_center: true
}
item {
  id: ITEM_ALCREMITE
  name: "Alcremite"
  description: "Enables Alcremie to Mega Evolve."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_MEGA_STONE
  image: "generic_megastone"
  palette: "hitmonchanite"
  adoption_center: true
}
item {
  id: ITEM_TOXTRICITITE
  name: "Toxtricitite"
  description: "Enables Toxtricity to Mega Evolve."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_MEGA_STONE
  image: "generic_megastone"
  palette: "hitmonchanite"
  adoption_center: true
}
item {
  id: ITEM_PIKANITE
  name: "Pikanite"
  description: "Enables P.Pikachu to Mega Evolve."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_MEGA_STONE
  image: "generic_megastone"
  palette: "hitmonchanite"
}
item {
  id: ITEM_MEOWTHITE
  name: "Meowthite"
  description: "Enables P.Meowth to Mega Evolve."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_MEGA_STONE
  image: "generic_megastone"
  palette: "hitmonchanite"
}
item {
  id: ITEM_EEVITE
  name: "Eevite"
  description: "Enables P.Eevee to Mega Evolve."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_MEGA_STONE
  image: "generic_megastone"
  palette: "hitmonchanite"
}
item {
  id: ITEM_DURALUDITE
  name: "Duraludite"
  description: "Enables DuraludonP. to Mega Evolve."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_MEGA_STONE
  image: "generic_megastone"
  palette: "hitmonchanite"
}
item {
  id: ITEM_ULTRANECROZIUM_P
  name: "U-Necrozium Z"
  description: "A crystal to turn fused Necrozma into a new form."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_PRIMAL_ORB
  image: "ultranecrozium_z"
  palette: "ultranecrozium_z"
  talk_to_legendary_sage: true
}
item {
  id: ITEM_FIDOUGHITE
  name: "Fidoughite"
  description: "Enables FidoughP. to Mega Evolve."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_MEGA_STONE
  image: "generic_megastone"
  palette: "hitmonchanite"
}
item {
  id: ITEM_WIGGLYTUFFITE_X
  name: "Wigglytuffite X"
  description: "Enables Wigglytuff to Mega Evolve."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_MEGA_STONE
  image: "wigglytuffite"
  palette: "wigglytuffite"
  talk_to_nurse_joy: true
}
item {
  id: ITEM_SERPERIORITE
  name: "Serperiorite"
  description: "Enables Serperior to Mega Evolve."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_MEGA_STONE
  image: "generic_megastone"
  palette: "hitmonchanite"
  talk_to_nurse_joy: true
}
item {
  id: ITEM_EMBOARITE
  name: "Emboarite"
  description: "Enables Emboar to Mega Evolve."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_MEGA_STONE
  image: "generic_megastone"
  palette: "hitmonchanite"
  talk_to_nurse_joy: true
}
item {
  id: ITEM_SAMUROTTITE
  name: "Samurottite"
  description: "Enables Samurott to Mega Evolve."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_MEGA_STONE
  image: "generic_megastone"
  palette: "hitmonchanite"
  talk_to_nurse_joy: true
}
item {
  id: ITEM_DECIDUITE
  name: "Deciduite"
  description: "Enables Decidueye to Mega Evolve."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_MEGA_STONE
  image: "generic_megastone"
  palette: "hitmonchanite"
  talk_to_nurse_joy: true
}
item {
  id: ITEM_WEAVILEITE
  name: "Weavileite"
  description: "Enables Weavile to Mega Evolve."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_MEGA_STONE
  image: "generic_megastone"
  palette: "hitmonchanite"
  adoption_center: true
}
item {
  id: ITEM_DECIDUITE_H
  name: "Deciduite H"
  description: "Enables Decidueye H to Mega Evolve."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_MEGA_STONE
  image: "generic_megastone"
  palette: "hitmonchanite"
  talk_to_nurse_joy: true
}
item {
  id: ITEM_INCINERITE
  name: "Incinerite"
  description: "Enables Incineroar to Mega Evolve."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_MEGA_STONE
  image: "generic_megastone"
  palette: "hitmonchanite"
  talk_to_nurse_joy: true
}
item {
  id: ITEM_MEOWSCARADITE
  name: "Meowscaradite"
  description: "Enables Meowscarada to Mega Evolve."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_MEGA_STONE
  image: "generic_megastone"
  palette: "hitmonchanite"
  talk_to_nurse_joy: true
}
item {
  id: ITEM_PRIMARINITE
  name: "Primarinite"
  description: "Enables Primarina to Mega Evolve."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_MEGA_STONE
  image: "generic_megastone"
  palette: "hitmonchanite"
  talk_to_nurse_joy: true
}
item {
  id: ITEM_QUAQUAVITE
  name: "Quaquavite"
  description: "Enables Quaquaval to Mega Evolve."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_MEGA_STONE
  image: "generic_megastone"
  palette: "hitmonchanite"
  talk_to_nurse_joy: true
}
item {
  id: ITEM_SAMUROTTITE_H
  name: "Samurottite H"
  description: "Enables Samurott H to Mega Evolve."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_MEGA_STONE
  image: "generic_megastone"
  palette: "hitmonchanite"
  talk_to_nurse_joy: true
}
item {
  id: ITEM_SKELEDIRGEITE
  name: "Skeledirgeite"
  description: "Enables Skeledirge to Mega Evolve."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_MEGA_STONE
  image: "generic_megastone"
  palette: "hitmonchanite"
  talk_to_nurse_joy: true
}
item {
  id: ITEM_TYPHLOSIONITE_H
  name: "Typhlosionite H"
  description: "Enables Typhlosion H to Mega Evolve."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_MEGA_STONE
  image: "generic_megastone"
  palette: "hitmonchanite"
  talk_to_nurse_joy: true
}
item {
  id: ITEM_MIENSHAOITE
  name: "Mienshaoite"
  description: "Enables Mienshao to Mega Evolve."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_MEGA_STONE
  image: "generic_megastone"
  palette: "hitmonchanite"
  adoption_center: true
}
item {
  id: ITEM_GOODRITE
  name: "Goodranite"
  description: "Enables Goodra to Mega Evolve."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_MEGA_STONE
  image: "generic_megastone"
  palette: "hitmonchanite"
  adoption_center: true
}
item {
  id: ITEM_SLOWBRONITE_G
  name: "Slowbronite G"
  description: "Enables Slowbro-G to Mega Evolve."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_MEGA_STONE
  image: "slowbronite"
  palette: "slowbronite"
  adoption_center: true
}
item {
  id: ITEM_SLOWKINGITE_G
  name: "Slowkingite G"
  description: "Enables Slowking-G to Mega Evolve."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_MEGA_STONE
  image: "generic_megastone"
  palette: "hitmonchanite"
  adoption_center: true
}
item {
  id: ITEM_ROSERADEITE
  name: "Roseradite"
  description: "Enables Roserade to Mega Evolve."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_MEGA_STONE
  image: "generic_megastone"
  palette: "hitmonchanite"
  talk_to_nurse_joy: true
}
item {
  id: ITEM_ARCANITE
  name: "Arcanite"
  description: "Enables Arcanine to Mega Evolve."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_MEGA_STONE
  image: "generic_megastone"
  palette: "hitmonchanite"
  adoption_center: true
}
item {
  id: ITEM_KINGDRANITE_Y
  name: "Kingdranite Y"
  description: "Enables Kingdra to Mega Evolve."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_MEGA_STONE
  image: "kingdranite"
  palette: "kingdranite"
  adoption_center: true
}
item {
  id: ITEM_PHANTOM_METEOR
  name: "Phantom Meteor"
  description: "Enables MimikyuApex to Primal Revert."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_PRIMAL_ORB
  image: "meteorite"
  palette: "meteorite"
}
item {
  id: ITEM_YVELTALITE
  name: "Yveltalite"
  description: "Enables Yveltal to Mega Evolve."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_MEGA_STONE
  image: "generic_megastone"
  palette: "hitmonchanite"
}
item {
  id: ITEM_GALACTIC_ORB
  name: "Galactic Orb"
  description: "Enables Espeon to Primal Revert."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_PRIMAL_ORB
  image: "purple_orb"
  palette: "purple_orb"
}
item {
  id: ITEM_CHIEN_PAOITE
  name: "Chien-Paoite"
  description: "Enables Chien-Pao to Mega Evolve."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_MEGA_STONE
  image: "generic_megastone"
  palette: "hitmonchanite"
}
item {
  id: ITEM_DRACOVISHITE
  name: "Dracovishite"
  description: "Enables Dracovish to Mega Evolve."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_MEGA_STONE
  image: "generic_megastone"
  palette: "hitmonchanite"
}
item {
  id: ITEM_MAWILITE_R_B
  name: "Mawilite P"
  description: "Enables Mawile R to Mega Evolve."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_MEGA_STONE
  image: "generic_megastone"
  palette: "hitmonchanite"
}
item {
  id: ITEM_RIBOMBITE_R
  name: "Ribombite R"
  description: "Enables Ribombee R to Mega Evolve."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_MEGA_STONE
  image: "generic_megastone"
  palette: "hitmonchanite"
}
item {
  id: ITEM_WEAVILEITE_R
  name: "Weavilite R"
  description: "Enables Weavile R to Mega Evolve."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_MEGA_STONE
  image: "generic_megastone"
  palette: "hitmonchanite"
}
item {
  id: ITEM_FLYGONITE_R_B
  name: "Flygonite E"
  description: "Enables Flygon R to Mega Evolve."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_MEGA_STONE
  image: "generic_megastone"
  palette: "hitmonchanite"
}
item {
  id: ITEM_SNORLAX_ORB
  name: "Dream Orb"
  description: "Enables Snorlax to Primal Reverse."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_MEGA_STONE
  image: "generic_megastone"
  palette: "hitmonchanite"
}
item {
  id: ITEM_VICTINI_ORB
  name: "Lucky Orb"
  description: "Enables Victini to Primal Reverse."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_MEGA_STONE
  image: "generic_megastone"
  palette: "hitmonchanite"
}
item {
  id: ITEM_WIGGLITUFF_ORB
  name: "Ancient Apple"
  description: "Enables Wigglytuff-A to Primal Reverse."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_PRIMAL_ORB
  image: "tart_apple"
  palette: "tart_apple"
}
item {
  id: ITEM_ABOMASITE_S
  name: "Abomasite S"
  description: "Enables Abomasnow to Mega Evolve."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_MEGA_STONE
}
item {
  id: ITEM_ULTRANECROZIUM_Z
  name: "U-Necrozium Z"
  description: "A crystal to turn fused Necrozma into a new form."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_PRIMAL_ORB
  image: "ultranecrozium_z"
  palette: "ultranecrozium_z"
}
item {
  id: ITEM_ADAMANT_ORB
  name: "Adamant Orb"
  description: "This orb enables Dialga to revert to its origin."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_PRIMAL_ORB
  image: "adamant_orb"
  palette: "adamant_orb"
  talk_to_legendary_sage: true
}
item {
  id: ITEM_LUSTROUS_ORB
  name: "Lustrous Orb"
  description: "This orb enables Palkia to revert to its origin."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_PRIMAL_ORB
  image: "lustrous_orb"
  palette: "lustrous_orb"
  talk_to_legendary_sage: true
}
item {
  id: ITEM_GRISEOUS_ORB
  name: "Griseous Orb"
  description: "This orb enables Giratina to revert to origin."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_PRIMAL_ORB
  image: "griseous_orb"
  palette: "griseous_orb"
  talk_to_legendary_sage: true
}
item {
  id: ITEM_RUSTED_SWORD
  name: "Rusted Sword"
  description: "A rusty, worn sword used by an ancient hero."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_PRIMAL_ORB
  image: "rusted_sword"
  palette: "rusted_sword"
  talk_to_legendary_sage: true
}
item {
  id: ITEM_RUSTED_SHIELD
  name: "Rusted Shield"
  description: "A rusty, worn shield used by an ancient hero."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_PRIMAL_ORB
  image: "rusted_shield"
  palette: "rusted_shield"
  talk_to_legendary_sage: true
}
item {
  id: ITEM_DUDUDUNITE
  name: "Dududunite"
  description: "Enables Dududunsparce to Mega Evolve."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_MEGA_STONE
  image: "audinite"
  palette: "audinite"
  adoption_center: true
}
item {
  id: ITEM_TEAL_MASK
  name: "Teal Mask"
  description: "Boosts Ogerpon's power and enables mega evolution."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_MEGA_STONE
  image: "teal_mask"
  palette: "teal_mask"
}
item {
  id: ITEM_HEARTHFLAME_MASK
  name: "Hearthflame Mask"
  description: "Boosts Ogerpon-H's power and enables mega evolution."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_MEGA_STONE
  image: "hearthflame_mask"
  palette: "hearthflame_mask"
}
item {
  id: ITEM_WELLSPRING_MASK
  name: "Wellspring Mask"
  description: "Boosts Ogerpon-W's power and enables mega evolution."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_MEGA_STONE
  image: "wellspring_mask"
  palette: "wellspring_mask"
}
item {
  id: ITEM_CORNERSTONE_MASK
  name: "Cornerstone Mask"
  description: "Boosts Ogerpon-C's power and enables mega evolution."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_MEGA_STONE
  image: "cornerstone_mask"
  palette: "cornerstone_mask"
}
item {
  id: ITEM_TINKATITE_R
  name: "Tinkatite R"
  description: "Enables Tinkaton R to Mega Evolve."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_MEGA_STONE
  image: "audinite"
  palette: "audinite"
  adoption_center: true
}
item {
  id: ITEM_LUXRAYNITE_R
  name: "Luxraynite R"
  description: "Enables Luxray R to Mega Evolve."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_MEGA_STONE
  image: "luxraynite_r"
  palette: "luxraynite_r"
  adoption_center: true
}
item {
  id: ITEM_SCIZORITE_R
  name: "Scizorite R"
  description: "Enables Scizor R to Mega Evolve."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_MEGA_STONE
  image: "audinite"
  palette: "audinite"
  adoption_center: true
}
item {
  id: ITEM_KLEAVITE_R
  name: "Kleavite R"
  description: "Enables Kleavor R to Mega Evolve."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_MEGA_STONE
  image: "audinite"
  palette: "audinite"
  adoption_center: true
}
item {
  id: ITEM_SCYTHERITE_R
  name: "Scytherite R"
  description: "Enables Scyther R to Mega Evolve."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_MEGA_STONE
  image: "audinite"
  palette: "audinite"
  adoption_center: true
}
item {
  id: ITEM_KINGLERITE_R
  name: "Kinglerite"
  description: "Enables Kingler to Mega Evolve."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_MEGA_STONE
  image: "audinite"
  palette: "audinite"
  adoption_center: true
}
item {
  id: ITEM_KILOZUNITE
  name: "Kilozunite"
  description: "Enables Kilozuna to Mega Evolve."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_MEGA_STONE
  image: "audinite"
  palette: "audinite"
  adoption_center: true
}
item {
  id: ITEM_GARDEVOIRITE_R
  name: "Gardevoirite R"
  description: "Enables Gardevoir R to Mega Evolve."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_MEGA_STONE
  image: "audinite"
  palette: "audinite"
  adoption_center: true
}
item {
  id: ITEM_GALLADITE_R
  name: "Galladite R"
  description: "Enables Gallade to Mega Evolve."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_MEGA_STONE
  image: "audinite"
  palette: "audinite"
  adoption_center: true
}
item {
  id: ITEM_CLODSITE
  name: "Clodsite"
  description: "Enables Clodsire to Mega Evolve."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_MEGA_STONE
  image: "audinite"
  palette: "audinite"
  adoption_center: true
}
item {
  id: ITEM_GOTHITITE
  name: "Gothitite"
  description: "Enables Gothitelle to Mega Evolve."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_MEGA_STONE
  image: "audinite"
  palette: "audinite"
  adoption_center: true
}
item {
  id: ITEM_SNORLAXITE_R
  name: "Snorlaxite R"
  description: "Enables Snorlax R to Mega Evolve."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_MEGA_STONE
  image: "audinite"
  palette: "audinite"
  adoption_center: true
}
item {
  id: ITEM_AGGRONITE_R
  name: "Aggronite R"
  description: "Enables Aggron R to Mega Evolve."
  grouping: POCKET_MEGA_STONES
  hold_effect: HOLD_EFFECT_MEGA_STONE
  image: "aggronite"
  palette: "aggronite"
  talk_to_nurse_joy: true
}