# proto-file: ItemList.proto
# proto-message: er.ItemList

item {
  id: ITEM_MASTER_BALL
  name: "Master Ball"
  description: "The best Ball that catches a Pok\303\251mon without fail."
  grouping: POCKET_POKE_BALLS
  use_type: ITEM_USE_PARTY_MENU
  image: "master_ball"
  palette: "master_ball"
  battle_use_func: "PokeBall"
  field_use_func: "PokeBall"
}
item {
  id: ITEM_ULTRA_BALL
  name: "Ultra Ball"
  description: "A better Ball with a higher catch rate than a Great Ball."
  grouping: POCKET_POKE_BALLS
  use_type: ITEM_USE_PARTY_MENU
  image: "ultra_ball"
  palette: "ultra_ball"
  battle_use_func: "PokeBall"
  field_use_func: "PokeBall"
}
item {
  id: ITEM_GREAT_BALL
  name: "Great Ball"
  description: "A good Ball with a higher catch rate than a Pok\303\251 Ball."
  grouping: POCKET_POKE_BALLS
  use_type: ITEM_USE_PARTY_MENU
  image: "great_ball"
  palette: "great_ball"
  battle_use_func: "PokeBall"
  field_use_func: "PokeBall"
}
item {
  id: ITEM_POKE_BALL
  name: "Pok\303\251 Ball"
  description: "A tool used for catching wild Pok\303\251mon."
  grouping: POCKET_POKE_BALLS
  use_type: ITEM_USE_PARTY_MENU
  image: "poke_ball"
  palette: "poke_ball"
  battle_use_func: "PokeBall"
  field_use_func: "PokeBall"
}
item {
  id: ITEM_SAFARI_BALL
  name: "Safari Ball"
  description: "A special Ball that is used only in the Safari Zone."
  grouping: POCKET_POKE_BALLS
  use_type: ITEM_USE_PARTY_MENU
  image: "safari_ball"
  palette: "safari_ball"
  battle_use_func: "PokeBall"
  field_use_func: "PokeBall"
}
item {
  id: ITEM_NET_BALL
  name: "Net Ball"
  description: "A Ball that works well on Water-and Bug-type Pok\303\251mon."
  grouping: POCKET_POKE_BALLS
  use_type: ITEM_USE_PARTY_MENU
  image: "net_ball"
  palette: "net_ball"
  battle_use_func: "PokeBall"
  field_use_func: "PokeBall"
}
item {
  id: ITEM_DIVE_BALL
  name: "Dive Ball"
  description: "A Ball that works better on Pok\303\251mon on the ocean floor."
  grouping: POCKET_POKE_BALLS
  use_type: ITEM_USE_PARTY_MENU
  image: "dive_ball"
  palette: "dive_ball"
  battle_use_func: "PokeBall"
  field_use_func: "PokeBall"
}
item {
  id: ITEM_NEST_BALL
  name: "Nest Ball"
  description: "A Ball that works better on weaker Pok\303\251mon."
  grouping: POCKET_POKE_BALLS
  use_type: ITEM_USE_PARTY_MENU
  image: "nest_ball"
  palette: "nest_ball"
  battle_use_func: "PokeBall"
  field_use_func: "PokeBall"
}
item {
  id: ITEM_REPEAT_BALL
  name: "Repeat Ball"
  description: "A Ball that works better on Pok\303\251mon caught before."
  grouping: POCKET_POKE_BALLS
  use_type: ITEM_USE_PARTY_MENU
  image: "repeat_ball"
  palette: "repeat_ball"
  battle_use_func: "PokeBall"
  field_use_func: "PokeBall"
}
item {
  id: ITEM_TIMER_BALL
  name: "Timer Ball"
  description: "A Ball that gains power in battles taking many turns."
  grouping: POCKET_POKE_BALLS
  use_type: ITEM_USE_PARTY_MENU
  image: "timer_ball"
  palette: "repeat_ball"
  battle_use_func: "PokeBall"
  field_use_func: "PokeBall"
}
item {
  id: ITEM_LUXURY_BALL
  name: "Luxury Ball"
  description: "A cozy Ball that makes Pok\303\251mon more friendly."
  grouping: POCKET_POKE_BALLS
  use_type: ITEM_USE_PARTY_MENU
  image: "luxury_ball"
  palette: "luxury_ball"
  battle_use_func: "PokeBall"
  field_use_func: "PokeBall"
}
item {
  id: ITEM_DUSK_BALL
  name: "Dusk Ball"
  description: "Works well if used in a dark place."
  grouping: POCKET_POKE_BALLS
  use_type: ITEM_USE_PARTY_MENU
  image: "dusk_ball"
  palette: "dusk_ball"
  battle_use_func: "PokeBall"
  field_use_func: "PokeBall"
}
item {
  id: ITEM_HEAL_BALL
  name: "Heal Ball"
  description: "A remedial Ball that restores caught Pok\303\251mon."
  grouping: POCKET_POKE_BALLS
  use_type: ITEM_USE_PARTY_MENU
  image: "heal_ball"
  palette: "heal_ball"
  battle_use_func: "PokeBall"
  field_use_func: "PokeBall"
}
item {
  id: ITEM_QUICK_BALL
  name: "Quick Ball"
  description: "Works well if used on the first turn."
  grouping: POCKET_POKE_BALLS
  use_type: ITEM_USE_PARTY_MENU
  image: "quick_ball"
  palette: "quick_ball"
  battle_use_func: "PokeBall"
  field_use_func: "PokeBall"
}
item {
  id: ITEM_CHERISH_BALL
  name: "Cherish Ball"
  description: "A rare Ball made in commemoration of some event."
  grouping: POCKET_POKE_BALLS
  use_type: ITEM_USE_PARTY_MENU
  image: "cherish_ball"
  palette: "cherish_ball"
  battle_use_func: "PokeBall"
  field_use_func: "PokeBall"
}
item {
  id: ITEM_FAST_BALL
  name: "Fast Ball"
  description: "Works well on very fast Pok\303\251mon."
  grouping: POCKET_POKE_BALLS
  use_type: ITEM_USE_PARTY_MENU
  image: "fast_ball"
  palette: "fast_ball"
  battle_use_func: "PokeBall"
  field_use_func: "PokeBall"
}
item {
  id: ITEM_LEVEL_BALL
  name: "Level Ball"
  description: "A Ball that works well on lower level Pok\303\251mon."
  grouping: POCKET_POKE_BALLS
  use_type: ITEM_USE_PARTY_MENU
  image: "level_ball"
  palette: "level_ball"
  battle_use_func: "PokeBall"
  field_use_func: "PokeBall"
}
item {
  id: ITEM_LURE_BALL
  name: "Lure Ball"
  description: "A Ball that works well on fished up Pok\303\251mon."
  grouping: POCKET_POKE_BALLS
  use_type: ITEM_USE_PARTY_MENU
  image: "lure_ball"
  palette: "lure_ball"
  battle_use_func: "PokeBall"
  field_use_func: "PokeBall"
}
item {
  id: ITEM_HEAVY_BALL
  name: "Heavy Ball"
  description: "Works well on very heavy Pok\303\251mon."
  grouping: POCKET_POKE_BALLS
  use_type: ITEM_USE_PARTY_MENU
  image: "heavy_ball"
  palette: "heavy_ball"
  battle_use_func: "PokeBall"
  field_use_func: "PokeBall"
}
item {
  id: ITEM_LOVE_BALL
  name: "Love Ball"
  description: "Works well on Pok\303\251mon of the opposite gender."
  grouping: POCKET_POKE_BALLS
  use_type: ITEM_USE_PARTY_MENU
  image: "love_ball"
  palette: "love_ball"
  battle_use_func: "PokeBall"
  field_use_func: "PokeBall"
}
item {
  id: ITEM_FRIEND_BALL
  name: "Friend Ball"
  description: "A Ball that makes a Pok\303\251mon friendly when caught."
  grouping: POCKET_POKE_BALLS
  use_type: ITEM_USE_PARTY_MENU
  image: "friend_ball"
  palette: "friend_ball"
  battle_use_func: "PokeBall"
  field_use_func: "PokeBall"
}
item {
  id: ITEM_MOON_BALL
  name: "Moon Ball"
  description: "A Ball that works well on Moon Stone users."
  grouping: POCKET_POKE_BALLS
  use_type: ITEM_USE_PARTY_MENU
  image: "moon_ball"
  palette: "moon_ball"
  battle_use_func: "PokeBall"
  field_use_func: "PokeBall"
}
item {
  id: ITEM_SPORT_BALL
  name: "Sport Ball"
  description: "A special Ball used in the Bug-Catching Contest."
  grouping: POCKET_POKE_BALLS
  use_type: ITEM_USE_PARTY_MENU
  image: "sport_ball"
  palette: "sport_ball"
  battle_use_func: "PokeBall"
  field_use_func: "PokeBall"
}
item {
  id: ITEM_PARK_BALL
  name: "Park Ball"
  description: "A special Ball for the Pal Park."
  grouping: POCKET_POKE_BALLS
  use_type: ITEM_USE_PARTY_MENU
  image: "park_ball"
  palette: "park_ball"
  battle_use_func: "PokeBall"
  field_use_func: "PokeBall"
}
item {
  id: ITEM_DREAM_BALL
  name: "Dream Ball"
  description: "A Ball that gives a captured Pok\303\251mon its Hidden Ability."
  grouping: POCKET_POKE_BALLS
  use_type: ITEM_USE_PARTY_MENU
  image: "dream_ball"
  palette: "dream_ball"
  battle_use_func: "PokeBall"
  field_use_func: "PokeBall"
}
item {
  id: ITEM_BEAST_BALL
  name: "Beast Ball"
  description: "A Ball designed to catch Ultra Beasts."
  grouping: POCKET_POKE_BALLS
  use_type: ITEM_USE_PARTY_MENU
  image: "beast_ball"
  palette: "beast_ball"
  battle_use_func: "PokeBall"
  field_use_func: "PokeBall"
}
item {
  id: ITEM_PREMIER_BALL
  name: "Premier Ball"
  description: "A rare Ball made in commemoration of some event."
  grouping: POCKET_POKE_BALLS
  use_type: ITEM_USE_PARTY_MENU
  image: "premier_ball"
  palette: "luxury_ball"
  battle_use_func: "PokeBall"
  field_use_func: "PokeBall"
}